### ISSUE TITLE
DetailsList not rendering updated selection

### ISSUE THREAD

**Issue by goodoldneon** [OfficeDev/office-ui-fabric-react#7525] opened 2019-01-04 18:02 UTC
### Environment Information 
 
 
- __Package version(s)__: 6.117.1
- __Browser and OS versions__: Chrome 71.0.3578.98 and macOS 10.14.2

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/goodoldneon/pen/BvJBEq
 
- I'm trying to keep `selectedItems` in state in a parent component (`<App />`).
- The child component (`<Child />`) is responsible for updating selections in the `<DetailsList />` component.
 
#### Actual behavior:

- The selections in `<DetailsList />` only clear when the "Sort" button is clicked a 2nd time.
- Below the sort button, I'm printing the length of `this.selection.getSelection()`. This proves that the instantiation of the `Selection` class has the correct number of selected items. But for some reason `<DetailsList />` is not showing the correct selections.
 
#### Expected behavior:
 
The selections in `<DetailsList /> should clear when the "Sort" button is clicked a once.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No (I think this one is beyond my skill level)
 
Requested priority: High
 
Products/sites affected: (if applicable)

**Comment by cliffkoh** [comment] 2019-01-05 10:41
@aditima, could you please look at this?

**Comment by goodoldneon** [comment] 2019-01-05 17:09
My question was answered in https://github.com/OfficeDev/office-ui-fabric-react/issues/7418#issuecomment-448032880. `DetailsList` will rerender when its props.items change. So to force the render I put:

```js
this.setState({
  items: [...this.state.items]
})
```

**Comment by cliffkoh** [comment] 2019-01-07 19:35
Oh! If this is the root cause - it is by-design that DetailsList treats the items array as pure (i.e. the items array itself is treated as immutable). 

JavaScript sorting usually happens in-place - I recommend you copy the elements to a new array first before executing the sort.

**Comment by cliffkoh** [comment] 2019-01-07 19:37
Please see this fork of your codepen where the problem you reported is mitigated.

https://codepen.io/cliffkoh-the-styleful/pen/LMrEad

**Comment by goodoldneon** [comment] 2019-01-09 23:38
Wow, I can't believe I made that mistake. Now I need review more code to see where else I thought `sort()` returned a new array...

Thanks for your help!

**Comment by cliffkoh** [comment] 2019-01-10 00:01
Please feel free to close the issue :)

Thanks for creating a codepen which helped me help you.

**Closed** 2019-01-10 00:02 UTC
Labels: Component: DetailsList, Needs: Author Feedback, Resolution: By Design
