### ISSUE TITLE
Dropdown options selection is not keyboard friendly

### ISSUE THREAD

**Issue by PatoBeltran** [OfficeDev/office-ui-fabric-react#9241] opened 2019-05-28 19:01 UTC
### Environment Information 
 
- __Package version(s)__: 6.184.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/PatoBeltran/pen/WBKWJG

#### Actual behavior:

Using keyboard shortcuts to select an option in a dropdown doesn't work. There are two scenarios:

- Open the dropdown (either by tabbing into it and hitting space bar or clicking into it to show options)
- Type a letter that matches an option (e.g. "F" in this case)
- Does not select an option that matches (e.g. "Four")

Second case:

- On collapsed dropdown (not expanded) with focus, type a letter to change selection (e.g. "Four")
- Does not select an option that matches (e.g. "Four")

#### Expected behavior:
 
I would expect to have the same behavior as a Select input that an option that matches the typed keys is selected.

**Comment by micahgodbolt** [comment] 2019-05-28 20:24
duplicate of #6565

**Comment by leddie24** [comment] 2019-05-28 21:08
Hi @PatoBeltran thanks for submitting this issue.  This looks like a duplicate of #6565.  As a workaround for this, you can use our `Combobox` component with `freeform = false` and `autocomplete = on`.

**Comment by PatoBeltran** [comment] 2019-05-28 21:15
Hey @leddie24 thanks for your response. I have tested using both combo box and dropdown for my scenarios but I ended up deciding to use dropdown instead because of https://github.com/OfficeDev/office-ui-fabric-react/issues/8893 and because I felt the interaction that dropdown provided was more fitted to what I was looking for (basically an accessible, cross browser styleable and better looking select field)

**Comment by leddie24** [comment] 2019-05-28 21:34
Sounds good.  We have plans to fix this issue in the future; we're tracking this in #6030.  Closing this since it's a duplicate of #6565.  If you have any additional questions or comments, please leave them in #6565, thanks!

**Closed by leddie24** 2019-05-28 21:34 UTC
Labels: Component: Dropdown, Needs: Attention :wave:, Resolution: Duplicate, Type: Feature
