### ISSUE TITLE
Single Selection DetailsList Allows Multiple Selection

### ISSUE THREAD

**Issue by canmenekse** [OfficeDev/office-ui-fabric-react#8807] opened 2019-04-22 22:00 UTC
### Environment Information 
 
- __Package version(s)__: 6.167.3 
- __Browser and OS versions__: Happens in Chrome, Edge & Firefox

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/BEPEPv?editors=1011
  
#### Actual behavior:
 

1. Select 'c' on the list.
2. Click in the empty space.
3. Press tab to select the column Header.
4. Press down arrow it will select 'a' too.

![multiselect](https://user-images.githubusercontent.com/42455391/56534744-1f90aa00-650f-11e9-82e9-ee17ee7b0258.PNG)

 
#### Expected behavior:
 
The focus should go to the already selected element, there should not be 2 selections active.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, **No**, don't have enough info on the root cause)
 
Requested priority: (Blocking, High, **Normal**, Low)

**Comment by KevinTCoughlin** [comment] 2019-04-25 23:41
Part of the problem is:

https://github.com/OfficeDev/office-ui-fabric-react/blob/c0b7dd66d1b09e30f9b92e40f8c517b119acc48e/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx#L116

Where if you specify `selectionMode` for `DetailsList`, but not `selection` as props, then it defaults to its constructor. Therefore the modes mismatch and multiple selection is allowed.

Also seems like how we read the "Select All" flag to conditionally render the "Select All" check is error-prone, see https://codepen.io/kevintcoughlin/pen/MRZrbQ?editors=1011

**Comment by xugao** [comment] 2020-02-12 22:04
@canmenekse - this seems to no longer repro in your codepen. can you check if this is fixed on your side?

**Comment by canmenekse** [comment] 2020-02-15 00:45
yeah it fixed it. I couldn't repro

**Closed** 2020-02-18 17:24 UTC
Labels: Component: DetailsList, Needs: Backlog review, Status: Fixed, Type: Bug :bug:
