### ISSUE TITLE
A11Y issue in command bar: aria-allowed-attr

### ISSUE THREAD

**Issue by dssharma** [OfficeDev/office-ui-fabric-react#11220] opened 2019-11-15 08:56 UTC
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

#### Actual behavior:
Getting accessibility error by using accessibility insights which says ARIA attribute not allowed: aria-orientation="horizontal"
![image](https://user-images.githubusercontent.com/20319691/68930284-05246380-07b4-11ea-8e25-2346be3aee91.png)

#### Expected behavior:
There should not by any error via accessibility insights tool. We should not use aria-orientation="horizontal" with role="presentation". We can either change the role to "scrollbar" or remove aria-orientation="horizontal" and put it at the place where role is something other than "presentation".

Reference: https://www.w3.org/WAI/PF/aria/states_and_properties#aria-orientation

**Comment by micahgodbolt** [comment] 2019-11-15 17:12
this is a dupe of #11039

**Closed by micahgodbolt** 2019-11-15 17:13 UTC
Labels: Needs: Triage :mag:
