### ISSUE TITLE
https://uifabric.io/ isn't loading (https specific)

### ISSUE THREAD

**Issue by cwhitten** [OfficeDev/office-ui-fabric-react#7641] opened 2019-01-14 21:16 UTC
https://uifabric.io/

### Environment Information
- __Browser and OS versions__: Chrome, MacOS

#### Actual behavior:
 
Request gives up after hanging for quite some time.
 
#### Expected behavior:
 
The site should load successfully.

#### Priorities and help requested:
 
Requested priority: Blocking
 
Products/sites affected: (if applicable)

Microsoft Bot Framework is wanting to experiment with the Fluent theme in office-ui-fabric-react

**Comment by cwhitten** [comment] 2019-01-14 21:38
Same issue. Odd.

```
Google Chrome
Version 71.0.3578.98 (Official Build) (64-bit)
```

<img width="1673" alt="screen shot 2019-01-14 at 1 32 53 pm" src="https://user-images.githubusercontent.com/1156704/51142724-91b36d80-1801-11e9-8b52-cdfc04118163.png">

**Comment by micahgodbolt** [comment] 2019-01-14 22:35
Does this url work for you? https://developer.microsoft.com/en-us/fabric

**Comment by dzearing** [comment] 2019-01-14 22:36
I am reproing sporadically

**Comment by dzearing** [comment] 2019-01-14 22:37
@Jahnp

**Comment by Jahnp** [comment] 2019-01-14 22:45
Yeah--confirmed for me that following http**s**://uifabric.io hangs. The non-https version loads as expected. Will follow up with the domain folks (this is not something we directly control).

**Comment by cwhitten** [comment] 2019-01-14 22:46
Confirmed - thanks all

**Comment by Jahnp** [comment] 2019-01-14 23:02
I've reached out to the domains group about this matter. I'll update here when they have an ETA.

Thanks for reporting this @cwhitten !

**Comment by mikewheaton** [comment] 2019-01-23 16:17
@Jahnp Has there been any response?

**Comment by Jahnp** [comment] 2019-01-24 18:20
Apologies for the delay! I fell sick shortly after initially reaching out, and forgot to follow up here. My bad.

They did reply, but it turns out there's a different team for handling requests like this (e.g. adding HTTPS support to redirect rules). I just filed a ticket to get this resolved; that should take 1-4 days. Will follow up when I hear back.

**Comment by Jahnp** [comment] 2019-01-29 19:37
We're now expecting this to be completed by end of week.

**Comment by Jahnp** [comment] 2019-02-26 16:06
Apologies for the delay here. Update: Turns out the piece that was completed was only one portion of the total work required to enable the redirect. I'm following up to confirm the ETA of the "actual" fix. Since it's unknown at this moment, I'm going to move this to March. Sorry for the disruption here—still learning the process for this.

**Comment by Losses** [comment] 2019-04-23 10:26
@Jahnp  It's April, my frind...

**Comment by Jahnp** [comment] 2020-01-27 17:09
Some news here... after getting stuck in various interconnected internal processes for close to a year, this work has been complete. The team that owned the domain route rules (adding https redirects) was not the team that managed DNS records (allowing the route team to manage the domain in their system), so some coordination had to happen to make it work.

On the bright side, it means the following domains have https and www support now:
1. uifabric.com
2. uifabric.info
3. uifabric.io
4. uifabric.net
5. uifabric.org
6. officeuifabric.info
7. officeuifabric.io
8. officeuifabric.net
9. officeuifabric.org

Closing as I consider this resolved now.

**Closed by Jahnp** 2020-01-27 17:09 UTC
Labels: Resolution: External
