### ISSUE TITLE
@fabricui/fluent-theme SSR issues

### ISSUE THREAD

**Issue by bkniffler** [OfficeDev/office-ui-fabric-react#7374] opened 2018-12-12 14:16 UTC
Using fluent-theme will throw errors on using something like nextJS. I know I can import from lib-commonjs, but even those commonjs packages will import stuff like `office-ui-fabric-react/lib/Styling` which in turn uses es modules (instead of referencing `office-ui-fabric-react/lib-commonjs/Styling`).

There is more problems like `document undefined` due to `@microsoft/load-themed-styles/lib/index` `registerStyles` not checking if document is defined.

I could go and create the stack traces and detailed error messages, but I guess that the new fluent-theme is still in preview and this has not yet been optimized.

**Comment by Vitalius1** [comment] 2018-12-12 21:30
I am guessing @kenotron or @cliffkoh could be more helpful here as this is more related to imports (not my area of expertise 🙄)

**Comment by cliffkoh** [comment] 2018-12-13 02:53
@khmakoto please sync with @kenotron or myself offline to discuss a fix for this.

**Comment by khmakoto** [comment] 2018-12-13 17:01
Sorry @Vitalius1, I'll sync with @cliffkoh of @kenotron to discuss this. Thanks.

**Comment by kenotron** [comment] 2018-12-13 19:55
Two issues here:

1. SSR support for load-themed-styles is through a configuration - you can consult that package's configure load theme function: https://github.com/Microsoft/web-build-tools/blob/33d670bf12fb70a93b28c55d9103550eeadf0738/libraries/load-themed-styles/src/index.ts#L193

Also, check out the apps/ssr-tests to see how that works

2. Official answer: it's a bug, Fabric needs to fix it so that internally we don't reference anything through lib. Unofficial answer: to support esm in node, you can actually use a package like `esm`: https://www.npmjs.com/package/esm

**Comment by kenotron** [comment] 2018-12-14 18:14
I still think there MAYBE be a bug depending on where the imports are. 

Looking Mak’s massive conversion PR, we are mostly dealing with experimental packages and app packages. The issue is with fluent-theme imports of `office-ui-fabric-react/lib/Styling`. We should focus on that package in the PR probably.

As @dzearing said, if the imported target is large like OUFR itself, we shouldn't import that whole package. I agree with this. **However**, /lib/Styling from OUFR is a direct forward of @uifabric/styling. In that case, I would have expected the replacement here in Mak’s PR to be:
 
 import {Foo, Bar} from ‘@uifabric/styling’;
 
Rather than
 
  import {Foo, Bar} from ‘office-ui-fabric-react’;

**Closed** 2019-01-07 19:21 UTC
Labels: Area: Fluent, Package: fluent-theme
