### ISSUE TITLE
All of sudden styles got changed for command bar

### ISSUE THREAD

**Issue by ymihir** [OfficeDev/office-ui-fabric-react#11225] opened 2019-11-15 17:50 UTC
I am using commandbar where I am getting borders for every command option from today. Yesterday Everything works fine. Any changes were added?
![image](https://user-images.githubusercontent.com/7568187/68964100-1f534700-079e-11ea-91ed-301ff84a639f.png)

Below are dependencies in package.json:
```
"dependencies": {
    "@material-ui/core": "^4.5.1",
    "@material-ui/icons": "^4.5.1",
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-lodash-subset": "1.9.1",
    "@microsoft/sp-office-ui-fabric-core": "1.9.1",
    "@microsoft/sp-webpart-base": "1.9.1",
    "@pnp/common": "^1.3.6",
    "@pnp/logging": "^1.3.6",
    "@pnp/odata": "^1.3.6",
    "@pnp/sp": "^1.3.6",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "material-table": "^1.52.0",
    "office-ui-fabric-react": "6.189.2",
    "react": "16.8.5",
    "react-accessible-accordion": "^3.0.0",
    "react-dom": "16.8.5",
    "react-responsive-accordion": "^1.0.0",
    "toastr": "^2.1.4"
  }
```

**Comment by dzearing** [comment] 2019-11-15 18:20
This is a needle in a haystack. You need to do investigation for your scenario here.

1. Inspect your scenario. Find where the borders are being defined. Likely some other css in your app is targeting all buttons or something.

2. If you think it's Fabric, go to the doc site (https://developer.microsoft.com/en-us/fabric#/controls/web/commandbar) and click "Export to codepen". 

3. In the codepen, you can adjust the version of Fabric to your version by changing the unpkg.com url to your applicable version. In your case, I see 6.189.2, so:

![image](https://user-images.githubusercontent.com/1110944/68965806-83bbd980-0791-11ea-97c8-8e2ec550e9d6.png)

4. Does it repro? *Then* log an issue and we can help investigate further and see if something was introduced. Otherwise there's not much we can do.

**Comment by dzearing** [comment] 2019-11-15 18:32
https://codepen.io/dzearing/pen/xxxQXVb Here's a codepen to start with, but I wanted to give those instructions above for future reference :)

**Comment by SimSpfx** [comment] 2019-11-18 07:01
Hello,

I had this issue too. Since i did not update any package or class, i think it is a sharepoint update. the border comes from the root class if you inspect the element. 

Kind regards
Simon

**Comment by hamedy** [comment] 2019-11-18 10:02
same here, haven't touched my solution and this morning got borders around CommandBarButton. a bit later they disappeared and now they are back!

**Comment by hamedy** [comment] 2019-11-18 10:58
actually same thing is happening in SP online too.

**Comment by bva999** [comment] 2019-11-18 11:17
I have same issue in SPO.

**Comment by mfdezvil** [comment] 2019-11-18 16:24
Same error in my SPO, I haven't touched anything on my solution and suddenly borders appeared in command bar buttons. I have Office UI Fabric version 6.191.0

**Comment by RoelVB** [comment] 2019-11-18 16:30
I've started seeing this in multiple SPO tenants since last Friday. All using OfficeUI version 6.x.
First is was in both targeted and standard release tenants, but now it's only in standard release (**targeted is fine now**)

**Comment by mfdezvil** [comment] 2019-11-21 07:43
Hi, looks like its fixed now... at least for my tenants. Thanks.

**Comment by RoelVB** [comment] 2019-11-21 08:20
I can confirm. Checked it on 3 different tenants.

**Comment by bva999** [comment] 2019-11-22 06:56
Yes , fixed!

**Closed** 2019-11-27 13:00 UTC
Labels: Needs: Actionable Feedback :female_detective:, Status: No Recent Activity, Type: Question ❔
