### ISSUE TITLE
CSS loaded in wrong order?

### ISSUE THREAD

**Issue by Nasicus** [OfficeDev/office-ui-fabric-react#9786] opened 2019-07-12 06:43 UTC
We had this problem since a long while, currently we're using `6.134.0`. However to verify that this still occurs I even upgraded to the latest version (`7.8.2`).

Setup:
 - Typescript react app (with latest `Create React App`)

Problem:
For some reason on **production builds** (with `npm start` it works!) the order of the CSS which is loaded is wrong, which leads to styling-problem. Up until now we could somehow always workaround the problem, by specifying a more accurate CSS identifier for our own classes, but now this even happens with the fabric core classes `ms-bgColor....`.

Example:

In the following screen we have a `DefaultButton` which has an additional custom CSS class applied as well as a `ms-bgColor` class....as you can see the `root-38` class overrides the styles from the more specific classes:
![image](https://user-images.githubusercontent.com/1086065/61107651-bcb10e00-a480-11e9-8157-d5a83453300e.png)

I read that the `ms-bgColor` classes are not the recommended way of doing things anymore...ok so I did it via the `getTheme()` (additionally done in styled components, but shouldn't matter I guess):

```
const StyledDefaultButton = styled(DefaultButton)`
  background-color: ${getTheme().palette.neutralLight};
  & :hover {
    background-color: ${getTheme().palette.neutralQuaternaryAlt};
  }
`;
``` 

But the result is the same:
![image](https://user-images.githubusercontent.com/1086065/61107812-0b5ea800-a481-11e9-9e76-b09edc672b22.png)

Any idea what could cause this?
I'm not sure if this is related to UI fabric or something other could be the problem.
However I have no idea what it could be...I'm hoping someone can point me in the right direction.

**Comment by Vitalius1** [comment] 2019-07-12 16:22
@dzearing I remember a thread on Teams with similar issue from one of our partners. Do you know if the issue got a resolution?

**Comment by Vitalius1** [comment] 2019-07-12 18:02
@Nasicus would be really helpful if you could provide a repro project that we can investigate on.

**Comment by dzearing** [comment] 2019-07-12 18:10
Having a difficult time reproing;
https://github.com/dzearing/test-css-bug-repro

I made a git repo using create-react-app
Added oufr 7 and styled-components
Styled up a NewPrimaryButton
Rendered old and new, even tried conditionally in different orders
Run `npm run build`
Run `serve build`

See things in the correct order:
![image](https://user-images.githubusercontent.com/1110944/61149310-a3668c80-a495-11e9-8e52-117f878f8782.png)

**Comment by dzearing** [comment] 2019-07-12 19:57
I got it to repro. The issue is that these rules are 1 level of specificity, so the resolution depends on the order in which `style` elements exist in the head. Last one wins. In this case you want the styled-component element to appear later than the fabric ones.

Here's what happens under the hood with merge-styles:

When a Fabric component is initially loaded, some css rules are registered early.
You render your first component, we will try to append a style element to the head. Any subsequent `style` elements we append become siblings to that initial element.

The same thing happens with styled-components. You can see below that this is probably what you're looking at: the `style` elements with the `data-merge-styles` attributes are appearing later than the one tagged with `data-styled`. You want the reverse.

![image](https://user-images.githubusercontent.com/1110944/61154508-27734100-a4a3-11e9-8f44-153e63ee962c.png)

I was able to repro it by forcing styled-components to "go first". I basically added:

```tsx
import { css } from 'styled-components';

css`
background: red;
`;
```

Early enough in the app startup, before fabric imports, to get it to register a style element. They when fabric gets imported, the stylesheets appear out of order.

We could certainly make a fix to merge-styles to respect an existing style element, and append after it. For example, because you can control the head in your app, you could add an element like so:

```tsx
<style data-merge-styles />
```

This would act as a placeholder where style elements should be inserted. @Vitalius1 you could make a change in `Stylesheet.js` to look for this on initial "getStyleElement" element creation to start appending after.

What do you think?

**Comment by Nasicus** [comment] 2019-07-12 21:15
Thank you guys so much for putting effort into resolving this!

I cannot (quickly) provide an example though, since this is from my company's app, however I can try to reproduce it.

I could also provide you a list of all npm packages if this helps.

@dzearing 
Yep I always was "knew" that it must have to do in how the css / style tags are added to the header. However I didn't find a way yet to "change" it.
After reading your research I checked our files (starting from `index.ts` until to the components where it fails first).

However already in the `index.tsx` we load:
`import { LayerHost } from 'office-ui-fabric-react/lib/components/Layer';`

and then ~2 files later in the file with the problems the import of  some other `office-ui-fabric` stuff also comes before styled components.

Plus what I don't really get too is why are even your "own" classes (`ms-BgColor...`) overwritten by the `root-xx` styles?

**Comment by Nasicus** [comment] 2019-07-12 21:26
@dzearing  @Vitalius1 

Ok you were exactly right! It has to do with the order could reproduce it with this minimal example too:

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';

// if the lines are in this order it won't work, if you swap them it works properly
import 'office-ui-fabric-react/dist/css/fabric.min.css'; 
import { DefaultButton } from 'office-ui-fabric-react';

ReactDOM.render(
  <div>
    <DefaultButton className="ms-bgColor-themePrimary" >
      test
    </DefaultButton>
  </div>,
  document.getElementById('root')
);

```

![image](https://user-images.githubusercontent.com/1086065/61159462-6e415500-a4fc-11e9-94fb-a507ddc894d0.png)

What I still don't understand / can't believe, that I couldn't find any other people / issues with the same problem...and we have this since a long time already.... hmm

**Comment by Vitalius1** [comment] 2019-07-13 03:44
@Nasicus glad that you got it sorted out. I actually learned some new stuff from David’s investigation.

@dzearing I feel like relying on the dev to provide a placeholder style element to solve load order issues is not going to scale as we would need to document this in a very good way. I can add this functionality with a fallback to the current behavior in case there is no placeholder provided and will have to follow up with proper documentation of this scenario.

Will mark this issue as not an issue and it will be soft closed by the bot.

**Comment by Nasicus** [comment] 2019-07-13 07:37
To be honest. I have not yet resolved this at all. I need to investigate "the workaround" (ordering) in our own Project, because as far as I could see in the `index.tsx` it is already in correct order. So basically I need to check if I have to order *every* file in the correct order and if this will resolve the problem...

**Comment by Nasicus** [comment] 2019-07-15 06:03
Sorry but again: This is not closed for me.

Yes I could reproduce it, yes I could "fix" it in the example by chaning the import order.

However now I just tested what happens if it's working and I do a production build (`npm run build`).
And guess what?
It doesn't work anymore, and the CSS is once again loaded in the wrong order in the DOM!

**Comment by dzearing** [comment] 2019-07-15 17:48
Hey @Nasicus no worries, we are certainly going to fix this. This was mistagged. I discussed with @Vitalius1 this morning on this plan:

If a `<style date-merge-styles>` tag exists when we initially inject styling, we will inject after that. This gives the app dev a way to control where styles get injected.

By default, we will append the first style element to the beginning of the head, rather than at the end. There is no scenario where we want our rules to be more specific than yours.

**Closed** 2019-07-17 15:26 UTC
Labels: Area: merge-styles, Status: In PR, Type: Feature
