### ISSUE TITLE
Dropdown control has no type-ahead. (Long lists are difficult to browse through)

### ISSUE THREAD

**Issue by Pangamma** [OfficeDev/office-ui-fabric-react#11102] opened 2019-11-06 23:21 UTC
### Environment Information

- **Package version(s)**:  "office-ui-fabric-react": "7.46.0"
- **Browser and OS versions**: All browsers, Windows 10

### Describe the issue:

Dropdown control has no typeahead. When expanded, the expected behavior is that you should be able to start typing and the dropdown will skip ahead to matches that fit what you just started typing. Most drop downs with a lot of options allow the user to type to move the selected option. A country dropdown list is an example of this. 

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/pangamma/pen/Baaxzqx
#### Actual behavior:

The user is not able to type to find options easier.

#### Expected behavior:

user is able to type to find options. Possibly with a small buffer so that if a user types "united s" and then stops, "united states" would be shown, instead of the first answer starting with "s".

### Documentation describing expected behavior

See above

**Comment by JasonGore** [comment] 2019-11-06 23:24
Covered by #6030. Duplicate of #6565.

**Closed** 2019-11-10 00:00 UTC
Labels: Component: Dropdown, Needs: Author Feedback, Resolution: Duplicate, Type: Feature
