### ISSUE TITLE
New Component: Grid Layout

### ISSUE THREAD

**Issue by maxali** [OfficeDev/office-ui-fabric-react#786] opened 2017-01-11 10:38 UTC
### Suggestion: components for style layout classes

Components for Layouts like:

```
<GridRow>
  <GridCol sm12 md4 lg2>
    <Menu onClick={ this.updatePageInfo }/>
  </GridCol>

  <GridCol sm12 md8 lg10>
    <PageInfo />
  </GridCol>
</GridRow>
```

instead of:
```
<div className="ms-Grid-row"> 
  <div className="ms-Grid-col ms-u-sm12 ms-u-md4 ms-u-lg2">
    <Menu onClick={ this.updatePageInfo }/>
  </div>
  <div className="ms-Grid-col ms-u-sm12 ms-u-md8 ms-u-lg10">
    <PageInfo />
  </div>
</div>
```

#### Expected behavior:
I think it will save keystrokes and simple to memorize component names instead of long abbreviated class names.

Its also more readable.

Any idea about this?

**Comment by dzearing** [comment] 2018-06-21 20:35
We are going to do this!

**Comment by micahgodbolt** [comment] 2018-12-28 22:30
duplicate of #5418

**Closed by micahgodbolt** 2018-12-28 22:30 UTC
Labels: Needs: Backlog review, Needs: Design 🎨, Priority 2: Normal, Type: Feature
