### ISSUE TITLE
Updating to React 15 causes errors when using TextFields

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#235] opened 2016-09-01 23:47 UTC
ERROR: 'Warning: TextField contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components'

**Comment by dzearing** [comment] 2016-09-02 00:33
Duplicate of https://github.com/OfficeDev/office-ui-fabric-react/issues/4

**Closed by dzearing** 2016-09-02 00:33 UTC
