### ISSUE TITLE
ComboBox active option does not have a boarder like Dropdown which makes it difficult to see what's selected

### ISSUE THREAD

**Issue by vivianhoang** [OfficeDev/office-ui-fabric-react#5245] opened 2018-06-18 20:20 UTC
### Bug Report 
 
- __Package version(s)__: 5.112.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: VSTS
 
#### Describe the issue:
 
Selecting an option via keyboard is difficult to see without a border, especially for those with sight disabilities. ComboBox should have a border or another visible indication that it is the active element.

ComboBox:
![image](https://user-images.githubusercontent.com/20330957/41559778-f8173b7c-72f9-11e8-9ee2-858386c54f44.png)

vs.

Dropdown:
![image](https://user-images.githubusercontent.com/20330957/41559746-da732e82-72f9-11e8-98a3-02c44c932e13.png)

**Comment by lynamemi** [comment] 2018-06-18 20:40
Closing as dupe of https://github.com/OfficeDev/office-ui-fabric-react/issues/3472

I agree, we should really fix this! Maybe someone with more JS styling expertise can help figure out why the focus styles aren't getting applied for ComboBox options. @cliffkoh @JasonGore

**Closed by lynamemi** 2018-06-18 20:40 UTC
