### ISSUE TITLE
Support Portals in Layers to support React 16.3 Context

### ISSUE THREAD

**Issue by cobbs-totem** [OfficeDev/office-ui-fabric-react#4911] opened 2018-05-18 01:46 UTC
I've been switching over much of my Redux code over to React 16.3 Context and noticed that Context Consumers don't seem to get props.  I believe this is because Modals create a layer outside of the App and therefore is not contained by the Context Provider.

I guess this is a question to any inside or outside the Office UI community- what's the appropriate path here?  Bridge it by passing props directly to the Modal and letting the Modal become the new Context Provider?

Thanks!

**Comment by jordandrako** [comment] 2018-05-24 17:49
In 6.0 beta, the min bar for Fabric React will be React 16.3, so once that is released stable, we'll update our layers to use React Portals which should be compatible with the new context API.

**Comment by micahgodbolt** [comment] 2018-08-30 16:42
dupe of #4849

**Closed by micahgodbolt** 2018-08-30 16:42 UTC
Labels: Request: Feature
