### ISSUE TITLE
ChoiceGroup: cannot use arrows to move to other radio controls on Edge with Narrator

### ISSUE THREAD

**Issue by ssingh28** [OfficeDev/office-ui-fabric-react#5285] opened 2018-06-21 09:33 UTC
On Edge with Narrator On it is not possible to navigate from one option to another of choice group. This behavior is also available on MS Fabric React page https://developer.microsoft.com/en-us/fabric#/components/choicegroup . Even here when the narrator is on it has to go through text on each individual buttons and righ and left cursor keys don't work..

**Comment by dzearing** [comment] 2018-06-21 20:24
@kkjeer Can you please help investigate this? I'm unsure if this is a real issue or an Edge/Navigator issue.

**Comment by JasonGore** [comment] 2018-06-21 20:28
ChoiceGroup navigation seems to be working fine with me when using Narrator and Edge. I can switch between options as expected. It does not go through text.

This seems to be a duplicate of #4938.

Are you sure [scan mode](https://support.microsoft.com/en-us/help/22809/windows-10-narrator-using-scan-mode) is not enabled?

**Comment by JasonGore** [comment] 2018-06-21 20:29
I'm going to close this as a duplicate of #4938.

**Closed by JasonGore** 2018-06-21 20:29 UTC
Labels: Area: Accessibility, Component: ChoiceGroup, Needs: Investigation 🔍

**Comment by ssingh28** [comment] 2018-06-22 06:37
@dzearing @JasonGore @kkjeer : The issues I have reported are w.r.t to keyboard navigation on Edge with Narrator On. These issues may not be reproducible when you choose mouse control instead.
Hence please have a look into them again.

**Comment by JasonGore** [comment] 2018-06-22 14:24
Please read the link I provided about scan made. This has nothing to do with mouse control.

Regardless, this bug is still a duplicate of #4938.
