### ISSUE TITLE
Styling of Nav's links does not work for pseudoclass states

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#5577] opened 2018-07-16 08:44 UTC
### Bug Report 
 
- __Package version(s)__: 6.22.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal, though this may become high/blocking soon for product, since we're in the last design finalization phase.

#### Describe the issue:
 
I try to style a Nav element in our app, including the :hover/:active states of the links. Right now, I'm trying to do this via the following style function:

```ts
private static getNavStyles: IStyleFunction<INavStyleProps, INavStyles> = ({ theme }) => {
	const background = theme.palette.neutralLighter;
	const backgroundHover = toneDown(background);
	const backgroundPressed = toneDown(backgroundHover);
	return {
		root: {
			background
		},
		compositeLink: {
			background,
			selectors: {
				":hover": {
					background: backgroundHover
				},
				":hover $link": {
					background: backgroundHover
				},
				":active": {
					background: backgroundPressed
				},
				":active $link": {
					background: backgroundPressed
				}
			}
		},
		link: {
			selectors: {
				":hover": {
					background: backgroundHover
				},
				":active": {
					background: backgroundPressed
				}
			}
		}
	};
};
```
 
#### Actual behavior:
 
The selector styles affect only the hover/active style of the compositeLink, but the styling of the button links is unaffected.
 
#### Expected behavior:
 
Both, link and compositeLink elements should be affected by the supplied styles.
 
### If applicable, please provide a codepen repro:
 
https://codepen.io/nimelrian/pen/MBKxwx

**Comment by micahgodbolt** [comment] 2018-07-16 16:58
I'm hoping there is a better, more permanent solution, but you can accomplish this via classnames if necessary

https://codepen.io/micahgodbolt/pen/jpqMGb?editors=1010

**Comment by cliffkoh** [comment] 2018-07-27 03:01
@Nimelrian I was able to get it to work like this (just a minor modification)
https://codepen.io/cliffkoh-the-styleful/pen/WKZGqG

The problem is that the default selector has a specificity of 3, so the selector you introduce loses and does not take effect.

**Comment by cliffkoh** [comment] 2018-07-27 03:01
I will close this as resolved. Please feel free to reopen if you have questions (e.g. if I misinterpreted what you're trying to achieve here).

**Closed** 2018-07-27 03:01 UTC
Labels: Component: Nav, Priority 2: Normal
