### ISSUE TITLE
Fluent Theme conflicts with Jest

### ISSUE THREAD

**Issue by ArrayKnight** [OfficeDev/office-ui-fabric-react#9150] opened 2019-05-20 17:29 UTC
### Environment Information 
 
- __Package version(s)__:
- "@uifabric/fluent-theme": "0.16.9"
- "jest": "24.7.1",
- "react": "16.8.6"
- "create-react-app": "3.0.1"
- "typescript": "3.4.5"

### Please provide a reproduction of the bug in a codepen:

Using a standard setup from Create React App, without building or importing anything else, the Fluent Theme import fails on compilation for running the test suite.

`npx create-react-app my-app --typescript`

`cd my-app`

`npm install @uifabric/fluent-theme`

Add `Theme.test.tsx` to `src`

```
import React from 'react'
import { FluentCustomizations } from '@uifabric/fluent-theme'

describe('Fluent Theme', () => {
    it('should pass', () => {
        console.log(FluentCustomizations)

        expect(true).toEqual(true)
    })
})
``` 

Run `jest Theme`

#### Actual behavior:

 ```
 FAIL  src/Theme.test.tsx
  ● Test suite failed to run

    C:\Users\ArrayKnight\Git\my-app\node_modules\office-ui-fabric-react\lib\Styling.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import './version';
                                                                                                    ^^^^^^^^^^^

    SyntaxError: Unexpected string

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/@uifabric/fluent-theme/lib-commonjs/fluent/src/fluent/styles/Breadcrumb.styles.ts:2:1)
```
 
#### Expected behavior:
 
Test should pass.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High

**Comment by kenotron** [comment] 2019-05-20 18:08
@Vitalius1 - all of these files that import from `office-ui-fabric-react/lib/xyz` will break anyone doing tests. Here's an excerpt from `/packages/fluent-theme/src/fluent/styles/Breadcrumb.styles.ts`

```ts
import { IBreadcrumbStyleProps, IBreadcrumbStyles } from 'office-ui-fabric-react/lib/Breadcrumb';
import { FontWeights } from 'office-ui-fabric-react/lib/Styling';
```

Can we just change these back to the root of it?

**Comment by Vitalius1** [comment] 2019-05-21 02:01
@kenotron the error that is mentioned above looks like is complaining because of `import './version';` and the author mentions that it's failing without building it first.

**Comment by ArrayKnight** [comment] 2019-05-21 16:04
Getting Jest to render node_modules is counter to intent. It would either/both have a substantial negative effect on build time and/or require a special setup to override the default build behavior.

It seems like the references could be updated to point at the `lib-commonjs` versions (?) since pointing at root seems to be an issue for the `odsp-next` team.

**Comment by kenotron** [comment] 2019-05-22 18:02
@Vitalius1 - the only reason why it's importing from ./version with that `import` keyword is because we weren't using the root import from OUFR. Why is pointing at root an issue for `odsp-next`? There are a lot of places where we import from root internally...

**Comment by Vitalius1** [comment] 2019-05-23 01:54
@kenotron `odsp-next` will be choke with a size increase due to the bundler they use... that is from @ThomasMichon explanation he gave me real quick.

**Comment by ArrayKnight** [comment] 2019-05-23 15:31
Sorry @kenotron I don't. It was just brought up in the PR.

**Comment by kenotron** [comment] 2019-05-28 22:05
@ThomasMichon & @Vitalius1 - It really seems I do not have any alternative than what the compromise was already checked in. Unless you can come up with something I'm just going to have to soft close this with @ArrayKnight's blessing. Because we have to service multiple teams who package differently, we have to resort to the strange lib-commonjs convention.

**Comment by ArrayKnight** [comment] 2019-05-29 21:02
For reference, this is what I added to my `jest.config.js` to get the test to pass:
```
moduleNameMapper: {
    ...
    '^office-ui-fabric-react[/\\\\]lib(.*)': 'office-ui-fabric-react/lib-commonjs$1',
},
```

If closing the issue makes the most sense go for it. Keeping the issue open might help serve as a reminder and a source for future devs. I'd say this should still be addressed when possible. You may want to document this workaround for now.

**Comment by kenotron** [comment] 2019-05-29 21:36
It's a bit buried somewhere, but it is documented in our wiki: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Fabric-6-Release-Notes#lib-commonjs

I'll use the "Needs: Author Feedback" to soft-close this issue - Fabric team doesn't close bugs by humans for the sake of friendliness to the community :)

**Comment by ArrayKnight** [comment] 2019-06-04 15:32
@lalicari I had already ejected on my CRA, so it wasn't an issue. But that does make sense. Sorry this solution doesn't work for you

**Comment by kenotron** [comment] 2019-07-12 22:01
Yes, I cannot do much more here unless we come up with a different scheme for how we do ESM & commonjs.

**Comment by dirkesquire** [comment] 2019-08-15 12:52
Please could you let me know if we have gotten any further with this?
Out team is struggling to test any react components that use @uifabric/fluent-theme inside of them. 

I've tried this:
```
moduleNameMapper: {
    '^office-ui-fabric-react[/\\\\]lib(.*)': 'office-ui-fabric-react/lib-commonjs$1'
}
```

Jest still errors out with the identical error listed in the first post. 

We are using react-scripts which uses jest and we are using Typescript. 
Any advice please?

**Comment by micahgodbolt** [comment] 2020-01-02 23:46
@dirkesquire now that 7.x is long out, have you been able to migrate and discontinue using fluent-theme?

**Comment by dirkesquire** [comment] 2020-01-07 05:36
Thank you - yes I can confirm I am using 7.x now and I managed to work around the problem, although its a while back now and I can't quite remember how. It might have been just getting the jest.config.js just right.  We are still using fluent-theme (we haven't discontinued using it).

**Closed** 2020-01-14 07:00 UTC
Labels: Area: Fluent, Needs: Author Feedback, Package: fluent-theme, Priority 1: ASAP, Resolution: By Design, Status: No Recent Activity, Type: Bug :bug:
