### ISSUE TITLE
DetailsList: Selected items don't track item when sorting

### ISSUE THREAD

**Issue by newtonsheikh** [OfficeDev/office-ui-fabric-react#6206] opened 2018-09-04 08:41 UTC
Hi,

I am not sure if, this is a bug or i am doing it wrong. 

Steps:
1. In the DetailsList (https://developer.microsoft.com/en-us/fabric#/components/detailslist), take the first example 
2. Select a row(may be the first row), the row gets greyed to show the selection. 
3. Now hit the column header to sort
4. The data gets sorted, but the selection doesnt float along with the sorting. The selection remains on the row 1, though the data has moved

Is this by design? How do i make sure that the selection floats along with the sorting??

The selection works with the DetialsList property called "setKey" but somehow the documentation for it missing. [https://github.com/OfficeDev/office-ui-fabric-react/issues/6009](url)

**Comment by micahgodbolt** [comment] 2018-09-04 18:30
Hey @ThomasMichon is this simply a missing feature, or is there a prescribed way to have your selections track when sorting a list?

**Comment by davsm** [comment] 2018-09-06 19:04
I need to keep the row selection in sync with other content on the screen that is outside the list. I am keeping it in sync now by handling the onItemInvoked action. The problem is when the list is sorted, the selection stays on row index that was previously selected, and the onItemInvoked is not fired - so now the content is out of sync. 

Maybe there isn't a prescribed way, but since I asked for the list to select by "Key", I expected that the selection would stay on that "Key" until I changed it. 

If there isn't a prescribed way, then I see 3 possibilities:

1. If I ask to select a Key, then the Key should stay selected as long as that item is in the list. (my vote)

2. Sorting could mean that we are discarding the previous selection - in which case the selection needs to be removed (and then probably an action should be raised to indicate the selection changed)

3. Sorting could mean that it should select a different row (different Key). In this case, then for sure some action like list.onItemInvoked should be raised.

(I just realize there is selection.onItemSelection... is that being fired when the selection changes due to sort? If it is, then maybe we can just update the sort documentation.)

**Comment by DanielHirschTpg** [comment] 2018-12-17 20:54
Just had the same issue. You need to implement the `getKey` callback of the `Selection` that you set to the `DetailsList`. Apprently, without the callback, the selection must internally work with row indexes. Once you supply the `getKey` method callback, which should return the `setKey DetailsList` value for an item passed to the callback, the selection is persisted properly after sorting.

**Comment by KevinTCoughlin** [comment] 2018-12-19 05:45
> Just had the same issue. You need to implement the `getKey` callback of the `Selection` that you set to the `DetailsList`. Apprently, without the callback, the selection must internally work with row indexes. Once you supply the `getKey` method callback, which should return the `setKey DetailsList` value for an item passed to the callback, the selection is persisted properly after sorting.

Need to confirm the above, but 👍 if its a workaround. I wonder if we can:

1. Improve OUFR documentation regarding this scenario
2. Improve the API between `DetailsList` and `Selection`.

We've recently had a number of related questions and bugs.

**Comment by DanielHTpg** [comment] 2018-12-19 08:19
I dont believe it's a workaround but rather the correct implementation. Like you mentioned, the use case is just not properly documented. 

If you would indeed improve the API between both `DetailsList` and `Selection`, the `getKey` callback might not be necessary by detault if the `DetailsList` passed the `setKey` to the `Selection` which would then create a "default" `getKey` callback

**Comment by barbara-lea** [comment] 2019-07-17 11:19
> Just had the same issue. You need to implement the `getKey` callback of the `Selection` that you set to the `DetailsList`. Apprently, without the callback, the selection must internally work with row indexes. Once you supply the `getKey` method callback, which should return the `setKey DetailsList` value for an item passed to the callback, the selection is persisted properly after sorting.

Could you help me out with this? I thought that the `Selection`'s `getKey` callback should be a function providing a given item's key. How should this be set to always return the `setKey` of the `DetailsList`? 
The sorting + selection does not work for me with this approach.

**Comment by newtonsheikh** [comment] 2019-11-13 12:21
@micahgodbolt @ThomasMichon 

I guess this one is fixed now. now selected row floats when sorting. :)

**Comment by micahgodbolt** [comment] 2019-11-13 21:49
Sounds good, closing the issue

**Closed by micahgodbolt** 2019-11-13 21:49 UTC
Labels: Component: DetailsList, Type: Feature
