### ISSUE TITLE
Fabric UI Grid-System stylesheets aren't loading. 

### ISSUE THREAD

**Issue by Kenn-o** [OfficeDev/office-ui-fabric-react#11236] opened 2019-11-18 05:43 UTC
###Description: 

1. We are currently using Fabric UI Grid styles in our SPFx Web Part Code. It is a project involving developing SharePoint Framework Web parts from SharePoint online. Our client is using the React Framework.
3. We've enabled the legacy Fabric UI styles in our Web Part Manifest Files
4. Fabric Ui Grid system style sheet are only loaded when we manually refresh the pages. 
5. This has been working for the last few weeks. We've noticed this problem in the last 72 hours. We are seeing similar issues on multiple O365 tenants. 

### Environment Information
**WebPart Manifest**

![image](https://user-images.githubusercontent.com/56100281/69027592-6d6c8280-0a0a-11ea-9ac5-f7f4c9968c72.png)

**Package Information**
"dependencies": {
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-lodash-subset": "1.9.1",
    "@microsoft/sp-office-ui-fabric-core": "1.9.1",
    "@microsoft/sp-webpart-base": "1.9.1",
    "@pnp/polyfill-ie11": "^1.0.2",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/smoothscroll-polyfill": "^0.3.1",
    "@types/webpack-env": "1.13.1",
    "mdn-polyfills": "^5.19.0",
    "office-ui-fabric-react": "7.61.1",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "smoothscroll-polyfill": "^0.4.4"
  },
  "resolutions": {
    "@types/react": "16.8.8"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.9": "0.7.16",
    "@microsoft/sp-build-web": "1.9.1",
    "@microsoft/sp-module-interfaces": "1.9.1",
    "@microsoft/sp-tslint-rules": "1.9.1",
    "@microsoft/sp-webpart-workbench": "1.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }
}

**HTML Code**

How it would look like from a Browser

**Before Refresh(Browser)** 
![image](https://user-images.githubusercontent.com/56100281/69028411-df45cb80-0a0c-11ea-8ac5-21646c9c3d3f.png)
![image](https://user-images.githubusercontent.com/56100281/69028384-cc32fb80-0a0c-11ea-982c-6b80a255196e.png)

**After refresh (Browser)**

![image](https://user-images.githubusercontent.com/56100281/69028442-f389c880-0a0c-11ea-80b5-9f8ee13a5c4e.png)

**Comment by Kenn-o** [comment] 2019-11-18 08:44
**Update**

We've found a temporary fixes by applying the following line to our CSS file:

**:global{ @import "../../../../node_modules/office-ui-fabric-react/dist/css/fabric.min"; }**

However, it has increased the page size by 1MB (because we have 4 x web parts @ 25kb each) for our SharePoint project. Hence, it would be great if we can drill down to the root cause and get a proper fix for this issue.

**Comment by TietjeDK** [comment] 2019-11-18 09:54
Any updates here? This is a major issue for our clients.

**Comment by davevh** [comment] 2019-11-18 13:26
We have the same problem that the grid system is not working anymore.

**Comment by aneeshack4** [comment] 2019-11-18 21:54
@Kenn-o @TietjeDK  @davevh There haven't been any recent changes to the Grid code in Fabric - the last change to Grid.base.tsx was 18 months ago (and the other files, last changes were 22 months ago). Is it possible that something within Sharepoint webparts was changed?

**Comment by aneeshack4** [comment] 2019-11-19 00:10
Spoke with Kevin offline - looks like there's work being done to solve the root problem in Sharepoint so I'll close this. If y'all find that it turns out to be a problem in Fabric, feel free to ping us on here again.

**Closed by aneeshack4** 2019-11-19 00:10 UTC

**Comment by Kenn-o** [comment] 2019-11-19 01:10
I've removed the following line(the interim solution) from our code:

**:global{ @import "../../../../node_modules/office-ui-fabric-react/dist/css/fabric.min"; }**

Re-deployed the WebParts to our dev environment. I can confirm the solution is now resolved. :)

**Comment by KevinTCoughlin** [comment] 2019-11-19 15:42
The problem was surfaced from the SPFx / SPO side. We've since reverted the change which caused the regression. Let's continue discussion in this issue if you are still facing the above issue (you shouldn't be): https://github.com/SharePoint/sp-dev-docs/issues/4911
