### ISSUE TITLE
FocusZone: bidirectional has an unexpected behavior for up down arrows 

### ISSUE THREAD

**Issue by skhule1984** [OfficeDev/office-ui-fabric-react#7247] opened 2018-11-28 22:49 UTC
**Bug Report**
Package version(s): office-ui-fabric-react 6.94.0
Browser and OS versions: IE 11 (11.407.17134.0)
Requested priority: High

**Describe the issue:**

On the 'FocusZone' component, setting the 'direction' attribute to 'FocusZoneDirection.bidirectional' does not work as expected for up and down arrow navigation.

**Repro Steps:**

We have a grid of tiles very similar to the grids under 'Variants' here - https://developer.microsoft.com/en-us/fabric#/components/focuszone

Set focus on the second tile by clicking on it .(1st row 2nd column)
Hit up arrow - The focus moves to the tile on the left (1st row 1st column).(this is unexpected behavior)
Hit down arrow - The focus moves to the tile on 2nd row 2nd column, instead of moving to the tile on 2nd row 1st column.(this is unexpected behavior)

On the other hand, when you click on some tile in the middle (any tile with tiles on the left and right), then hitting the up arrow key takes you to the tile in the same column one row up, 
and hitting the down arrow key takes you to the tile in the same column one row down.(this works as excepted)
Example: If you are on tile on 2nd row 3rd column, 
hitting up arrow take you to tile on 1st row 3rd column
and from there if you hit down arrow it will take you to 2nd row 3rd column
If you hit down arrow again, it will take you to 3rd row 3rd column. This is an expected behavior.

**Expected behavior:**
Set focus on the second tile by clicking on it .(1st row 2nd column)
If you hit up arrow, nothing should happen as there are no rows above it.
If you hit down arrow, it should take you to 2nd row 2nd column.

**Comment by aftab-hassan** [comment] 2018-11-28 23:09
@skhule1984 thanks for reporting. This seems like a bug, I will be working on it.

**Comment by betrue-final-final** [comment] 2018-11-29 00:16
I agree. This is a legit bug.

**Comment by natalieethell** [comment] 2018-11-29 22:21
I'll take this one.

**Comment by natalieethell** [comment] 2018-11-30 22:50
Ooh look's like @aftab-hassan has this one! I'll reassign him.

**Comment by aftab-hassan** [comment] 2018-12-07 17:36
Mark this issue as _Resolution: By Design_. Upon submitting this [PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/7277) to match the requested behavior, found tests (the ones that are failing) that were written with the original behavior as expected.

> Ah, yes. If I'm reading this correctly the current behavior has looping. I must have misunderstood initially, as that is ok.

@betrue-final-final's response [here](https://github.com/OfficeDev/office-ui-fabric-react/pull/7277#issuecomment-444366506) confirms the current behavior is by design. Thanks for confirming.

**Comment by aftab-hassan** [comment] 2018-12-07 17:56
@skhule1984 Thanks for submitting this. We have confirmed that the current behavior with looping is by design.

However, in order to get the behavior you were expecting, here is a possible fix. The fix is to check if the distance of the element from the center is a large value, LARGE_DISTANCE_FROM_CENTER, signifying no element to move to.

[Here](https://github.com/OfficeDev/office-ui-fabric-react/pull/7277) is a PR where this was implemented (we will not be merging this). [This](https://github.com/aftab-hassan/office-ui-fabric-react/blob/1e06350a111d5f0f09bb1d2621d67fef6497a858/packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx#L520) is the specific line number, where the fix begins.

```
let elementDistanceToBreak = -1;
    do {
      element = (isForward ? getNextElement(this._root.current, element) : getPreviousElement(this._root.current, element)) as HTMLElement;

      if (isBidirectional) {
        if (element) {
          const targetRect = element.getBoundingClientRect();
          const elementDistance = getDistanceFromCenter(activeRect as ClientRect, targetRect);

          elementDistanceToBreak = elementDistance;
          if (elementDistance === -1 && candidateDistance === -1) {
            candidateElement = element;
            break;
          }

          if (elementDistance > -1 && (candidateDistance === -1 || elementDistance < candidateDistance)) {
            candidateDistance = elementDistance;
            candidateElement = element;
          }

          if (candidateDistance >= 0 && elementDistance < 0) {
            break;
          }
        }
      } else {
        candidateElement = element;
        break;
      }
    } while (element);
    if (elementDistanceToBreak === LARGE_DISTANCE_FROM_CENTER) {
      return false;
    }
 
```

Please let us know if this helps, or if you have more questions

**Closed** 2018-12-14 20:00 UTC
Labels: Component: FocusZone, Needs: Author Feedback, Resolution: By Design, no-recent-activity

**Comment by skhule1984** [comment] 2018-12-28 19:52
+Adding folks from our team.

Hi Aftab,
Thanks for getting back on this issue.
I wanted to follow up on this discussion.
The concern we have here is, we really expect the behavior that we have described in the issue.
If we apply your PR we will have to keep patching on our end for every new build release you make. And that’s not what we are looking forward to do.
Since the behavior doesn’t really seem a normal expected behavior by a user, can you please consider fixing this on our end?
Please let us know your thoughts.

Thanks,
Shraddha.
