### ISSUE TITLE
Setting itemType to ContextualMenuItemType.Divider on CommandBar has no effect

### ISSUE THREAD

**Issue by chenxinyanc** [OfficeDev/office-ui-fabric-react#10035] opened 2019-08-02 10:00 UTC
### Environment Information

- **Package version(s)**: 7.19.0
- **Browser and OS versions**: Edge Dev 77.0.230.2 on Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/ZgJmvm

#### Actual behavior:
I cannot see the divider. The place where the divider is supposed to be shows a blank button.
![image](https://user-images.githubusercontent.com/50703224/62362089-d6f57d80-b54e-11e9-9181-d27ad1e6a8fd.png)

However I can see the divider in overflow menu
![image](https://user-images.githubusercontent.com/50703224/62362202-14f2a180-b54f-11e9-9bf3-2ff25efacb64.png)

This is likely to be a regression of #2749 .

#### Expected behavior:
I think I should be able to see the divider both on the command bar, and in the overflow menu.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal / Low

Products/sites affected: (if applicable) -

**Comment by marygans** [comment] 2019-08-03 00:17
Hi @chenxinyanc, thanks for submitting this issue! 

For clarity, are you trying to use the `ContextualMenuItemType.Divider` as a horizontal divider in your menu without any text content? 
Also, this doesn't seem to be a regression since the #2749 wasn't merged. If you're looking to use a vertical divider similar to the closed PR maybe try [VerticalDivider](https://fabricweb.z5.web.core.windows.net/oufr/7.19.1/#/examples/references/verticaldivider)?

**Comment by chenxinyanc** [comment] 2019-08-05 05:02
> For clarity, are you trying to use the `ContextualMenuItemType.Divider` as a horizontal divider in your menu without any text content?

I'm using `ContextualMenuItemType.Divider` because [`ICommandBarItemProps`](https://github.com/OfficeDev/office-ui-fabric-react/blob/27aa28f0bc898794482d55d6eed26d79217b6924/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.types.ts#L129) accepts [`itemType`](https://github.com/OfficeDev/office-ui-fabric-react/blob/27aa28f0bc898794482d55d6eed26d79217b6924/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts#L299) inherited from `IContextualMenuItem`. And this seems to be the only way I can change a button into a divider on the command bar. Actually I was not too aware how it looks in the overflow menu. Not compared to its appearance in command bar.

I was not specifying any `text` content because I believe it's the right thing to do. At least the [example of ContextualMenu](https://developer.microsoft.com/en-us/fabric#/controls/web/contextualmenu#usage) does not specify `text` for the divider.

> Also, this doesn't seem to be a regression since the #2749 wasn't merged. If you're looking to use a vertical divider similar to the closed PR maybe try VerticalDivider?

Just found out I have neglected some of the comments there. Oops. After some tries, I found I should specify `onRender` for `CommandBar` to show a Divider properly
```ts
{ key: "divider1", itemType: ContextualMenuItemType.Divider, onRender: () => <VerticalDivider /> },
```
CodePen: https://codepen.io/anon/pen/GVOmzL

`ContextualMenuItemType.Divider` is still needed for overflow menu to work.

Now my problem solved, but I think it would be better if ui-fabric-react can make such render function default for `ContextualMenuItemType.Divider`.

**Comment by marygans** [comment] 2019-08-05 21:21
@chenxinyanc I'm glad `VerticalDivider` worked for you. I do agree that it wasn't clear that onRender function needed to be used to pass the `VerticalDivider`. I can see a few different alternatives being suitable for this scenario in the future, thanks for your feedback :)

**Closed** 2019-08-06 22:00 UTC
Labels: Component: ContextualMenu, Resolution: Not An Issue
