### ISSUE TITLE
Running office-ui-fabric-react offline

### ISSUE THREAD

**Issue by cobbs-totem** [OfficeDev/office-ui-fabric-react#3186] opened 2017-10-21 20:55 UTC
Sometimes I like to develop/run my app offline (airplane, for example).  I've imported all .css with success and eliminated the links from my public/index.html.

However, it still requires some external font packages that I don't know how to import (.woff files).  Is there a way to import those and not depend on external links?

**Comment by CDoughty08** [comment] 2017-10-24 13:42
Also, curious about this!
As using fabric in a proxied environment that doesn't have access to sharepoint is a pain.

**Comment by cobbs-totem** [comment] 2017-11-29 15:47
I've been semi-successful in resolving this by passing in a baseurl to the initializeIcons() routine:

`initializeIcons("/@uifabric/icons/fonts/");`

Then, I let my nginx server know where to find those.  However, some icons still show up as "squares" instead of actual icons.

**Comment by michaelangotti** [comment] 2018-04-09 18:44
@Jahnp @dzearing Can one of you look into this?

**Comment by Jahnp** [comment] 2018-04-09 22:44
@cobbs-totem , that approach *should* work. Can you give an example of some icons that aren't showing up? Is this something you can demo in a Codepen or [Codesandbox](https://codesandbox.io/)?

For what it's worth, per #3218 , we're working on a tool that will allow you to create your own icon font subsets (.woff only) that you can host in your own environment. Right now, we can't that usage for Segoe, though. Is it mostly the icons that are causing issues for you?

**Comment by botbrix** [comment] 2018-06-15 14:47
I experience this same issue in offline environments.   Seems to be reproducible whenthe  pixel ratio is changed using zoom.  Pulled the latest file icons down to the baseurl path on my server.  Confirmed that it I'm passing in the baseurl to the initializeIcons().  Fabric fonts are rendering consistently on the other components, just not the file icons.

**Comment by JasonGore** [comment] 2018-08-14 16:27
Original poster never replied and #3218 is proposed as a solution, so I will close this issue for now. If it doesn't resolve your issue, please feel free to reopen.

Also, if you have a specific component having issues please fell free to open another issue. Thanks!

**Closed by JasonGore** 2018-08-14 16:27 UTC
Labels: Type: Question ❔
