### ISSUE TITLE
[Icon Tool] Error 500 Internal Server Error

### ISSUE THREAD

**Issue by e-gallis** [OfficeDev/office-ui-fabric-react#11133] opened 2019-11-08 21:50 UTC
### Environment Information
- **Browser and OS versions**: Win 10, Chrome 78.0.3904.97

### Describe the issue:
When trying to export the subset for a selection of icons in the Office UI Fabric Icons site, an error 500 is triggered after a while.

#### Actual behavior:
Error 500 is triggered.

#### Expected behavior:
Should generate the zip file.

### If applicable, please provide a codepen repro:
Go to Office UI Fabric Icons, select icons, click Get subset, click Ok

**Comment by JasonGore** [comment] 2019-11-08 22:46
I see it as well at https://fabricicons.azurewebsites.net/:
![image](https://user-images.githubusercontent.com/26070760/68515638-86b94600-0236-11ea-9a0e-8e9e5d9fc8a4.png)

**Comment by Jahnp** [comment] 2019-11-08 23:21
Thanks for the heads-up folks, and apologies for the disruption.

It turns out the same type of issue that plagued the site [before](https://github.com/OfficeDev/office-ui-fabric-react/issues/10462) is a problem here, though the cause is a little different. Basically, the Fabric icons tool is on a shared app service plan that's met its storage quota. As a result, the icons tool literally isn't able to write to disk, causing the 500 error you see here. 

Short term, we just need to clear up some disk space to get the site working again. We'll get started on this asap.

Longer-term, we'll look into ways to prevent this from happening again. That may mean moving the icons tool to its own service plan so it's more reliable.

Sorry again—we'll keep you posted as we fix this.

**Comment by Jahnp** [comment] 2019-11-08 23:52
Update: We've cleared some disk space (#engineeringftw) so the site should be functional again. Just tested it myself and am able to download subsets. @e-gallis , would you mind giving it another try when you have a chance?

**Comment by maxwellred** [comment] 2019-11-09 00:07
I also tried it successfully. Thanks, Peter!

**Comment by dzearing** [comment] 2019-11-09 03:50
confirmed as well, closing this out. Thank you for reporting!

**Closed by dzearing** 2019-11-09 03:50 UTC
Labels: Area: Website, Type: Bug :bug:

**Comment by e-gallis** [comment] 2019-11-09 18:20
Sorry, I wasn't available during the last 24 hours. I see everthing's fine now. Thanks for the quick fix @Jahnp.
