### ISSUE TITLE
role="link" to command bar menu items changing way of key board access.

### ISSUE THREAD

**Issue by saidas3524** [OfficeDev/office-ui-fabric-react#8062] opened 2019-02-21 09:52 UTC
### Environment Information 
 
- __Package version(s)__: 6.129.0
- __Browser and OS versions__: chrome, widows 10
### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/anon/pen/gqJrNe#anon-login

 
#### Actual behavior:
 up/down keys are being used for navigation between items

 
#### Expected behavior:
 left/right arrows should be used to navigate between items.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  High
 
Products/sites affected: (if applicable)
https://www.microsoftoem.com/

**Comment by aneeshack4** [comment] 2019-02-21 23:46
@saidas3524 Up/down doesn't work for me to go between New, Upload, Share, etc... (those are what you meant by items right?). I'm able to use only left/right arrows which is the expected behavior.

**Comment by saidas3524** [comment] 2019-02-22 10:05
@aneeshack4  when i use role="link" for the items, we are forced to use up/down arrows to navigate between commands. please check the code pen url for reproducing the issue.

**Comment by aneeshack4** [comment] 2019-02-25 18:55
@saidas3524 I am using your CodePen and I'm unable to repro. As you can see below, the item that I'm using the left/right arrows to navigate does have role="link" and I'm not able to use up/down arrows to navigate between the commands... 
![image](https://user-images.githubusercontent.com/4161791/53360925-b106e580-38eb-11e9-92b3-2e4db9ca5db1.png)

**Comment by saidas3524** [comment] 2019-02-26 05:04
@aneeshack4 , This is a weird behaviour. when i turn on NVDA and try to navigate, i can repro the issue. but if i turn the screen reader off, i cannot. Not sure if the bug is related to NVDA or the control.

**Comment by aneeshack4** [comment] 2019-02-26 07:02
This works on Edge & Chrome so this is likely a NVDA-specific problem and because we have no control over that, resolving as external.

**Closed** 2019-02-26 07:02 UTC
Labels: Component: CommandBar, Resolution: Can't Repro, Resolution: External
