### ISSUE TITLE
Picker with an icon

### ISSUE THREAD

**Issue by ParadimeWeb** [OfficeDev/office-ui-fabric-react#11751] opened 2020-01-21 15:02 UTC
#### Describe the feature that you would like added

The ability to add an icon to the picker components. Just like the TextField, we could have the iconProps to set an icon on the right side of the field.

#### What component or utility would this be added to

BasePicker

**Comment by khmakoto** [comment] 2020-01-21 21:59
Hi @ParadimeWeb, I think this is a fair feature request and we might want to take it into account when upgrading our `Picker` components, however, I don't know if we would currently put any effort into this. 

@joschect what are your thoughts here?

**Comment by joschect** [comment] 2020-01-22 20:25
@ParadimeWeb and @khmakoto I'm not sure that we should add an icon. There are a lot of different positions that the icon could go and it's going to end up being fairly distinct depending on who is using it. For a more customized experience I would suggest using the floating picker since you can have complete control over the input. Here's an example of it being used [here](https://codesandbox.io/s/basic-floating-picker-stivj)

**Comment by ParadimeWeb** [comment] 2020-01-23 21:12
I don't understand what you mean? Adding a icon just like the SearchBox would be perfect. Or like the TextField would also work. I don't even know what a floating picker is. Is that a component, I don't see it on the controls page.

**Comment by ParadimeWeb** [comment] 2020-01-23 21:21
Hi, using the floating picker puts a lot of work in managing the selections. You are suggesting I reproduce all the logic for showing the persona in the SearchBox, being able to remove them, select multiple. That is way to much work.

The best would be to add an iconProps to the BasePicker and have it exactly how the TextField component displays the icon.

**Comment by khmakoto** [comment] 2020-01-23 22:52
@ParadimeWeb your concern is real but we also have to take into account how much logic we should put into our library. @joschect any more thoughts on this?

**Comment by joschect** [comment] 2020-01-23 23:42
@khmakoto I have a few more thoughts. @ParadimeWeb I understand that it can be a bit of work to implement the selection behavior. A simpler alternative could be to do something like [this](https://codepen.io/slimemold/pen/XWJOwXW?editors=0111) where you override the border. You'll need to do just a little work to make sure that focus goes to the picker when the icon is clicked, but that's not bad. 

My concerns with adding the icon are this: we cannot account for all designs of where the icon should go and how it should act. If the icon really just needs to go to the right of the picker, then the codepen I provided a good place to start with it. You could even use your own styling function if you want. If the icon needs to do more complicated things, then the picker shouldn't own that. A possibility for the future would be to allow the input to be slotable/provide a custom render function. For right now though, the input is pretty tightly coupled with the component as a whole and it might take us a while to get to that.

**Comment by ParadimeWeb** [comment] 2020-01-24 16:05
I guess I'll leave the control without an icon. I don't like yours alternatives.

**Comment by khmakoto** [comment] 2020-01-24 19:40
Alright @ParadimeWeb, I'll be resolving this as "Resolution: By Design" then. I'm sorry we were unable to help you more with this but there is a balance to how much technical debt we are responsible as the platform vs people as developers using the platform and this would be tilting the balance a little too much to our side.

**Closed** 2020-01-31 23:00 UTC
Labels: Component: Pickers, Needs: Author Feedback, Resolution: By Design, Status: No Recent Activity, Type: Feature
