### ISSUE TITLE
CSS Modules: CSS style of Command button has been changed

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#1214] opened 2017-03-08 04:24 UTC
### Bug Report

- __Package version(s)__: beta 8
- __Browser and OS versions__: any

#### Describe the issue:

I noticed the style of button has changed after the change of module CSS:
before:
![image](https://cloud.githubusercontent.com/assets/16030290/23690002/5380edda-03f9-11e7-9a1f-4f915979c767.png)
![image](https://cloud.githubusercontent.com/assets/16030290/23689985/309a9a46-03f9-11e7-98ff-b565da2deb5f.png)
beta8:
![image](https://cloud.githubusercontent.com/assets/16030290/23689965/0bcc6528-03f9-11e7-9afc-a1a32c022c9a.png) 
![image](https://cloud.githubusercontent.com/assets/16030290/23690028/88f8b01a-03f9-11e7-8ab0-61a1357a4d2f.png)

#### Actual behavior:

I checked the code of command button, the style is changed a lot, take the button height as example, in master, the height is set when there is a .ms-Button-label or .ms-Button-icon class:
```
.ms-Button.ms-Button--command {
    ...
    .ms-Button-label,
    .ms-Button-icon {
      height: $button-commandButtonHeight;
      line-height: $button-commandButtonHeight;
    }
...
}
```
In module css, the height is set directly:
```
.root {
  @include button-core-root-styles;

  background-color: transparent;
  padding: 0 4px;
  height: $button-commandButtonHeight;
  color: $ms-color-neutralPrimary;
}
```

#### Expected behavior:

Should the style be the same?

**Comment by micahgodbolt** [comment] 2017-03-08 16:42
@dzearing and I did some refactoring of button styles, including moving to some different methods for height and layout. These changes are intentional. If they deviate from redlines or are causing regressions, plase let us know.

**Comment by dzearing** [comment] 2017-03-08 19:21
This is by design and there isn't an actual visual regression.

There should be 8px padding on each side; but in the changes, I made the paddings symmetrical. The icon has 4px on each side, the label text has 4px on each side, and the container itself has px on each side. So edges and inbetween elements will all have 8px, and even if you remove the icon or label, it will stay symmetrical without hacks, which wasn't really the case before (with padding-left hacks.)

**Closed by dzearing** 2017-03-08 19:21 UTC
