### ISSUE TITLE
ChoiceGroup: does not behave correctly within a FocusZone

### ISSUE THREAD

**Issue by haonliu** [OfficeDev/office-ui-fabric-react#7679] opened 2019-01-16 20:23 UTC
### Environment Information 
 
- __Package version(s)__: 6.121.0
- __Browser and OS versions__: win10 chrome

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/ZVZojB
 
#### Actual behavior:
 
users cannot change choice group's selected choice using arrow key inside focus zone
 
#### Expected behavior:
 
users should be able to change choice group's selected choice using arrow key inside focus zone

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) yes
 
Requested priority: (Blocking, High, Normal, Low) high
 
Products/sites affected: (if applicable)

**Comment by mikewheaton** [comment] 2019-01-16 20:34
This looks to be related to the buttons above and below the ChoiceGroup. Here's a CodePen without those buttons that doesn't have the issue: https://codepen.io/mikewheaton/pen/YdMvKB

**Comment by dzearing** [comment] 2019-01-17 15:49
@mikewheaton I think your codepen might be hiding the issue. There is definitely an issue here. Just to illustrate, I forked your codepen and moved the FocusZone around both ChoiceGroups.

https://codepen.io/dzearing/pen/bOyLdG

If you arrow up and down, you will see some really bad behavior.

Now, I will caveat all of this in asking a different question: why is a vertical `FocusZone` wrapping a `ChoiceGroup`? They will fight each other. `FocusZone` wrapping should really be for menu scenarios, so I'd be really interested in the actual usage scenario.

I think this is a bug with ChoiceGroup; here's what's happening:

When `ChoiceGroup` is the only thing within the `FocusZone`, There is only one element marked as `data-is-focusable=true`. This seems to be because `ChoiceGroup` is managing this. When you up and down arrow through options, the keypress events are not being stopped via `stopPropagation`, and therefore FocusZone ends up handling them, looking for the next focusable entity to move them to.

I think removing the data-is-focusable attribute componently may end up resolving this. The default tabbing behavior of radio buttons is pretty much how FocusZone works, so this wouldn't affect normal scenarios. But when in a FocusZone, it would interpret input elements as focusable (even without the data attribute) and handle the arrowing, moving focus to the next thing.

Needs some testing, but I think this is probably the best fix.

**Comment by haonliu** [comment] 2019-01-18 22:17
@dzearing Thanks for the details explanation. Our actual usage scenario is that we are using a details list to list a bunch of items, and in each row of the list there is a choice group. Since Details list has FocusZone inside, the choice end up living inside the focus zone.

**Comment by dzearing** [comment] 2019-01-18 22:20
@haonliu Ah thank you! I was nervous it was that combo. We will see how we can address.

**Comment by flyingUnderTheRadar** [comment] 2019-01-22 18:08
Any update on this @dzearing

**Comment by dzearing** [comment] 2019-01-25 04:46
I believe I have a fix ready for you. In PR now. Need to cycle with @JasonGore on why `data-is-focusable` was originally added.

**Comment by JasonGore** [comment] 2019-01-25 18:22
`data-is-focusable` was added in #5842 as a resolution for #5160 for this reason:

>Further analysis shows that FocusTrapZone is not detecting ChoiceGroup as a whole as the last tabbable child, only the last ChoiceGroupOption. As a result, FocusTrapZone does not trap tabs from any other ChoiceGroupOption, which ends up highlighting the next element outside of FocusTrapZone.

**Comment by dzearing** [comment] 2019-02-02 00:21
Just an update here, still looking at the right fix. I tried the repo from the old issue and see that this will introduce a different break.

**Comment by waabid** [comment] 2019-02-12 01:56
@dzearing any update on this?

**Comment by markreay** [comment] 2019-02-14 01:42
@dzearing - Can we help with this?

**Comment by dzearing** [comment] 2019-02-20 19:04
Sorry about the delay here; the fix we had would have caused additional regressions. We are still working on this.

**Comment by dzearing** [comment] 2019-02-22 02:48
This was fixed in https://github.com/OfficeDev/office-ui-fabric-react/pull/8053 and was published yesterday in 6.142.0:

https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v6.142.0

The codepen now works:
https://codepen.io/anon/pen/ZVZojB

**Closed by dzearing** 2019-02-22 02:48 UTC
Labels: Component: ChoiceGroup, Component: FocusZone, Type: Bug :bug:
