### ISSUE TITLE
Accessibility blocker: Calendar control: Tabbing inside control unexpectedly tabs to top of page

### ISSUE THREAD

**Issue by lukehumphrey** [OfficeDev/office-ui-fabric-react#8225] opened 2019-03-06 22:24 UTC
This bug is preventing Project from passing a PWD usability test and has been identified as a MAS bug.

repro:
Use Edge 
Open calendar control with month picker shown.
Tab 7 times inside control

Expected: Tab cycles inside control.
Actual: Tab reset to the browser address bar. Shift+tab does not exhibit this behavior (works as expected). Only forward tabs are broken here.

Can this be fixed in the short-term?
Contact PM lukehum@microsoft.com for more qs.

**Comment by aftab-hassan** [comment] 2019-03-08 02:02
@lukehumphrey thanks for reporting. Able to see this bug.

**Comment by JasonGore** [comment] 2019-03-15 00:16
This is a possible duplicate of #8134 which has been resolved.

**Comment by aftab-hassan** [comment] 2019-03-15 01:33
@lukehumphrey As @JasonGore's mentions, this was fixed.

Here is a video of it action while @leddie24 was reviewing it
https://streamable.com/zc06v

Thanks for letting us know @JasonGore

**Closed** 2019-03-22 20:00 UTC
Labels: Area: Accessibility, Needs: Author Feedback, Resolution: Duplicate, no-recent-activity
