### ISSUE TITLE
Number of Suggested items Alert for Tag Picker

### ISSUE THREAD

**Issue by TheLayman** [OfficeDev/office-ui-fabric-react#5893] opened 2018-08-10 10:34 UTC
Tag picker currently provides alert when suggestions are available and when there are no suggestions available. The Alert is read out by the screen-readers only when there is a change in the state(i.e, whether there are suggestions available or not).  

Visually impaired users, who rely on screen reader will not be aware of the suggestions as they type the search keyword because even though the suggestions might have changed there'd be no alert since the suggestionsavailablity state has not changed.

**Comment by natalieethell** [comment] 2018-08-10 16:57
Hey @TheLayman thanks for submitting this issue! This is an issue we're aware of and looks like a dupe of #3715 (so I'll close this one and reopen that one). 

It might be something that we can solve in the new "Announced"/"Announcement" component we'll be working on, which is being tracked here: #5615. @dzearing what do you think?

**Closed by natalieethell** 2018-08-10 16:57 UTC
Labels: Area: Accessibility, Component: Pickers
