### ISSUE TITLE
support for color '#6BB700' in semantic slots

### ISSUE THREAD

**Issue by shivasai09** [OfficeDev/office-ui-fabric-react#10236] opened 2019-08-22 09:43 UTC
currently in fabric 6.186.1, there is no semantic slots for the color '#6BB700'.

The above mentioned color can be useful many place, one such scenario is posted below
![image](https://user-images.githubusercontent.com/33802398/63504328-eda84800-c4ee-11e9-97e8-4cea5b643693.png)

**Actual behavior**
currently there is no semantic slot in theme for above mentioned color

**Expected behavior**
There should be semantic slot for the above mentioned color(#6BB700) in the theme

**Comment by kenotron** [comment] 2019-08-22 17:00
Hey @Jahnp - do we want to add this in semantic slot color? If so, what would this be called?

**Comment by kenotron** [comment] 2019-08-22 20:48
@phkuo - ping if you have some opinion about this

**Comment by maxwellred** [comment] 2019-08-22 20:48
Hi @phkuo we were wondering if you had some input on this semantic color proposal, thanks!

**Comment by phkuo** [comment] 2019-08-22 21:08
I'd recommend:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/interfaces/ISemanticColors.ts#L159
(which is partially transparent)

Or:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/interfaces/IPalette.ts#L250
But then you'd have problems finding the appropriate slot to use as text on top of it.

**Comment by phkuo** [comment] 2019-08-22 21:11
So I would also caution, you should not approach this with the attitude "I need to find a slot whose hex value is exactly #6BB700" but instead "what already exists that fulfills the same intention as this?" We seek coherence, so when you have a new color that isn't used anywhere else, you should try to align with what already exists, instead of adding a yet another new option to the existing options.

**Comment by kenotron** [comment] 2019-08-22 21:14
I agree with @phkuo as well here. We're unlikely to add a brand new semantic color here. I'm marking this resolution: by design. Please close this at your earliest convenience.

**Closed** 2019-08-29 23:00 UTC
Labels: Needs: Author Feedback, Needs: Design 🎨, Resolution: By Design, Status: No Recent Activity
