### ISSUE TITLE
Coachmark will not be dismissed when click outside of coachmark (set preventDismissOnLostFocus as false).

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#7975] opened 2019-02-13 04:59 UTC
Here is the codepen:
[https://codepen.io/keirayang/pen/PXMByz](https://codepen.io/keirayang/pen/PXMByz)

I set preventDismissOnLostFocus as false in calloutProps. But the coachmark cannot be dismissed by clicking outside of coachmark.

**Comment by Vitalius1** [comment] 2019-02-13 07:14
This is because the `TeachingBubbleContent` is not using the callout props at all. There is a higher parent that renders `TeachingBubbleContent` in a callout and it's called `TeachingBubble` here:
https://github.com/OfficeDev/office-ui-fabric-react/blob/0c8e4d3aed46a6bbf521bc48509a6f988446760d/packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubble.base.tsx#L74-L86

In the case of the `Coachmark` it's a little of an odd situation in that it's not using a `Callout` to render the `TeachingBubbleContent` (which is just a content container), but instead is using a `PositioningContainer` here: https://github.com/OfficeDev/office-ui-fabric-react/blob/0c8e4d3aed46a6bbf521bc48509a6f988446760d/packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.base.tsx#L228-L283
... which is kind of an attempt to replace the `Callout`'s positioning logic but never got finalized.

As for your issue here is a [codepen](https://codepen.io/vitalius1/pen/gqjPYq) I modified yours by adding `onDismiss` prop on the `Coachmark` itself. As long as the `preventDismissOnLostFocus` prop is not toggled on it should do exactly the same thing as the X button on the `TeachingBubbleContent`. If this solves your issue feel free to close the issue or leave it and our Fabric bot will handle this for you 😄 


@JasonGore I already had to deal with Coachmark before and with it's `PositioningContainer` replacement for `Callout`. It feels odd that we have 2 components that share a LOT of code and are doing the same thing.

**Comment by KeiraYang** [comment] 2019-02-13 07:59
Sorry I have another issue wantto explain. If I didn't add ondismiss, the coach mark will not be dismissed until user expand coach mark and click 'X' button to dismiss it. Then for my page, when switch to another page by left nav in the same window, the coachmark will still on it's position even though it's target button has been unmounted. Did I make misunderstand or it will act like this?

**Comment by KeiraYang** [comment] 2019-02-13 08:53
It seems doesn't solve my issue because I want have different dismiss action for the coachmark circle and for the expanded teaching bubble. But they share the same onDismiss action. Add onDismiss in TeachingBubbleContent not work.

**Comment by Vitalius1** [comment] 2019-02-13 16:12
@KeiraYang for your first reply what do you mean by :

> Then for my page, when switch to another page by left nav in the same window, the Coachmark will still on its position even though it's target button has been unmounted.

Do you navigate to a page that is rendered by the same component that initialy rendered the Coachmark? If yes, then I would assume that this is a normal behavior of the Coachmark circle to stasy put after it positioned itself. What is your expected behavior or is this something that happens in your application?
Also, you can press `ESC` key to dismiss the circle without expanding it.

As for your second reply:

> It seems doesn't solve my issue because I want have different dismiss action for the coachmark circle and for the expanded teaching bubble. But they share the same onDismiss action. Add onDismiss in TeachingBubbleContent not work.

You can easily point the `onDismiss` prop of the Coachmark to a different private method and do whatever you like. What do you mean by `onDismiss` in `TeachingBubbleContent` not working?

**Comment by KeiraYang** [comment] 2019-02-14 00:41
Thank you @Vitalius1  for reply. I'm sorry for confusion. I'll make it clear.
For the first reply, may the coachmark itself can check if it's target is gone (When click outside of coachmark will not dismiss the coachmark)? Because if the target is missed in the page, the coachmark should not be still there.

For second reply, for coachmark, there is a circle and a dialog opened. I want to control different dismiss action for this circle and this dialog. Is there any way to do that? Currently, `onDismiss` is both for the circle and the opened dialog.

**Comment by Vitalius1** [comment] 2019-02-14 01:06
@KeiraYang 
1. Can you mock up this scenario in the codepen? Do you have an app using Coachmark and it's not dismissed when navigating to a different page and the target element is unmounted? Is it an issue you have in your product or is this just a theoretical question? 

2. I've updated the codepen to show that you don't have to do a dismissal in either of the callbacks. Let me know if I got it wrong again on what you are asking. Apologies for that 😄

**Closed** 2019-02-21 03:00 UTC
Labels: Component: Coachmark, Needs: Author Feedback, no-recent-activity
