### ISSUE TITLE
Unable to use a react-dropzone component inside a Fabric Dialog

### ISSUE THREAD

**Issue by claudiuchetan** [OfficeDev/office-ui-fabric-react#8491] opened 2019-03-27 09:22 UTC
### Environment Information 
 
- __Package version(s)__:  6.158.0
- __Browser and OS versions__:  All

### Please provide a reproduction of the bug in a codepen:
 https://codesandbox.io/s/0m31n02ozl
(not Codepen, but still useful)

 
#### Actual behavior:
The dragEnter and Drop events are not triggered when the dropzone is used inside the Dialog component. The isPropagationStopped property of the event is set to true on the async callbacks.

 
#### Expected behavior:
 The events should trigger normally.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix?  No
 
Requested priority:  Normal

Related issue created on react-dropzone's space: https://github.com/react-dropzone/react-dropzone/issues/799

**Comment by Vitalius1** [comment] 2019-03-27 20:21
@JasonGore can this be related to the event filtering in `Layer`? You are much more familiar with that area 😄 . Would you mind taking a look?

**Comment by JasonGore** [comment] 2019-03-27 21:42
`Layer` doesn't bubble events by default because it can cause unwanted behavior. Our [Layer & Portals page](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Portals#overview) provides more of a background.

In this case we can allow events to propagate by passing in `eventBubblingEnabled` to the `Layer` component:

```tsx
modalProps={{
  layerProps: { eventBubblingEnabled: true },
  isBlocking: false
}}
```

I [modified the CodeSandbox](https://codesandbox.io/s/loo8oq93z) to use this approach and it seems to work as expected.

However, note that using `eventBubblingEnabled` will also cause events to pass up the hierarchy, which can cause unwanted or unexpected behavior. This is why `eventBubblingEnabled` is disabled by default. You can also see this in the same CodeSandbox as shown below:

![Tooltip](https://user-images.githubusercontent.com/26070760/55114132-6620ef00-509e-11e9-934c-347ac66ea10e.gif)

I had to tweak the example a bit to show this behavior by making DropZone a child of the first DropZone, but it is a relatively simple example of how this can affect components in the background that you may not normally expected.

**Comment by JasonGore** [comment] 2019-03-27 22:20
I do think, however, that drag & drop events should work within `Layer` without having to use `eventBubblingEnabled`. While `eventBubblingEnabled` can be used for now, I think we need to take a closer look at `Layer` and see if we're blocking a capture event that's preventing drag and drop events from being used within `Layer` content. 

When making changes to `Layer`, I found that I could not trust `ev.bubble` and instead had to filter certain events by name, such as mouse enter and mouse leave. It may be that we have to do something similar for drag events, too.

**Comment by Vitalius1** [comment] 2019-03-27 22:50
@JasonGore what is the resolution of this issue? Is there anything else you wanna investigate with `Layer` drag and drop events and make a fix as part of this issue or should this be a separate issue to tackle later?

**Comment by Vitalius1** [comment] 2019-03-27 23:13
@claudiuchetan is the solution provided by @JasonGore working for your scenario? I recommend going through the [Layer & Portals Page](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Layer-&-Portals) and be aware of the possible side effects of using `eventBubblingEnabled`.

**Comment by larnera** [comment] 2019-03-28 11:59
I had this same issue and it just so happen that @claudiuchetan faced it at the same time. 

Thanks everyone for your help in resolving this issue, and so quickly too. 

Cheers.

**Comment by JasonGore** [comment] 2019-03-28 15:56
Rather than a documentation update, I do believe drag and drop events should work within Modal content without the need for `eventsBubbleEnabled`, so this is something we should look into. I'll reopen this assigned to me for further investigation.

**Comment by AndrewCraswell** [comment] 2019-05-26 21:58
Thank you for reopening. I came to report the same thing and build a sample code sandbox before realizing this is already being addressed. I had tried using Dialog, Modal, Panel, and all weren't working. I figured they were all dependent on a component that was stopping event propagation somewhere. The explanation of `Layer` being that component makes more sense to me now.

https://codesandbox.io/s/dazzling-flower-6dnuz

For now modifying the `LayerProps` is a suitable workaround for my use case. But I do agree this took way too much effort to understand why it didn't work.

**Comment by srungta** [comment] 2019-07-08 07:13
> However, note that using `eventBubblingEnabled` will also cause events to pass up the hierarchy, which can cause unwanted or unexpected behavior in the "background content" behind the Modal. This is why `eventBubblingEnabled` is disabled by default. 

Hi @JasonGore ,
I am using layerprops for now, but would like to understand the side effects you mention above in detail. Do you have any link / code file/ reference material that i can study?

**Comment by JasonGore** [comment] 2019-07-08 17:08
Yeah, there's a [Layer wiki](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Layer-&-Portals) describing behavior. It appears that the `dragenter` and `dragleave` events will also need some special exceptions like `mouseenter` and `mouseleave` events do now.

**Comment by JasonGore** [comment] 2019-07-08 21:11
I took another look at this again and With just a [slight tweak to the provided examples](https://codesandbox.io/s/layer-drag-8491-8uyed), I do get the drag callbacks called as expected:

```tsx
{({ getRootProps, getInputProps }) => (
  <section>
    <div
      {...getRootProps()}
      // BEGIN added lines
      onDragEnter={() => {
        this.handleOnDragEnter();
      }}
      onDragLeave={() => {
        this.handleOnDragLeave();
      }}
      // END added lines
    >
```

![Dropzone](https://user-images.githubusercontent.com/26070760/60842604-56c73c80-a189-11e9-99d4-f5f0eadf6b50.gif)

It seems the issue is actually within React Dropzone somehow. The change I made above seems equivalent to what the [React Dropzone code is doing](https://github.com/react-dropzone/react-dropzone/blob/93bded79f01641aaf5c4d29642a881cdc0e77bcf/src/index.js#L686), so I'm not sure where the difference is. Perhaps it's an issue with how they compose or use native events vs. synthetic events.

I think this does show that it is possible to do drag and drop behavior inside of a `Dialog`, however.

**Closed** 2019-07-15 23:00 UTC
Labels: Component: Dialog, Component: Layer, Needs: Author Feedback, no-recent-activity
