### ISSUE TITLE
GroupedList not Rendering when the first group has a count of 0

### ISSUE THREAD

**Issue by Xannic** [OfficeDev/office-ui-fabric-react#6438] opened 2018-09-21 08:38 UTC
### Please provide a reproduction of the bug in a codepen:
https://codepen.io/Xannic/pen/vzPXzv

### Bug Report 
 
- __Package version(s)__: 6.72.0
- __Browser and OS versions__: Chrome Version 69.0.3497.100 on Windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
#### Describe the issue:
 
When you give the Grouped list an array of groups and the first group has a count of 0, then the other groups will not render.
 
#### Actual behavior:
 
No list will render.
 
#### Expected behavior:
 
The list will Render the other groups that have a count.

**Comment by KevinTCoughlin** [comment] 2018-09-21 22:01
This behavior looks to be intentional and can be overridden by using `showEmptyGroups` prop within `groupProps`.

https://github.com/OfficeDev/office-ui-fabric-react/blob/ff52ec0f21c634437efb8fa568081878713ceefb/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.types.ts#L226

Here's your above example with that prop set to `true` @Xannic: https://codepen.io/kevintcoughlin/pen/jvJJJd

**Comment by KevinTCoughlin** [comment] 2018-09-21 22:03
I'm going to close this issue since it can be addressed using an available prop and looks to be by design. Please re-open if you feel that the issue hasn't been addressed.

**Comment by Xannic** [comment] 2018-09-24 05:38
@KevinTCoughlin I think you misunderstood me. Because it does not look by design. The problem that I found is not that one group does not render(that is what the showEmptyGroups prop is for). But that the entire list will not render when the first group has a count of zero.

I had everything in one codepen but let me split it into 2 codepens.
Here the first which renders the list correctly with group 2 having no items so happens group 1 and group 3 render.
https://codepen.io/Xannic/pen/vzPXzv

Now when the first group has no count. I would expect to see a list with group 2 and group 3. But what happens is that nothing renders. As you can see in this example:
https://codepen.io/Xannic/pen/OoYLLG

And the only change between these lists is that by the second example the list starts with an empty group. Below the code for the groups:

First codepen:
```
groups: [
                {
                    key: 1,
                    children: [],
                    count: 1,
                    startIndex: 0,
                    name: 'group 1',
                },
                {
                    key: 2,
                    children: [],
                    count: 0,
                    startIndex: 1,
                    name: 'group 2',
                },
                {
                    key: 3,
                    children: [],
                    count: 2,
                    startIndex: 1,
                    name: 'group 3',
                },
            ]
```
Second codepen:
```
groups: [
                {
                    key: 1,
                    children: [],
                    count: 0,
                    startIndex: 0,
                    name: 'group 1',
                },
                {
                    key: 2,
                    children: [],
                    count: 1,
                    startIndex: 0,
                    name: 'group 2',
                },
                {
                    key: 3,
                    children: [],
                    count: 2,
                    startIndex: 1,
                    name: 'group 3',
                },
            ]
```

**Comment by KevinTCoughlin** [comment] 2018-09-25 22:21
Thanks for the additional context @Xannic, I had indeed misunderstood the bug. I debugged this yesterday for a bit, but haven't arrived at a solution. For the failing to render case, we are exiting early while building list "pages". This indeed should be fixed, but requires more investigation.

https://github.com/OfficeDev/office-ui-fabric-react/blob/74bfc90fdbfae64ba91a53e9bd9b47493e326d60/packages/office-ui-fabric-react/src/components/List/List.tsx#L719

**Comment by Vitalius1** [comment] 2018-09-28 07:03
@KevinTCoughlin  I investigated the issue and found the culprit. `GroupedList` renders a `List` which in turn does a measurement of the first page (in our case each group is a page). In `GroupedList` we have this [check](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L163-L165) happening which returns null when `group.count === 0`. So in the example where first group has `count` set to 0 `GroupList` renders null and the `List` has no sample element from which to take some measurements and gets stuck in state where it thinks it renders for the first time for each group when building pages due to a break condition [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L163-L165).

As a solution I tested would be to pass to `GroupedList` the `getGroupHeight` prop providing the initial measurements needed for `List` to build correctly the pages. It even works if you return 0 with that prop in case the consumer has some dynamic heights... In most of the cases the application nows the end height of at least the groupHeader. And if each row height of the expanded group is known too than we can do something like this:
```
private _getGroupHeight = (group: IGroup) => {
    return GROUP_HEADER_HEIGHT + GROUP_ITEM_HEIGHT * group.count;
};
```
@Xannic Would this solve your issue? If not than we should look into changing the logic of `GroupedList` returning null when `count = 0`

**Comment by Vitalius1** [comment] 2018-10-01 18:40
@Xannic let us know if the use of `getGroupHeight` prop solves your issue.

**Comment by Xannic** [comment] 2018-10-02 05:40
@Vitalius1 I have a work around in place already by just checking which groups have a count of 0 and removing them. I just reported the issue so you guys know that there is a bug in the grouped list.

Looking at it from a user perspective I would say using the getGroupHeight is not a valid solution. That is just another workaround. It's up to you guys when/how you are gonna fix/close it.

**Comment by Vitalius1** [comment] 2018-10-02 23:02
Looks like we need some tweaking in the logic located here:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L163-L165
List relies on the first element to measure the height of the page for some optimization and when it receives `null` it gets stuck in thinking it's still a first render in here https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/List.tsx#L800-L802.

`getGroupHeight` prop solves this issue but feels that this is an edge case that needs to be solved internally and node through usage of a prop.

**Comment by Vitalius1** [comment] 2018-10-04 00:48
@KevinTCoughlin do you think we need anything to fix in here. I left a comment above my investigation findings.

**Comment by micahgodbolt** [comment] 2018-12-28 18:40
assigning to @KevinTCoughlin to keep an eye on this. at least the OP has a workaround, so priority is low.

**Comment by micahgodbolt** [comment] 2020-01-02 19:12
It appears that this is working correctly in current release:

![image](https://user-images.githubusercontent.com/1434956/71686708-c725d380-2d50-11ea-9249-55a73fcaba11.png)

Please reply if this is not correct.

**Closed** 2020-01-09 21:00 UTC
Labels: Component: GroupedList, Needs: Author Feedback, Priority 2: Normal, Status: No Recent Activity, Type: Bug :bug:
