### ISSUE TITLE
In High contrast (Black and White) theme, Selected checkbox are not visible properly

### ISSUE THREAD

**Issue by Srikanth1110** [OfficeDev/office-ui-fabric-react#12264] opened 2020-03-11 13:27 UTC
### Environment Information

- **Browser and OS versions**: (Edge Windows 10 Version 2004 (OS Build 19559.1000) )

### Describe the issue:

If any checkbox or any element disappear when high contrast mode is enabled, will make the UI confusing and difficult for users with low vision to navigate to the desired element.

**Repro steps :**

1. Go to url https://developer.microsoft.com/en-us/fabric#/controls/web/checkbox
2. In Windows go to Setting>Ease of Access>High contrast>Choose a theme>High Contrast Black/White theme
3. Verify the check boxes in High Contrast Black/White theme

#### Actual behavior:

In High contrast (Black and White) selected checkbox are not visible properly.

**Normal Mode  :**
<img width="772" alt="Normal Mode" src="https://user-images.githubusercontent.com/16889881/76418186-327cc900-63c4-11ea-84b8-1655fa719cb9.png">

**High Contrast Black :**

<img width="742" alt="High Contrast Black" src="https://user-images.githubusercontent.com/16889881/76418271-5809d280-63c4-11ea-8958-2b2e45473608.png">

**High Contrast White:**

<img width="806" alt="High Contrast White" src="https://user-images.githubusercontent.com/16889881/76418298-6657ee80-63c4-11ea-8b75-2b06dbdbd6b9.png">

#### Expected behavior:

Selected checkbox should be visible properly in high contrast mode.

### Documentation describing expected behavior

MAS Reference:

https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={672c8a8b-ed4f-463f-868f-e8131caf9b74}

Suggested Fix:

https://microsoft.sharepoint.com/teams/msenable/mas/pages/mas-details.aspx?masid=4.3.1

**Comment by aneeshack4** [comment] 2020-03-11 17:05
duplicate of #12201

**Comment by aneeshack4** [comment] 2020-03-11 17:06
Thanks @Srikanth1110 for reporting this! We're following up on this bug on #12201 so I'll close this one.

**Comment by aneeshack4** [comment] 2020-03-11 17:12
![image](https://user-images.githubusercontent.com/4161791/76444003-89f94580-6380-11ea-8a35-480302326146.png)
![image](https://user-images.githubusercontent.com/4161791/76444061-a1383300-6380-11ea-90a1-3f5c98f47219.png)
Actually maybe these are separate issues - what you're saying is the selected state is not visible right? But as you can see in the screenshots above they are...

**Comment by Srikanth1110** [comment] 2020-03-12 06:14
@aneeshack4 : Yes, the selected state is not visible. This is repro'ing in latest chromium edge browser-
Edge(Canary) Version: 82.0.432.0 (Official build) canary (64-bit)

**Comment by aneeshack4** [comment] 2020-03-13 00:23
@Srikanth1110 It's only reproing for you on Edge Chromium, not the old Edge right?

**Comment by Srikanth1110** [comment] 2020-03-13 07:02
> @Srikanth1110 It's only reproing for you on Edge Chromium, not the old Edge right?

Yes, Reproing on Edge chromium and not reproing on old Edge browser.

**Closed** 2020-03-16 12:00 UTC
Labels: Component: Checkbox, Needs: Attention :wave:, Resolution: Duplicate
