### ISSUE TITLE
Facepile: is not tab-able without onClick, which affects some accessibility scenarios

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#853] opened 2017-01-20 00:00 UTC
### Bug Report

- __Package version(s): v0.87

#### Describe the issue:
Facepile is not accessible. It does not have any tabIndex properties on any of the persona sub-components

#### Actual behavior:

I cannot focus a facepile persona

#### Expected behavior:

I should be able to focus a facepile persona

**Comment by dzearing** [comment] 2017-01-25 02:40
I think this is actually by design. If you provide an `onClick`, it renders as a tab-able entity.

I do think there should be a FocusZone around it however. I see Matt has a PR for this. @cliffkoh and I will work with him on it.

**Comment by dzearing** [comment] 2017-01-25 02:41
Keep in mind that for accessibility, you want interactive entities to be tabable. For non-interactive entities, I believe from a JAWS perspective they can arrow to the elements in a specific reading mode.

@cschlechty can keep me honest here.

**Comment by dzearing** [comment] 2017-01-25 16:49
I think we need discussion here; I don't believe the answer here to making it accessible is to make it tab-able even when non-interactive. If you have an `onClick` handler, it becomes interact-able and therefore should be tab-able.

**Comment by abettadapur** [comment] 2017-01-25 17:12
I would expect to be able to tab through the items in the facepile and get a readout of their name perhaps? Even if their persona had no action associated with them. There are other components on the page that are not interact-able, yet can still be tabbed to: titles, cards, etc.

**Comment by cschlechty** [comment] 2017-01-25 17:19
Tabs aren't required, nor necessary for an element to be readable via screen reader. Each AT has key commands for reading through a page. In jaws, that's the down arrow in virtual cursor mode, narrator is Caps+M.

**Comment by dzearing** [comment] 2017-01-26 01:04
Per discussion, closing. Accessibility rules are:

Add tab stops for interactive items
Add aria-labels to things that need them if the content is unclear
Don't add tab-stops on every element just to get the screen reader reading them

**Closed by dzearing** 2017-01-26 01:04 UTC
Labels: bug

**Comment by mattlind** [comment] 2017-01-26 21:26
Thanks.

--
Matt
