### ISSUE TITLE
Documentation: propertyName format

### ISSUE THREAD

**Issue by liuyangc3** [OfficeDev/office-ui-fabric-react#7471] opened 2018-12-25 06:29 UTC
### Please provide a reproduction of the bug:
https://developer.microsoft.com/en-us/fabric#/components/nav

 
![image](https://user-images.githubusercontent.com/6705844/50414529-fad24180-0850-11e9-82e8-9859cfc6fabb.png)

 

#### Expected behavior:
 
![image](https://user-images.githubusercontent.com/6705844/50414569-48e74500-0851-11e9-89eb-6c82c6f39996.png)

I see `(Optional)` in it's Description but it  is puted in `Required Members`.

maybe this property should be moved to`Optional Members`.
```js
// change like this ?
[propertyName: string]: any; -> [propertyName: string]?: any;
```
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Nav/Nav.types.ts#L234
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by cliffkoh** [comment] 2018-12-26 23:51
Thanks for reporting. Assigning to @natalieethell.

**Comment by micahgodbolt** [comment] 2018-12-29 00:32
duplicate of #6010

**Closed** 2018-12-29 00:33 UTC
Labels: Area: Documentation, Resolution: Duplicate, Type: Feature
