### ISSUE TITLE
SearchBox Focus issue: Search icon does not hide on refocus

### ISSUE THREAD

**Issue by mekumari** [OfficeDev/office-ui-fabric-react#11502] opened 2019-12-18 05:57 UTC
### Environment Information

- **Package version(s)**: office-ui-fabric-react@6.204.4
- **Browser and OS versions**: NA

### Please provide a reproduction of the bug in a codepen: https://codepen.io/megha21K/pen/OJPbEEa

Repro steps -
1. Click inside SearchBox
2. Click on ... button
3. Click on SearchBox again

#### Actual behavior:
Search icon is still displayed -  I found that "is-active" class is missing from the ms-SearchBox class name
![image](https://user-images.githubusercontent.com/59005777/71059126-0288a580-2188-11ea-8b48-f7ab30bd226e.png)

#### Expected behavior:
Search icon is not displayed
![image](https://user-images.githubusercontent.com/59005777/71058755-e1738500-2186-11ea-911c-4e98ebdcee97.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: project.microsoft.com

**Comment by micahgodbolt** [comment] 2019-12-18 18:33
Great repro @mekumari. We'll look into how/when the is-active class gets applied and see why it is not happening in this case.

**Comment by micahgodbolt** [comment] 2020-01-02 20:49
duplicate of #8261

**Closed by micahgodbolt** 2020-01-02 20:49 UTC
Labels: Component: SearchBox, Type: Bug :bug:
