### ISSUE TITLE
Shimmer in IE performance issue

### ISSUE THREAD

**Issue by casvaniersel** [OfficeDev/office-ui-fabric-react#8295] opened 2019-03-13 07:57 UTC
<img width="1993" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3843874/54262393-58338000-456e-11e9-82f3-03e30a730aaf.png">
<img width="1993" alt="Screenshot 2" src="https://user-images.githubusercontent.com/3843874/54262415-608bbb00-456e-11e9-8621-dae3222f10c7.png">

### Environment Information 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: IE 11 on Win 10

### Please provide a reproduction of the bug in a codepen:

Unfortunately CodePen doesn't work in IE 11. Just open this link in IE 11 and the performance issue is reproduced right away: https://developer.microsoft.com/en-us/fabric#/components/shimmer.

This codepen provides a possible solution to the issue described: 
https://codepen.io/casvaniersel/pen/YgEBEy

 
#### Actual behavior:
 
The shade animation in the shimmer causes the browser to continuously call paint. The browser is trying to do this at 60 fps the entire time which can cause the page to be very slow. (Especially in IE). 

Screenshot 1 provides the performance analysis. (The analysis is made in Chrome because of the tools)
 
#### Expected behavior:
 
The shade animation shouldn't impact the browser as much as it does. A possible solution is attached in codepen above. 

Screenshot 2 provides the performance analysis for possible solution.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No. Sorry my colleague helped with this solution and at the moment I can't find the time to implement it in UIFabric. Hopefully someone else finds my possible fix useful! I'm available for contact. 
 
Requested priority: Normal
 
Products/sites affected: ?

**Comment by KevinTCoughlin** [comment] 2019-03-13 17:09
@casvaniersel is the fix moving the animation calls to within a `requestAnimationFrame` callback? Can you expand a bit on your solution?

@Vitalius1 is this something we should move to Shimmer's backlog?

I'm not sure how actionable this is for SHIELD given the product surface area it would impact and testing required.

**Comment by KevinTCoughlin** [comment] 2019-03-13 17:10
Also it doesn't seem like this potential problem is isolated to IE, just that IE is sluggish when repainting at such a high rate. Is that correct?

**Comment by TDezentje** [comment] 2019-03-13 21:07
I’m the author of the example solution. Indeed the problem is not isolated to IE. Browsers like Chrome just handle the animation a lot faster. You can probably see the same issue on lower end mobile devices with Chrome.

The problem occurs because the current animation triggers the browser to do a lot of expensive style calculations and painting on every animation tick. The codepen uses an inner div that is translated to a new position with every tick. The requestAnimationFrame only makes sure we calculate new positions when needed. Optimising it to only set styles for shimmer elements that are on screen can probably save some extra ms per frame.

At my machine in IE the current solution takes 160ms style calculation and 50ms painting.
The codepen takes 10ms javascript calculations, 2ms style calculation and 4ms painting.

Using translate3d instead of translateX can further optimise the animation because most browsers will then promote the element. More info here: https://dassur.ma/things/forcing-layers/

**Comment by KevinTCoughlin** [comment] 2019-03-14 00:23
Thanks for the awesome explainer @TDezentje! We'll see what we can do in the short term. Admittedly Shimmer is a bit of an unknown to me, but I like the challenge this presents. Will circle back in some time.

**Comment by Vitalius1** [comment] 2019-03-14 02:14
@KevinTCoughlin this is something definitely not a Shield bug to resolve and needs to be moved under Shimmer's backlog. And it looks like this is something we actually want to look in and optimize.
A little background about Shimmer creation is that we wanted a pure CSS solution with no extra JS involved. Perhaps using a different CSS property to animate the wave movement (like `transform`) which will promote the element to a separate layer and thus moving it away of the main thread could also help, but Safari browser will still act the same so some sort of JS solutions worth to be investigated. It's definitely a subject to look into.

@TDezentje thanks for the numbers and very detailed explanation. Just so that you know we also welcome PRs 😄 if you are interested ))) Looks like you have deep knowledge in regards to animation performance and we would be very grateful for your contribution.

To be fair... Shimmer was not intended to be left on screens for very long periods of time so that the user can perceive a loss in page performance. Its purpose was to create a quick illusion that we are almost done in fetching the data and we know how the layout approximately looks.

@atneik for visibility.

**Comment by casvaniersel** [comment] 2019-03-14 06:57
Thanks @TDezentje for elaborating 👍 hopefully you guys can optimise, because in my experience there are still a LOT of users on IE.

**Comment by Vitalius1** [comment] 2019-03-14 19:17
@casvaniersel can you exemplify how the Shimmer was used that this performance issue surfaced? As I mentioned Shimmer is intended to live on the screen very shortly so it should not cause any perceived slowing down of the page. Is there a case where Shimmer is used being rendered for long periods of time? Just curious of all scenarios where it is used.

**Comment by TDezentje** [comment] 2019-03-14 20:06
@Vitalius1 We only tested it on the demo page. We did not use a real life scenario. But as soon as the shimmer is shown the main thread will have jank.

I'm currently working on a PR. But the change will probably create a breaking change in the API because the gradient will be applied to a different classname.

**Comment by Vitalius1** [comment] 2019-03-14 20:35
@TDezentje I was thinking the same thing on how to avoid this breaking change by adding a new element in the DOM. With that said we are preparing for a major release soon and this kind of breaking changes are more suited for it so I guess we can discuss having the change available for a next major version if it brings lots of improvements performance wise. Thanks for looking into this and we will be happy to review it. 👍

**Comment by casvaniersel** [comment] 2019-03-15 07:15
@Vitalius1 sorry for the late response, but @TDezentje already replied and made a PR I see 👍 awesome!

**Comment by KevinTCoughlin** [comment] 2019-04-02 21:28
This will be resolved in `7.0` as the fix introduced a non-backwards compatible API change. It has been merged (see above).

Letting the bot soft-close. Thanks all!

**Closed** 2019-04-09 23:00 UTC
Labels: Area: Performance, Component: Shimmer, Needs: Author Feedback, no-recent-activity
