### ISSUE TITLE
Global styles applied to "button"

### ISSUE THREAD

**Issue by hoovercj** [OfficeDev/office-ui-fabric-react#9036] opened 2019-05-09 21:42 UTC
### Environment Information 
 
- __Package version(s)__: 6.175 

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/dEGrwz
 
* Open the codepen
* Edit the css styles so the margin property has a non-0 pixel value
* **Note:** now the margin is respected
![image](https://user-images.githubusercontent.com/2957173/57488620-eea4c900-72b3-11e9-859d-833d3879f203.png)
* Edit the jsx to change the text in a button
* **Note:** now the margins are ignored because the global button styles from the `<Fabric>` component have taken precedence.
![image](https://user-images.githubusercontent.com/2957173/57488656-03815c80-72b4-11e9-878b-ba2279c43b24.png)

#### Actual behavior:

The `<Fabric>` component defines global styles for buttons which affect styling for non-fabric components rendered by our page. . 
 
#### Expected behavior:
 
Including a `<Fabric>` component in our product does not affect any elements outside of that tag.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High, potentially blocks us from finally upgrading from 5.x
 
Products/sites affected: D365 Business Central

**Comment by hoovercj** [comment] 2019-05-09 21:52
This is caused by these two PRs: #3970 and #4797

It is not immediately clear to me why it was necessary to apply the styles globally instead of scoped to fabric controls as I've done in #9037

Hopefully @micahgodbolt can comment as he was involved in both pull requests.

**Comment by jdhuntington** [comment] 2019-05-09 22:13
@hoovercj - In "Edit the css styles so the margin property has a non-0 pixel value", what margin did you change? I added a margin to the `.fabric-button` selector and did not see it overwritten when I changed the JSX. Should I be adding another selector entirely?

**Comment by hoovercj** [comment] 2019-05-09 22:25
@jdhuntington oops, I don't think I saved the codepen.

I have added some comments in the code now as shown in this screenshot:

![image](https://user-images.githubusercontent.com/2957173/57490608-126b0d80-72ba-11e9-8d40-72cc86adf500.png)

**Comment by hoovercj** [comment] 2019-05-09 22:28
So every time I edit the line where "step 1" is, the margin is set to what I define there.

Every time I edit "Hello World" text where "step 2" is, the margin is set to 0 which is defined in `Fabric.styles.ts`.

**Comment by jdhuntington** [comment] 2019-05-13 18:06
@hoovercj Thanks for the clarification!

Found the cause at https://github.com/OfficeDev/office-ui-fabric-react/blob/9c9af6633a74a548915ceae24cc7abb67bd2d13d/packages/office-ui-fabric-react/src/components/Fabric/Fabric.styles.ts#L32

Will figure out the right fix for this; thanks!

**Closed** 2019-05-20 17:51 UTC
Labels: Component: Button, Component: Fabric, Type: Bug :bug:
