### ISSUE TITLE
ComboBox input field is empty while dropdown is visible

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7558] opened 2019-01-08 06:12 UTC
I need to show selected values when we selecting on each. normally it shows when focus out from the comboBox
![comboboxissue](https://user-images.githubusercontent.com/33615108/50812864-611f8f80-133a-11e9-84ea-a5ee9409175b.png)

**Comment by piyumi25** [comment] 2019-01-08 09:18
normally when we focus out from the combobox the selected values are shown as comma separated string. I need to show when click on checkbox.

**Comment by cliffkoh** [comment] 2019-01-08 19:37
@stanleyymsft do you know if there is a reason why we don't show the current set of options in the textbox when changing the selected options in multi-select ComboBox?

**Comment by stanleyymsft** [comment] 2019-01-08 19:41
This is a simplification so we could get multi-select implemented quicker to unblock some projects.  When we show the intermediate selected items, we need to gracefully take care of the situation when the user directly click into the box and modify them, which will need some non-trivial work.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Vitalius1** [comment] 2019-01-08 19:41
@piyumi25 @cliffkoh 
I believe this is the intended behavior as `ComboBox` is allowing the user to start typing the options he wants to add to the multiselection.

**Comment by cliffkoh** [comment] 2019-01-08 19:42
Thanks @stanleyymsft. Will mark this issue as a feature request.

**Comment by Vitalius1** [comment] 2019-01-09 17:47
@micahgodbolt this feels like a dupe of #6084. I will let you decide which one needs to be closed in favor of the other one. If you decide to leave 6084 and close this one, judging from Stanley's answer this should be labeled as a feature was not implemented when multi-select was introduced.

**Comment by micahgodbolt** [comment] 2019-01-09 21:20
yes, I think it's similar. This one appears to be a bit more fully fleshed out. Be sure to reach out to 6084 author just to make sure.

**Comment by khmakoto** [comment] 2020-01-14 02:37
This has been fixed in #11436. Hence, I'll be closing this issue.

**Closed by khmakoto** 2020-01-14 02:37 UTC
Labels: Component: ComboBox, Type: Feature, help wanted
