### ISSUE TITLE
[Accessibility] ComboBox has invalid aria-* attributes

### ISSUE THREAD

**Issue by stephenzsy** [OfficeDev/office-ui-fabric-react#4450] opened 2018-04-04 00:41 UTC
### Bug Report

- __Package version(s)__: 5.78
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:

* role="option" widget has invalid attribute aria-pressed
* role="combobox" has invalid aria attributes

Refer to https://www.w3.org/TR/wai-aria-1.1/#combobox

**Comment by aditima** [comment] 2018-05-10 20:58
@stephenzsy - thanks for the PR! Assigning the issue to you since you already have the PR...

**Comment by JasonGore** [comment] 2018-08-15 22:25
I believe this is a duplicate of #4873 and was resolved by #5001. I see no other invalid attributes reported by scans against the ComboBox page so I will close this issue.

**Closed by JasonGore** 2018-08-15 22:25 UTC
Labels: Area: Accessibility, Component: ComboBox, Type: Bug :bug:
