### ISSUE TITLE
checkboxVisibility not respected in DetailsList

### ISSUE THREAD

**Issue by cschlechty** [OfficeDev/office-ui-fabric-react#5908] opened 2018-08-10 22:08 UTC
### Bug Report 
 
- __Package version(s)__: 4.5.0
- __Browser and OS versions__: all
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: SharePoint
 
#### Describe the issue:
 
I want to show the checkboxes by default, so I set checkboxVisibility={ CheckboxVisibility.always }
 
#### Actual behavior:
 
Checkboxes only show on hover
 
#### Expected behavior:
 
Checkboxes should be visible

**Comment by KevinTCoughlin** [comment] 2018-08-13 20:05
Can repro, doesn't look like we respect that flag since the `mergeStyles` conversion or prior to that. Will dig in and fix.

**Comment by KevinTCoughlin** [comment] 2018-08-13 20:06
Actually looks like @kenotron has a fix for this already out #5912

**Comment by KevinTCoughlin** [comment] 2018-08-13 20:29
Confirmed locally that #5912 fixes the above issue. Thanks for the report @cschlechty and for the fix @kenotron!

**Closed by KevinTCoughlin** 2018-08-13 20:29 UTC
Labels: Component: DetailsList, Type: Bug :bug:
