### ISSUE TITLE
Panel doesn't allow close on click outside panel when isBlocking prop is false

### ISSUE THREAD

**Issue by bansalrachita** [OfficeDev/office-ui-fabric-react#12226] opened 2020-03-06 17:48 UTC
Panel should allow for close on click outside of panel if modal overlay is false.

Current:
The panel props onOuterClick doesn't take effect if the isBlocking is false.

Expected:
The panel props onOuterClick should be able to dismiss the panel even when isBlocking is false.

Reference code:
https://codepen.io/bansalrachita/pen/QWWRXXB

**Comment by aneeshack4** [comment] 2020-03-06 22:33
@bansalrachita this is by design - you can see the explanation in the non modal example (that's what setting isBlocking does): "This panel is non-modal: even when it's open, it allows interacting with content outside the panel."

**Comment by bansalrachita** [comment] 2020-03-09 20:02
@aneeshack4 : Basically my use-case was to be able to close the dialog when mouse click handler `onOuterClick` was called, specifically where the panel was non-modal and interaction is allowed with the content outside the panel. But it doesn't look like that function is being called as you could see in the codepen the `console.log()` is not printed when you click outside of the panel.

**Comment by aneeshack4** [comment] 2020-03-10 21:01
@bansalrachita and I spoke offline on a Teams call about this. Resolving because the light dismiss example on the OUFR examples page shows how to implement a Panel that closes itself as soon as there's interaction outside and the non-modal example shows how to implement a panel that allows interaction outside while keeping the panel open.

**Closed by aneeshack4** 2020-03-10 21:01 UTC
Labels: Component: Panel, Needs: Attention :wave:, Resolution: By Design
