### ISSUE TITLE
Todo App doesn't run

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#1479] opened 2017-04-11 20:23 UTC
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: Chrome on MacOS

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No 

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

`npm install`
and then `gulp serve` in apps/todo-app

#### Actual behavior:

Opens up a blank browser page

#### Expected behavior:

Opens up the todo-app sample in the new browser page

**Comment by leddie24** [comment] 2017-04-11 21:37
@atneik, I'm not having issues on my end.  Can you provide details on your versions of node, npm etc?

<img width="802" alt="screen shot 2017-04-11 at 2 36 16 pm" src="https://cloud.githubusercontent.com/assets/1291968/24931994/566b2dea-1ec4-11e7-8c2a-600e8c4adc24.png">

**Comment by dzearing** [comment] 2017-04-15 01:17
Closing, not reproing. Please provide additional info if it really is broken for you.

**Comment by MJomaa** [comment] 2017-05-25 19:04
@leddie24 @dzearing I'm getting the exact same behavior as @atneik

**Steps to reproduce**
1. Download this repo
2. Cut the Todo sample into another folder
3. npm install
4. npm start or gulp serve

**Versions**
OS: Windows 10 Build 15063
Node Version: 6.10.2
NPM Version: 3.10.10
Browser: Chrome 58

**Additional Info**
This is because it can't find `todo-app.js`. VS Code can't find `Todo.module.scss`

**Comment by erichdev** [comment] 2017-10-12 19:02
Couldn't repro, and app now uses webpack. Please reopen if there are still issues

**Closed by erichdev** 2017-10-12 19:02 UTC
Labels: bug, build-system, needs-owner
