### ISSUE TITLE
IconName class does not include all MDL2 icons

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#669] opened 2016-12-08 19:03 UTC
### Bug Report

- __Package version(s)__: 0.78.1

#### Describe the issue:

With the change for `CommandBar` to use the `Icon` component, several previously supported icons in the `CommandBar` no longer work. As the component references the `IconName` collection, it converts any icon not present there to `undefined`.

Non-exhaustive list of icons this affects: `Read`, `Send`, `Package`

#### Actual behavior:

![image](https://cloud.githubusercontent.com/assets/20823465/21023559/e7c86b22-bd35-11e6-8961-6db89f288971.png)

#### Expected behavior:

![image](https://cloud.githubusercontent.com/assets/20823465/21023541/d8af77e8-bd35-11e6-817a-984fa270c146.png)

**Comment by joschect** [comment] 2016-12-08 19:07
@MLoughry Hey, I just put in a pr to add package, I'll also add read and send. If you hear of any others please let me know!

**Comment by mikewheaton** [comment] 2016-12-08 19:08
I didn't realize we had enums for icon names. It turns out these are in `src/components/Icon/IconName.ts`. The icons come from [office-ui-fabric-core](https://github.com/OfficeDev/office-ui-fabric-core) and we have a JSON file in there, but no enums. So we'll either want to add this enum file to Fabric Core, or update the enum within Fabric React every time we update the version of Fabric Core used.

**Comment by MLoughry** [comment] 2016-12-08 19:08
Should there be some sort of build-verification?

**Comment by joschect** [comment] 2016-12-08 19:11
@mikewheaton They're pretty new. It would be cool if they were part of core.

@MLoughry I'll alter the contextualmenu to properly respect icons if there is no enum in the meantime.

**Comment by joschect** [comment] 2016-12-08 19:29
@MLoughry  and @mikewheaton could you confirm real quick that this is the correct icon list? https://github.com/OfficeDev/office-ui-fabric-core/blob/dd2aeb55b6ebe10fe633430042583b0da3e49de5/src/data/icons.json

**Comment by joschect** [comment] 2016-12-08 19:40
@mikewheaton random thing I noticed, the mdl2 icons have a duplicate of "snow"

**Comment by mikewheaton** [comment] 2016-12-08 19:45
@joschect: Yes, that JSON file is always updated with the latest icons in Fabric Core. So we'll want the enum to match.

And Snow is in there twice, which is odd. I'll look into that. ❄️

**Comment by mikewheaton** [comment] 2016-12-08 20:09
Turns out that there are two different snow icons with the same name. We'll have this corrected in the next version of the icon font.
![screen shot 2016-12-08 at 12 08 08 pm](https://cloud.githubusercontent.com/assets/1382445/21025905/2c3081b0-bd3f-11e6-8a3c-b502ddff646f.png)
![screen shot 2016-12-08 at 12 08 36 pm](https://cloud.githubusercontent.com/assets/1382445/21025908/2d6a10c8-bd3f-11e6-96b3-31e8970ed42d.png)

**Comment by dzearing** [comment] 2016-12-09 17:31
Can we at least get them in sync for now? Is there someone that can update the list asap?

**Comment by mikewheaton** [comment] 2016-12-09 18:38
Sure thing, I'll get these updated today. 😄

**Comment by mikewheaton** [comment] 2016-12-10 00:43
The only icon I've found that doesn't match the font is "CustomIcon". @joschect, ContextualMenu looks to be the only component that uses this. How does it work? Seems like it would output `ms-Icon--CustomIcon` but there's no corresponding CSS class for that.

**Comment by joschect** [comment] 2016-12-23 00:40
@mikewheaton It's supposed to be when you add in your own background image or something like that. For now I'm closing this as I have added all of the mdl2 icons

**Closed by joschect** 2016-12-23 00:40 UTC
Labels: bug
