### ISSUE TITLE
Icon Button: Clicking on the button creates flickering behaviour

### ISSUE THREAD

**Issue by twarzo** [OfficeDev/office-ui-fabric-react#5847] opened 2018-08-08 05:43 UTC
### Bug Report 
 
- __Package version(s)__: (fill this out)
- __Browser and OS versions__: IE and Windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: VSTS
 
#### Describe the issue:
 
Clicking on the button makes the button jumps. 
 
#### Actual behavior:
 
The button jumps when clicked. 
 
#### Expected behavior:
 
The button should not show flickering/jumpy behavior on click. 
 
![iconbuttonflickerbehaviour](https://user-images.githubusercontent.com/2266283/43818394-0f3e6bb6-9afc-11e8-9ef0-a8c2f4f5dcc9.gif)

**Comment by natalieethell** [comment] 2018-08-08 17:33
Hey @twarzo it looks like this is a known issue for buttons in IE. It looks like the problem is fixed by adding the following styles and wrapping the button in the span:

```
button:active span {
    	position:relative;
    	top: 0;
    	left: 0;
}

...

<button><span>I don't move!</span><button>
```

(Reference: https://stackoverflow.com/questions/10305658/prevent-button-from-shifting-during-click-in-ie)

@dzearing I heard you're working on a refactor for buttons, do you think this is something you want to account for in your PR?

**Comment by dzearing** [comment] 2018-08-23 03:28
This can be considered in the refactor, but this could just be patched immediately as the fix is relatively small.

**Closed** 2018-09-11 00:11 UTC
Labels: Browser: ie11, Component: Button
