### ISSUE TITLE
It's possible to select the same person multiple times in people picker

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#8500] opened 2019-03-27 18:32 UTC
### Environment Information 

- __Package version(s)__: The version used on the Office Fabric React page.

#### Reproduction steps

1. Go to the [Office Fabric React demo page](https://developer.microsoft.com/en-us/fabric#/components/peoplepicker).

2. Click on the people picker text field and type Annie lindquest.

3. Tab to the first suggested item (there should only be one).

4. Press enter repeatedly at a fast speed.

#### Actual behavior
 
The item is added for as many times as the enter button is pressed.
 
#### Expected behavior:

The additional keystrokes should be ignored and the item should only be added once, the way it works when clicking instead of using the keyboard.

#### Priorities and help requested:
Are you willing to submit a PR to fix? **No**
 
Requested priority: **High**

**Comment by Vitalius1** [comment] 2019-03-27 20:47
![2019-03-27 13 35 30](https://user-images.githubusercontent.com/29514833/55111114-d9266780-5096-11e9-899e-c7d2be27c4b0.gif)

**Comment by Vitalius1** [comment] 2019-03-27 20:48
Bug verified and indeed is something needs to be fixed. Will take a stab at it. @joschect any pointers where to start looking 🤔 ?

**Comment by Vitalius1** [comment] 2019-03-27 20:54
@JoshuaLamusga Thanks for submitting the issue and we will have a fix shortly. At the same time will be closing the issue in favor of #8451 as it's a duplicate of that one. You can subscribe for notifications on the issue mentioned to know when a release with the fix will be ready for you to use.

**Closed** 2019-03-27 20:56 UTC
Labels: Component: PeoplePicker, Resolution: Duplicate, Type: Bug :bug:
