### ISSUE TITLE
[doc]interface of components may lack properties

### ISSUE THREAD

**Issue by HaveF** [OfficeDev/office-ui-fabric-react#7960] opened 2019-02-12 04:07 UTC
**Describe the feature that you would like added**
In the doc of [Dropdown component](https://developer.microsoft.com/en-us/fabric#/components/dropdown#Implementation), the `IDropdownProps interface` should have `defaultSelectedKey` property, but in fact, the `defaultSelectedKey` is here: [packages/office-ui-fabric-react/src/utilities/selectableOption/SelectableDroppableText.types.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/utilities/selectableOption/SelectableDroppableText.types.ts#L41), which used as extends `export interface IDropdownProps extends ISelectableDroppableTextProps<IDropdown, HTMLDivElement>`, but **did not include in the doc**.

Btw, based on the type of defaultSelectedKey: `defaultSelectedKey?: string | number | string[] | number[];`, the `defaultSelectedKeys` seems be a redundant. 

**What component or utility would this be added to**

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by JasonGore** [comment] 2019-02-12 18:11
This issue appears to be a dupe of #7819. Documentation not capturing inherited issues is known and being worked on (#6780).

Regarding `defaultSelectedKeys`, I don't think it's quite redundant as we want to guarantee that it's a flat array of `string` or `number` and therefore can't be `defaultSelectedKey[]`.

**Comment by HaveF** [comment] 2019-02-12 22:30
Thanks, @JasonGore . I did not notice that dupe issue.

> Regarding `defaultSelectedKeys`, I don't think it's quite redundant as we want to guarantee that it's a flat array of `string` or `number` and therefore can't be `defaultSelectedKey[]`.

I see. Maybe we can remove the `string[] | number[]` types from defaultSelectedKey to make more clean? We make the `defaultSelectedKeys` and `defaultSelectedKey` as orthogonal properties.

**Comment by JasonGore** [comment] 2019-02-12 22:34
Well, that would technically be a breaking change. Are you saying `string[] | number[]` are not valid typings for `defaultSelectedKey`?

**Comment by HaveF** [comment] 2019-02-12 22:46
I mean the user may confused on where to put their default keys `string[] | number[]` when seeing the future enhanced document,  in `defaultSelectedKeys` or `defaultSelectedKey`, or both?

**Comment by JasonGore** [comment] 2019-02-13 19:19
It appears `defaultSelectedKeys` is only used when `multiSelect` is true, otherwise `defaultSelectedKey` is used. I'll update the documentation to clarify.

**Closed** 2019-02-13 20:27 UTC
Labels: Area: Documentation, Component: Dropdown, Needs: Attention :wave:
