### ISSUE TITLE
require.js and listviewdataprefetch.js of SharePoint removes styles of Office UI Fabric

### ISSUE THREAD

**Issue by db3005** [OfficeDev/office-ui-fabric-react#2938] opened 2017-09-25 12:45 UTC
### Bug Report

- __Package version(s)__: 4.35.1
- __Browser and OS versions__: All browsers, Windows 10, ...

Requested priority: Blocking

Products/sites affected: All SP Online classic pages on tenants with the require.js version below which are using Office UI Fabric components.

#### Describe the issue:

We still got the problem on our tenant that our styles get removed when the page is loaded (mostly with clear cache)

require.js version: https://spoprod-a.akamaihd.net/files/odsp-next-prod_ship-2017-09-08-sts_20170920.006/require-951f856e.js

For example we use the Facepile component to display Users but sometimes the css got removed, always when require.js and listviewdataprefetch.js are loaded. 

Any suggestions what we have to do?
Thanks in advance!

#### Actual behavior:

![image](https://user-images.githubusercontent.com/32265743/30807549-a7d315a8-a1fa-11e7-85ac-87bddaf21bce.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/32265743/30807584-d26d9aa4-a1fa-11e7-93d9-0e70269c6856.png)

Steps to reproduce:

1. Open any browser 
2. Clear Cache and require.js include listviewdataprefetch.js gets loaded
3. CSS for components is missing completely

**Comment by dzearing** [comment] 2017-09-26 05:15
@jijizz Can you please take a look?

It seems this has regressed again.

**Comment by jijizz** [comment] 2017-09-26 05:34
sure, I have couple questions:
1. did this issue only start happening with most recent build?
2. @db3005 Can you please share a repro page? A test account that I can login to debug would be the best because I can not reproduce by myself.

**Comment by db3005** [comment] 2017-09-26 08:55
Hey @jijizz ,

this issue happened with nearly every build version we tested, i created a new app with office ui version 4.50.1, which only renders a rating component with 3 stars, but the CSS is broken sometimes. This only happens if the require.js gets loaded, this is mostly after clear cache, otherwise the layout is correct if it doesnt get loaded.

I created a repro page with this little app, can u send me an email ?

Thanks in advance

**Comment by jijizz** [comment] 2017-09-26 14:40
@db3005, email sent, waiting for the repro information.  Thanks

**Comment by db3005** [comment] 2017-09-27 06:08
@jijizz, email with repro information sent, thanks for your help!

**Comment by jijizz** [comment] 2017-09-27 07:21
Thanks for the repro. For this particular case, it is caused by the interference between your Office UI bundle (main.js)  and a modern document library UI performance feature.  That performance feature overloads loadStyles function before being used by your office UI bundle.  To easily workaround it, please add this line of code before loading your office ui fabric react bundle:

```js
window.__themeState__.loadStyles = undefined;
```
 
So your bundle loading code should be something like this:

document.getElementById("buttonTest").onclick = function() {
                window.__themeState__.loadStyles = undefined
var script = document.createElement("script"); //Make a script DOM node
script.src = "https://officeleftnavigationmenuaddin.azurewebsites.net/ReactJS/OfficeUiTest/static/js/main.js";
document.head.appendChild(script); 
}

**Comment by db3005** [comment] 2017-09-27 07:43
Thanks for your fast feedback!

In this case that we click a button and the react stuff gets loaded it will work with your workaround.
But in many other cases we start loading the react files on page load and then it will happen the same issue.
I changed the repro that the javascript load the react files on page load:

`if (window.__themeState__ !== undefined) {
   window.__themeState__.loadStyles = undefined;
}`
`var script = document.createElement("script");`
`script.src = "main.js";`
`document.head.appendChild(script); `

Still the same issue :-( Any other workaround with this problem ? 

Thanks and best regards

**Comment by jijizz** [comment] 2017-09-27 08:53
Yeah, it is a nasty race condition.  for your case, add the highlighted code before your script loading code:

```js
window.__themeState__ = window.__themeState__ || {
        theme: undefined,
        lastStyleElement: undefined,
        registeredStyles: [],
   loadStyles: undefined
};

var script = document.createElement("script");
script.src = "main.js";
document.head.appendChild(script);
```

I understand the code looks a bit hacky this way. But you should be unblocked. Meanwhile, I am seeking a fix in sharepoint code base.

**Comment by db3005** [comment] 2017-09-27 09:55
Thanks for your workaround. 
I included it now without the "window.__themeState__ ||" so that the themeState Object its always set to 

`{
   theme: undefined,
   lastStyleElement: undefined,
   registeredStyles: [],
   loadStyles: undefined
};`

when the React gets loaded. Now it always renders correct, but another fix in the sharepoint code if possible would be ofcourse much better. 

Thanks for your help so far!

**Comment by dzearing** [comment] 2017-10-12 16:08
Closing as this seems to have been resolved.

**Closed by dzearing** 2017-10-12 16:08 UTC
Labels: needs-investigation
