### ISSUE TITLE
fabric docs website broken

### ISSUE THREAD

**Issue by harshzalavadiya** [OfficeDev/office-ui-fabric-react#9121] opened 2019-05-16 13:20 UTC
### Environment Information 
 
- __Package version(s)__: NA
- __Browser and OS versions__: Chrome and Firefox desktop

#### Actual behavior:
 
- Docs website not loading completely
 
#### Expected behavior:
 
docs website should load completely

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: High
 
Products/sites affected: https://developer.microsoft.com/en-us/fabric
 
```txt
# Errors on console

fabric:624 GET https://developer.microsoft.com/en-us/fabricweb.azureedge.net/fabric-website/20190516.1/fabric-sitev5.min.js

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://web.vortex.data.microsoft.com/collect/v1?$mscomCookies=false&ext-javascript-msfpc=%27GUID%3D2a2b33418000499d9f4f4b1495b33fb4%26HASH%3D2a2b%26LV%3D201905%26V%3D4%26LU%3D1558011872813%27 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by Perneel** [comment] 2019-05-16 14:14
+1

Request URL: https://developer.microsoft.com/en-us/fabricweb.azureedge.net/fabric-website/20190516.1/fabric-sitev5.min.js
Request Method: GET
Status Code: 404

**Comment by ecraig12345** [comment] 2019-05-16 15:58
Thanks for reporting this! I just rolled the site back to the previous build, which should fix the issue (it may take up to an hour to show up due to CDN caching). We'll look into what happened and get a real fix out sometime today.

**Comment by cwhitten** [comment] 2019-05-16 16:13
@ecraig12345 here is what I'm seeing in Chromium Edge
<img width="1033" alt="Screen Shot 2019-05-16 at 9 13 11 AM" src="https://user-images.githubusercontent.com/1156704/57869920-e7515400-77ba-11e9-92f3-9b9fe1d3740f.png">

**Comment by ecraig12345** [comment] 2019-05-16 16:59
That looks like a separate issue, which shouldn't be impacting whether the page renders (that code appears to be from the developer.microsoft.com header, which isn't something we own). The CDN cache should have expired now--can you try loading the website again?

**Comment by ecraig12345** [comment] 2019-05-16 17:13
@kenotron just checked in a fix for the root cause, but I'm reopening this for now in case anyone is still having issues.

**Comment by harshzalavadiya** [comment] 2019-05-17 06:06
Checked just now site works fine :smile: 
@cwhitten, i guess that error might be because your ad blocker might be blocking tracking script on developer.microsoft.com

**Closed** 2019-05-20 18:44 UTC
Labels: Area: Website, Needs: Author Feedback, Type: Bug :bug:

**Comment by tmt003-ho** [comment] 2019-06-12 05:44
Please reopen this, for some reason it is not working again https://developer.microsoft.com/en-us/fabric

**Comment by micahgodbolt** [comment] 2019-06-12 06:02
yup, looks like an issue with upgrading to the newest version of react. we're currently rolling back to a previous version
