### ISSUE TITLE
Image: Does not handle loaded event correctly in Edge

### ISSUE THREAD

**Issue by AbhinavSTeotia** [OfficeDev/office-ui-fabric-react#694] opened 2016-12-14 07:44 UTC
### Bug Report

- __Package version(s)__: "0.74.0"
- __Browser and OS versions__: Edge on Win10

#### Describe the issue:

ChoiceGroup options accepts imageSrc. In one of the cases imageSrc is CDN url. 

The the image is never shown on first load, this happens only in following condition
1. Browser is edge. Works fine on chrome/FF
2. Hard refresh(ctrl+f5) is done (browser cache off)

#### Actual behavior:

Image is never loaded, the css of element remains "is-notLoaded". Although we can observe network request being made and fulfilled with 200 response.

On debug, the image load works fine, hence stuck on root-causing it further. Relevant src - Image.js -> Image.render.

#### Expected behavior:

As in case of chrome/ff, the image should show up when load is complete.

**Comment by pankajkhanzode** [comment] 2016-12-16 04:10
I have seen it happening on List control as well. Essentially, the images are sources from CDN and for fresh load it takes some time. So my hunch is other controls where we have icons sourced from CDN, this issue is seen on Edge.

@AbhinavSTeotia - Please confirm.

**Comment by AbhinavSTeotia** [comment] 2016-12-16 06:55
Observing this issue at multiple controls. Based on src of this issue, culprit seems to be in image.js. Hence a generic issue of image load from CDN (some delay) on edge when hard refresh is done.

**Comment by AbhinavSinghT** [comment] 2016-12-26 04:53
Any update on this issue, we are observing it more frequently now. The issue is observed only in Edge. Will upgrading package version help ?

**Comment by mikewheaton** [comment] 2016-12-30 17:14
@AbhinavSTeotia: I'm not aware of any work that's been done to investigate or fix this issue, as many people are out for the holidays right now. So even though it's unlikely to help, could you please verify that this issue exists in the [latest release (0.82.4)](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v0.82.4)?

**Comment by dzearing** [comment] 2017-01-05 01:51
@AbhinavSinghT @AbhinavSTeotia I don't really understand what you're experiencing. We have not seen this issue in our use cases. Do you have any details? You need to dig in to understand your scenario, what the server is returning, and why the image isn't getting a callback. Is there an event that isn't set up in time? Is the response hitting some code path that prevents the image from loading?

I made an example of Image loading images from a CDN here and I see no problems in Edge:

http://codepen.io/dzearing/full/ENPzYM/

**Comment by dzearing** [comment] 2017-01-12 23:07
I'm going to close this issue as I can't repro it. Please re-open if you can provide a repro.

**Closed by dzearing** 2017-01-12 23:07 UTC
Labels: bug, waiting-for-details

**Comment by Squiggle** [comment] 2017-01-24 15:05
I am experiencing the same problem on IE11.

We're securely loading images by including a token in the query string.
From the Browser's perspective (developer tools network log), the request is sent but never appears to complete (is stuck on 'Pending').

There are no issue with the server, and it all works fine in Chrome.

Have also reverted to using a normal `<img>` element, and this also works fine in IE.


Will attempt a repro if I don't find a solution soon.

**Comment by AbhinavSTeotia** [comment] 2017-01-31 10:36
As mentioned above, the issue can be reproduced with image from CDN. In codepen created above use following image src : **https://cdn.vsassets.io/v/20170127T182013/_content/CIWorkflow/brand-visualstudio.svg**.

I have copied your codepen here with above image src: http://codepen.io/abhinavsinghteotia/pen/YNeyqe/.

**Clear the browser cache**, issue happens on first load only.
