### ISSUE TITLE
Cards should be using themable elevation rather than depth constants

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#9169] opened 2019-05-22 00:09 UTC
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 

![image](https://user-images.githubusercontent.com/17696563/58138497-3ba96900-7beb-11e9-8884-0e8eb34fc41c.png)

 
#### Expected behavior:
 

![image](https://user-images.githubusercontent.com/17696563/58138542-85924f00-7beb-11e9-9996-c147e5416daa.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
 
I think it's caused by boxShadow color in fluent style 
https://github.com/OfficeDev/office-ui-fabric-react/blob/40487942eabddbb5a7daee45acd7f90a909ad07a/packages/react-cards/src/components/Card/Card.styles.ts

**Comment by kenotron** [comment] 2019-05-22 15:33
@khmakoto for FYI
@JasonGore gave me a great tip about `<Customizer>` that will allow you to override border:

https://codesandbox.io/s/card-tokens-4cg9n

To note, these are the magical lines for how to make border change for Cards:

```tsx
      <Customizer
        scopedSettings={{
          Card: {
            tokens: {
              boxShadow: "none"
            }
          }
        }}
      >
        <Card>hello</Card>
      </Customizer>
```

**Comment by kenotron** [comment] 2019-05-22 15:34
Please close this bug if this addresses the issue for you, thanks!

**Comment by gggjtgxing** [comment] 2019-05-22 15:55
Thanks for your great tip, but is that possible to make Depths.depth4 and other Depths variables themable, otherwise people need to override all boxShadow with Depths variables(as it's not used only for cards), and not sure if override border breaks fluent style.

**Comment by kenotron** [comment] 2019-05-22 17:46
Unfortunately not at this time - but these are just variables and they're used as such. There's not much of an opportunity to override them other than one component at a time. This is a good feature request though. For reference: 

```tsx
export declare namespace Depths {
    const depth0 = "0 0 0 0 transparent";
    const depth4 = "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)";
    const depth8 = "0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108)";
    const depth16 = "0 6.4px 14.4px 0 rgba(0, 0, 0, 0.132), 0 1.2px 3.6px 0 rgba(0, 0, 0, 0.108)";
    const depth64 = "0 25.6px 57.6px 0 rgba(0, 0, 0, 0.22), 0 4.8px 14.4px 0 rgba(0, 0, 0, 0.18)";
}
```

**Comment by JasonGore** [comment] 2019-05-22 17:49
Depths are constants specific to `fluent-theme` package. I think the issue here is that `Card` is using these constants directly instead of using the `elevation` defined in the theme, which map to `Depths`.

I think the fix here is to have `Card` use `elevations` in theme instead of `Depths` directly. That way end users can customize their own theme with whatever `elevations` they choose.

**Comment by kenotron** [comment] 2019-05-22 17:54
Oh I didn't even know there is an effects.elevation thing in themes! This is the right call.

**Comment by JasonGore** [comment] 2019-05-22 17:56
@gggjtgxing Once this issue is fixed you should be able to do something like this and control the `elevation` values used by components:

```tsx
createTheme({
  effects: {
    elevation4: Depths.depth4,
    elevation8: Depths.depth8,
    elevation16: Depths.depth16,
    elevation64: Depths.depth64
  }
});
```

**Comment by JasonGore** [comment] 2019-05-22 18:03
Also, please let us know if you've observed this with any other components. I did a check and I think this was the only component using `fluent-theme` constants directly. Thanks!

**Comment by gggjtgxing** [comment] 2019-05-22 18:14
sorry, I was wrong, I noticed other compoents are using `Depths` constants but not from `fluent-theme` package
https://github.com/OfficeDev/office-ui-fabric-react/blob/5f231856701a7217cfd785a69b593593aa9a7210/packages/azure-themes/src/azure/styles/ColorPicker.styles.ts

**Comment by JasonGore** [comment] 2019-05-22 18:17
As long as the `Depths` are only used in a theme package (`fluent-theme`, `azure-theme`, etc.) like the one you listed, that's ok because end users can still override them via theming. The issue is when component style files in non-theme packages are referring directly to `Depths` instead of `elevation` in the theme.

**Comment by gggjtgxing** [comment] 2019-05-22 20:38
@JasonGore does that mean 'elevation' will have different values according to the theme setting

**Comment by JasonGore** [comment] 2019-05-22 20:43
Yes, it will. Fluent will prescribe defaults to `elevation` mapping them to various values of `Depths`, but when `Card` is fixed, you will be able to override them with your own theme (like I showed above.)

**Comment by gggjtgxing** [comment] 2019-05-22 20:45
but I got same `elevation` for different theme, 
![image](https://user-images.githubusercontent.com/17696563/58207605-d790ae80-7c97-11e9-88e1-5aeb0165deb8.png)

**Comment by JasonGore** [comment] 2019-05-22 22:04
I'm not sure what problem you're highlighting. Sure, different themes may have the same elevation, but it doesn't really matter what the default theme is because you can modify it. When you say "respect theme settings", I don't know what you mean. You have full control over the theme. [Here's a CodeSandbox ](https://codesandbox.io/s/fluent-elevations-9169-mh3qq) that shows the default elevations with code that changes the elevations and the new theme showing those changes.

![image](https://user-images.githubusercontent.com/26070760/58212161-cac58800-7ca2-11e9-977b-c4c4bd591337.png)

**Closed** 2019-06-18 17:58 UTC
Labels: Component: Card, Type: Bug :bug:
