### ISSUE TITLE
How to use Selawik which an open source drop-in substitute for Segoe UI.

### ISSUE THREAD

**Issue by CaptainSadaf** [OfficeDev/office-ui-fabric-react#5011] opened 2018-05-28 06:52 UTC
There is no CDN avaiable of Selawik library so how we can replace it with Segoe and there is no proper documention and npm package available of Selawick.
So how i can apply font family selawick , while i have applied Open Sans which is working because CDN and npm package is available of it but how Selawick could be applied?

**Comment by micahgodbolt** [comment] 2018-12-27 19:32
duplicate of #7417 - we need better docs/process for swapping out fonts.

**Closed by micahgodbolt** 2018-12-27 19:32 UTC
Labels: Type: Question ❔
