### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & IModalProps'.

### ISSUE THREAD

**Issue by Dangerous-Mind** [OfficeDev/office-ui-fabric-react#9300] opened 2019-05-31 18:46 UTC
When building a SPFx 1.8.2 solution (it started on 1.8) it gives the message:

> Property 'children' does not exist on type 'IntrinsicAttributes & IModalProps'.

### Environment Information 
 
- __Package version(s)__: (6.143.0) 
- __Browser and OS versions__: (Windows 10)
- __rush-stack-compiler__: (3.3 or 2.9)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Blocking, Low) 
It depends

**Comment by JasonGore** [comment] 2019-05-31 19:14
This may be a dupe of #8458. Could you review and see if it applies? Thanks!

**Comment by Dangerous-Mind** [comment] 2019-06-07 21:44
Sorry, I thaught I had made a comment.
No. Its not the same issue.
It only on the modal element from office fabric.

**Comment by JasonGore** [comment] 2019-06-07 22:39
While the component it's reported against may be different, the compiler error is the same, as is the rush-stack-compiler version. Can you try the steps [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/8458#issuecomment-478388791) and see if they have any effect? Thanks!

**Comment by gschwendt** [comment] 2019-06-10 14:48
I'm on rush-stack-compiler-3.2@0.2.17 and I'm also experiencing this issue. 

Type '{ children: Element[]; isDarkOverlay: true; isOpen: boolean; isBlocking: false; onDismiss: () => void; containerClassName: string; }' is not assignable to type 'IntrinsicAttributes & IModalProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IModalProps'.

```
<Modal
  isDarkOverlay={true}
  isOpen={this.state.showModal}
  isBlocking={false}
  onDismiss={this.handleDismiss}
  containerClassName={styles.orgChartModal}
  >
  <IconButton
    title='Open in New Window'
    iconProps={{iconName: 'OpenInNewWindow'}}
    onClick={() => window.open(this.state.myUrl)}
    style={{position: 'fixed', left: '6%', zIndex: 9999}}
    />
  <IconButton 
    title='Close'
    iconProps={{iconName: 'ChromeClose'}}
    onClick={this.handleDismiss} 
    style={{position: 'fixed', right: '6%', zIndex: 9999}}
    />
  <MyCustomComponent />
</Modal>
```

**Comment by Dangerous-Mind** [comment] 2019-06-14 17:55
I had some compiling errors at the time
But I managed to get it to compile

**Comment by kodofix** [comment] 2019-07-23 11:26
I have also really similar issue right now, but it's affected by environmental quite strong.

I'm using DialogComtent and get this message:
Message:
Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & IDialogContentProps'.

I use 
"@microsoft/sp-office-ui-fabric-core": "1.8.2",
 "@microsoft/rush-stack-compiler-3.2": "0.3.26",

Everything looks fine just one problem in Problems tab, but when I try to use webpart with this Dialog after click on icon my screen grayout and nothing happened:
![DialogBug](https://user-images.githubusercontent.com/17184220/61708408-09cc9400-ad4d-11e9-81a8-016484cfb0f2.gif)

I have try to use this solution https://github.com/OfficeDev/office-ui-fabric-react/issues/8458#issuecomment-478388791 but unfortunately doesn't work

**Comment by nguyentoantuit** [comment] 2019-07-24 07:37
I have the same issue know with "typescript": "3.3.4000",
Do we have any workaround solution yet?

**Comment by OverkillTV** [comment] 2019-07-27 05:04
Using typescript 3.2.4 vs rush-stack-compiler-3.2 works for me even though the error still show in VS but it compiled and built successfully

**Comment by cliffkoh** [comment] 2019-08-13 02:48
cc @aditima @KevinTCoughlin

**Comment by chotkos** [comment] 2019-09-08 13:57
> Using typescript 3.2.4 vs rush-stack-compiler-3.2 works for me even though the error still show in VS but it compiled and built successfully

Hi, could you please share your package.json? Are you using it like this?:
```
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.2": "0.3.2",
```

**Comment by OverkillTV** [comment] 2019-09-09 08:13
> > Using typescript 3.2.4 vs rush-stack-compiler-3.2 works for me even though the error still show in VS but it compiled and built successfully
> 
> Hi, could you please share your package.json? Are you using it like this?:
> 
> ```
>   "devDependencies": {
>     "@microsoft/rush-stack-compiler-3.2": "0.3.2",
> ```

Hi @chotkos,
 
```
"devDependencies": {
    "@microsoft/rush-stack-compiler-3.2": "0.2.3",
    "@microsoft/sp-build-web": "1.8.2",
    "@microsoft/sp-module-interfaces": "1.8.2",
    "@microsoft/sp-tslint-rules": "1.8.2",
    "@microsoft/sp-webpart-workbench": "1.8.2",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "typescript": "3.2.4"
  }
```

**Closed** 2020-02-11 00:40 UTC
Labels: Area: SPFx / Rush-Stack, Area: Typescript
