### ISSUE TITLE
Details list is not announcing the position of row in the list.

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#3847] opened 2018-01-31 15:25 UTC
Products/sites affected: (if applicable) VSTS

I am consuming Details list in my product, and it is not announcing position of respective row in the list. (For ex- 2 of 5, where 2 is the selected row and 5 is the total rows in list.)

I looked in https://developer.microsoft.com/en-us/fabric#/components/detailslist and here also it is not announcing it on changing the rows.

From the code, I can see that in each row aria-rowindex is given but not sure why it is not reading it.

Can you please tell me if this is expected behaviour of DetailsList or is it a bug. ?

**Comment by mdmdakbar** [comment] 2018-01-31 15:26
The above code I am talking about is related to this UI.
![image](https://user-images.githubusercontent.com/19491487/35631187-42784870-06c9-11e8-8a2b-d054b4f6b9a4.png)

**Comment by battletoilet** [comment] 2018-01-31 21:11
Duplicate of https://github.com/OfficeDev/office-ui-fabric-react/issues/3834

**Closed by battletoilet** 2018-01-31 21:11 UTC
Labels: accessibility, enhancement, needs-screen-reader-testing
