### ISSUE TITLE
Narrator doesn't read expanded information on Dropdown

### ISSUE THREAD

**Issue by cnamal** [OfficeDev/office-ui-fabric-react#9659] opened 2019-07-02 11:41 UTC
Go to https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown
Start Narrator
Tab until you get to the _Basic uncontrolled example_ dropdown.

Narrator doesn't convey the `aria-expanded` information. 

I saw this [comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/6326#issuecomment-493503894), however the linked W3 documentation doesn't use `aria-expanded`, so it's incomparable IMO. Might still be a Narrator issue though :)

**Comment by khmakoto** [comment] 2019-07-02 22:35
Hi @cnamal! Thanks for filing the issue! I can confirm that this is indeed happening. I'll take a look to see if this is our issue or an issue with Narrator. Thanks!

**Comment by cnamal** [comment] 2019-07-17 10:55
the same is true for Combobox.

**Comment by cnamal** [comment] 2019-07-17 10:58
W3C provides a working Combobox:
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
I think the difference is W3C's expanded information is on a div, and on OUFR it's on an input

**Comment by eveleens** [comment] 2019-07-24 20:05
Any traction on this one?

**Comment by khmakoto** [comment] 2019-07-25 16:15
Hi @eveleens still waiting for a response on this one. The narrator team has not been very responsive lately.

**Comment by kenotron** [comment] 2019-09-19 20:57
I've linked the internal Narrator team via their Feedback Hub on Windows with this link:
https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

Which is closer in functionality than a ComboBox (simpler). We cannot action on this since we're already applying the correct aria-expanded state already. I'm closing this one - it is an external issue.

**Closed by kenotron** 2019-09-19 20:57 UTC
Labels: Area: Accessibility, Area: Narrator, Component: Dropdown, Resolution: External, Type: Bug :bug:
