### ISSUE TITLE
Checkbox: ARIA attribute "aria-describedby" is getting attached without any reference value in 5.x

### ISSUE THREAD

**Issue by kmrrakesh** [OfficeDev/office-ui-fabric-react#4944] opened 2018-05-22 12:30 UTC
Bug Report
Describe the issue :
ARIA attribute, "aria-describedby" for checkbox is getting attached, without any reference value

It is happening in the latest fabric ui, for all chekbox with/without associated label, and run keros to replicate it.
It complains as "ARIA attributes must conform to valid values"

Actual behavior:
Checkbox is associating an attribute as "aria-describedby" without value

Expected behavior:
Checkbox attribute "aria-describedby", should have relevant value

**Comment by micahgodbolt** [comment] 2018-07-16 05:10
What version of Fabric are you using, and can you provide a reporable example? I don't see any issue with our current release.

**Comment by arunarokk** [comment] 2018-07-16 20:58
@micahgodbolt , this bug is repro on the version 5.110, its resolved in current version.

**Comment by micahgodbolt** [comment] 2018-07-16 23:10
So the problem is that this fix needs to be backported to 5.x.

What version of Fabric are you using? Are you able to upgrade to 6.x? If not, would you be able to create a PR to backport the changes to 5.x? I'd be happy to review/approve the PR.

**Comment by arunarokk** [comment] 2018-07-17 04:29
we will be upgrading to 6.x very soon.

**Closed** 2018-07-17 05:12 UTC
Labels: Component: Checkbox, Needs: Author Feedback
