### ISSUE TITLE
Support dir=RTL tag on elements other than HTML

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#7966] opened 2019-02-12 18:45 UTC
**Describe the feature that you would like added**
Currently our RTL logic assumes that the language direction is specified via <html dir=RTL>. Some apps have longstanding expectations that the dir tag is on the body tag, or other parts of the application. 

**What component or utility would this be added to**
Utilities/RTL

**Have you discussed this feature with our team, and if so, who**
@JasonGore

**Comment by micahgodbolt** [comment] 2019-02-12 18:45
@dzearing do you know if there is a reason RTL has to be on HTML? Or was it just build that way for simplicity. Teams is having an issue with this specifically.

**Comment by dzearing** [comment] 2019-02-12 19:12
Dupe of https://github.com/OfficeDev/office-ui-fabric-react/issues/6604

You can specify `<div dir='rtl'>` anywhere you want. HTML styling would filp. But, the problem is that styling would not be affected; our lefts would not flip to right, because they would not be aware of the context.

Which is why `dir` should be provided through theme settings, which are accessible to styling, prior to rendering. If you want to flip the `dir` of a subsection, provide a theme subset around an area to style appropriately.

**Comment by JasonGore** [comment] 2019-02-12 19:16
Updating `getRTL` to use body `dir` but as David mentioned that still leaves the issue of styling not applying the proper direction. Closing as dupe of #6604.

**Comment by JasonGore** [comment] 2019-02-12 19:20
Actually I misunderstood the resolution. It seems worthwhile to have an `html` tag with `body` fallback with or without theming. I'll reopen this to address that part.

**Comment by micahgodbolt** [comment] 2019-02-12 20:29
yeah, I agree there is a better solution here with theme, but I'd like to get a faster fix out the door for teams if possible.

**Comment by JasonGore** [comment] 2019-02-13 18:49
We need to discuss components that use CSS too. The `@mixin LTR` and `RTL` assume that dir attribute is on html element. That means components using CSS (like `Calendar`) will still ignore body dir attribute:

![image](https://user-images.githubusercontent.com/26070760/52735629-eff87b00-2f7c-11e9-9f49-9de5bd5e21e3.png)

**Closed** 2019-02-14 00:20 UTC
Labels: Package: utilities, Type: Bug :bug:
