### ISSUE TITLE
Issue with office fabric dependency while building with webpack 

### ISSUE THREAD

**Issue by Ajay-MS** [OfficeDev/office-ui-fabric-react#7542] opened 2019-01-07 05:44 UTC
I am trying to build an web extension building via vss-web-extension-sdk .  

I am building web extension via webpack. Below is build script ( from package.json ) 
```
"build": "npm run lint && npm run clean && npm run webpack",
"clean": "rimraf ./dist && rimraf ./*.vsix",
"lint": "tslint -c tslint.json 'src/*.tsx'",
"webpack": "webpack --progress --colors --config webpack.config.js --output-path ./dist"
```

While building UI component of the extension, I am taking dependency on office fabric node module. 

I am getting following issue with office fabric node module: 
```
[tsl] ERROR in E:\SampleExtension\extension\node_modules\@uifabric\merge-styles\lib\IStyleSet.d.ts(15,67)
      TS1005: ';' expected.

[tsl] ERROR in E:\SampleExtension\extension\node_modules\@uifabric\merge-styles\lib\IStyleSet.d.ts(15,114)
      TS1005: '(' expected.

[tsl] ERROR in E:\SampleExtension\extension\node_modules\@uifabric\merge-styles\lib\IStyleSet.d.ts(15,136)
      TS1005: '(' expected.
```

### Environment Information 

- @uifabric/merge-styles@6.15.0
-  office-ui-fabric-react@6.119.0
-  Chrome Version 71.0.3578.98 (Official Build) (64-bit)

#### Actual behavior:
 
[tsl] ERROR in E:\SampleExtension\extension\node_modules\@uifabric\merge-styles\lib\IStyleSet.d.ts(15,67)
      TS1005: ';' expected.
 
#### Expected behavior:
 
Compilation should be successful. 

#### Priorities and help requested:
 
Requested priority: (High)

**Comment by Vitalius1** [comment] 2019-01-07 06:05
@cliffkoh can you look into this? Looks like you touched last that line (#6649). The only thing I can confirm is that the `IStyleSet` file indeed has a tslint error pointing out a missing semicolon. The other 2 errors from the logs provided look like are on the same line and may be a consequence of the first error.

<img width="866" alt="screen shot 2019-01-06 at 9 51 37 pm" src="https://user-images.githubusercontent.com/29514833/50751223-ba35d900-11fd-11e9-9dde-c76078f15457.png">

**Comment by cliffkoh** [comment] 2019-01-07 07:21
@ajay-ms  what is the version of TypeScript you're using? Most likely that is the root cause. Fabric has a minimum requirement of TypeScript 2.8.2.

**Comment by Ajay-MS** [comment] 2019-01-07 07:39
@cliffkoh 

I was using typescript version 2.3.4 , I have just tried with version 2.8.2  and compilation succeed. Thanks for quick response. I am unblocked on this.

**Comment by Vitalius1** [comment] 2019-01-07 07:41
Thanks @cliffkoh for the solution. Closing this now.

**Closed by Vitalius1** 2019-01-07 07:41 UTC
Labels: Area: Typescript, Area: merge-styles, Needs: Attention :wave:, Needs: Triage :mag:
