### ISSUE TITLE
IconNames is undefined in unit tests

### ISSUE THREAD

**Issue by Pajn** [OfficeDev/office-ui-fabric-react#4504] opened 2018-04-10 11:19 UTC
### Bug Report

- __Package version(s)__: 5.79.1
- __Browser and OS versions__: N/A, OSX HIgh Sierra

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: Not yet public

#### Describe the issue:
IconNames from @uifabric/icons is undefined in our unit tests which makes it impossible to create any unit test in code which uses fabric icons. This occurs event if we set up the icons with initializeIcons in a Jest setupFile.

#### Actual behavior:
IconNames is undefined

#### Expected behavior:
IconNames is not undefined so that code can refer to icons in IconNames without crashing due to reading a property of undefined.

### If applicable, please provide a codepen repro:

N/A

**Comment by michaelangotti** [comment] 2018-04-12 17:27
@Pajn Could supply a repro or code sample?

**Comment by dzearing** [comment] 2018-04-16 03:38
This is easy to repro. 

```bash
create-react-app my-app --scripts-version=react-scripts-ts
yarn add office-ui-fabric-react @types/prop-types prop-types @uifabric/icons
yarn start
```

In the App.tsx, use `IconNames`:

```ts
import { IconNames } from '@uifabric/icons/lib/IconNames';
import { Icon } from 'office-ui-fabric-react';

...
        <Icon iconName={IconNames.Download} />

```

Will compile just fine, but at runtime `IconNames` is undefined. This is because it is marked as a const enum, and TypeScript doesn't want to auto expand const enums.

You can see the declaration in `@uifabric/icons/lib/IconNames.d.ts` that the const enum is there and intact. However, TypeScript is not consuming the const enum correctly. The expectation is that TypeScript expands `IconNames.Download` to the literal string `"Download"`.

@RyanCavanaugh might know what to do here.

**Comment by dzearing** [comment] 2018-04-16 03:40
If we remove the "const" or mark the project to keep const enums intact, it ends up causing you to pull in 5k of definitions. This is not acceptable.

Another possibility is to export each individual name as an individual const... they will treeshake out properly once we convert the `lib` folder to es6 in 6.0. But I don't feel super great about that idea.

**Comment by RyanCavanaugh** [comment] 2018-04-16 14:26
This compiles correctly if you use `tsc`.

The most likely problem here is that `ts-loader` is using `ts.transpile` or equivalent (e.g. Babel?) to do emit, which means you are not allowed to use `const enum`s because TypeScript is not loading in the imports so it doesn't know that `IconNames.Download` refers to a `const enum`.

Assuming that's the case, then whoever configured this starter project should have put `isolatedModules: true` in the config file.

It's also possible that `ts-loader` is incorrectly getting the dependencies loaded in.

> Another possibility is to export each individual name as an individual const... they will treeshake out properly once we convert the lib folder to es6 in 6.0. But I don't feel super great about that idea.

Honestly `const enum` with `string` is a code smell to me and I'm kind of sad TypeScript even has the feature. Obviously we have to think about JavaScript consumers when writing a library, so any JS consumer has to be able to write `"Download"` instead of `IconNames.Download`, which means you can't really ever change that string anyway... so why not just make TypeScript authors write `"Download"` too and stop depending on transpile-time magic? It gets typechecked equally well, autocompleted equally well, etc.. Just my opinion though.

**Comment by Pajn** [comment] 2018-04-19 07:32
This is in unit tests so it is unrelated to Webpack or `ts-loader`. However I guess most of what you said can be read anyway by just replacing `ts-loader` with `ts-jest`.

I don't want to have `isolatedModules: true` just to be able to unit test the project. The project works fine without it and I have never before seen a module that requires it just to be able to write unit tests.

**Comment by dzearing** [comment] 2018-04-29 16:51
@RyanCavanaugh Right now, users do type "download" for the icon name.

```
<Icon name='download'/>
```

But they want intellisense:

```
<Icon name={ IconNames.Download } />
```

So that's why the const enum; we just want the `IconNames.Download` to be replaced with the string literal.

Hmmm there has to be something you can do here with ts-jest.

**Comment by dzearing** [comment] 2018-04-29 17:13
ts-jest issue:
https://github.com/kulshekhar/ts-jest/issues/112

Related note:
https://github.com/kulshekhar/ts-jest/blob/master/README.md#const-enum-is-not-supported

I don't see any workaround here other than:

export the icons names as consts;

```tsx
export const Download = 'download';
```

or a full on object (nicer from the autocomplete perspective, worse because you get the whole thing and all the unused entries won't tree shake out):

```tsx
export const IconNames = {
  Download: 'download'
};
```

or a non const enum (which is even worse because of no tree shaking, plus enums are twice as heavy as plain objects):

```tsx
export enum IconNames {
  Download = 'download'
}
```

**Comment by dzearing** [comment] 2018-04-29 17:15
Another idea is to add a non-const, non exported enum to the package, so that at the `ts-jest` layer you can alias `@uifabric/lib/IconNames` to `@uifabric/lib/FullIconNames`. It's a little bit extra friction but maybe better than nothing.

**Comment by dzearing** [comment] 2018-06-21 03:39
@cliffkoh is there a way we can adjust the typings of Icons? I am a bit confused on the right way to do this.

**Comment by micahgodbolt** [comment] 2018-09-10 05:57
Wanted to give this one a little nudge to see if there's any ideas on how we can resolve this.

**Comment by kenotron** [comment] 2019-01-07 17:21
@dzearing, there's an internal email thread about this with the OneDrive & Gearbox folks. I ended my last part asking for an opinion from you:

"Given the usage, I am proposing that we end up deprecating the IconNames enum for 7.x. For now, we should tag that object as @deprecated to discourage use. @dzearing  – what’s your opinion?"

In the meantime, **internally** within the Fabric codebase, we should remove the use of these IconNames enum altogether and just use strings like the library consumers should. So then the unit tests would be an issue.

**Comment by kenotron** [comment] 2019-01-07 17:35
@dzearing - I took a look at our codebase and can't find usage of the IconNames enum anymore except inside a visual regression test story for Nav. (I searched for "IconNames."). I think this bug is actually addressed.

@pajn - it seems that `ts-jest` now has isolatedModules default to false, I think that jest would ts-jest would work with this const enum output for now. I don't think Fabric team will action on this other than adding deprecation warnings on the IconNames enum. Please close this bug if you feel that your issue as been addressed.

**Closed** 2019-01-14 19:00 UTC
Labels: Needs: Author Feedback, Type: Bug :bug:, no-recent-activity
