### ISSUE TITLE
[Accessibility][Supporting the platform-Calendar]:Visual focus indicator is overlapping with button text  'Click for overlaid Day picker and Month picker without go to today button' at 400% zoom

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9711] opened 2019-07-04 12:34 UTC
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/ESYzqyYnjmxGvK-NFAUqol0B_kF4ayb343cRym6JMyKOZw?e=U1lU2b)

Component: Calendar

**Comment by khmakoto** [comment] 2019-07-05 20:43
Hi @dollykumari5, thanks for filing this issue! I can confirm that I can repro this but that it seems to be more of a problem with multiline `Buttons` than with the `Calendar` component. I'll work towards a fix for this issue. Thanks!

**Comment by lorejoh12** [comment] 2019-09-16 21:40
This is not a DatePicker bug. The bug is with overlap of the outline on text in a button, which happens to be used in one of the Calendar component examples, but is just a problem with the DefaultButton component being used.

Also, in latest version of Fabric 7.34.0, the white spacing on the focus outline has been removed so the text is less covered. Not sure if that's sufficient to close this bug, but the Button component tag seems more appropriate than the DatePicker one. @micahgodbolt, any idea whether this can be moved back or closed?

**Comment by micahgodbolt** [comment] 2019-10-01 15:08
Yeah, this is an issue with button, not calendar. No need to track it here.

**Closed** 2019-10-02 16:00 UTC
Labels: Area: Accessibility, Component: DatePicker, Resolution: Not An Issue
