### ISSUE TITLE
SetChangeEvents() for Selection is confusing

### ISSUE THREAD

**Issue by pougetat** [OfficeDev/office-ui-fabric-react#9219] opened 2019-05-24 15:02 UTC
### Environment Information 
 
- __Package version(s)__: 6.186.0
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
Consider the following code :

````ts
const selection = new Selection({onSelectionChanged: mySelectionChangedCallback})
selection.setChangeEvents(false, true /* suppressChanges */);
selection.setItem(myKeys);
selection.setChangeEvents(true, true /* suppressChanges */);
````
I would like this to prevent mySelectionChangedCallback from executing

#### Actual behavior:
 
mySelectionChangedCallback executes

 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes

Looking at the implementation it seems that ```setItems``` uses ```setChangeEvents``` itself and as a result using ```setChangeEvents``` in my own code is useless.
Also, the implementation does not make use of the ```suppressChanges``` option which means that my callback function is executed.
I would like to add an option to ```setItems``` indicating that we don't want ```onSelectionChanged``` to execute:

````ts
const selection = new Selection({onSelectionChanged: mySelectionChangedCallback})
selection.setItem(myKeys, dontFireCallBack = true);
````
 
In this code ```mySelectionCallback``` would not fire.

Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by kenotron** [comment] 2019-05-24 19:25
To me this seems like a really big departure from the intended behavior of having callbacks get fired. It would be much more flexible for consumers of the library to simply disregard the callback when fired (since you DO know that you wanted to set the item without doing the callback action). You could simply keep track of your own flag for this purpose. I don't think we'd change this behavior.

Feel free to close this issue since we're probably not going to pick up this feature.

**Comment by pougetat** [comment] 2019-05-24 19:56
First of all thank you for taking the time to review this issue. I understand that you won't be taking this feature and indeed today we track state with a variable indicating in which case to actually fire the callback. :smile: 

Having said that I am still curious as to the cases for which setChangeEvents should be used since it is now apparent that its purpose is not to prevent "events from being fired".

From my understanding setItems modifies items the selection tracks one by one and using this method itself prevents each individual modification from firing the callback. At the very end of setItems executing setChangeEvents(true) now allows for the callback to be fired.

If my above understanding is more or less accurate then I find it confusing that this function is used internally by the Selection object and is also offered as a public API. :smile:

**Comment by kenotron** [comment] 2019-05-24 22:24
@ThomasMichon - feel free to elaborate on the question. I'm not an expert of this component and need a bit of help here...

**Comment by Markionium** [comment] 2019-05-29 19:00
@kenotron Neither am I. Did you `git blame`. I'm probably there just because of `prettier` :D

>Having said that I am still curious as to the cases for which setChangeEvents should be used since it is now apparent that its purpose is not to prevent "events from being fired".

@pougetat I agree with you on the above. It also definitely looks like that from the source code. Which still somewhat confuses me.

**Comment by Markionium** [comment] 2019-05-29 19:32
@pougetat I tried the code you gave in the initial request and it seemed to work as intended? 

https://codesandbox.io/s/hrp1n

**Closed** 2019-06-05 21:00 UTC
Labels: Needs: Author Feedback, Resolution: By Design, Type: Feature, no-recent-activity
