### ISSUE TITLE
Placeholder disappears when focus goes on comboBox through keyboard or mouse click in IE11

### ISSUE THREAD

**Issue by HarkeshS** [OfficeDev/office-ui-fabric-react#11442] opened 2019-12-12 10:19 UTC
Placeholder disappears when focus goes on comboBox through keyboard or mouse click in IE11

### Environment Information

OS: Win 10
Browser: IE11
Build : 1.2019.1112.36

### Describe the issue:

Placeholder disappears when focus goes on comboBox through keyboard or mouse click in IE11

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fabric#/controls/web/combobox
Code pen link
https://codepen.io/Harkesh/pen/YzPWpMM?&editable=true

#### Actual behavior:

Placeholder disappears when focus goes on comboBox through keyboard or mouse click in IE11

#### Expected behavior:

Placeholder should not disappears when focus goes on comboBox through keyboard or mouse click in IE11

**Comment by micahgodbolt** [comment] 2019-12-12 17:56
This is IE11 default behavior for placeholder text in any input, We don't plan to work around that.

**Comment by khmakoto** [comment] 2020-01-30 00:43
This was resolved as `Resolution: By Design` back in December but the bot didn't close the issue. Closing it now.

**Closed by khmakoto** 2020-01-30 00:43 UTC
Labels: Component: ComboBox, Resolution: By Design, Resolution: External
