### ISSUE TITLE
[Accessibility][Visual requirements-Breadcrumb]: 'Tooltip' is not defined for 'More option' control. 

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9688] opened 2019-07-03 11:41 UTC
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EV9qaZLZ9jdLuBq0SHh4RogBXhHAlh6GdMFMhfgWcV9Xow?e=t5KcFg)

Component:Breadcrumb

**Comment by khmakoto** [comment] 2019-07-03 23:48
Hi @dollykumari5, thanks for filing this issue!

@micahgodbolt this seems like a reasonable request to me. If you're ok with it I can make a PR to fix this.

**Comment by micahgodbolt** [comment] 2019-07-04 05:10
This is probably going to be the same thing with command bar. The problem is that we don't intent to include strings in OUFR. We can certainly ensure that users can add their own string here, and update "dos and don'ts" to address that.

**Comment by micahgodbolt** [comment] 2019-07-04 05:11
@betrue-final-final do we know what the guidance is for tooltips on breadcrumb, command bar, Facepile and other controls that have built in "see more" affordances? Do they all need tooltips? Should we use the Fabric tooltip?

**Comment by khmakoto** [comment] 2019-07-05 17:24
@micahgodbolt I was thinking maybe conditionally render a `Tooltip` using the text from `overflowAriaLabel` as the text for the `Tooltip` and not rendering a `Tooltip` otherwise. What do you think of this approach?

**Comment by micahgodbolt** [comment] 2019-07-09 21:27
we want to make it consistent as much as we can. What are other controls doing that automatically show a tooltip?

**Comment by khmakoto** [comment] 2019-07-18 18:22
@micahgodbolt it seems we're doing very different things in different controls:
- We actually have `tooltipHostProps` in `Breadcrumb`, which I'll use to fix this bug.
- We also have `tooltipHostProps` in `CommandBar` (which creates a separate question about how to have multiple `Tooltip` props for different parts of a component).
- We use `title` in `Nav`, `SelectableOption` and `SpinButton`.
- We use the `label` in `GridCell` and `ColorPickerGridCell`.
- We use a render function in `DetailsColumn` and `DetailsHeader`.

So yeah, we're pretty much scattered on our approach all over the place. I'll also comment this on the `CommandBar` related issue.

**Comment by micahgodbolt** [comment] 2019-07-18 18:24
and this is why we now have an API review board :D

**Comment by khmakoto** [comment] 2019-07-18 18:45
Actually, I take it bag, `tooltipHostProps` in `Breadcrumb` refer to the `Tooltips` on individual items, not on the overflow. So I'm back to square one on that.

**Comment by khmakoto** [comment] 2019-07-19 17:50
I've created issue #9873 to track the overarching theme of `Tooltips` in components that can overflow. I'll close this because we'll use that to track this work instead.

**Closed by khmakoto** 2019-07-19 17:50 UTC
Labels: Area: Accessibility, Component: Tooltip, Type: Bug :bug:
