### ISSUE TITLE
DatePicker formatDate property doesn't work

### ISSUE THREAD

**Issue by pstakashi** [OfficeDev/office-ui-fabric-react#11757] opened 2020-01-22 03:19 UTC
Datepicker formatDate property cannnot format date in the official [doc](https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker) 'DatePicker allows dates to be formatted'.
Browser: Chrome 79.0.3945.130 64bit

**Comment by khmakoto** [comment] 2020-01-22 18:06
Hi @pstakashi, this is a duplicate of #11750 that is already being tracked, so I'll be closing down this issue in favor of that one. Thanks!

**Closed by khmakoto** 2020-01-22 18:06 UTC
Labels: Component: DatePicker, Resolution: Duplicate, Type: Bug :bug:
