### ISSUE TITLE
Single or multiple option for picker components

### ISSUE THREAD

**Issue by hankanman** [OfficeDev/office-ui-fabric-react#1588] opened 2017-04-24 19:45 UTC
The picker components need a way of restricting the number of items that can be picked especially the people picker as the field its headed for may only be a single user select.

A component member such as `singleSelection=true` would be ideal.
Better yet would be being able to specify a number. In case you need to select a team of 5 or something.

**Comment by kristoferbrown** [comment] 2017-08-10 18:41
Closing as duplicate of #1304

**Closed by kristoferbrown** 2017-08-10 18:41 UTC
Labels: enhancement
