### ISSUE TITLE
[Usable - PowerApps Admin- Scheduling] In Scan mode, screen reader focus moves to hidden elements and read unwanted info under Scheduling tab item

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#7478] opened 2018-12-27 07:26 UTC
<!-- 🚨 STOP 🚨 𝗦𝗧𝗢𝗣 🚨 𝑺𝑻𝑶𝑷 🚨

We’re here to help, but we need a few things from you! 

 Please provide a reproduction of the bug in a codepen, if possible. Here’s how:
Here below is the codepen of this issue . 
https://codepen.io/anon/pen/MZvago?&editable=true 

To repro this issue:
please turn on the scan node.
Go to the label "Basic uncontrolled example"
now press down arrow key. you will find the focus has moved to somewhere else, but its talking about the dropbox.
press the down arrow key again, focus will come back to the dropdown again.
you will find the same issue with the next dropdown from the code pen. 
please try theup arrow key as well, you will find the same thing.  

The expected behavior will be. the focus won't move to some hidden element.

### Environment Information 
 Test Environment:
OS version: Version 1803 (OS build 17134. 228)
Browser: Edge,Chrome
Screen Reader: Narrator, JAWS

- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

Pre-Requisite:
1. Turn on narrator by pressing Ctrl + window + ENTER combination.

Repro Steps:
1. Navigate to https://admin.powerplatform.microsoft.com/ext/DataIntegration

  and login with intusr.
2. Navigate to the Data Integration menu item on the left bar and select it.
3. Navigate on the controls of data integration page thus opened.
4. Navigate to 'Projects' tab and select it . 
5. Navigate to any already existing project and select it. Project edit screen will open.
6. Navigate to 'Scheduling' tab and select it.
7. Navigate to 'Recur Every' radio button and select it. All below fields got enabled .
8. Navigate on the enabled controls like Frequency unit drop down.
9. Turn on scan mode(Caps+Space bar) and press down arrow key.
10. Verify the screen reader focus moves to hidden elements

 
#### Actual behavior:
 
Screen reader focus moves to hidden elements and read unwanted information. It announces it as 'tab panel scheduling'.
 
#### Expected behavior:
 Screen reader focus should not move to hidden elements and it should not announce any unwanted information. Focus order should be like Start date control ->
Frequency unit control.

Note:
1. This issue also exist with Chrome.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) Blocking 
 
Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment] 2018-12-27 16:51
I believe this is a duplicate of #6422. @aneeshack4, will the improved support for aria-modal resolve this issue as well?

**Comment by aneeshack4** [comment] 2018-12-27 17:48
@micahgodbolt @sonimishra Yes I believe it is. I checked in #6884 so that it'll get picked up on future releases of Narrator when they add support for aria-modal which I think will resolve this issue also.

**Closed** 2018-12-29 00:33 UTC
Labels: Needs: Author Feedback, Resolution: Duplicate
