### ISSUE TITLE
Picker Compatibility Issue within SharePoint Online and IE11

### ISSUE THREAD

**Issue by 2toLeadMike** [OfficeDev/office-ui-fabric-react#810] opened 2017-01-13 16:40 UTC
### Bug Report

- __Package version(s)__: 0.86.2 (previously was at 0.56.0 with same issue)
- __Browser and OS versions__: Windows 10 IE 11

#### Describe the issue:

The picker controls (i.e. People Picker, Tag Picker) do not work in IE11 in the sense that whenever a second character is typed it comes before any available selection. This appears to be only an issue when run within a SharePoint Online Site (tested on a team site / STS#0). 

#### Actual behavior:

When typing a tag, the 'optional autocomplete' text will show ahead when there is a matching term after the first character. When typing the next character (any character, no matter the case) whatever option was initially shown now becomes unselected and the character typed comes before everything else.

![pickerie11](https://cloud.githubusercontent.com/assets/25105464/21937311/ed50fa6c-d984-11e6-801b-019e290afc28.gif)

#### Expected behavior:

Expected behavior is that when typing a character and having potentially matching tags, any further character should always appear in the next place after the last character typed, without influence from non-matching or matching tags.

**Comment by joschect** [comment] 2017-01-13 22:10
@2toLeadMike hey, I'm not able to reproduce this. I made a lot of improvements to the autofill that was released in v.83.0 https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v0.83.0 . Could you give it a try with those changes? I suspect it should fix it.

**Comment by joschect** [comment] 2017-01-13 22:12
@2toLeadMike I just can't read, let me try out more things to see if I can repro

**Comment by joschect** [comment] 2017-01-19 02:02
@2toLeadMike I still can't reproduce this. Do you have a code sample of how and where you're putting it into sharepoint?

**Comment by dzearing** [comment] 2017-01-25 01:44
@joschect are you testing in IE11?

**Comment by joschect** [comment] 2017-01-25 02:04
@dzearing Yes, it works fine. The bug is specificially about it not working in sharepoint in IE 11, but we have a few components using it right now that work fine in Groups in IE 11.

**Comment by joschect** [comment] 2017-02-01 20:06
@2toLeadMike is this still an issue?

**Comment by 2toLeadMike** [comment] 2017-02-01 20:13
@joschect It is still an issue but I think for now we have decided that we would simply have to avoid IE11 for the time being on that SP site as I'm out of time to try to break the solution down further and provide extra details.

Hoping that down the road I can look into this further.  I would require more time to see if it has something to do with webpack for instance, or perhaps a certain feature being activated on SP. Tough one to troubleshoot.

**Closed** 2017-02-01 20:14 UTC
Labels: bug

**Comment by joschect** [comment] 2017-02-01 22:11
@2toLeadMike Hey Mike. Thanks for your response. I'm very curious to see what the problem might be, if you can point me to how you were trying to implement it I might have some time to troubleshoot.

**Comment by freefire8** [comment] 2017-02-24 10:39
@joschect  Hi!
I actually got the same problem, ie11 only ,Chrome is working fine with it.

after the suggestion pops up, the next char is writen at the start of the previous typing, not the end :(

![image](https://cloud.githubusercontent.com/assets/13870349/23300411/b33fa7b6-fa85-11e6-8aac-b5f83d30df2c.png)

![image](https://cloud.githubusercontent.com/assets/13870349/23300429/ca6f56d4-fa85-11e6-9730-bef20dcc4249.png)

any idea?

**Comment by joschect** [comment] 2017-02-24 17:14
@freefire8 I have still been unable to reproduce this. It's clearly happening though, I need to keep investigating. I have some ideas, but no tangible leads yet. I'll make some time this weekend and try to do a deep dive.

**Comment by freefire8** [comment] 2017-03-02 09:07
hi @joschect ! Any update on the problem? :)

**Comment by joschect** [comment] 2017-03-02 18:16
@freefire8 Not much. I have gotten pretty busy. I do have good news, I was able to reproduce the problem in IE 10, which should help me figure out why.

**Comment by joschect** [comment] 2017-03-02 23:14
@freefire8 after some more investigation it looks like there is a bug in react https://github.com/facebook/react/issues/8531 . I'll have to think about how to have a fix for this since it only appears to happen in IE 10.

**Comment by joschect** [comment] 2017-03-02 23:23
@freefire8 I know that you're issue is only occurring in IE 11 but I still haven't seen that behavior, only in IE 10.

**Comment by freefire8** [comment] 2017-03-06 07:15
Hi @joschect !

I got the last IE installed on win10 so it's an IE11, but maybe the engine was set to ie10 compatibility. Unfortunately i can't check right now because the infrastructure i use is not available for now. 

I'm happy to see you have some hints about the problem :)

**Comment by robinsoderlund** [comment] 2018-07-06 07:49
Is this fixed in later versions? I'm having the same problem with 5.87.0.
