### ISSUE TITLE
Fabric checkbox control does not support high contrast

### ISSUE THREAD

**Issue by esabherwal** [OfficeDev/office-ui-fabric-react#12299] opened 2020-03-13 18:53 UTC
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

Currently the fabric checkbox control does not support high contrast. 

#### Actual behavior:

After clicking the fabric checkbox in high contrast there is no visual change. It does not appear checked if you move mouse away. 

#### Expected behavior:

The fabric checkbox control should support high contrast and have a visual state change when checkbox is checked. 

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment] 2020-03-13 22:51
Dupe of #12264 - closing this because discussion and fix will be updated on this first issue report.

**Closed by aneeshack4** 2020-03-13 22:51 UTC
Labels: Needs: Triage :mag:
