### ISSUE TITLE
DetailsList: toggling selection does not mention state for screen-readers

### ISSUE THREAD

**Issue by waabid** [OfficeDev/office-ui-fabric-react#5235] opened 2018-06-16 00:01 UTC
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
Normal
Products/sites affected: (if applicable)
VSTS
#### Describe the issue:

The toggle/checkbox controls in detail list do not have any indication of state. I believe something like aria-checked can resolve this issue.

#### Actual behavior:

When a checkbox is selected, the selection state is not read out by the screen reader.

#### Expected behavior:

When a checkbox is selected, the selection state is read out by the screen reader.

**Comment by ThomasMichon** [comment] 2018-06-20 16:34
@waabid Our Design team had previously requested that the checkboxes within individual rows not be focusable, preferring the 'space' key to bubble up to the parent row to toggle selection. However, Narrator will only read the toggle state if the focus is on an element with `role='checkbox'`, which the parent row may not have (since it has `role='row'` already). I am not sure how to make Narrator read the toggle state of `aria-selected` because it is not a proper checkbox.

**Comment by philipzloh** [comment] 2018-08-01 20:44
@ThomasMichon Um. What. The *correct element* needs to have focus, and the correct metadata needs to be used to convey the correct thing. Do you mind sharing the errant HTML DOM?

I also have a separate PR for making Toggle proper toggles. #5754

**Comment by dzearing** [comment] 2019-02-13 23:59
Dupe of https://github.com/OfficeDev/office-ui-fabric-react/issues/6525

**Closed by dzearing** 2019-02-13 23:59 UTC
Labels: Area: Accessibility, Component: DetailsList
