### ISSUE TITLE
Callout: position relative to browser instead of specific element when use "preventDismissOnScroll=true"

### ISSUE THREAD

**Issue by hojovi** [OfficeDev/office-ui-fabric-react#7979] opened 2019-02-13 15:16 UTC
### Bug Report

- __Package version(s)__: 6.138.1
- __Browser and OS versions__: Chrome/Windows 10

#### Priorities and help requested (not applicable if asking question):

Requested priority: Normal

#### Describe the issue:

When I use "Callout" with "preventDismissOnScroll=true", the "Callout" doesn't attach to target any more while scrolling page.

#### Actual behavior:

The "Callout" isn't positioned based on its target.

#### Quick fix:

How could I fix this?

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/ErpEbK?editors=1111

Thanks.

**Comment by JasonGore** [comment] 2019-02-13 22:57
@joschect Do you know if it's expected that `Callout` repositions with content when scrolling with use of `preventDismissOnScroll`?

**Comment by JasonGore** [comment] 2019-02-13 23:08
As `TeachingBubble` uses `Callout` this is a possible dupe of #7846.

**Comment by joschect** [comment] 2019-02-13 23:29
@JasonGore The callout is not supposed to re-position on scroll. Since it needs to calculate it's position, any scroll becomes pretty expensive and jittery. At least for right now. This is working as intended.

**Comment by hojovi** [comment] 2019-02-14 01:56
Sorry, but this is not in line with daily awareness. We need to implement a feature "beginner guidance", like this, https://introjs.com/ , is there any way to achieve this by "office ui fabric"?

@JasonGore I think we might solve this by making "Callout" child of the target element, using "position: absolute" instead of "position: fixed", then we don't need to calculate it's position while scrolling.

**Comment by JasonGore** [comment] 2019-02-15 23:54
I [modified your CodePen](https://codepen.io/jasongore/pen/rPZNag) to do something similar by just adding this line to `Callout`

```tsx
layerProps={{ styles: { root: { position: 'absolute '}}}}
```
Which I believe gives you the effect you're looking for.

From an API perspective I wonder if we should add a `floating` prop to `Layer` to achieve a similar effect without having to dive into styling this way. I'm not sure what the history is for deciding to make `Layer` floating only or if there is another way to achieve this. @dzearing Do you have any thoughts?

**Comment by hojovi** [comment] 2019-02-18 09:10
@JasonGore Wow, this is good, thank you for your time.

However this doesn't solve all problems, this bug happens again when the scroll bar isn't on the "body" element. Codepen repro: https://codepen.io/anon/pen/LqMmmR .
I've used "ant design" before, there's a property named "[getPopupContainer](https://github.com/ant-design/ant-design/issues/14830)" which can change the element it bases on, is there parameter like that in "office ui fabric"?

**Comment by JasonGore** [comment] 2019-02-19 21:54
Actually I've since found out that `doNotLayer` prop exists for these scenarios, sorry for the roundabout here.

Have you tried using this prop? When I applied it to your [most recent CodePen](https://codepen.io/jasongore/pen/JxzKJv) it seems to behave the way you want.

**Comment by hojovi** [comment] 2019-02-20 02:30
@JasonGore Excellent! That's exactly what I want, thank you!

**Comment by JasonGore** [comment] 2019-02-20 03:05
If this resolves the issue for you, could you close it? Thanks!

**Closed** 2019-02-20 03:24 UTC
Labels: Component: Callout, Component: Layer, Needs: Author Feedback, Type: Feature
