### ISSUE TITLE
In old version of Edge, spin button value can't be edited with keyboard controls while Narrator is on

### ISSUE THREAD

**Issue by wutonghao** [OfficeDev/office-ui-fabric-react#12338] opened 2020-03-17 22:22 UTC
### Environment Information

- **Package version(s)**: 7.98.0;  also repros in latest version
- **Browser and OS versions**: Any version of legacy Edge browser (ex. 44.18362.449.0)

### Describe the issue:

Our team is building a react pane for Excel Online, and we use spin button control in the pane. When we conduct accessibility tests, we found that when Narrator is on, the value in spin button can't be edited using keyboard (ex. delete value, change value, enter new value, etc.) using legacy Edge browser. This issue, however, does not repro for other input controls (ex. text field) or other browsers (ex. IE, Chrome, New Edge).

### Please provide a reproduction of the issue in a codepen:
Spin button example (where the issue repros): https://fabricweb.z5.web.core.windows.net/oufr/7.105.0/#/examples/spinbutton

Text field example (where the issue does not repro):
https://fabricweb.z5.web.core.windows.net/oufr/7.105.0/#/examples/textfield

#### Actual behavior:

When Narrator is on, the value in spin button can't be edited using keyboard (ex. delete value, change value, enter new value, etc.)

#### Expected behavior:

When Narrator is on, the value in spin button can still be edited using keyboard (ex. delete value, change value, enter new value, etc.), just like text field.

### Documentation describing expected behavior

Not sure which accessibility guideline applies to this issue, but we should still be able to edit control value using keyboard when Narrator is on. Given that this issue only repros for spin button (not for other input controls) in old Edge (not in IE/Chrome/New Edge), the current behavior does not seem correct.

**Comment by aneeshack4** [comment] 2020-03-17 23:04
@wutonghao Hi, thanks for reaching out to us and providing all these details. Are you only reproing this while in scan mode? Or when not in scan mode too? 

This is a duplicate of Bug 6 of #7217 - and from that investigation, it was found that this is a [Narrator bug](https://stackoverflow.microsoft.com/questions/135485/bugs-in-narrators-interactions-with-fabrics-spinbutton) and they're tracking it but a fix of this scenario relies on them closing their gaps in support of spinners.

**Comment by wutonghao** [comment] 2020-03-17 23:37
@aneeshack4 Thanks for the reply. We are only reproing this while in scan mode. We can edit spin button value when scan mode is off.

**Comment by aneeshack4** [comment] 2020-03-19 21:29
Ok @wutonghao since it's a duplicate and already being tracked by #7217 I'm going to close this.

**Closed by aneeshack4** 2020-03-19 21:29 UTC
Labels: Area: Accessibility, Component: SpinButton, Needs: Attention :wave:, Status: Blocked
