### ISSUE TITLE
TagPicker: does not read out the delete option of selected tag in edge

### ISSUE THREAD

**Issue by code-mage** [OfficeDev/office-ui-fabric-react#5098] opened 2018-06-05 05:09 UTC
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: VSTS

#### Describe the issue:

Tag Picker does not read out the delete option of selected tag in edge

#### Expected behavior:

Along with the name of the tag, delete option should also be mentioned in the name so that the user will be able to know that the tags can be deleted.

**Comment by betrue-final-final** [comment] 2018-06-05 13:58
@lynamemi

**Comment by code-mage** [comment] 2018-10-19 14:55
Guys, is there any progress on this?

**Comment by micahgodbolt** [comment] 2018-12-27 19:44
duplicate of #4817

**Closed** 2019-01-03 21:00 UTC
Labels: Area: Accessibility, Component: Pickers, Needs: Author Feedback, Resolution: Duplicate, no-recent-activity
