### ISSUE TITLE
New Component: Toast

### ISSUE THREAD

**Issue by aboe026** [OfficeDev/office-ui-fabric-react#5479] opened 2018-07-07 03:11 UTC
**Describe the feature that you would like added**
A toast notification component. For example: When a new resource is added into the system (either by the user or someone else on the system) alert the user that a new resource has been added. Should just pop up in the top right with an option to dismiss

**What component or utility would this be added to**
This would be a new component

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
It would be somewhat similar to how toasts are done in [react-uwp](https://www.react-uwp.com/Components/Toast)

**Comment by micahgodbolt** [comment] 2019-01-16 23:12
This is a dupe of #865, when we do notifications we'll be sure to support "Toast" style notifications.

**Closed** 2019-01-16 23:12 UTC
Labels: Needs: Backlog review, Type: Feature
