### ISSUE TITLE
Accessibility issue of DatePicker in window with small width

### ISSUE THREAD

**Issue by LukeOwlclaw** [OfficeDev/office-ui-fabric-react#11114] opened 2019-11-07 12:27 UTC
### Environment Information

- **Package version(s)**: 7.58
- **Browser and OS versions**: any

### Describe the issue:

When the browser window has very small width (smaller than DatePicker is wide), the important left part (day to choose) is hidden. The control is thus not usable.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/2737900/68387213-1ccd6d80-015e-11ea-8246-413479204f45.png)

To reproduce open https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker, limit browser width and click on first sample date picker control.

#### Expected behavior:

I expect the control to usable despite the size of the browser. This could e.g. be done be hiding the month overview when there is not enough room, or by simply anchoring the datepicker on the left side so that the month picker moves outside of the visible area.

Could [Callout's property 'alignTargetEdge'](https://developer.microsoft.com/en-us/fabric#/controls/web/callout#ICalloutProps) help here? Checkout: https://codepen.io/LukeO/pen/BaaxYZo and [DatePicker source](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.base.tsx)

### Documentation describing expected behavior

I did not find any documentation that states that Office Ui Fabric React should be usable in small browsers. But I did not find a minimum required browser width either, so I assume that it should make a best effort to work well with any browser width.

**Comment by JasonGore** [comment] 2019-11-07 20:17
I think the behavior you're looking for can be modified using `calloutProps.directionalHint`, which I did in [this CodePen](https://codepen.io/jasongore/pen/abbGMaz): 

![image](https://user-images.githubusercontent.com/26070760/68424203-59966600-0158-11ea-84c4-9caeab179a6a.png)

Does that work for you?

I'm not sure if this is an actionable item from DatePicker's perspective. @lorejoh12 What do you think?

**Comment by LukeOwlclaw** [comment] 2019-11-08 06:09
Thank you @JasonGore! I missed [``calloutProps: ICalloutProps``](https://developer.microsoft.com/en-us/fabric#/controls/web/callout#ICalloutProps). Using `calloutProps.alignTargetEdge = true` I can achieve the desired behavior, shown in [this update of your CodePen](https://codepen.io/LukeO/pen/xxxzbrg).

I do not see any negative side effects of using `calloutProps.alignTargetEdge = true`. Maybe it can become the default setting? Just close this issue if you feel that this is not a good idea.

**Comment by JasonGore** [comment] 2019-11-08 17:43
The fix seems easy enough, but I'm not sure if this is by design. I will let @lorejoh12 pick up the fix if he feels it is good, otherwise close this issue for now.

**Closed by JasonGore** 2019-11-08 17:43 UTC
Labels: Component: DatePicker, Needs: Attention :wave:, Needs: Triage :mag:
