### ISSUE TITLE
ComboBox value appears highlighted if we select any value from ComboBox using keyboard.

### ISSUE THREAD

**Issue by HarkeshS** [OfficeDev/office-ui-fabric-react#11565] opened 2019-12-27 05:57 UTC
ComboBox value appears highlighted if we select any value from ComboBox using keyboard.

### Environment Information

OS: Win 10
Browser: Edge

### Describe the issue:

ComboBox value appears highlighted if we select any value from ComboBox using keyboard. You can see this issue in below office fabric link
https://developer.microsoft.com/en-us/fabric#/controls/web/combobox

### Please provide a reproduction of the issue in a codepen:
Please refer below code pen link for Repro
https://codepen.io/Harkesh/pen/gObxYma?&editable=true

#### Actual behavior:

ComboBox value appears highlighted if we select any value from ComboBox using keyboard.

#### Expected behavior:

ComboBox value should not highlighted if we select any value from ComboBox using keyboard.

**Comment by micahgodbolt** [comment] 2019-12-27 17:41
It looks like this bug is being taken care of in #11497

**Comment by micahgodbolt** [comment] 2019-12-27 19:54
Also note, it seems old Edge looks fine

![image](https://user-images.githubusercontent.com/1434956/71530630-98ff4a00-289f-11ea-9582-
4dd7007d4625.png)

But chrome and chromium edge look a bit funky

![image](https://user-images.githubusercontent.com/1434956/71530622-90a70f00-289f-11ea-82eb-34b3f4f454f1.png)

**Comment by micahgodbolt** [comment] 2019-12-27 23:28
@HarkeshS just to confirm, are you talking about the border highlight, or the text highlight?

**Comment by micahgodbolt** [comment] 2019-12-27 23:32
@jspurlin just to confirm, the default focus state is to have the combobox text selected like this:

![image](https://user-images.githubusercontent.com/1434956/71535816-db378400-28bd-11ea-9b62-446523f2a926.png)

not like this

![image](https://user-images.githubusercontent.com/1434956/71535823-e7bbdc80-28bd-11ea-9557-77ae1a39372f.png)


I'm actually fixing a bug now where focus doesn't return to the input on item click, which would make mouse and keyboard experience the same.  #11570 

So this issue would be resolved with "As Designed"

**Comment by jspurlin** [comment] 2019-12-28 00:37
Correct, the issue described here is by design

**Closed** 2019-12-30 18:19 UTC
Labels: Component: ComboBox, Resolution: By Design
