### ISSUE TITLE
PeoplePicker: unwanted blur triggered

### ISSUE THREAD

**Issue by mdanielcristian** [OfficeDev/office-ui-fabric-react#5288] opened 2018-06-21 09:46 UTC
### Bug Report 
 
- __Package version(s)__: 6.4.1
- __Browser and OS versions__: Internet Explorer
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
#### Describe the issue:
 
People picker onblur event is called (not the input onBlur event) when clicking on the vertical scroll bar in the suggestions list. This should not happen in my opinion.
 
#### Actual behavior:
 
Onblur event is called but only on IE.
 
#### Expected behavior:
 
Onblur should not be called on IE, as it happens on Chrome

**Comment by aslanovsergey** [comment] 2018-09-10 08:59
very similar issue in version 5.120. OnBlur is called when select a person from suggestion

**Comment by JasonGore** [comment] 2018-10-22 18:41
I've captured what I believe is the cause of this behavior for IE11. In this image you can see another instance of the popup briefly appearing after a selection. This second popup seems like it would be the cause of extraneous onBlur events and does not occur in Chrome.

![peoplepicker](https://user-images.githubusercontent.com/26070760/47311732-613ba900-d5ef-11e8-9b17-f7bb3e95fec2.gif)

**Comment by joschect** [comment] 2018-10-22 18:44
@JasonGore interesting, I'll take a look. I put in a bunch of picker fixes and most of the onblur problems should be fixed.

**Comment by JasonGore** [comment] 2018-10-22 18:45
I deleted my comment as it was in response to @aslanovsergey comment. It doesn't have to do with the reported issue and wanted to reduce confusion. If the issue @aslanovsergey still occurs after addressing root cause of this issue, I will make a new issue with my previous post's comments.

**Comment by JasonGore** [comment] 2018-10-22 18:47
I am able to repro both OP's and @aslanovsergey issues in latest master build.

**Comment by JasonGore** [comment] 2018-10-22 20:29
I have found root cause for reported error.` BasePicker` passes `ev.relatedTarget` to `elementContains` in `onInputBlur`. However, `ev.relatedTarget` is always `null` in IE11, which causes the `elementContains` call to evaluate incorrectly. It seems that having a `relatedTarget` for `onBlur` events is [non-standard behavior](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget), which means Chrome actually has the non-standard behavior here.

I'm not sure why the code is using `relatedTarget` instead of `target` and am still investigating that...

**Comment by JasonGore** [comment] 2018-10-22 20:34
Actually I didn't realize this was assigned to Jon so I'll just move on for now. Let me know if you want to pick it up again. 😄

**Comment by JasonGore** [comment] 2018-10-24 21:17
`ComboBox._onBlur` seems to have a workaround for this type of issue, duplicated here:

```tsx
    // Do nothing if the blur is coming from something
    // inside the comboBox root or the comboBox menu since
    // it we are not really bluring from the whole comboBox
    let relatedTarget = event.relatedTarget;
    if (event.relatedTarget === null) {
      // In IE11, due to lack of support, event.relatedTarget is always
      // null making every onBlur call to be "outside" of the ComboBox
      // even when it's not. Using document.activeElement is another way
      // for us to be able to get what the relatedTarget without relying
      // on the event
      relatedTarget = document.activeElement;
    }
```

**Closed** 2018-11-01 20:48 UTC
Labels: Component: Pickers, Platform: IE11, Type: Bug :bug:
