### ISSUE TITLE
[Accessibility][Usable-Calendar]: In Scan mode screen reader focus is going to the calendar dates twice.

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9704] opened 2019-07-04 09:41 UTC
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/ESSfG1C8NvtCuvClyF07xoEBH-1jHI3aSEtmIJudL3JEZw?e=N0g3Jo)

Component: Calendar

**Comment by khmakoto** [comment] 2019-07-05 20:20
Hi @dollykumari5, thanks for filing this issue! This seems to be a duplicate of Bug 3 in #8349, so I'll be closing this since the issue is already being tracked there. Thanks again!

**Closed by khmakoto** 2019-07-05 20:20 UTC
Labels: Area: Accessibility, Component: Calendar, Resolution: Duplicate, Type: Bug :bug:
