### ISSUE TITLE
Rating: Not working on OSX 10.10.5

### ISSUE THREAD

**Issue by Soedy** [OfficeDev/office-ui-fabric-react#3747] opened 2018-01-19 06:30 UTC
### Bug Report

- __Package version(s)__: 5.39.1
- __Browser and OS versions__: Safari 10.1.2 and Firefox 52.5.2 on OSX 10.10.5

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No
Requested priority: Low

Products/sites affected: only a demo project

#### Describe the issue:

When clicking the stars of the rating component, nothing happens. Works great on my several Windows machines

#### Actual behavior:

onClick method does not jump into my handle method. Same on the demo page.

#### Expected behavior:

The value for the rating should be set

**Comment by battletoilet** [comment] 2018-01-31 22:32
It looks like the code repros in this codepen as well https://codepen.io/dzearing/pen/LzEKoN

**Comment by cschleiden** [comment] 2018-04-27 19:57
@oengusmacinog could you take a look? Does that still repro with your latest changes?

**Comment by oengusmacinog** [comment] 2018-04-27 20:49
@cschleiden yes still an issue with the latest version.  It's not even specific to the CodePen.  None of the Rating examples on the Fabric website work either.  Chrome is fine, firefox and safari both don't work.  The click is working - changes the **tabindex** value, but doesn't affect the style change that should make the star.

Interesting, actually it looks like something is wrong with the state in Safari and Firefox.  The **rating** is undefined in Mozilla's React Dev Tools.  Will be interesting to find the cause of this.

**Closed** 2018-04-30 23:06 UTC
Labels: Component: rating, Needs: investigation, Type: bug
