### ISSUE TITLE
[Accessibilty][Functional]: Selection dates are not correct in 'selected dates' after selecting week header using keyboard 

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9709] opened 2019-07-04 12:08 UTC
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EdHxwDqb2apNkpVEGH4sgn8B_OwBxuij0MFeMR7iJzrPXw?e=dG5BiO)

Component :Calendar

**Comment by khmakoto** [comment] 2019-07-05 20:37
Hi @dollykumari5, thanks for filing this issue! The behavior in this case is by design because that example is restricting the selected dates to those established by `workWeekDays`, which runs from Tuesday to Saturday.

I'll be closing this issue for that reason. Thanks!

**Closed by khmakoto** 2019-07-05 20:37 UTC
Labels: Component: Calendar, Resolution: Not An Issue
