### ISSUE TITLE
Toggle: Hover/click area is incorrect?

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6753] opened 2018-10-18 19:32 UTC
See this [screen recording](https://cl.ly/df449c73c914/Screen%252520Recording%2525202018-10-18%252520at%25252012.28%252520PM.gif).

Currently, the Toggle can be triggered by clicking on the associated label above it or the toggle itself. Should the text contained within the toggle (e.g. On or Off) be a hit target as well?

**Comment by betrue-final-final** [comment] 2018-10-18 20:39
Yes. On/Off should be a hit target. Not sure about the label though.

**Comment by dzearing** [comment] 2018-10-30 18:09
This looks by design.

**Comment by mikewheaton** [comment] 2018-10-30 22:07
@betrue-final-final had said that the text (e.g. On/Off) _should_ be a hit target, so we have a bug here.

**Comment by micahgodbolt** [comment] 2018-12-28 21:57
Right now the toggle has two labels. Labels typically are attached to the functionality of the input via the 'for' attribute. 

So a few questions:
1. Should this control have two labels?
2. If not, which one is actually the label?
3. If the 'on/off' has the click target, it should be the label

![image](https://user-images.githubusercontent.com/1434956/50529210-30bd3300-0aa8-11e9-9265-ed9cd4221d42.png)

**Comment by betrue-final-final** [comment] 2019-01-07 16:54
Well, On/Off is a state description. In mental model terms, the text above is the "label". I don't know how we want to describe it in code. I just know that people will be inclined to click on the off/on text or the toggle itself more than the "label".

**Comment by betrue-final-final** [comment] 2019-01-07 17:54
I don't have an issue as long as it doesn't make the screen reader say redundant information.

**Comment by micahgodbolt** [comment] 2020-01-02 19:48
![toggle](https://user-images.githubusercontent.com/1434956/71688911-b035b000-2d55-11ea-88ef-52ef62e746a4.gif)

This seems to be fixed now.

**Closed** 2020-01-02 19:48 UTC
Labels: Component: Toggle, Needs: Discussion 🙋, Type: Bug :bug:
