### ISSUE TITLE
HoverCard - Card still dismisses on mouse out when 'sticky' prop set to true

### ISSUE THREAD

**Issue by jimmywim** [OfficeDev/office-ui-fabric-react#7848] opened 2019-01-30 11:59 UTC
### Environment Information 
 
- __Package version(s)__: Whatever comes with SPFX 1.7.0
- __Browser and OS versions__: Chrome & Windows 10

CodePen: https://codepen.io/anon/pen/WPoXzo
 
#### Actual behavior:
 
HoverCard dismisses as usual
 
#### Expected behavior:
 
HoverCard remains open

Requested priority: Normal

**Comment by SpencerLynn** [comment] 2019-02-05 05:13
After some debugging, it appears that it's actually the card is closing because of the mouse leave event from the `ExpandingCard` or `PlainCard` rendered by the `HoverCard`.

I'm not sure expectation here. If the card is marked as `sticky`, when does it dismiss?

We can create a wrapper function to handle the `onLeave` callback passed to the card and only execute a dismiss if the `sticky` prop is false, but then the card will never dismiss.

I think the fix is likely relatively simple once the expected behavior is determined.

**Comment by SpencerLynn** [comment] 2019-02-05 05:43
One approach could be to only *not* dismiss the card when the `onLeave` callback fires if the event is a `mouseleave` MouseEvent event. Will be opening a PR shortly with this fix. If this fix breaks something else or is invalid for some other reason, please let me know!

**Closed** 2019-02-08 23:40 UTC
Labels: Component: HoverCard, Type: Bug :bug:
