### ISSUE TITLE
ComboBox: aria label of an item cannot be set separately from preview text

### ISSUE THREAD

**Issue by janormanms** [OfficeDev/office-ui-fabric-react#6665] opened 2018-10-11 18:40 UTC
### Bug Report 

- __Package version(s)__: 6.74.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High (accessibility)
 
Products/sites affected: Outlook
 
#### Describe the issue:
 
Setting the ariaLabel property on IComboBoxOption does not set the aria-label on the option. It only does so if useAriaLabelAsText is set to true, which results in the aria label being used as the preview text.
 
Related PRs:
https://github.com/OfficeDev/office-ui-fabric-react/pull/4540
https://github.com/OfficeDev/office-ui-fabric-react/pull/4722

#### Actual behavior:
 
Aria label can only be set if you want to use it as the preview text as well
 
#### Expected behavior:
 
Aria label can be set, and if you want to use it as the preview text you can use the existing useAriaLabelAsText property

See ComboBox._renderOption and ComboBox._getPreviewText, essentially leave _getPreviewText as is but update the aria-label props being set on the CommandButton or CheckBox to be "item.ariaLabel ? item.ariaLabel : item.text"

**Comment by dzearing** [comment] 2018-11-12 15:16
@natalieethell were you working on this? I'm not sure if that behavior suggested is even right. May be good to chat with @jspurlin

**Comment by natalieethell** [comment] 2018-11-12 16:18
Hey @dzearing I am not working on this. I just moved the card from “Ready for Engineering” to “In PR” because I noticed there was a PR opened for it.

**Comment by dzearing** [comment] 2018-11-12 16:43
@natalieethell Ah oops I see it now :) thanks!

**Comment by micahgodbolt** [comment] 2018-12-28 21:49
seems the PR for this fizzled out. something to look into during #6030? @ecraig12345

**Comment by micahgodbolt** [comment] 2020-01-02 19:40
I was about to create a PR to allow a different value for aria-label, but it was basically the same the PR closed above, which @jspurlin said was unnecessary. 

My solution was to add a getAriaLabel similar to getPreviewText:

```jsx
  private _getPreviewText(item: IComboBoxOption): string {
    return item.useAriaLabelAsText && item.ariaLabel ? item.ariaLabel : item.text;
  }

  private _getAriaLabel(item: IComboBoxOption): string {
    return item.ariaLabel ? item.ariaLabel : item.text;
  }
```

@jspurlin unless you think this approach is better than the closed PR, i'll let this issue close via "By Design"

**Comment by jspurlin** [comment] 2020-01-06 15:52
@micahgodbolt , yeah, I think this should be closed as "by design" due to the issues I called out in https://github.com/OfficeDev/office-ui-fabric-react/pull/6797

**Closed** 2020-01-06 15:53 UTC
Labels: Component: ComboBox, Resolution: By Design, Type: Bug :bug:
