### ISSUE TITLE
Make pivot item support extra html attributes in props

### ISSUE THREAD

**Issue by Friedrikovic** [OfficeDev/office-ui-fabric-react#10909] opened 2019-10-18 15:44 UTC
#### Describe the feature that you would like added

I'd like the PivotItem component to support custom attributes that would be added as html atttributes when not consumed by the react component. ex with the following data-automation-id attribute:

          <PivotItem
            headerText="My tab item"
            itemKey="key1"
            data-automation-id="automationID"
          >

Many other UI fabric components do that which makes automation much easier

#### What component or utility would this be added to

PivotItem

#### Have you discussed this feature with our team, and if so, who

No

**Comment by marygans** [comment] 2019-10-18 22:34
Hi @Friedrikovic thanks for submitting this issue! 

I see that this is a dupe of this open issue: #10642. Feel free to ping the conversation with your perspective and insights! 

Thanks!

**Closed by marygans** 2019-10-18 22:34 UTC
Labels: Needs: Triage :mag:
