### ISSUE TITLE
DetailsList: Sticky/fixed header

### ISSUE THREAD

**Issue by sharpoverride** [OfficeDev/office-ui-fabric-react#925] opened 2017-02-01 06:55 UTC
It should be possible to have the header fixed. I explored the documentation and I'm unable to find a property to handle this.

At the moment I need to go through a lot of ugly hacks to get to the header component.

```
const detailsList = refs.detailsList as any;
const header = detailsList._composedComponentInstance.refs.header.refs.root;
```

**Comment by dzearing** [comment] 2017-02-01 17:09
yeah that's not great. :) We've wanted a sticky header feature for a while so this is a great feature ask.

**Comment by mikewheaton** [comment] 2017-06-06 03:15
Closing as a duplicate of #1146.

**Closed by mikewheaton** 2017-06-06 03:15 UTC
Labels: feature-request
