### ISSUE TITLE
Cannot assign a label to the PeoplePicker control

### ISSUE THREAD

**Issue by cezapata** [OfficeDev/office-ui-fabric-react#10662] opened 2019-09-28 23:01 UTC
### Environment Information

- **Package version(s)**: 7.22.2

- **Browser and OS versions**:
Browser: Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
OS: Windows 10 Version 1903 (OS Build 18362.356)

> Note that our screen reader support is limited to Edge + Narrator. Issues that do not reproduce in Edge + Narrator, and aren't caused by obvious invalid aria values, should be filed with the respective screen reading software, not the Fabric repo.

### Describe the issue:

Cannot assign a label to the people picker component. There are no props available to it.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/sigurdvh/pen/JjPqyej?&editable=true

#### Actual behavior:

See how the UI doesn't display a label. Try passing the label as a prop, it doesn't allow it.

#### Expected behavior:

We should have a hook for a visual prop and also allowing us to use it for accessibility.

### Documentation describing expected behavior

See how other editable fields like the TextField allow us to do this. In the example provider even the dropdown container allows us to do it.

**Comment by khmakoto** [comment] 2019-09-30 16:26
Hi @cezapata, thanks for filing this bug!

@joschect @micahgodbolt this seems like a reasonable feature request given our pattern in other controls but I wanted to get your opinions before moving forward on a solution for this. Do you think we should add a `label` attribute with its corresponding functionality to the `PeoplePicker`.

**Comment by khmakoto** [comment] 2019-10-07 23:15
I had an offline conversation with @joschect and we decided that we're putting this feature in the backlog for now while we work on more pressing issues.

**Comment by khmakoto** [comment] 2020-01-13 22:38
This is a duplicate of #9935, so I'll be closing this issue in favor of that one.

**Closed by khmakoto** 2020-01-13 22:38 UTC
Labels: Component: PeoplePicker, Needs: Backlog review, Type: Feature
