### ISSUE TITLE
[merge-styles] TypeScript error TS2349 when trying to invoke subComponentStyle members which are not defined as IStyleFunctionOrObject

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#6615] opened 2018-10-09 10:10 UTC
### Bug Report 

- __Package version(s)__:
  - merge-styles: 6.9.4 (as a dependency of office-ui-fabric-react 6.81.0)
  - typescript: 3.0.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, if I find the cause of this issue.
 
Requested priority: High
 
#### Describe the issue:
 
**This is a regression.** The error did not occur with office-ui-fabric-react 6.58.0 / merge-styles 6.7.0

Given the following interface
```ts
export interface Styles {
	root: IStyle;

	subComponentStyles: {
		label: IStyleFunctionOrObject<ILabelStyleProps, ILabelStyles>;
		button: Partial<IButtonStyles>;
	};
}
```

applying the `IProcessedStyleSet` mapping type maps `button` to `never`:
```ts
type Processed = IProcessedStyleSet<Styles>;
type Label = Processed["label"]; // IStyleFunction<ILabelStyleProps, ILabelStyles>
type button = Processed["button"]; // never
```

 
#### Actual behavior:
 
Trying to call the button property causes TS to fail compilation with the mentioned error:
```
Error TS2349: Cannot invoke an expression whose type lacks a call signature.
Type 'never' has no compatible call signatures.
```
 
#### Expected behavior:
 
Calling the button property returns a `Partial<IButtonStyles>`

**Comment by Nimelrian** [comment] 2018-10-09 12:15
Bisecting revealed 90cd34d276e26bcc8368f57 as the commit which introduced the regression. The commit was part of #6146.

cc @cliffkoh since they are the commit author.

**Comment by Nimelrian** [comment] 2018-10-09 15:10
I have found a fix, but the tests fail because the subComponentStyles property doesn't get mapped to a function but remains as an object?

You can find my branch [here](https://github.com/Nimelrian/office-ui-fabric-react/tree/b48a4081df1719d89e743f7d967141b00dc1486e) with the commit being [here](https://github.com/Nimelrian/office-ui-fabric-react/commit/b48a4081df1719d89e743f7d967141b00dc1486e)

the test fails in line 301:

```
 FAIL  src/mergeStyleSets.test.ts
  ● Console

    console.log src/mergeStyleSets.test.ts:300
      { subComponentStyles: { button: { root: [Object] } },
        root: 'root-0' }

  ● mergeStyleSets › typings tests › IStylesWithStyleObjectAsSubCommponent › IStyleSet/IProcessedStyleSet should work with legacy sub components that only take IStyleFunctions

    TypeError: classNames.subComponentStyles.button is not a function

      299 |         const classNames = mergeStyleSets<IStylesWithStyleObjectAsSubCommponent>(getStyles2());
      300 |         console.log(classNames);
    > 301 |         LegacySubComponent({ styles: classNames.subComponentStyles.button({ isCollapsed: false }) });
          |                                                                    ^
      302 |
      303 |         // this test primarily tests that the lines above do not result in a Typescript error.
      304 |         expect.assertions(0);

      at Object.<anonymous> (src/mergeStyleSets.test.ts:301:68)
```

The typings are correct however.
cc @dzearing since he also did some changes to merge-styles and I'm not sure whether they're the cause of the runtime failure.

I'm out of office tomorrow, so I may react a little slowly until Thursday :)

**Comment by cliffkoh** [comment] 2018-10-10 19:08
Thanks @nimelrian, taking a look.

**Comment by cliffkoh** [comment] 2018-10-10 22:21
Hi @Nimelrian, I have tested and validated your proposed fix. Because of the runtime bug you pointed out, I created a PR that incorporates your fix (but credits the expression to you and call you out in the changefile :)). Please do review #6649 when you get a chance.

**Comment by cliffkoh** [comment] 2018-10-11 22:48
Just noting here that the "regression" was something we were aware of. The syntax previously used for ReduceToFunction only worked correctly from Typescript 3 (possibly Typescript 2.9 as well) but Fabric was and still is on TS 2.8 and we could not check the right syntax in. In the end, we checked in something that would work for the majority of cases but fail in the very specific scenario  (where the type incorrectly resolves to never). 

Thank you @Nimelrian again for figuring out an alternative way to express ReduceToFunction that would work in Typescript 2.8 as well.

**Comment by Nimelrian** [comment] 2018-10-12 06:13
Alright, good to know :)

**Closed** 2018-10-14 22:47 UTC
Labels: Area: merge-styles, Type: Bug :bug:
