### ISSUE TITLE
Panel popup navigate on Parent page when pressing Backspace key on IE 11

### ISSUE THREAD

**Issue by HarkeshS** [OfficeDev/office-ui-fabric-react#11747] opened 2020-01-21 09:17 UTC
Panel popup navigate on Parent page when pressing Backspace key on IE 11, Working fine in rest of browsers

### Environment Information

OS: Win 10
Browser:  IE

### Describe the issue:

Panel popup navigate on Parent page when pressing Backspace key on IE 11, Working fine in rest of browsers

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fabric#/controls/web/panel

See snap

![Panel_IE11_Backspace_Issue](https://user-images.githubusercontent.com/53938674/72791183-debff000-3c5c-11ea-8293-25c51180c7da.png)

#### Actual behavior:

Panel popup navigate on Parent page when pressing Backspace key on IE 11, Working fine in rest of browsers

#### Expected behavior:

Panel popup should not navigate on Parent page when pressing Backspace key on IE 11, as working in rest of browsers

**Comment by khmakoto** [comment] 2020-01-21 21:36
Hi @HarkeshS, since the new Chromium based Edge is now out for consumption in older versions of Windows we are now deprioritizing IE11 specific work unless it's completely breaking rendering or critical functionality. As such, I'll be tagging this issue with `Resolution: By Design`. Please let us know if this is really important and why in case you want us to take another look so that we can wager our efforts. Thanks!

**Comment by HarkeshS** [comment] 2020-01-27 04:09
This is trivial issue, if you can fix this then its ok for us

**Comment by khmakoto** [comment] 2020-01-27 19:29
@HarkeshS I'll go ahead and close the issue then, thanks for understanding!

**Closed by khmakoto** 2020-01-27 19:29 UTC
Labels: Component: Panel, Platform: IE11, Resolution: By Design, Type: Bug :bug:
