### ISSUE TITLE
PeoplePicker: Focus will lost after delete a selected person with keyboard

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#883] opened 2017-01-25 23:55 UTC
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Describe the issue:

1. select some people in PeoplePicker
2. use direction key to select a selected person, make focus on the delete button.
3. press enter to delete the person
4. the next person will be high lighted, but if you continue using keyboard, it can't select person any more, the focus has gone to the page.

#### Expected behavior:

the focus will go to the next person.

**Comment by dzearing** [comment] 2017-01-26 00:36
@joschect 

I'm a bit surprised it's happening, I thought this worked. Will let Jon take a look, unless you beat him to it @MirandaGe .

**Comment by joschect** [comment] 2017-01-26 01:10
@MirandaGe what browser are you using? I see that it's working in chrome. There does appear to be a separate bug in IE where backspace causes the page to navigate.

**Comment by joschect** [comment] 2017-01-26 01:15
@MirandaGe I was not synced with the latest. I will look into this.

**Comment by joschect** [comment] 2017-01-26 02:31
@MirandaGe Okay, sorry to keep flip flopping, backspace appears to work properly in Chrome, but IE does navigate back to the previous page.

**Comment by joschect** [comment] 2017-01-26 02:36
I have been able to reproduce this if I have the ctrl key pressed while selecting, very interesting interaction.

**Comment by joschect** [comment] 2017-01-26 02:44
@dzearing it looks like there are times where an item can be selected and yet not selected. Basically the onSelectionChange is called and focus is given to the item, but when getSelectedCount() is called there is nothing selected.

**Comment by joschect** [comment] 2017-01-26 03:03
@dzearing Okay, so it seems like SelectionZone gives focus to the target and sets it as an anchor giving it the appearance of selection, but for all intents and purposes it's not selected. See the _onFocus method.

**Comment by MirandaGe** [comment] 2017-01-26 12:19
Sorry for missing so much... I am on vacation and thank you for your quick reply. I test it use the example shown on [demo page](https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/PeoplePicker) and seems it's not the newest version.

**Comment by joschect** [comment] 2017-02-01 20:05
@MirandaGe Since this isn't a problem in the latest version I'll close this issue. Please reopen it or open a new one if you experience this problem again.

**Closed by joschect** 2017-02-01 20:05 UTC
Labels: bug
