### ISSUE TITLE
Office UI Fabric Dropdown event onChange not working

### ISSUE THREAD

**Issue by ravick4u** [OfficeDev/office-ui-fabric-react#6951] opened 2018-11-02 15:48 UTC
I am creating SPFx component with React framework. For UI I am using Office UI Fabric controls.

During my development I have found that "Dropdown" control's onChange event is not firing

Based on documentation on "https://developer.microsoft.com/en-us/fabric#/components/dropdown" site, I created below react component with a dropdown. When I look at browser console only two events are firing "onFocus called" and "onBlur called". Also, I do not see any error.

```tsx
import * as React from "react";
import styles from "./HelloWorld.module.scss";
import { IHelloWorldProps } from "./IHelloWorldProps";
import { escape } from "@microsoft/sp-lodash-subset";
import {
  Dropdown,
  IDropdown,
  DropdownMenuItemType,
  IDropdownOption
} from "office-ui-fabric-react/lib/Dropdown";

export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
  public render(): React.ReactElement<IHelloWorldProps> {
    return (
      <Dropdown
        label="Controlled example:" 
        onSelect={this._log("onSelect called")}
        onChange={this._log("onChange called")}
        onFocus={this._log("onFocus called")}
        onBlur={this._log("onBlur called")}
        placeHolder="Select an Option"
        options={[
          { key: "A", text: "Option a" },
          { key: "B", text: "Option b" },
          { key: "C", text: "Option c" },
          { key: "D", text: "Option d" },
          {
            key: "divider_1",
            text: "-",
            itemType: DropdownMenuItemType.Divider
          },
          { key: "E", text: "Option e" },
          { key: "F", text: "Option f" },
          { key: "G", text: "Option g" }
        ]}
      />
    );
  }

  private _log(str: string): () => void {
    return (): void => {
      console.log(str);
    };
  }
}
```

### Environment Information 
 SPFx version 1.5.1
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by JasonGore** [comment] 2018-11-02 16:42
I copied your code into [this CodePen](https://codepen.io/jasongore/pen/XyrQVb) and I do see `onChange` firing whenever a Dropdown item is selected. I will close this issue as no repro for now, but feel free to comment if you find any other issues. Thanks!

**Comment by kalyany1** [comment] 2018-11-11 01:02
onChange event is not firing while extending react.component. It looks weird.

https://sharepoint.stackexchange.com/questions/252011/office-ui-fabric-dropdown-event-onchange-not-working/252048#252048

**Comment by mariantoader** [comment] 2018-12-04 12:05
> I copied your code into [this CodePen](https://codepen.io/jasongore/pen/XyrQVb) and I do see `onChange` firing whenever a Dropdown item is selected. I will close this issue as no repro for now, but feel free to comment if you find any other issues. Thanks!

You did not copy the example, you are extending BaseComponent, not React.Component.

**Comment by JasonGore** [comment] 2018-12-04 16:49
I changed the same CodePen to use `React.Component` and I still see `onChange` getting called in the console.

**Comment by oozoo-solutions** [comment] 2018-12-05 10:36
I'm getting the same issue for the last two days in an SPFx WebPart

SPFx version 1.7.0

```
import * as React from 'react';
import { IProjectDashProps } from './IProjectDashProps';
import { Dropdown } from 'office-ui-fabric-react/lib/Dropdown';

export default class ProjectDash extends React.Component<IProjectDashProps, {}> {

  private _log(str: string): () => void {
    return (): void => {
      console.log(str);
    };
  }

  public render(): React.ReactElement<{IProjectDashProps}> {
    return (
      <div>
          <Dropdown
          label="View"
          options={[
            { key: 'A', text: 'All live projects' },
            { key: 'B', text: 'Proposal submitted' },
            { key: 'C', text: 'Project archive' }
          ]}
          onSelect={this._log("onSelect called")}
          onChange={this._log("onChange called")}
          onFocus={this._log("onFocus called")}
          onBlur={this._log("onBlur called")}
          />
      </div>
    );
  }
}
```

It exhibits the same behaviour as above; onBlur and onFocus are called but onChange is never fired.

This is both on a locally hosted workbench or the tenant hosted one.

The codepens work fine but not when it's actually in an SPFx webpart.

**Comment by KevinTCoughlin** [comment] 2018-12-05 10:51
Hmm.. I believe SPFx recently rolled-out a new version. I have not had a chance to investigate, but perhaps we're speaking about a difference in OUFR versions if the problem does not occur here on `master`.

**Comment by oozoo-solutions** [comment] 2018-12-05 11:08
onChanged event still works, I'll have to use that for now as it's stopping me working otherwise.

Interestingly as well, when you copy the code from https://developer.microsoft.com/en-us/fabric#/components/dropdown, the signature for the onChange handler shows a TS error. So when using the following from the docs above

```
public changeState = (event: React.FormEvent<HTMLDivElement>, item: IDropdownOption): void => {
    console.log('here is the things updating...' + item.key + ' ' + item.text + ' ' + item.selected);
    this.setState({ selectedItem: item });
  };
```

You get the following error when assigning this to onChange:
```
[ts] Type '(event: FormEvent<HTMLDivElement>, item: IDropdownOption) => void' is not assignable to type '(event: FormEvent<HTMLDivElement>) => void'. [2322]
```

**Comment by kalyany1** [comment] 2018-12-05 13:53
Nearly a month back, when I had noticed that 'onChange' is not firing, I have to use onChanged (deprecated) which worked for me. But, in a long term perspective this will be an issue.

**Comment by zbrox** [comment] 2018-12-11 16:22
I'm using this for an Office Online add-in and I observe the same behaviour.

**Comment by axxx307** [comment] 2018-12-17 14:48
I've ran into the same problem. @kalyany1 workaround with using deprecated 'onChanged' did help.

**Comment by ThreadPitt** [comment] 2019-02-04 10:38
Same issue here, is this going to be fixed? ETA? Is this still maintained? Or is it dead like Fabric.js?

This came up as early as may 2018 (brendenseidel commented on May 23, 2018). And MS wants us to use this in enterprise software!?
Thx!

**Comment by JasonGore** [comment] 2019-02-07 20:58
I provided a [CodePen](https://codepen.io/jasongore/pen/XyrQVb) that shows onChange being fired [above](https://github.com/OfficeDev/office-ui-fabric-react/issues/6951#issuecomment-444171318) which is still working as expected. It is not "dead like Fabric.js", @ThreadPitt.

Can anybody reporting this issue reproduce it in a CodePen? Can you tell which version of Fabric you are using?

**Comment by dzearing** [comment] 2019-02-08 02:02
Just to be really, super clear, this does not repro in the current version of Fabric. I also did a codepen here: https://codepen.io/dzearing/pen/pGpaXR

You might be on an old version. @ThreadPitt @axxx307 @zbrox do you know what version you're on? Can you look at your `node_modules/office-ui-fabric-react/package.json` for this?

**Comment by dzearing** [comment] 2019-02-08 02:10
I am fairly convinced that this is a Fabric v5.x issue. It is certainly possible we could cherrypick a fix here, but I'd like to make sure that's the case and that a fix to 5.x would help here.

**Comment by dzearing** [comment] 2019-02-08 18:50
I have gotten in touch with office addins and they will be updating the yeoman template dependencies on monday.

Following up on the spfx templating.

We are looking at what can be done to backport fixes to 5.x build.

**Comment by KevinTCoughlin** [comment] 2019-02-08 19:12
I'm going to investigate this by creating a web part and looking through `OUFR 5.x` change history. However an answer to the following would be helpful:

>You might be on an old version. @ThreadPitt @axxx307 @zbrox do you know what version you're on? Can you look at your `node_modules/office-ui-fabric-react/package.json` for this?

Knowing which version of OUFR those affected are on will help pinpoint the regression if it exists.

**Comment by KevinTCoughlin** [comment] 2019-02-08 19:14
> I have gotten in touch with office addins and they will be updating the yeoman template dependencies on monday.
> 
> Following up on the spfx templating.
> 
> We are looking at what can be done to backport fixes to 5.x build.

Refreshed and saw the above. Will sync to understand the SPFx templating story.

**Comment by KevinTCoughlin** [comment] 2019-02-08 20:58
The prop `onChanged` was deprecated wholesale in favor of `onChange` in https://github.com/OfficeDev/office-ui-fabric-react/commit/137fbcef0a2c118db0097f38075427a41c769ca0#diff-de0b982ce1e3f05601608127c8b3fcd8 targeting `6.x`.

To resolve the above issue, we have a few options:

1. Folks running into this issue are likely to be on `5.x` and can either use `onChanged` or upgrade to `6.x` 
 to unblock themselves.
1. Cherry-pick the above commit isolated to `Dropdown` related files. However, with this approach folks may still run into the problem where they expect `onChange` to work in `5.x` for other components based on our _current_ documentation.
1. Cherry-pick _all_ of the above commit. This would require testing given the surface area and that some of the component internals have changed between `5.x` and `6.x`. The cherry-pick isn't clean.

The first option seems ideal since it would simply require consumers change `onChange` usage to `onChanged` in `5.x` as we enable versioned documentation to resolve this documentation inconsistency.

I will confirm that `onChanged` works in `5.x` and that both `onChanged` and `onChange` work in `6.x` to support the first option.

**Comment by ThreadPitt** [comment] 2019-02-11 10:11
Hi,
first of all thank you for your fast replies - so the project is not only alive, but vibrant :-)
I checked the ChangeLog of the npm package we use ("office-ui-fabric-react") and in there I find:

"# Change Log - office-ui-fabric-react

This log was last generated on Tue, 29 Jan 2019 13:35:55 GMT and should not be manually modified.

## 6.131.0
Tue, 29 Jan 2019 13:35:55 GMT"

I will retest this now, but the issue came up on IE and Chrome...

**Closed** 2019-02-18 13:00 UTC
Labels: Component: Dropdown, Needs: Author Feedback, Resolution: Can't Repro, no-recent-activity

**Comment by rejoystom** [comment] 2019-03-06 07:46
Guys all your problems are caused by a typo... 'onChange' (javascript) and 'onChanged' (JSX) are different.
Just replace with 'onChanged={this.yourFunction.bind(this)}'

**Comment by falkin** [comment] 2019-03-13 10:34
I'm currently working with SharePoint Framework and Office UI Fabric 5.135.0. And i got the same problem on Toggle component. OnChanged works perfect but not Onchange.  

it's a shame because with redux-form when you passing all props input,  function onChange isn't directly called. :(

**Comment by lutherdexter** [comment] 2019-03-29 17:44
Chaps,
I'm having this issue and we are using 6.157.0. Any fixes?

**Comment by JasonGore** [comment] 2019-03-29 17:49
The previous CodePens I've posted as well as [one specifically targeting v6.157.0](https://codepen.io/jasongore/pen/RObKgB) seem to be working as expected.

**Comment by lutherdexter** [comment] 2019-03-29 18:00
@JasonGore - something isn't quite right with the onChange property definition for DDL. I replicated your CodePen and still have the same issue.

**Comment by JasonGore** [comment] 2019-03-29 18:04
What is DDL? Can you share your CodePen with the issue? If we can't repro it in a CodePen I'm not sure we can address the underlying issue.

**Comment by lutherdexter** [comment] 2019-03-29 19:11
@JasonGore ,

**D**rop**D**own**L**ist.

See codepen [here](https://codepen.io/lutherdexter/pen/oOvBKP)

**Comment by JasonGore** [comment] 2019-03-29 20:02
DropDownList is not a component anywhere in Fabric, thus my confusion.

Your CodePen wasn't running correctly so I [updated it here](https://codepen.io/jasongore/pen/NmKgXQ). I see `changeState` getting called. Can you elaborate on the issue you're seeing?

**Comment by lutherdexter** [comment] 2019-03-29 20:58
Thanks for updating the code, I can see it works in codepen.  I tried your updated version in my environment and the issue remains.

The issue is simple: **nothing happens when you click the chevron**. You can scroll through options with the up/down arrow keys when the drop down is in focus.

**Comment by JasonGore** [comment] 2019-03-29 21:08
Please define "nothing". What do you expect to happen when you click on the chevron? It's expanding for me and acting as expected.

This issue specifically is about onChange not being called. I do see onChange being called when an option is selected. onChange won't be called as you're scrolling through options as that would cause a lot of undesired callback activity when a user hasn't made a selection.

I think at this point the best thing to do would be to create an issue with a recording, animated gif, or clear description of the erroneous behavior you're seeing.

**Comment by lutherdexter** [comment] 2019-03-30 07:05
Thanks @JasonGore - I've created an issue for it here #8547

**Comment by trevorkoch** [comment] 2019-04-01 23:00
I experience the same problem in my SPFX project.  When the dropdown selection changes, the onChange event doesn't fire.  When I change "onChange" to "onChanged" it does work but I had to use // @ts-ignore.
