### ISSUE TITLE
setIndexSelected selects multiple items in DetailsList when Selection mode is single

### ISSUE THREAD

**Issue by reficul31** [OfficeDev/office-ui-fabric-react#10471] opened 2019-09-17 09:02 UTC
### Environment Information

- **Package version(s)**: 7.34.0 (Latest master branch)
- **Browser and OS versions**: Chrome Version 76.0.3809.132, Microsoft Edge 44.18362.329.0, / Windows 10 Enterprise Edition

### Please provide a reproduction of the bug in a codepen:
Please find the [codepen link](https://codepen.io/reficul31/pen/BaBOmKO)
On line 98, I explicitly state the SelectionMode of the DetailsList.  
On line 76 and 77 I modify the selection using Selection.setIndexSelected.

#### Actual behavior:
When I have the SelectionMode of the DetailsList set as Single and I use Selection object to change the selection index(setIndexSelected), I encounter the behavior wherein the originally selected item in the details list is not deselected(or toggled) and the new item is selected. This leads to the my DetailsList functioning as in SelectionMode multiple where 2 items in the Details List are selected. 

#### Expected behavior:

When the SelectionMode of the DetailsList is single and we call Selection.setIndexSelected it should toggle the originally selected item and then select the new index.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Blocked

**Comment by aneeshack4** [comment] 2019-09-17 23:13
@reficul31 Trying to repro this and I see on your codepen at first load that both item 4 and 6 are selected but once I focus on the detailslist and click around on different items, I'm unable to select multiple ever again... can you clarify - am I supposed to be seeing this only on the first load? And if so, I'm not sure what this means for how DetailsList's setIndexSelected was intended to be used.

**Comment by reficul31** [comment] 2019-09-18 03:38
Yes, the functionality I was trying to demonstrate was when the selection mode of the DetailsList is set to single; subsequently calling setIndexSelected causes multiple selections. To clarify, in the pen you might see that the DetailsList SelectionMode is set to single.
Now when I call setIndexSelected from any function, not necessarily from componentDidMount, the initial selection is not deselected and the new selection is selected. This emulates the behavior of a Details List with Selection Mode multiple.

In the pen, consider the first call to select index 4 as the initial selection. Now subsequently calling the setIndexSelected should have selected 6 only since the selection mode is single, but this causes multiple selections in the list.

I apologize for not clearly explaining the problem before. I hope this clarifies expected behavior of the Details List more lucidly.

**Comment by aneeshack4** [comment] 2019-09-23 21:13
@reficul31 I spoke with one of my teammates @natalieethell & she's found a fix for you! Please try setting the `SelectionMode` to `Single` on the initialized selection object in the constructor. Right now, the selection object is initialized to `SelectionMode.Multiple` & when initialization a selection object to pass into a `DetailsList`, it defaults to `Multiple` also so that's most likely what's causing this problem. Natalie also has a PR out that should fix this going forward so you won't even have to specifically set the SelectionMode during initialization.

**Comment by aneeshack4** [comment] 2019-09-26 23:04
@reficul31 I believe this above PR #10458 solves this problem so I'll go ahead and close this. If something else comes up please feel free to ping here again.

**Closed by aneeshack4** 2019-09-26 23:04 UTC
Labels: Component: DetailsList, Needs: Author Feedback, Status: In PR
