### ISSUE TITLE
Tooltip for Combo Box option

### ISSUE THREAD

**Issue by batrived** [OfficeDev/office-ui-fabric-react#4549] opened 2018-04-13 19:55 UTC
### Bug Report

- __Package version(s)__: (5.79.1)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (High) 

Products/sites affected: (VSTS)

#### Describe the issue:

Currently, react ComboBox doesn't support tooltip for options, so it the text in the option is too long, its hard for a user to figure out what the option describes.
DropDown component supports it,

#### Actual behavior:

ComboBox doesn't support tooltip in option

#### Expected behavior:

Support tooltip for combobox option or better provide an option to render a custom option

**Comment by KevinTCoughlin** [comment] 2018-04-16 19:12
@batrived for the existing `Dropdown` support, is this by using a custom option item renderer or is there a prop that does it? A Codepen or LoC link for the behavior would be awesome so I can figure out how to best tackle this. Thank you!

**Comment by KevinTCoughlin** [comment] 2018-04-16 20:30
Related https://github.com/OfficeDev/office-ui-fabric-react/issues/4455

**Comment by michaelangotti** [comment] 2018-04-27 19:04
Closing this one as it is a duplicate of #4455

**Closed by michaelangotti** 2018-04-27 19:04 UTC
