### ISSUE TITLE
[Icon Tool] Some icons are empty !

### ISSUE THREAD

**Issue by e-gallis** [OfficeDev/office-ui-fabric-react#11138] opened 2019-11-09 19:43 UTC
### Describe the issue:
Some icons are empty. Is it normal ?

![Image 1](https://user-images.githubusercontent.com/32480338/68534175-818cf180-0331-11ea-9b01-ecf3c37e44e8.png)

**Comment by kenotron** [comment] 2019-11-11 18:08
@Jahnp - I think there's a mismatched font file being loaded here:

https://uifabricicons.azurewebsites.net/

**Comment by Jahnp** [comment] 2019-11-11 18:25
Thanks folks. So this is actually a known "issue" that traces back to the new [multi-color Office app icons](https://developer.microsoft.com/en-us/fabric#/styles/web/office-brand-icons). 

**tl/dr:** Known issue. Don't use the blank icons. We'll clean it up soon.

**Context:** Basically, when the multiple versions of those icons started to get rolled out, there was a question of how they'd be supported in the icon font; this was of particular interest because the icons are multi-color, not monoline like the rest of the MDL2 icons. At the time, a decision was made to include each colored part of each app icon in a separate icon "layer", such that they could be stacked on top of one another to reproduce the multi-colored visuals of the SVG versions.

But this approach was kind of bloated and un-ergonomic. Why layer these icons when one could just use the SVGs or PNGs? So there was another decision to remove those icons and reclaim them for future use; at some point those Unicode values will be replaced with new icons, but in the meantime, on the font side, they couldn't be removed outright—so the decision was made to remove the icons themselves but not the names/data points. Hence, the empty spaces.

That said, it's definitely confusing if you don't know the context. I'll schedule some work to just remove them from this version of the tool for simplicity.

Thanks again for reporting!

**Comment by e-gallis** [comment] 2019-11-11 20:46
Duely noted.. :)
@Jahnp: I've created a Power Apps component that helps developper generate the SVG of any of the MDL2 icon provided on the Icon Tool page. Would there be a way for me to be informed when there is any modification done to the list of MDL2 icons so I can update my component and stay up to date ?

**Comment by kenotron** [comment] 2019-11-11 22:21
I'm closing this issue as it doesn't seem to be actionable other than work that is already underway tracked somewhere else.

**Closed by kenotron** 2019-11-11 22:21 UTC
Labels: Area: Icons, Type: Bug :bug:
