### ISSUE TITLE
ToolTipHost closes when content hovered

### ISSUE THREAD

**Issue by TomekPi** [OfficeDev/office-ui-fabric-react#9464] opened 2019-06-14 09:42 UTC
### Environment Information 
 
https://fabricweb.z5.web.core.windows.net/oufr/6.189.4/#/examples/Tooltip

#### Actual behavior:
 
The Tooltip closes even if mouse is over tooltip content. The `closeDelay` doesn't help, the tooltip is closed after that time.
 
#### Expected behavior:
 
The Tooltip stays opened when hovering the content according to `closeDelay` description:

> Hovering over the tooltip will count as hovering over the host, so that the tooltip will stay open if the user is actively interacting with it. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low

**Comment by natalieethell** [comment] 2019-06-14 17:51
Hey @TomekPi thanks for opening an issue! We're taking a look.

**Comment by natalieethell** [comment] 2019-06-14 18:32
@TomekPi is it the "Tooltip with a closing delay" where you're seeing this weird behavior? What browser are you using?

**Comment by TomekPi** [comment] 2019-06-18 14:06
@natalieethell , yes, "Tooltip with a closing delay" should stay opened while I'm hovering the tooltip content but it doesn't, it just closes after `closeDelay` time.
For me it occurs on all browser (Firefox, Chrome, Edge, IE).

**Comment by natalieethell** [comment] 2019-06-18 17:05
Oh strange, I'm not able to repro the issue you're seeing on Firefox, Chrome, Edge, or IE with that link you provided (https://fabricweb.z5.web.core.windows.net/oufr/6.189.4/#/examples/Tooltip). Here's what I'm seeing on all browsers:
![TooltipWithClosingDelayEdge](https://user-images.githubusercontent.com/14134000/59703441-bfd11b00-91ae-11e9-97bf-a355be66df45.gif)

Are you by change using a different link/version? If not, could you potentially record what you're seeing?

**Comment by TomekPi** [comment] 2019-06-19 07:54
@natalieethell , you misunderstood me. If I understand correctly, the tooltip should stay opened when you're interacting with it so e.g. hovering it's content (tooltip content, not the element, so text "This is the tooltip"), but it doesn't:

![TooltipRec](https://user-images.githubusercontent.com/13480993/59746948-31c16700-9278-11e9-965b-965209e1e2d4.gif)

**Comment by natalieethell** [comment] 2019-06-19 18:15
@TomekPi oh gotcha! So it looks like what's happening is the delay countdown starts once you leave the TooltipHost. If you look at the Default Tooltip example, it does the same thing.

![DefaultTooltipClosing](https://user-images.githubusercontent.com/14134000/59789357-9d103680-9282-11e9-8d1b-018ea62c9670.gif)

If you, however, go straight over the Tooltip from the TooltipHost, the Tooltip does not close. Here's what I'm seeing in both the Default Tooltip and the Tooltip with a closing delay examples:

![DefaultTooltipStayingOpen](https://user-images.githubusercontent.com/14134000/59789519-e9f40d00-9282-11e9-8769-c8a440f0f860.gif)\

![TooltipWithClosingDelayStayingOpen](https://user-images.githubusercontent.com/14134000/59789640-258ed700-9283-11e9-865e-eeebb8a423dc.gif)

What do you think @micahgodbolt - does this seem expected? Should we instead invalidate the delay countdown if a user starts interacting with a Tooltip within the delay time, even if that user did not go directly from the TooltipHost to the Tooltip?

**Comment by micahgodbolt** [comment] 2019-06-19 18:26
Yeah, the original PR #4364 added this feature in. I'd assume that hovering over the tooltip itself (even if you left the tooltip) would reset the timer. Not sure if this was a regression or error in the original work, but I'd expect it to work that way. It'd be worth looking at the logic added in that PR and make sure it supports resetting the dismiss timer anytime the tooltip is hovered.

**Comment by natalieethell** [comment] 2019-06-19 18:45
@micahgodbolt cool, sounds good. Thanks for the clarification! I'll look into it. Thanks @TomekPi for bringing this to our attention!

**Comment by natalieethell** [comment] 2019-06-19 20:21
Alright found the lines of code causing this behavior:

https://github.com/OfficeDev/office-ui-fabric-react/blob/abd449b2323831dd5c636fa6a196818a78f0585c/packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.base.tsx#L159-L162

It looks like this was added in the following PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/6211. We'll see if there's a way to keep those changes and fix this issue it caused.

**Closed** 2019-06-20 22:31 UTC
Labels: Component: Tooltip, Status: In PR, Type: Bug :bug:
