### ISSUE TITLE
Can't interact with Tooltip which has closeDelay

### ISSUE THREAD

**Issue by ms-qinyang** [OfficeDev/office-ui-fabric-react#8694] opened 2019-04-11 08:07 UTC
### Environment Information 
 
- __Package version(s)__: 6.165.0
- __Browser and OS versions__: Chrome 73.0.3683.103 & Windows 10 1809

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/ROVKBZ
 

 
#### Actual behavior:
Can't interact with tooltip like selecting text. Tooltip auto closes after 500ms no matter mouse is hovering or not.
 

 
#### Expected behavior:
Tooltip shouldn't auto close if mouse is hovering.
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)

**Comment by joschect** [comment] 2019-04-11 19:17
@ms-qinyang Thanks for submitting this! To help clarify, what is the expected use case for this? Are you looking to allow users to copy and paste information from the tooltip?

**Comment by ms-qinyang** [comment] 2019-04-12 02:31
A very common use case is copy/parse long text from the tooltip.

![image](https://user-images.githubusercontent.com/25601395/56007741-492a2400-5d0c-11e9-8a2a-0dcdad79d2ad.png)

And in the [tooltip document](https://developer.microsoft.com/en-us/fabric#/components/tooltip#Implementation) `closeDelay` property, it says that

> Optionally a number of milliseconds to delay closing the tooltip, so that
 the user has time to hover over the tooltip and interact with it. __Hovering
 over the tooltip will count as hovering over the host, so that the tooltip
 will stay open if the user is actively interacting with it.__

I think tooltip shouldn't be auto closed if mouse is hovering over it. I guess we should also [clear the dismiss timer](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.base.tsx#L171) when mouse enter the tooltip.

**Comment by ms-qinyang** [comment] 2019-04-16 03:38
@joschect Any update?

**Comment by joschect** [comment] 2019-04-16 16:24
@ms-qinyang I've taken a look at the code a bit more and it looks like this behavior should already be supported. There is a closeDelay property and the callout does have an onMouseEnter/onMouseLeave proper passed in. I believe that this is actually a bug. I'm working on a fix now.,

**Comment by joschect** [comment] 2019-04-16 17:42
@ms-qinyang I talked with @micahgodbolt about this and as it turns out this is all expected behavior. The tooltip is not supposed to be interacted with, much in the same way that browser tooltips are not able to be interacted with. 

A way that you can achieve this behavior would be to use the tooltip component, ratherthan tooltip host, and control it's opening and closing yourself.

**Closed** 2019-04-23 19:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
