### ISSUE TITLE
Facepile gives non-default persona coin size if you pass in null

### ISSUE THREAD

**Issue by phkuo** [OfficeDev/office-ui-fabric-react#5808] opened 2018-08-04 01:56 UTC
Facepile component will show persona coins at a different size when you pass in null then when you pass in undefined. Something to do with defaultProps I'm guessing, and defaults for the size for Facepile and Persona being different.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: none

**Comment by natalieethell** [comment] 2018-08-06 19:55
Just tried repro-ing, and the compiler does not allow `null` to be passed into the `personaSize` prop on Facepile. 

I did notice that the default size for the PersonaCoin is different for Facepile (32px) and Persona (48px). 

@jordandrako and I spoke offline briefly about this and it seems like facepiles are typically meant to be more compact. Just to check, though, @mtennoe and @jakob101 do you know if this difference in defaults is by design?

**Comment by mtennoe** [comment] 2018-08-08 16:42
I think it makes sense that the standard personacoin size in the two components are different, as the facepile contains a list of several persona coins, and having a too large coin would take up (in a typical experience) too much space. In the meanwhile, the Persona component is typically used to render more information about a single user, not just the image, so it typically needs more real estate, and therefore has a bigger personacoin. These are at least my thoughts; I am not sure if that is by design

**Comment by natalieethell** [comment] 2018-08-08 16:59
Hey @mtennoe thanks for the update! Given what Marius said above regarding the default persona coin size for each component and given that the compiler does not allow `null` to be passed into the `personaSize` prop on Facepile, I'll close this issue.

**Closed by natalieethell** 2018-08-08 16:59 UTC
Labels: Component: Facepile, Needs: Design 🎨
