### ISSUE TITLE
[ActionButton][Accessibilty][HighContrast] Border around action button does not change when focused in high contrast

### ISSUE THREAD

**Issue by aadhars** [OfficeDev/office-ui-fabric-react#3622] opened 2017-12-21 11:29 UTC
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) : Normal

Products/sites affected: (if applicable)VSTS

#### Describe the issue:
Action Button does not have border in normal mode but it stareted showing border in high contrast. As a result when ActionButton is focussed in high Contrast it is difficult to distinguish when it is focussed.

![image](https://user-images.githubusercontent.com/29277148/34254008-07cc73e6-e670-11e7-89a2-468adfc88251.png)

#### Actual behavior:

Action button has border by default in high contrast. As a result it becomes difficult to recognize when it is focused.

#### Expected behavior:

There should be some way to identify if action button is focused or not.

### If applicable, please provide a codepen repro:

**https://developer.microsoft.com/en-us/fabric#/components/button**

**Comment by betrue-final-final** [comment] 2018-01-11 20:34
This is busted. @lynamemi, want to learn high contrast. Get me if you want to deal with this. Should be easy.

**Comment by betrue-final-final** [comment] 2018-01-11 20:37
Dupe of #3419

**Closed by betrue-final-final** 2018-01-11 20:37 UTC
