### ISSUE TITLE
npm install office-ui-fabric-react latest(7.90.0) fails

### ISSUE THREAD

**Issue by AparnaPrasad** [OfficeDev/office-ui-fabric-react#11918] opened 2020-02-11 16:52 UTC
### Environment Information

- **Package version(s)**: 6.90.0
- **Browser and OS versions**: OS: Windows 10 Pro v1903

### Describe the issue:

npm install office-ui-fabric-react fails
npm ERR! notarget No matching version found for @uifabric/icons@^7.3.6
(Attaching screenshot for more details)

**I see in npm page for @uifabric/icons the latest version is 7.3.5, but office ui tries to pull the next version**

https://www.npmjs.com/package/@uifabric/icons

### Please provide a reproduction of the issue in a codepen:
-

#### Actual behavior:

npm i fails

#### Expected behavior:

should install office-ui-fabric-react
![Capture](https://user-images.githubusercontent.com/1925970/74259044-86c65780-4cf7-11ea-8867-730aa3cd212d.PNG)

**Comment by dzearing** [comment] 2020-02-11 17:40
Thanks for reporting.

The "latest" tag has now moved back to 7.90.1 until we've resolved the root cause. 

Please validate you're good to go now and close this bug if so! :)

**Comment by t-walker** [comment] 2020-02-11 17:42
I was seeing this a lot yesterday and I think it has to do with this: https://status.npmjs.org/incidents/1dpd0zjyhj2v?u=3q2zbsynvt3t

**Comment by dzearing** [comment] 2020-02-11 17:44
@t-walker That looks like a viable culprit. Thanks for mentioning! @kenotron for heads up.

**Comment by kenotron** [comment] 2020-02-11 18:15
Nice, thanks a lot for reporting the npmjs status there... we all have been scratching our heads as to why releases was so randomly busted... looked a lot like a network issue where the publish would die in the middle :)

**Comment by xugao** [comment] 2020-02-11 18:46
@AparnaPrasad - this is fixed now. it was the issue with npm. pls try again

**Closed** 2020-02-11 18:46 UTC
Labels: Needs: Author Feedback, Resolution: External, Status: Fixed, Type: Bug :bug:

**Comment by KevinTCoughlin** [comment] 2020-02-12 01:49
Thanks all for fixing!
