### ISSUE TITLE
[Accessibility][Usable-Calendar]: Role=Application is used for calendars.

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9708] opened 2019-07-04 11:23 UTC
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EakH150kSwRGpKnSl9WocPABBf8DajkaRRcue8qWxOiQmQ?e=ifeol6)

Component: Calendar

**Comment by khmakoto** [comment] 2019-07-05 20:28
Hi @dollykumari5, thanks for filing this issue! This seems to be a duplicate of Bug 10 in #8349, so I'll be closing this since the issue is already being tracked there. Thanks again!

**Closed by khmakoto** 2019-07-05 20:28 UTC
Labels: Area: Accessibility, Component: Calendar, Resolution: Duplicate, Type: Bug :bug:
