### ISSUE TITLE
[Functional- Power Apps Admin - Table] No horizontal scroll bar is present to scroll page horizontally with mouse on DATA integration screen..

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#7329] opened 2018-12-07 08:00 UTC
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 Repro Steps:
1.  Navigate to https://admin.powerplatform.microsoft.com/ext/DataIntegration  and login with intusr.
2. Navigate to the Data Integration menu item on the left bar and select it.
3. Navigate on the controls of data integration page thus opened. Navigate through the screen and the table.
4. Verify if there is a 'horizontal' scroll bar present to scroll page horizontally. 

 
#### Actual behavior:
 No horizontal scroll bar is present to scroll page horizontally with mouse. No other way is present to horizontaly scroll the screen via mouse.

 
#### Expected behavior:
 Horizontal scroll bar should be present so that user using mouse can scroll the screen to access complete information on the table.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) Blocking 
 
Products/sites affected: (if applicable)
![funtional_powerappsadminportal](https://user-images.githubusercontent.com/30456910/49634946-30d78f00-fa24-11e8-87f3-cabd6bb9c514.jpg)

**Comment by KevinTCoughlin** [comment] 2018-12-08 00:12
@sonimishra thank you for reporting this. In order for us to triage this appropriately I require additional information to login for the debug scenario. I can't login, nor do I see the issue with my own User account because the list is not rendered.

Can you or someone contact me with more complete login instructions to debug the above?

Also, as per our "Bug" issue template, the following information would help our team triage and scope the problem (if it indeed exists within the library):

> * **Package version(s)**: (fill this out)
> 
> * **Browser and OS versions**: (fill this out if relevant)

**Comment by sonimishra** [comment] 2018-12-10 07:41
@KevinTCoughlin Hi, Please let me know your availability timings on skype so that i can ping you login credentials or you can ping "v-rads@microsoft.com"  during "0900 to 1800 IST" .

**Comment by kkjeer** [comment] 2018-12-14 19:52
Hi @sonimishra, we're currently tracking several issues related to horizontal scrolling in DetailsList (#6546 and #5176), which seem to be related to DetailsList width calculations. Please let us know if you think this issue is related to different DetailsList behavior.

**Comment by sonimishra** [comment] 2018-12-17 06:51
hi kkjeer.  #7329 is similar to #6546 and #5176), as all the bugs are related to DetailsList width calculations

**Comment by kkjeer** [comment] 2018-12-27 23:49
Closing as a duplicate of #6546 and #5176.

**Closed by kkjeer** 2018-12-27 23:49 UTC
Labels: Component: DetailsList, Resolution: Duplicate
