### ISSUE TITLE
DetailsList Grouped: On adding more elements and groups to the grouped detailsList it becomes inaccessible

### ISSUE THREAD

**Issue by akashperfect** [OfficeDev/office-ui-fabric-react#5400] opened 2018-07-02 05:46 UTC
### Bug Report 
 
- __Package version(s)__: (Latest) 6.23.0
- __Browser and OS versions__: Any (chrome, windows 10)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Not yet
 
Requested priority: **Blocking** 
 
Products/sites affected: VSTS
 
#### Describe the issue:
 
On using grouped details list when more elements and groups are added.
Scrolling to the bottom of the list becomes completely inaccessible.
 
#### Actual behavior:
 
Using grouped details list example template.
On Clicking a link adding more elements and groups to the list
The elements and groups are added to the bottom of the list
In order to view those elements scrolling the list to the bottom, 
Adds some flickering and renders the list completely inaccessible

Gif:
![groupeddetailslistaddmoreissue](https://user-images.githubusercontent.com/2953096/42147029-3ed9dd68-7de9-11e8-921f-892966d2ac84.gif)
 
#### Expected behavior:
 
The list should scroll smoothly and on reaching the end the focus should stay consistently at the end

### If applicable, please provide a codepen repro:
 
https://codepen.io/akashperfect/pen/vrbvEM

**Comment by dzearing** [comment] 2018-07-05 18:05
@ThomasMichon @aditima There seems to be a major regression here. Repro by going to the codepen, and then:

scroll to the bottom, click show more.
scroll to the top, set focus to row 0 or something close to the top.
mousewheel to the end

Expected:
You can see the end

Resulted:
Focus keeps pulling to the top.

**Comment by dzearing** [comment] 2018-07-21 01:11
@aditima @ThomasMichon 

I don't think this has much to do with List. It could be that groups are re-rendering because they don't have the right keys or something...

**Comment by micahgodbolt** [comment] 2018-08-08 18:02
@ThomasMichon this is our only Pri0 bug right now. Wanted to make sure it was still on your radar. Is there a workaround they could use, or a timeframe for when they can expect this resolved?

**Comment by KevinTCoughlin** [comment] 2018-11-12 21:16
Interesting that this only occurs in Chrome. I've also tested Firefox and Edge. No solution yet, but it does seem like a difference in browser behavior with how we programmatically focus when rendering virtualized content. Debugging that further with this trimmed down Codepen: https://codepen.io/kevintcoughlin/pen/mQOGxx?editors=0010.

**Comment by KevinTCoughlin** [comment] 2018-11-15 23:57
I've yet to arrive at solution, but here are some observations while debugging:

I believe the bug resides within [List#_updateRenderRects](https://github.com/OfficeDev/office-ui-fabric-react/blob/bc132408840fe0f8de86e6f9c20bd3e9344657db/packages/office-ui-fabric-react/src/components/List/List.tsx#L920) and how it calculates and sets `scrollTop` over time.

https://github.com/OfficeDev/office-ui-fabric-react/blob/bc132408840fe0f8de86e6f9c20bd3e9344657db/packages/office-ui-fabric-react/src/components/List/List.tsx#L946

I've noticed a few differences while testing this in Chrome and Firefox. It seems like at various points in time, the `scrollElement` which is used to calculate `scrollTop` is `undefined` in ALL browsers. When `undefined`, the `scrollTop` value defaults to `0`, here is the LoC.

https://github.com/OfficeDev/office-ui-fabric-react/blob/bc132408840fe0f8de86e6f9c20bd3e9344657db/packages/office-ui-fabric-react/src/components/List/List.tsx#L931

This results in the following measurements _after scrolling to the bottom_ of the scrollable element:

**Firefox**

```shell
12:25:15.081 _scrollTop 0  
12:25:18.790 _scrollTop 176  
12:25:18.954 _scrollTop 5180  
12:25:19.181 _scrollTop 16914  
12:25:19.304 _scrollTop 18028  
12:25:19.344 _scrollTop 0  
12:25:19.422 _scrollTop 8310  
12:25:19.527 _scrollTop 0  
12:25:19.751 _scrollTop 8310  
12:25:19.761 _scrollTop 0  
12:25:19.816 _scrollTop 8310  
12:25:19.955 _scrollTop 5966  
12:25:19.976 _scrollTop 3818  
12:25:20.017 _scrollTop 0  
12:25:20.176 _scrollTop 2528  
12:25:20.293 _scrollTop 0  
12:25:20.439 _scrollTop 1946 
```

**Chrome**

```shell
12:26:32.750  _scrollTop 9429
12:26:32.785  _scrollTop 0
12:26:33.008  _scrollTop 9429
12:26:33.539  _scrollTop 0
12:26:33.725  _scrollTop 1689
12:26:33.829  _scrollTop 1689
12:26:33.857  _scrollTop 0
12:26:33.960  _scrollTop 9429
12:26:33.969  _scrollTop 9429
12:26:34.087  _scrollTop 571
12:26:34.090  _scrollTop 571
12:26:34.104  _scrollTop 0
12:26:34.105  _scrollTop 0
12:26:34.106  _scrollTop 0
12:26:34.106  _scrollTop 0
12:26:34.438  _scrollTop 0
12:26:34.443  _scrollTop 0
12:26:34.510  _scrollTop 0
12:26:34.512  _scrollTop 0
12:26:34.513  _scrollTop 0
12:26:34.526  _scrollTop 0
```

Both browsers make _invalid_ calculations of `scrollTop` due to `scrollElement` being `undefined`. However, Chrome experiences them in a _batch_ in the final iterations. _I think_ this is why Chrome jumps to the top of the scrollable element, while Firefox seems to land around the middle to bottom third of the element.

Since the scrollable element's `scrollTop` value is used in this tight loop for calculating virtualized rectangles it approaches zero, each time moving closer to the top of the element.

Will continue digging... I believe fixing this will address _most_ of the scrollbar jumping we currently see with `DetailsList`. However, I'm unsure what that fix will entail.

cc: @natalieethell as we spoke in-person about this issue.

**Comment by KevinTCoughlin** [comment] 2018-11-16 00:02
I should note, you can mitigate this issue by disabling virtualization via `DetailsList` prop `onShouldVirtualize={() => false}` assuming the performance impact is acceptable.

However, this needs to be addressed given that virtualization is a core attribute of `DetailsList`.

**Comment by dzearing** [comment] 2019-01-25 22:08
This will be investigated along with the intersectionobserver work.

**Comment by KevinTCoughlin** [comment] 2019-02-26 21:53
You don't need to append items to a Grouped DetailsList to see this behavior. Try scrolling via mouse pointer to the bottom of the viewport quickly in the following examples:

- Before Codepen: https://codepen.io/kevintcoughlin/pen/bZNKrX?editors=0010
- After Codepen: https://codepen.io/kevintcoughlin/pen/VRYBwg?editors=0010

@akashperfect, the suggested workaround is to supply a `getGroupHeight` prop for `DetailsList` as done in the "After Codepen" above. Doing so should produce more reliable scroll behavior for this scenario. 

See the following interface method definition and corresponding doc block for additional context.

https://github.com/OfficeDev/office-ui-fabric-react/blob/ab29c5f3b3a0e01c2c660dcd581b8a1978ab47c8/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L279

Although `IntersectionObserver` would address this, it feels like a patched release of OUFR should provide a base implementation of `getGroupHeight` if groups are defined given our default styling i.e. height values.

**Comment by KevinTCoughlin** [comment] 2019-02-27 00:47
I've raised a pull-request to patch this behavior linked above.

**Closed** 2019-03-01 00:04 UTC
Labels: Component: DetailsList, Type: Bug :bug:
