### ISSUE TITLE
Upgrading to office-ui-fabric-react (6.164.3) throws Javascript heap out of memory error

### ISSUE THREAD

**Issue by maalwa** [OfficeDev/office-ui-fabric-react#8648] opened 2019-04-09 00:17 UTC
I am upgrading the package to use Stack component.

Error:

1>  Unknown output: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory (TaskId:38)
1>  Unknown output:  1: 00150BEE  (TaskId:38)
1>  Unknown output:  2: 004378B2  (TaskId:38)
1>  Unknown output:  3: 0042E746  (TaskId:38)
1>  Unknown output:  4: 00435C1E  (TaskId:38)

Control: (almost the exact code !!)
`export class XYZ extends React.Component<XYZProps, any> {
    public render() {
        return (
            <Stack horizontal={true} horizontalAlign="end" gap="10">
                <div>Count 1</div>      
               <div>Count 2</div>
               <div>Count 3</div>
            </Stack>
        );
    }
}`

**Comment by jdhuntington** [comment] 2019-04-09 15:54
Sorry to hear you're running into this issue!

Would you mind sharing the package versions you are using of the following packages? Will help us reproduce locally and figure out next steps.
 - react
 - react-dom
 - typescript
 - @types/react
 - @types/react-dom

**Comment by KevinTCoughlin** [comment] 2019-04-09 16:14
@maalwa while we investigate, have you tried to bump the node process' heap size as a workaround?

`node --max-old-space-size=<size> <command>`

Also, what version of Node are you running?

**Comment by maalwa** [comment] 2019-04-10 17:21
Yes. I tried the increasing heap size which has unblocked me.

Below is the package,json in case you need to investigate.

{
    "name": "",
    "private": true,
    "version": "2.0.0",
    "scripts": {
        "webpack": "webpack --mode=development --config webpack.config.js --progress",
        "webpack:watch": "webpack --watch --mode=development --config webpack.config.js --progress",
        "webpack:preview": "webpack --env.preview=1 --mode=production --config webpack.config.js --progress",
        "webpack:prod": "webpack --mode=production --config webpack.config.js --progress",
        "webpack:watchdev": "webpack --watch --mode=development --react=development --config webpack.config.js --progress",
        "tsc": " --max-old-space-size=4096 tsc -p tsconfig.json --diagnostics",
        "tsc:watch": "tsc --watch -p tsconfig.json",
        "watchers": "start npm run tsc:watch && start npm run webpack:watch",
        "buildandwatch": "msbuild & npm run watchers"
    },
    "devDependencies": {
        "@types/react": "^16.8.3",
        "@types/react-dom": "^16.8.2",
        "@types/react-select": "^1.3.4",
        "css-loader": "^1.0.0",
        "file-loader": "^1.1.11",
        "ignore-loader": "^0.1.2",
        "post-compile-webpack-plugin": "^0.1.2",
        "rxjs-compat": "^6.2.1",
        "script-loader": "^0.7.2",
        "source-map-loader": "^0.2.4",
        "style-loader": "^0.21.0",
        "tslint": "^5.12.0",
        "tslint-eslint-rules": "^5.4.0",
        "tslint-react": "^3.6.0",
        "typescript": "^3.2.2",
        "url-loader": "^1.0.1",
        "webpack": "^4.16.0",
        "webpack-cli": "^3.0.8"
    },
    "dependencies": {
        "@types/draft-js": "^0.10.30",
        "@uifabric/fluent-theme": "^0.13.4",
        "@vx/axis": "0.0.153",
        "@vx/event": "0.0.153",
        "@vx/gradient": "0.0.153",
        "@vx/grid": "0.0.171",
        "@vx/group": "0.0.153",
        "@vx/mock-data": "0.0.153",
        "@vx/responsive": "0.0.165",
        "@vx/scale": "0.0.153",
        "@vx/shape": "0.0.153",
        "@vx/text": "0.0.153",
        "@vx/tooltip": "0.0.153",
        "blueimp-md5": "^2.10.0",
        "bootstrap": "^3.3.7",
        "classnames": "^2.2.5",
        "csstype": "^2.6.2",
        "d3": "^3.5.4",
        "d3-array": "^1.2.1",
        "draft-js": "^0.10.5",
        "draft-js-plugins-editor": "^2.1.1",
        "faker": "^4.1.0",
        "hoist-non-react-statics": "^3.3.0",
        "html-react-parser": "^0.4.6",
        "jsoneditor": "^5.5.7",
        "linkify-it": "^2.1.0",
        "mobx": "^5.8.0",
        "mobx-react": "^5.4.3",
        "mobx-react-devtools": "^6.0.3",
        "numeral": "^2.0.6",
        "office-ui-fabric-react": "^6.164.3",
        "owl.carousel2": "^2.2.1",
        "react": "^16.8.2",
        "react-clipboard.js": "^2.0.2",
        "react-datetime": "^2.10.3",
        "react-dom": "^16.8.2",
        "react-markdown": "^3.3.2",
        "react-rangeslider": "^2.2.0",
        "react-router-dom": "^4.3.1",
        "react-select": "^1.3.0",
        "react-tiny-virtual-list": "^2.2.0",
        "satcheljs": "^4.0.0-beta2",
        "satcheljs-trace": "^2.15.0",
        "seedrandom": "^2.4.2",
        "showdown": "^1.6.4",
        "tlds": "^1.203.1",
        "ts-odatajs": "^4.0.4"
    }
}

**Comment by joschect** [comment] 2019-04-10 17:56
@maalwa Hey! Thanks for responding. One other question is, what version of node were you using? We'll look into it!

**Comment by maalwa** [comment] 2019-04-10 18:05
v8.9.4

**Comment by maalwa** [comment] 2019-04-10 22:19
I dont know if this will help narrow down your investigation, but here are more details:
I found that in the .csproj file, if I run "tsc" as a command rather than compiling using targets from Microsoft.Typescript.MSBuild.targets, fixed the issue in VS2017 as well as VSCode.


![image](https://user-images.githubusercontent.com/47611256/55907665-3be62b80-5b8c-11e9-9dd6-d002700981b7.png)

It did solve the heap issue, however, it didnt solve the problem completely. The Azure DevOps build still complaint about

![image](https://user-images.githubusercontent.com/47611256/55917355-f03f7c00-5ba3-11e9-9861-60c8fb18477c.png)

**Comment by joschect** [comment] 2019-04-10 22:53
@maalwa what are you running when this fails? Is this during npm install? Npm run?

**Comment by joschect** [comment] 2019-04-10 22:53
I tested just npm run locally with the package.json that you provided and it installed without issue.

**Comment by maalwa** [comment] 2019-04-10 23:03
We have .csproj as shown below. (remove file names !)
This is the only project file in the solution on which msbuild is run on Azure DevOps. Hope it clarifies a bit. Note the typescript target included !


```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  <Import Project="..\packages\Microsoft.TypeScript.MSBuild.3.2.2\build\Microsoft.TypeScript.MSBuild.props" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.3.2.2\build\Microsoft.TypeScript.MSBuild.props')" />
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{6D2F9B0E-15FC-43C7-AF0D-638CBC30B607}</ProjectGuid>
    <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>XYZ.Web</RootNamespace>
    <AssemblyName>XYZ.Web</AssemblyName>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
    <MvcBuildViews>false</MvcBuildViews>
    <UseIISExpress>false</UseIISExpress>
    <MvcProjectUpgradeChecked>true</MvcProjectUpgradeChecked>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Prefer32Bit>false</Prefer32Bit>
    <SignAssembly>false</SignAssembly>
    <AllowedReferenceRelatedFileExtensions>
      .exe.config;
      .dll.config
    </AllowedReferenceRelatedFileExtensions>
    <UseGlobalApplicationHostFile>true</UseGlobalApplicationHostFile>
    <TypeScriptToolsVersion>3.2</TypeScriptToolsVersion>
    <Use64BitIISExpress />
    <IISExpressSSLPort />
    <IISExpressAnonymousAuthentication>disabled</IISExpressAnonymousAuthentication>
    <IISExpressWindowsAuthentication>enabled</IISExpressWindowsAuthentication>
    <IISExpressUseClassicPipelineMode>false</IISExpressUseClassicPipelineMode>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition="'$(BuildingInsideVisualStudio)' == 'true'">
    <OutDir>bin</OutDir>
  </PropertyGroup>
  <!-- We need to define OutputPath for every flavor to avoid the VS default Release/Debug flavor. -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'dev|AnyCPU'">
    <OutputPath>bin\</OutputPath>
    <DefineConstants>TRACE;DEBUG;;CODE_ANALYSIS</DefineConstants>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AllowedReferenceRelatedFileExtensions>
      .pdb;
      .xml;
      .exe.config;
      .dll.config
    </AllowedReferenceRelatedFileExtensions>
    <FilesToIncludeForPublish>OnlyFilesToRunTheApp</FilesToIncludeForPublish>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'paasprod|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ciprod|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'previewprod|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <DeployOnBuild Condition=" '$(DeployMCWeb)'!='' ">$(DeployMCWeb)</DeployOnBuild>
  </PropertyGroup>
    
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
        <WebProjectProperties>
          <UseIIS>True</UseIIS>
          <AutoAssignPort>True</AutoAssignPort>
          <DevelopmentServerPort>49632</DevelopmentServerPort>
          <DevelopmentServerVPath>/</DevelopmentServerVPath>
          <IISUrl>http://localhost/</IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>False</UseCustomServer>
          <CustomServerUrl>
          </CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
        </WebProjectProperties>
      </FlavorProperties>
    </VisualStudio>
  </ProjectExtensions>
  <ItemGroup>
    
  </ItemGroup>
  <ItemGroup />
  <ItemGroup>
    <Service Include="{4A0DDDB5-7A95-4FBF-97CC-616D07737A77}" />
  </ItemGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v15.0\WebApplications\Microsoft.WebApplication.targets" />
  <!-- Typescript .map override for non dev flavor. -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' != 'dev|AnyCPU'">
    <ExcludeFilesFromDeployment>**\*.map;</ExcludeFilesFromDeployment>
  </PropertyGroup>
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Microsoft.TypeScript.MSBuild.3.2.2\build\Microsoft.TypeScript.MSBuild.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.TypeScript.MSBuild.3.2.2\build\Microsoft.TypeScript.MSBuild.props'))" />
    <Error Condition="!Exists('..\packages\Microsoft.TypeScript.MSBuild.3.2.2\build\Microsoft.TypeScript.MSBuild.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.TypeScript.MSBuild.3.2.2\build\Microsoft.TypeScript.MSBuild.targets'))" />
  </Target>
  <Import Project="..\packages\Microsoft.TypeScript.MSBuild.3.2.2\build\Microsoft.TypeScript.MSBuild.targets" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.3.2.2\build\Microsoft.TypeScript.MSBuild.targets')" />
  <Target Name="BeforeBuild">
    <Exec Command="npm install" />
  </Target>
  <Target Name="NpmRunWebpack" AfterTargets="CompileTypeScriptWithTSConfig" Condition="'$(BuildingInsideVisualStudio)' == 'true'">
    <Exec Command="npm run webpack" />
  </Target>
  <Target Name="NpmRunWebpackPreview" AfterTargets="CompileTypeScriptWithTSConfig" Condition="'$(BuildingInsideVisualStudio)' != 'true' AND '$(Configuration)' == 'previewprod'">
    <Exec Command="npm run webpack:preview" />
  </Target>
  <Target Name="NpmRunWebpackProd" AfterTargets="CompileTypeScriptWithTSConfig" Condition="'$(BuildingInsideVisualStudio)' != 'true' AND '$(Configuration)' != 'previewprod'">
    <Exec Command="npm run webpack:prod" />
  </Target>
  <Target Name="CopyDistFolder" AfterTargets="PipelineCopyAllFilesToOneFolderForMsdeploy;CopyAllFilesToSingleFolderForPackage">
    <Message Text="Copying webpack built files from $(ProjectDir)dist to $(_PackageTempDir)/dist">
    </Message>
    <ItemGroup>
      <DistFiles Include="$(ProjectDir)dist\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(DistFiles)" DestinationFolder="$(_PackageTempDir)\dist" />
  </Target>
</Project>
```

**Comment by joschect** [comment] 2019-04-11 22:30
@maalwa This seems like isn't a fabric specific problem and is related to the build system that is being used. Since this isn't an oufr bug I would seek help in the Fabric team chat or [stackoverflow](https://stackoverflow.com/questions/tagged/office-ui-fabric) .

**Comment by KevinTCoughlin** [comment] 2019-04-17 20:44
@maalwa, SPFx team has had _some_ success updating Webpack to `>= 3.12.x` when using `office-ui-fabric-react@6`. It might be worth a try on your end to see if it unblocks you. In parallel they are exploring updating the SPFx tooling to mitigate this.

I have not yet looked at Webpack's changelog to see if there was a memory issue resolved in that release.

**Closed** 2019-04-25 07:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
