### ISSUE TITLE
[Keyboard Navigation  - MyAccess - Filters] Name is not defined for 'Cancel' button control under 'Filter' blade. 

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#10336] opened 2019-09-03 10:24 UTC
**Repro steps:**
1. Open URL 'https://myaccess.microsoft.com/@M365x202152.onmicrosoft.com#/access-packages' and enter valid credentials.
2. Navigate to 'Access Package' list item and select it.​
3. 'Access Package' screen will open.​
4. Navigate to 'Active' tab items and select it.​
5. 'Active' packages screen will open and select any active package like 'test' from table.​
6. Navigate to 'Filter' button and select it.​
7. 'Filters' screen will open.​
8. Navigate to various controls such as radio buttons on the screen.​
9. Verify Name is defined for 'Cancel' button control or not under 'Filter' blade

**Actual Result:**
Name is not defined for 'Cancel' button control under 'Filter' blade.  and due to this user is unable to identify the context of that control.

**Expected Result:**
Name should be defined for 'Cancel' button control under 'Filter' blade, so that end user could get the context and preform functionality over such controls.

**Note:**
1. Same issue exists under "Request Access", "Help", "Switch Organizations", "My Profile", "Deny" blade.
2. Same issue exists under 'Access request' blade on 'Approve'.
3. Same issue exists under 'Notification' blade.

![MAS 4 1 2_Cancel button](https://user-images.githubusercontent.com/30456910/64165549-f1c75480-ce62-11e9-9344-b5eb9f0254ab.png)

**Comment by KevinTCoughlin** [comment] 2019-09-03 17:42
This potential issue looks like a duplicate of #10338 in that whatever solves that should also solve this.

**Comment by dzearing** [comment] 2019-09-16 04:50
Duplicate of #10338; which means, please provide the correct props to Panel.

**Closed by dzearing** 2019-09-16 04:50 UTC
Labels: Area: Accessibility, Component: Panel
