### ISSUE TITLE
Tooltip support for ContextualMenu items

### ISSUE THREAD

**Issue by phyllers** [OfficeDev/office-ui-fabric-react#10681] opened 2019-10-01 18:52 UTC
#### Describe the feature that you would like added

I'd like to add a tooltip to a ContextualMenu. There was previously a ticket filed under accessibility that got closed. However, my scenario is to be able to explain to a user why a menu item is disabled/or not. 

#### What component or utility would this be added to

ContextualMenuItem

**Comment by khmakoto** [comment] 2019-10-01 20:48
Hi @phyllers, thanks for filing this issue!

This seems like a feature request, @joschect what do you think we should do about this? I can certainly try to include tooltips in `ContentualMenuItems` but I don't know if that's a scenario we want to support and, if we do, if we should do it now or add it to the backlog. Curious to know your opinion on this.

**Comment by khmakoto** [comment] 2019-10-07 23:17
I had an offline conversation with @joschect and we decided that we're putting this feature in the backlog for now while we work on more pressing issues.

**Comment by abithap** [comment] 2019-10-10 21:48
@khmakoto we have the exact same scenario to tell the user why the button is disabled. I tried to use the tooltipHostProps but that gets enabled only with IconOnly is set to true and it makes the UI look weird. Is there a workaround for this issue till the feature gets actually shipped?

**Comment by khmakoto** [comment] 2019-10-10 21:53
@abithap, it seems like you're using a specific surface, like a `CommandBar` for example. Can you tell me if that's the case, and if so which surface you're using?

**Comment by abithap** [comment] 2019-10-10 21:59
@khmakoto we are using the CommandBar, is there a way to show the tooltip from CommandBar in disabled state? 
We are also using ComboBox with title and it works fine in disabled state.

**Comment by khmakoto** [comment] 2019-10-10 22:12
Let me try to spin up a PR for the `CommandBar` where you can show that tooltip.

**Comment by khmakoto** [comment] 2019-10-10 23:00
@abithap I've made [this codepen](https://codepen.io/khmakoto/pen/MWWaVav) where you can see that the `Share` button has a tooltip. It is not ideal but it is a workaround while we get to the real issue.

**Comment by abithap** [comment] 2019-10-10 23:32
@khmakoto  thank you it works. Will wait for the real issue fix. Appreciate your help.

**Comment by khmakoto** [comment] 2019-10-10 23:54
@abithap You're welcome! Let me know if there is anything else I can do to help!

**Comment by xugao** [comment] 2020-01-23 21:42
@khmakoto @joschect - i think we should close this as "by design". We should never build in the prop to enable tooltip as part of the contextual menu component. that's unnecessary bundle size increase for the component. I think the solution Mak gave is the proper way to solve this.

**Comment by khmakoto** [comment] 2020-01-23 22:45
@xugao I believe so as well, what do you think @joschect?

**Comment by joschect** [comment] 2020-01-23 22:53
@xugao  and @khmakoto I agree. I think it's okay to close this as by design. I think that @khmakoto 's solution is the right one, it's a relatively lightweight wrapper that enables the desired behavior and helps keep the contextualmenu decoupled from tooltip.

**Closed** 2020-01-31 02:00 UTC
Labels: Component: ContextualMenu, Needs: Author Feedback, Needs: Backlog review, Resolution: By Design, Status: No Recent Activity, Type: Feature
