### ISSUE TITLE
[DetailsList] 'initialFocusedIndex' doesn't select the row

### ISSUE THREAD

**Issue by ajaypantangi** [OfficeDev/office-ui-fabric-react#2481] opened 2017-08-11 20:59 UTC
### Bug Report
We are using 'initialFocusedIndex' to set focus on the first item in the list. The focus is set but there is no selection highlight.

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by kristoferbrown** [comment] 2017-08-17 17:10
@ajaypantangi, is this a duplicate of #1112? What I currently see is that if initialFocusedIndex is set, then that item will be focused when the details list itself is focused, but not before. Can you clarify further how this is not meeting your expectations?

**Comment by stellage** [comment] 2017-08-17 18:06
I'm also experiencing a similar issue while using the DetailsList within a callout and trying to shift focus via 'initialFocusedIndex' to the first item in the list after filtering. While debugging, I'm seeing that in 'componentDidUpdate', an 'activeRows' variable is being utilized to locate the row to focus but in 'setFocusToRowIfPending' it's simply using initialFocusedIndex, which causes misaligned indices resulting in no focus on any row, let alone the first row. I've only encountered this problem after filtering results, though. Any ways to work around/fix this problem?

**Closed** 2018-05-18 23:07 UTC
Labels: :bug: Type: bug, no-recent-activity
