### ISSUE TITLE
[Accessibility] Dropdown not announcing "expand/collapse" when opened/closed

### ISSUE THREAD

**Issue by tianbli** [OfficeDev/office-ui-fabric-react#12228] opened 2020-03-06 20:18 UTC
### Environment Information

- **Package version(s)**: 7
- **Browser and OS versions**: Narrator on Microsoft Edge (old, not chromium)

### Describe the issue:
Using Narrator on old Microsoft Edge, opening/closing dropdown doesn't announce "expand/collapse". 

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/tianbli-the-encoder/pen/qBdPgLO?editable=true
1. use above repro, click on the anywhere except dropdown on the canvas
2. use tab key to focus on dropdown
3. Press Enter to open callout, noticed there is no "expand" announced
4. Press ESC to exist callout, noticed there is no "collpase" announced
#### Actual behavior:
not announce "expand/collapse"

#### Expected behavior:
should announce "expand/collapse"

**Comment by aneeshack4** [comment] 2020-03-07 00:29
This is a dupe of #9374 - this behavior is intentional, explained here on that issue. Closing this.

**Closed by aneeshack4** 2020-03-07 00:29 UTC
Labels: Needs: Triage :mag:

**Comment by jamesedjac** [comment] 2020-03-16 18:07
Commenting here because #9374 is locked for commenting

@aneeshack4 @xugao and @khmakoto can we reconsider the decision to close this?

I took a look at the code and noticed some issues with the semantics I believe is causing the problem. I also I think there was some miscommunication of the expected behavior.

Regarding the expected behavior, I do not expect that the screen reader will announce expanded immediately after the listbox is expanded. But it should announce the current state of the list box when the "original control" has focus (putting original control in quotes because of the semantic issues outlined below)

The user impact of this is that when the user reaches the control, they are not cued in that it can expand. I have included some updated expected behaviors below

**Semantics**
I noticed that the aria-expanded attribute is set on the dropdown and is just not actually being read. This is because the dropdown's role is "listbox", and [aria-expanded is not a support state or property of the listbox role](https://www.w3.org/TR/wai-aria-1.1/#listbox). In addition, aria-hadpopup is set to listbox, which is a valid value of that attribute, however my understanding is that haspopup is not meant to be self referential (essentially a popup can't open itself)

If the role of the dropdown is changed to "button" aria-expanded is announced correctly. This will mean the elements with role="option" will not have a listbox to contain them, so I recommend that a new listbox be added to contain them. Essentially the dropdown is a button that opens a listbox popup as in the [ARIA Authoring Practices example for Collapsible Dropdown Listbox Example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html)

**Updated Expected Behavior**
When the users reaches the drop down, it will announce that it is a "button" and is "collapsed". When the user selects the button, the listbox is expanded, and focus moves inside it (it is not neccesary for the screen reader to announce expanded). Finally, if focus can reach the button again, without the listbox closing automatically, it should read as "expanded", but there is not expectation that the user can reach the control in this state

The most critical thing is that when the dropdown is closed, it is read as collapsed when it has focus

**Comment by xugao** [comment] 2020-03-27 19:54
@jamesedjac - the reason for this bug is Narrator is treating aria-expanded as advanced information. see this: https://microsoft.visualstudio.com/OS/_workitems/edit/25287194
I believe they are reverting this decision but looks like the work is not done yet
