### ISSUE TITLE
Dropdown: Display above if not enough space below

### ISSUE THREAD

**Issue by nguyentoantuit** [OfficeDev/office-ui-fabric-react#3719] opened 2018-01-14 10:54 UTC
![image](https://user-images.githubusercontent.com/6096518/34915158-90a75eba-f953-11e7-9d37-7b4beb5ae9bc.png)
Currently, I have problem with dropdown that if there is less space at bottom the dropdown selections is still shown at bottom which is quite hard for end-user selects the correctly option that he/she want. So it is really handy if the dropdown options show at the top of dropdown if there is less space at bottom.

Thanks,
Toan

**Comment by Jahnp** [comment] 2018-01-18 22:18
@micahgodbolt, thoughts? Is this something you could take a look at?

**Comment by micahgodbolt** [comment] 2018-01-18 22:56
We initially had dropdown displaying to the side if not enough space below. I believe it was a design decision to force it below (i.e. drop"DOWN"). I'm fine with a change as long as it passed by design.

**Comment by Jahnp** [comment] 2018-01-19 19:52
Thanks for the quick response! Ha, I always assumed the "down" part was just a colloquialism, since afaik most native menus like this will respond to screen position, including "dropping up" if needed.

That said, do you remember who made that design decision so we can check with them? I checked with @betrue-final-final and he agrees they should reposition if there isn't enough space to display, say, 3 items.

**Comment by micahgodbolt** [comment] 2018-01-19 20:07
No, I don't have a strong recollection. @David Zearing<mailto:dzearing@microsoft.com> might remember a bit better.  I can say that I was the one to make the change back in August.

https://github.com/OfficeDev/office-ui-fabric-react/pull/2383
[https://avatars0.githubusercontent.com/u/1434956?s=400&v=4]<https://github.com/OfficeDev/office-ui-fabric-react/pull/2383>

Dropdown: Support custom widths by micahgodbolt · Pull ...<https://github.com/OfficeDev/office-ui-fabric-react/pull/2383>
office-ui-fabric-react - React components for building experiences for Office and Office 365.
github.com




Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by micahgodbolt** [comment] 2018-05-30 16:19
added this to our backlog. Will try to get some dev resources on it once the 6.0 work settles down.

**Comment by fexdev** [comment] 2018-05-30 20:09
Cool thanks!

**Comment by dzearing** [comment] 2018-06-11 16:37
@joschect Is this a regression?

**Comment by micahgodbolt** [comment] 2018-06-12 16:40
@dzearing this was an intentional change, though not fully thought through. 

It appears that default browser behavior for selects is to either render above (firefox/chrome) if there isn't enough space, 
![image](https://user-images.githubusercontent.com/1434956/41304311-a19b722e-6e24-11e8-9d14-2c9720867120.png)


or to render on top of the select (Edge) with the bottom edge at the bottom of the page.

![image](https://user-images.githubusercontent.com/1434956/41304336-b009d864-6e24-11e8-8868-7b3445fe42a0.png)

**Comment by micahgodbolt** [comment] 2018-06-12 16:41
So before making this change, we need to determine what is the correct behavior we want to model.

**Comment by micahgodbolt** [comment] 2018-07-20 18:17
Waiting until the dropdown conversion is finished (almost done). Then will update this if it hasn't already been done.

**Comment by dzearing** [comment] 2018-07-31 23:01
@micahgodbolt I believe conversion is complete; are you going to come back here or should we assign to Cliff or Jon?

**Comment by micahgodbolt** [comment] 2018-08-01 05:08
I can do it

**Closed** 2018-08-02 15:17 UTC
Labels: Component: Dropdown, Priority 1: ASAP, Type: Bug :bug:
