### ISSUE TITLE
FocusTrapZone example page bug

### ISSUE THREAD

**Issue by web-warrior** [OfficeDev/office-ui-fabric-react#9633] opened 2019-06-30 08:35 UTC
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 

the demo page breaks all links and left navigation when any o the trap zones have focus
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by khmakoto** [comment] 2019-07-01 17:27
@web-warrior thanks for filing this issue! I can confirm that this is indeed happening in the example page.

@JasonGore I know that this is intended behavior of `FocusTrapZone` given that we're using our own controls to create the website but it does appear to be a bug that the left `Nav` cannot be accessed when focus is trapped. Do you think this should be classified as a bug or that this is by design? If by design, I think we should at least add some notes in the `Overview` section of the control to indicate this behavior so that users aren't caught off guard by it.

**Comment by web-warrior** [comment] 2019-07-01 18:40
I just wondered if this is by design or if in production code you would only disable certain appropriately by targeting... and if so dome discussion around how to target and be specific to context for better ‘control’ over control state.

**Comment by JasonGore** [comment] 2019-07-08 16:16
This is by design. `FocusTrapZone` traps focus for the entire page, and even prevents using keyboard navigation to access browser menus. Ideally browsers would support a method for trapping focus that doesn't exclude browser menus, but until they do, we will use `FocusTrapZone` to approximate.

We've modified the content to try and make this more clear:
![image](https://user-images.githubusercontent.com/26070760/60825535-bf4df380-a160-11e9-96c8-85d84ffa58e0.png)

We might be able to make it more obvious by using `FocusTrapZone` in a popup, but I also think that could make the demo pages more cumbersome.

**Comment by khmakoto** [comment] 2019-07-08 18:31
@web-warrior if there's anything else we can help you with please let us know. If not, feel free to close this issue. Thanks!

**Comment by web-warrior** [comment] 2019-07-08 18:47
Ok, good to know that is intended behavior!  Thank you for the additional explanation.

**Comment by khmakoto** [comment] 2019-07-08 20:44
I'll still make a PR to make this obvious on the component overview that should hopefully help with this confusion.

**Closed** 2019-07-09 20:27 UTC
Labels: Component: FocusTrapZone, Resolution: By Design, Status: In PR
