### ISSUE TITLE
Build error with SPFX @uifabric : error TS1005

### ISSUE THREAD

**Issue by kachihro** [OfficeDev/office-ui-fabric-react#8051] opened 2019-02-20 12:54 UTC
### Environment Information 
 
- __Package version(s)__: 6.141.1
- __Browser and OS versions__: Windows 10 / Chrome
 
#### Actual behavior:

New webpart project using YO generator, with SPFX v1.7.1

When adding <stack> component, or any other Fabric UI component, project won't build ;

Error - [tsc] node_modules/@uifabric/foundation/lib/ISlots.d.ts(68,124): error TS1005: ')' expected.
Error - [tsc] node_modules/@uifabric/foundation/lib/ISlots.d.ts(68,177): error TS1005: '(' expected.
Error - [tsc] node_modules/@uifabric/foundation/lib/ISlots.d.ts(68,185): error TS1005: ':' expected.

Error - [tsc] node_modules/@uifabric/foundation/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,67): error TS1005: ';' expected.
Error - [tsc] node_modules/@uifabric/foundation/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,114): error TS1005: '(' expected.
Error - [tsc] node_modules/@uifabric/foundation/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,136): error TS1005: '(' expected.

Error - [tsc] node_modules/office-ui-fabric-react/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,67): error TS1005: ';' expected.
Error - [tsc] node_modules/office-ui-fabric-react/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,114): error TS1005: '(' expected.
Error - [tsc] node_modules/office-ui-fabric-react/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,136): error TS1005: '(' expected.
Error - 'tsc' sub task errored after 31 s

tslint version: 5.9.1
typescript version: 2.4.2
node 8.12.0

---------------- 

1st error - is within this line (ISlots.d.ts);

export declare type ISlotPropValue<TProps, TShorthandPropType = never> = TShorthandPropType | TProps | (TShorthandPropType extends React.ReactNode ? IPropsWithChildren<TProps> : never);

---------------- 

2nd error - is within this line (IStyleSet.d.ts)

export declare type __MapToFunctionType<T> = Extract<T, Function> extends never ? (...args: any[]) => Partial<T> : Extract<T, Function>;

---------------- 

2nd error - is within this line (IStyleSet.d.ts)

export declare type __MapToFunctionType<T> = Extract<T, Function> extends never ? (...args: any[]) => Partial<T> : Extract<T, Function>;

#### Expected behavior:
 
Project will build - and not trip up on errors within these three (3) files

?? Is this a typescript compiler issue - and code is using 'new' method features ?

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Blocking) 
 
Products/sites affected: (if applicable)
SPFX, webpart project

**Comment by aneeshack4** [comment] 2019-02-20 18:51
@kachihro Can you try updating your Typescript to 2.8.4? This is what office-ui-fabric-react's on so you should be able to compile then.

**Comment by kachihro** [comment] 2019-02-20 22:22
I'm wondering if it's a restriction with SPFX - v1.7...    Other projects, and the scaffold refer to Office UI Fabric React as v5.3.1 - does it mean that we can't include the new components (like Stack) within an SPFX webpart...?    When can we expect an update to SPFX for more recent components ?

**Comment by cliffkoh** [comment] 2019-02-20 22:33
@kachihro I recommend asking this question at https://github.com/SharePoint/sp-dev-docs. The Fabric team is unable to speak for SPFx's release plans unfortunately...

**Comment by cliffkoh** [comment] 2019-02-20 22:34
Duplicate of #7054

**Closed** 2019-02-21 22:41 UTC
Labels: Needs: Author Feedback, Resolution: Duplicate, Resolution: External
