### ISSUE TITLE
feature-request: TimePicker

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#1544] opened 2017-04-18 12:42 UTC
Currently we have DatePicker but don't have time picker so we Used DropDown to build our own time picker.
I see there is another feature request #533 about it. Is there some update on this?

**Comment by kristoferbrown** [comment] 2017-08-10 18:44
Closing as a duplicate of #1565.

**Closed by kristoferbrown** 2017-08-10 18:44 UTC
Labels: feature-request

**Comment by asith-w** [comment] 2019-05-13 05:09
time picker control is an important control. it would be great if it is available
