### ISSUE TITLE
Panel does not have horizontal scrolls

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#3696] opened 2018-01-10 06:57 UTC
No horizontal scroll bars when the zoom level is high.
Steps to repro the issue:
1. Go to  : https://developer.microsoft.com/en-us/fabric#/components/panel
2. Open Custom Panel.
3. When the screen resolution is low(1024 x 768) and browser zoom level is high (200%), the content in the panel is truncated and there is no horizontal scroll bar.

**Comment by micahgodbolt** [comment] 2018-01-12 21:17
its not as much scroll as width vs max width. The panels are absolutely positioned and a hard width is set. If the screen is smaller than the width, the panel overflows. Changing these to max-width should solve the issues. Is this a change you'd be comfortable making? I'd be happy to review the code.

**Comment by JasonGore** [comment] 2018-08-14 20:59
A quick check confirms Micah's suggestion of changing `width` to `maxWidth` works. Just needs some checks to make sure no regressions occur with this fix.

**Comment by JasonGore** [comment] 2018-08-16 16:57
Going to leave this open until #5823 is merged to ensure that the fix still applies.

**Comment by kkjeer** [comment] 2018-08-27 16:28
Closing since #5823 is merged.

**Closed by kkjeer** 2018-08-27 16:28 UTC
Labels: Blocked, Component: Panel, Request: Feature, Type: Bug :bug:
