### ISSUE TITLE
Hovercard need instant dismiss function

### ISSUE THREAD

**Issue by chaofeng2014** [OfficeDev/office-ui-fabric-react#8361] opened 2019-03-18 20:01 UTC
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
If user click actions on hovercard, the focus will be set into the new UX that the action opened, then since hovercard dismiss has 300ms delay, the focus will be set back to the anchor, so the new opened UX will be dismissed. 
![hovercardDismissIssue](https://user-images.githubusercontent.com/6550896/54559507-70940800-497d-11e9-863f-a6098da65729.gif)
 
#### Expected behavior:
 
When user click actions on hovercard, we should be able to dismiss the hovercard instantly. So we need a instant dismiss function from <Hovercard> of fabric.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No
 
Requested priority: (Blocking, High, Normal, Low) 
Normal
 
Products/sites affected: (if applicable)
 ODB, SharePoint

**Comment by khmakoto** [comment] 2019-03-18 20:51
Hi @chaofeng2014, can you provide a codepen with a similar scenario to start looking into this?

@micahgodbolt is this a feature we would be interested in providing?

**Comment by micahgodbolt** [comment] 2019-03-18 22:47
This feels a bit more like a bug actually. It's possible that @atneik might be the best one to handle it, but I'd certainy like to get it resolved vs putting it into the backlog as a feature.

**Comment by atneik** [comment] 2019-03-18 23:17
As the interaction on the HoverCard give rise to another layer on top of it (Sharing Dialog), the HoverCard seem to count it as a MouseOut event and not only tries to dismiss itself but also sets the focus back to the originating target. This is the expected behavior on most common case. I don't think this is a bug, but rather a new feature request to support the given scenario (multi layer).

We can either expose the dismiss function or another idea is to provide a new prop, lets say `setFocusOnDismiss`, which if false doesn't set the focus on target while dismissing. It will be true by default (no breaking change). With this user can update the prop to false if they require to handle the focus by themselves.

**Comment by khmakoto** [comment] 2019-03-25 16:15
@atneik, since this is a feature request on `Hovercard`, would you mind taking over the issue?

**Comment by atneik** [comment] 2019-03-25 23:18
@Vitalius1 and I were talking about this one. He might be better positioned for it as he has more context about HoverCard atm. Does that sound fine @Vitalius1?

**Comment by khmakoto** [comment] 2019-03-26 17:17
I'll remove my assignment of this issue as I see that @Vitalius1 has also been assigned to it.

**Comment by Vitalius1** [comment] 2019-03-26 18:16
Will take look into this and see what I can do later today.

**Closed** 2019-03-28 20:59 UTC
Labels: Component: HoverCard, Needs: Triage :mag:
