### ISSUE TITLE
Can't enable transpileOnly because @uifabric/icons/lib/index isn't generating the IconNames enum correctly.

### ISSUE THREAD

**Issue by justinmwarner** [OfficeDev/office-ui-fabric-react#4232] opened 2018-03-10 00:00 UTC
### Bug Report

- __Package version(s)__: 5.62.1
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Analytics

#### Describe the issue:

For dev builds, we'd like to speed up our build process. To do this, we can enable transpileOnly for ts-loader.  This cuts the time from ~10 seconds to <1 second.  

But we run into an issue with one of the exports from "@uifabric/icons/lib/index".  The exported .d.ts file doesn't generate the IconNames enum.  We narrowed the cause down to the fact that IconNames.d.ts in @uifabric/icons/lib/IconNames.d.ts exports with the word ```declare```.  When this word is removed, the code is compiled correctly and exported correctly in index.d.ts.

#### Actual behavior:

@uifabirc/icons/lib/index.js looks like:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fabric_icons_1 = require("./fabric-icons");
var fabric_icons_0_1 = require("./fabric-icons-0");
var fabric_icons_1_1 = require("./fabric-icons-1");
var fabric_icons_2_1 = require("./fabric-icons-2");
var fabric_icons_3_1 = require("./fabric-icons-3");
var fabric_icons_4_1 = require("./fabric-icons-4");
var fabric_icons_5_1 = require("./fabric-icons-5");
var fabric_icons_6_1 = require("./fabric-icons-6");
var fabric_icons_7_1 = require("./fabric-icons-7");
var fabric_icons_8_1 = require("./fabric-icons-8");
var fabric_icons_9_1 = require("./fabric-icons-9");
var fabric_icons_10_1 = require("./fabric-icons-10");
var fabric_icons_11_1 = require("./fabric-icons-11");
var fabric_icons_12_1 = require("./fabric-icons-12");
var fabric_icons_13_1 = require("./fabric-icons-13");
var fabric_icons_14_1 = require("./fabric-icons-14");
var thing = require("./IconNames");
require("./icon-aliases");
var DEFAULT_BASE_URL = 'https://spoprod-a.akamaihd.net/files/fabric/assets/icons/';
function initializeIcons(baseUrl, options) {
    if (baseUrl === void 0) { baseUrl = DEFAULT_BASE_URL; }
    [fabric_icons_1.initializeIcons, fabric_icons_0_1.initializeIcons, fabric_icons_1_1.initializeIcons, fabric_icons_2_1.initializeIcons, fabric_icons_3_1.initializeIcons, fabric_icons_4_1.initializeIcons, fabric_icons_5_1.initializeIcons, fabric_icons_6_1.initializeIcons, fabric_icons_7_1.initializeIcons, fabric_icons_8_1.initializeIcons, fabric_icons_9_1.initializeIcons, fabric_icons_10_1.initializeIcons, fabric_icons_11_1.initializeIcons, fabric_icons_12_1.initializeIcons, fabric_icons_13_1.initializeIcons, fabric_icons_14_1.initializeIcons].forEach(function (initialize) { return initialize(baseUrl, options); });
}
exports.initializeIcons = initializeIcons;
//# sourceMappingURL=index.js.map
```
Notice at the end, the IconNames export does not exist.

#### Expected behavior:

IconNames export exists in the index.js file.

### If applicable, please provide a codepen repro:

N/A

**Comment by dzearing** [comment] 2018-03-11 20:52
This is pretty unclear about what exactly the problem is. I think in general there is friction in consuming const enums from a library. Basically I think if you dont have `"preserveConstEnums": true,` they will get stripped in your compilation. Or maybe I have that backwards. Basically I *think* we're doing the right thing which is that they should be 0 impact on bundle size, but still provide type safety.

Removing "const" in the enum definition might make your problem fixed, but would also substantially increase bundle size, which is not acceptble.

I *think* I might have an idea of how we can move away from the IconNames const enum.

It is possible we could build the IconNames dictionary at runtime, with minimal bundle size impact by looping through the icon partitions and building up a dictionary and corresponding typescript typing. Basically a tradeoff of minor startup perf for dev convenience. I'm a little unconvinced this is a great idea though.

@justinmwarner have you tried tweaking your tsconfig settings (preserveConstEnums)? Should we perhaps preserveConstEnums for debug builds? Can you be crisp on the ask?

**Comment by justinmwarner** [comment] 2018-03-12 16:21
I have tried adding preserveConstsEnums and still face the issue because this is based on the generated code in office-ui-fabric-react and not our own.

https://github.com/OfficeDev/office-ui-fabric-react/commit/2160f2eb3f73deb473b879273030ed2b737d63a0

In this commit, you added preserveConstEnums to be false for the Icons package to not produce javascript.

We rely on the generated javascript though so we can use the enum directly to give us the string values (that we can pass to getIconClassName and iconName={}).

So my ask is more of clarification on a better way to consume the IconNames enum, to get the string values directly and have the type checking so that we can start using other features. It doesn't sound like we want to change how the file is compiled to start generated javascript again.

Do you know if your alternative to IconNames const enum would solve this issue?

**Comment by dzearing** [comment] 2018-06-21 06:06
@cliffkoh This may be a dupe of another bug i assigned you.

**Comment by justinmwarner** [comment] 2018-08-03 14:02
@dzearing what's the other bug?

And I found a good way for you guys to repro it locally.

Using create-react-app with the typescript config (https://github.com/Microsoft/TypeScript-React-Starter)

Add office-ui-fabric-react.

Now try to use IconNames.

**Comment by kenotron** [comment] 2018-09-04 22:46
@justinmwarner - While we're working to reduce / remove the use of const enums in our codebase, we added `IconNamesInput`. So we should be able to write code this way:

```
<Icon name={'Home' as IconNamesInput} />
```

Sorry, we can't really rip out IconNames enum at this point. Please re-open if this doesn't address the issue for you.

**Closed by kenotron** 2018-09-04 22:46 UTC
Labels: Area: DevExp, Type: Bug :bug:
