### ISSUE TITLE
ExtendedPeoplePicker should pass in autocorrect=off and spellcheck=false to Autofill as native props

### ISSUE THREAD

**Issue by philipzloh** [OfficeDev/office-ui-fabric-react#6470] opened 2018-09-25 21:01 UTC
### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
![image](https://user-images.githubusercontent.com/836760/46042935-7f36ec00-c0cb-11e8-82de-db490ee38587.png)

[spoke with Francis in person]

**Comment by Vitalius1** [comment] 2018-10-01 18:41
@philipzloh ping

**Comment by Vitalius1** [comment] 2018-10-08 23:50
@philipzloh to prevent this issue from closing automatically could you make it more clear if the issue is that you can not use the attributes you mentioned? After a surface investigation only `spellCheck` is already a part of `inputProps`. Are you having issues with using them both or only the `autoCorrect` which is not present at the moment as a native prop?

**Comment by philipzloh** [comment] 2018-10-16 22:12
The code owner is aware of the requirements; the desire is for ExtendedPeoplePicker to set these by default because ExtendedPeoplePicker is used to pick people

**Comment by philipzloh** [comment] 2018-10-17 18:52
@FrancisMengx

**Comment by cliffkoh** [comment] 2018-10-18 20:09
Hey @philipzloh, I'm going to label this good first issue since it seems like it would be relatively straightforward. 

If I am interpreting this thread correctly, @FrancisMengx is the code owner and he is aware of this problem and desires to have it fixed.

**Comment by aleury** [comment] 2018-11-15 06:19
Hi, I'd like to provide a patch for this. 

By "should pass in autocorrect=off and spellcheck=false to Autofill" does that mean that `ExtendedPeoplePicker` should override `autoCorrect` and `spellCheck` regardless of what's being passed in with `inputProps`?

**Comment by philipzloh** [comment] 2018-11-23 23:59
ExtendedPeoplePicker is meant to pick "people". Spellchecking/autocorrecting names here is probably never a good thing. @aleury

**Comment by yumikohey** [comment] 2018-12-04 21:56
@aleury @Vitalius1 
I think we should actually have spellCheck and autoCorrect defaults to false for BasePicker, should it?

**Closed** 2018-12-06 01:35 UTC
Labels: Component: Pickers, Good First Issue 🏆
