### ISSUE TITLE
Bundle font icons

### ISSUE THREAD

**Issue by jonathaneckman** [OfficeDev/office-ui-fabric-react#3586] opened 2017-12-15 21:36 UTC
I have an application that runs offline. Ideally, Id like to bundle all font icons using webpack like I would with other libraries like font awesome. If that is not an option, Id like to output the necessary woff files to my dist folder so they are deployed to the www root and use the `initializeIcons` overload.

Any tips on how I can make something like this happen?

**Comment by cobbs-totem** [comment] 2017-12-22 22:10
I have the same problem:

https://github.com/OfficeDev/office-ui-fabric-react/issues/3186

**Comment by kristoferbrown** [comment] 2018-01-25 23:01
Looks like a duplicate of #3186. Feel free to reopen if these is some other aspect to this issue that isn't covered by the original issue.

**Closed by kristoferbrown** 2018-01-25 23:01 UTC
Labels: bug
