### ISSUE TITLE
PeoplePicker: librarymanagedattributes not working - "Property '[Invalid_defaultProps]' is missing in type"

### ISSUE THREAD

**Issue by IAMtheIAM** [OfficeDev/office-ui-fabric-react#7270] opened 2018-11-30 16:52 UTC
### Environment Information 
 
 
- __Package version(s)__:
  "office-ui-fabric-core": "9.6.1",
    "office-ui-fabric-react": "6.109.0",
    "typescript": "3.2.1",
node: v10.13.0
npm 6.4.1
    "react": "16.6",
- __Browser and OS versions__: (fill this out if relevant)

windows 10
compile time error

#### Actual behavior:

```tsx
<NormalPeoplePicker (props omitted) />
```
Results in type error

```shell
[1] TS2741: Property '[Invalid_defaultProps]' is missing in type '{ onResolveSuggestions: (filterText: string, currentPersonas: IPersonaProps[], limitResults?: number) => IPersonaProps[]; getTextFromItem: (persona: IPersonaProps) => string; key: string; pickerSuggestionsProps: IBasePickerSuggestionsProps; inputProps: { ...; }; onChange: (items: IPersonaProps[]) => void; }' but required in type 'Invalid_defaultProps<Readonly<{ children?: ReactNode; }> & Readonly<IPeoplePickerProps>, { onRenderItem: (props: IPeoplePickerItemProps) => Element; onRenderSuggestionsItem: (props: IPersonaProps, itemProps?: IBasePickerSuggestionsProps) => Element; createGenericItem: (name: string, currentValidationState: Validatio...'.
[1] Version: typescript 3.2.1 
```

If I go into PeoplePicker.d.ts and remove
`        createGenericItem: typeof createGenericItem;` from 

```tsx
export declare class NormalPeoplePicker extends BasePeoplePicker {
    static defaultProps: {
        onRenderItem: (props: IPeoplePickerItemProps) => JSX.Element;
        onRenderSuggestionsItem: (props: IPersonaProps, itemProps?: IBasePickerSuggestionsProps | undefined) => JSX.Element;
        createGenericItem: typeof createGenericItem;
    };
}
```
Then the error goes away. So something is wrong with that in typescripts eyes.

#### Expected behavior:

No error

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (High)

**Comment by aftab-hassan** [comment] 2018-11-30 19:22
@joschect This seems like a bug from using TS 3.2.1. Would you be able to take a look at this?

**Comment by KevinTCoughlin** [comment] 2018-11-30 19:34
> 
> 
> @joschect This seems like a bug from using TS 3.2.1. Would you be able to take a look at this?

Er, it might be better to involve @JasonGore and @cliffkoh if they have some time. Folks, at a glance is this an incorrect typing on our end or a language feature in `typescript@3.2.1` we'll need to do more work to support.

**Comment by JasonGore** [comment] 2018-11-30 22:38
Hmm, at a glance it may be because [`typeof createGenericItem`](https://github.com/OfficeDev/office-ui-fabric-react/blob/71c6f5a7cb3ba6a8ba64c0b5b539db3ba679ffa5/packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePicker.tsx#L65) does not match the [`createGenericItem` prop type](https://github.com/OfficeDev/office-ui-fabric-react/blob/71c6f5a7cb3ba6a8ba64c0b5b539db3ba679ffa5/packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts#L120) but I'm totally theorizing. TS3.x issues so far have seemed to be legitimate issues with Fabric.

**Comment by dzearing** [comment] 2019-01-25 22:20
@aftab-hassan @JasonGore any recommendations here on what to do?

**Comment by aditima** [comment] 2019-03-12 22:03
@cliffkoh @JasonGore - should we be able to use
`createGenericItem?: (input: string, isValid: boolean) => ISuggestionModel<T>;`
instead of 
`createGenericItem?: typeof createGenericItem;`
?

**Comment by cliffkoh** [comment] 2019-03-12 22:05
I'll defer to @JasonGore here as he has been doing far, far more work in Fabric typings in recent months and I've been focused on other projects/other kinds of engineering.

**Comment by JasonGore** [comment] 2019-03-12 22:18
It looks like the code listed in original issue has changed a bit so it's probably worth verifying this is still an issue. For example, `allowPhoneInitials` that appears in my links above no longer appears in master.

In an y case I don't think it's a good idea to duplicate the function type definition since it's already specified in the prop and the use of this function is coerced by the prop definition.

I suspect the issue is conflicting signatures as I mentioned above, so I'd first confirm that's the case. Assuming that's the cause, I'd create a common function type for `createGenericItem` and then use it in the two spots I linked above..

**Comment by KevinTCoughlin** [comment] 2019-03-14 05:14
Yea, these Picker areas / typings were recently modified

**Comment by Adjective-Object** [comment] 2019-03-14 15:04
Looks to me like the defaultProps are not typed correctly, since that IGenericItem and ISuggestedItem types don't seem even related.

I'd have to do another pass after getting into the office - I don't know if there's any casting to IGenericItem under the hood internally. It could be that the actual expected return type is T|ISuggestedItem<T>|IGenericItem

**Comment by micahgodbolt** [comment] 2020-01-02 20:53
@IAMtheIAM has this issue been resolved in recent typescript?

**Closed** 2020-01-09 22:00 UTC
Labels: Area: Typescript, Component: PeoplePicker, Needs: Author Feedback, Status: No Recent Activity, Type: Bug :bug:
