### ISSUE TITLE
Build Issue with 5.71.1 - Property 'monthPicker' of type 'CalendarMonth' is not assignable to string index type 'ReactInstance'.

### ISSUE THREAD

**Issue by Oceanswave** [OfficeDev/office-ui-fabric-react#3281] opened 2017-11-01 11:02 UTC
### Bug Report

- __Package version(s)__: 5.17.1

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Office UI Fabric

#### Describe the issue:

When building with TS, the following error is output:

```
TS error on build:
./node_modules/office-ui-fabric-react/lib/components/Calendar/Calendar.d.ts:23:9
    TS2411: Property 'monthPicker' of type 'CalendarMonth' is not assignable to string index type 'ReactInstance'.
```

#### Actual behavior:

Builds that depend on office-ui-fabric-react fail.

#### Expected behavior:

Builds that depend on office-ui-fabric-react succeed.

**Comment by Oceanswave** [comment] 2017-11-01 11:03
Update title

**Comment by honb** [comment] 2017-11-02 09:33
I had the same issue.
D:\Testing\node_modules\office-ui-fabric-react\lib\components\Calendar\Calendar.d.ts
(22,9): error TS2411: Property 'monthPicker' of type 'CalendarMonth' is not assignable to string index type 'ReactInstance'.

"office-ui-fabric-core": ">=7.1.2 <8.0.0",
"office-ui-fabric-react": ">=4.35.0 <5.0.0",
"typescript": "^2.4.2"

**Comment by aappddeevv** [comment] 2017-11-06 20:00
I just started hitting this today. For me, the problem seemed to be caused by moving to typescript 2.6.1 vs 2.6.0-rc2 but that does not appear to the case for others based on the notes above. It could be some combination of compiler and versions of @types/react.

**Comment by michaelangotti** [comment] 2018-04-11 18:27
We believe this was a temporary issue at the time and will  close this issue. If it still repros for you, please open a new bug.

**Closed by michaelangotti** 2018-04-11 18:27 UTC
Labels: Type: bug, no-recent-activity
