### ISSUE TITLE
Toggle state is changing while clicking on its label

### ISSUE THREAD

**Issue by v-ajrai** [OfficeDev/office-ui-fabric-react#12310] opened 2020-03-16 07:16 UTC
Toggle state is changing while clicking on its label
### Environment Information

OS: Win 10 Enterprise N
Browser:  Edge 

### Describe the issue:

Toggle state is changing while clicking on its label

### Please provide a reproduction of the issue in a codepen:
Link where it is repro
https://developer.microsoft.com/en-us/fabric#/controls/web/toggle

![bug_id_1336507_ui_fabric](https://user-images.githubusercontent.com/62233982/76731737-1db58200-6784-11ea-9cd7-585908b31375.png)

#### Actual behavior:

Toggle state is changing while clicking on its label

#### Expected behavior:

Toggle state should not change while clicking on its label

**Comment by aneeshack4** [comment] 2020-03-16 20:01
@v-ajrai Thanks for reaching out to us! I can see this repro on the website. Looking at the code, the Label seems pretty separate from the Pill but let me investigate further.

**Comment by aneeshack4** [comment] 2020-03-16 20:26
@v-ajrai Actually this was intentional - #8597 description has the details on the text itself and the label enabling the state change. Going to close this as it's resolved by design but please feel free to ping us if you have further questions.

**Closed by aneeshack4** 2020-03-16 20:26 UTC
Labels: Component: Toggle
