### ISSUE TITLE
Pivot component is not mobile friendly like CommandBar

### ISSUE THREAD

**Issue by nsksaisaravana** [OfficeDev/office-ui-fabric-react#11181] opened 2019-11-14 02:57 UTC
#### Describe the feature that you would like added

PivotItems are not mobile-friendly, it looks fine in the desktop but when it comes to the small screens it keeps it original size and it is not re-arranging like commandbar 

#### What component or utility would this be added to

Pivot

#### Additional context/screenshots

Please check the screenshot below, user have to move the screen horizontally to click the other pivot items.

![image](https://user-images.githubusercontent.com/17681573/68822971-81507580-06e6-11ea-875c-7c35d83d2921.png)

**Comment by nsksaisaravana** [comment] 2019-11-14 03:09
CommandBar is responsive to the mobile but Pivot is not mobile responsive.

**Comment by micahgodbolt** [comment] 2019-11-14 21:00
this is a duplicate of a long standing feature request #4066

Our current recommendation is to not use pivots at smaller screen widths. You can use a different control (dropdown or an accordion) to display paged data on smaller screens.

**Closed** 2019-11-18 00:00 UTC
Labels: Resolution: Duplicate
