### ISSUE TITLE
Version 6.x component types don't extend React.Component

### ISSUE THREAD

**Issue by mattmazzola** [OfficeDev/office-ui-fabric-react#8177] opened 2019-03-04 16:37 UTC
### Environment Information 
 
`"office-ui-fabric-react": "6.148.1"`
Chrome: Version 72.0.3626.119 (Official Build) (64-bit)
Windows 10: Version 10.0.17763 Build 17763

### Please provide a reproduction of the bug in a codepen:
 
I'm not sure how to show type errors in the codepen.
I only tested on our product but these steps should reproduce the issue:
1. Create new react app: `create-react-app my-app --typescript`
2. Add `office-ui-fabric-react` package: `npm i office-ui-fabric-react@latest`
3. Try to add example using the `<Modal>`

#### Actual behavior:
 
The new `<Modal>` doesn't extend from `React.Component` which means it doesn't inherit any of the implicit types that are part of being a component such as the `children`

![image](https://user-images.githubusercontent.com/2856501/53747317-d9e12a80-3e57-11e9-8c31-0cc16e3868ef.png)

It is only a function `(props: IModalProps) => JSX.Element` which isn't equivalent:
![image](https://user-images.githubusercontent.com/2856501/53747207-a1d9e780-3e57-11e9-8a16-398c4db74e42.png)
 
#### Expected behavior:
 
In 5.x the `<Modal>` properly extended `React.Component` and thus behaved properly in JSX.

![image](https://user-images.githubusercontent.com/2856501/53747388-ff6e3400-3e57-11e9-9cfc-773ac9cf1635.png)
![image](https://user-images.githubusercontent.com/2856501/53747413-0c8b2300-3e58-11e9-8cc8-c64ffed92e4d.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
**Requested priority:**
Not sure what priority to put.  On one case priority is high because it prevents an upgrade since the types are wrong. We would have persistent errors in VSCode.  On other hand we're working with 5.x ok and aren't completely blocked as we can just continue on this version.
 
**Products/sites affected:**
Conversation Learner

**Comment by KevinTCoughlin** [comment] 2019-03-05 06:09
This issue seems similar to https://github.com/OfficeDev/office-ui-fabric-react/issues/7874#issuecomment-460716298

**Comment by JasonGore** [comment] 2019-03-05 16:23
This is a duplicate of #7874 and will be fixed by #8189. I will mark that PR as resolving this issue.

**Closed** 2019-03-05 16:55 UTC
Labels: Component: Modal, Type: Bug :bug:
