### ISSUE TITLE
Spinner Not Properly Visible in High Contrast Mode

### ISSUE THREAD

**Issue by bmeersma** [OfficeDev/office-ui-fabric-react#12040] opened 2020-02-24 17:34 UTC
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Edge Version 82.0.425.3 on Windows 10

### Describe the issue:

Fabric Spinner is not properly visible in high contrast mode. The spinner looks like a static circle and does not properly convey that the page is loading.

#### Actual behavior:

The Spinner looks like a static circle

#### Expected behavior:

Users can see two parts of the Spinner (a small section that spins around the circle and the circle itself).

**Comment by khmakoto** [comment] 2020-02-24 17:53
Hi @bmeersma, what Fabric version are you using? Using the latest version I can't seem to reproduce this behavior:

![image](https://user-images.githubusercontent.com/7798177/75177663-7648b080-56eb-11ea-8016-5b30f62f8329.png)

**Comment by bmeersma** [comment] 2020-02-24 17:55
Hi,

I’m using the version that is live here: https://developer.microsoft.com/en-us/fabric#/controls/web/spinner

Thanks,

Brian

________________________________

**Comment by khmakoto** [comment] 2020-02-24 17:59
Are you using the old Edge or the new Chromium-based Edge?

**Comment by bmeersma** [comment] 2020-02-24 18:03
I’m using the Chromium based Edge.

________________________________

**Comment by xugao** [comment] 2020-02-24 18:08
@bmeersma - see our issue #11742. we are currently tracking similar bugs with Edge team instead fixing this in our code.

**Comment by bmeersma** [comment] 2020-02-24 18:19
Okay, thanks.

________________________________

**Comment by aneeshack4** [comment] 2020-02-26 19:20
Going to close this since it's being tracked elsewhere

**Closed by aneeshack4** 2020-02-26 19:20 UTC
Labels: Area: Accessibility, Component: Spinner, High Contrast, Resolution: External, Type: Bug :bug:
