### ISSUE TITLE
[Panel] scrollable item inside <ms-Panel-scrollableContent> can not work on IOS mobile browser

### ISSUE THREAD

**Issue by hxltinh** [OfficeDev/office-ui-fabric-react#11343] opened 2019-11-29 10:54 UTC
### Environment Information

- **Package version(s)**: 7.66.0
- **Browser and OS versions**: IOS, Mobile Safari, Mobile Chrome

### Please provide a reproduction of the bug in a codepen:
[Please switch to vertical view](https://codepen.io/hxltinh/pen/povzvoa)

#### Actual behavior:

can not scroll the item list (it behaves normally on normal browsers)

![-private-var-mobile-Containers-Data-Application-862BC3A0-720A-4B89-89D9-3A8F5D7E6F53-tmp-AFB64EBD-C6DD-4E35-B7FA-D524EB75EC34-Image](https://user-images.githubusercontent.com/8114730/69864540-befdf280-12d1-11ea-8de0-62449b70dc3b.jpeg)

#### Expected behavior:

scroll the item list properly

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

**Comment by khmakoto** [comment] 2019-12-02 21:44
Hi @hxltinh, thanks for filing this issue! I've checked on an iOS device and I cannot seem to reproduce the issue you're dealing with in the codepen you provided. Here is a screenshot taken in an iPhone 6S where the Panel's content is scrolled as you can see by the lack of the `----` in the first `this is child` item:

![Panel](https://user-images.githubusercontent.com/7798177/69997796-c6a7dc00-1509-11ea-98f8-e863ab611be7.jpg)

**Comment by hxltinh** [comment] 2019-12-03 02:56
Hi @khmakoto kh
I guest that the content inside <ms-Panel-scrollableContent> is scrolled, it's not the content inside <parent> is scrolled. 
Please have a look with Ipad or reduce the height of <parent>.

**Comment by laiprorus** [comment] 2019-12-04 13:51
I think this is related to this #8855

**Comment by khmakoto** [comment] 2019-12-04 18:48
Thanks @laiprorus! @hxltinh as you can see, this is actually a duplicate of #8855, so I'll be marking this issue as such so that we can have the larger conversation in one place.

**Comment by hxltinh** [comment] 2019-12-06 06:13
Thanks @khmakoto, @laiprorus I shall inform our team about this :)

**Comment by khmakoto** [comment] 2019-12-06 18:53
No problem @hxltinh! Feel free to reach out again if you need anything else!

**Closed** 2019-12-10 00:00 UTC
Labels: Component: Panel, Needs: Author Feedback, Resolution: Duplicate, Type: Bug :bug:
