### ISSUE TITLE
Dialog control has a light pink bubble around it in certain monitors

### ISSUE THREAD

**Issue by shreedhart** [OfficeDev/office-ui-fabric-react#11764] opened 2020-01-22 21:05 UTC
### Environment Information

- **Package version(s)**: 7.78.1
- **Browser and OS versions**: Chrome and Edge Dev Preview on Windows 10.

### Please provide a reproduction of the bug in a codepen:

1. Open https://fabricweb.z5.web.core.windows.net/oufr/7.84.0/#/examples/dialog
2. Click on "Open Dialog" button in Default Dialog sample.

#### Actual behavior:
Dialog has a pinkish bubble around it. Repro in Dell monitor U2717D. No repro in Dell curved screen monitor.

![image](https://user-images.githubusercontent.com/9101715/72930861-b7772a80-3d11-11ea-9146-7cd2eef2f30a.png)

#### Expected behavior:

No pink bubble. The gray shadow is still expected.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment] 2020-01-22 21:26
Hi @shreedhart, thanks for filing this issue. Unfortunately, I cannot seem to reproduce this behavior, even after trying on 3 different monitors. Given that this is only reproducing in some monitors I think this might do with the color configuration in them and not with the control itself, especially because I double checked on the color values we're using in the dialog and nothing seems to be related to pink. Would you mind playing with your monitor's color configuration to see if this changes what you're seeing? Thanks!

**Comment by khmakoto** [comment] 2020-01-27 19:21
Hi @shreedhart, after talking with design they say that this is by design and that the behavior you're experiencing is more likely than not related to the monitors and we shouldn't make changes to styling based on specific hardware configurations. I'll be resolving this as `Resolution: By Design` given the previous reasons. If you have any other issues please let me know. Thanks!

**Comment by shreedhart** [comment] 2020-01-29 18:41
@khmakoto This issue doesn't repro in v6. This is a regression introduced in v7. Also I am not using any custom color profiles in my monitor. I understand that it is not possible to change styles based on issue in one specific monitor. I am fine with resolving as By Design. This can be re-visited if there are more reports of this issue. Meanwhile, I will be updating the style in my app to match the v6 style.

**Comment by khmakoto** [comment] 2020-01-29 21:00
Hi @shreedhart the `box-shadow` styling in Fabric 7 is different from that one in Fabric 6, which is why you notice the difference. However, the colors we're using are to spec.

**Closed** 2020-01-30 22:00 UTC
Labels: Component: Dialog, Resolution: By Design, Resolution: Not An Issue
