### ISSUE TITLE
Using the Tab Key in a details list does not work.

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#1893] opened 2017-05-31 18:12 UTC
Hi, I have A details list set up like this:

```
        <DetailsList
          layoutMode={DetailsListLayoutMode.fixedColumns}
          selectionMode={SelectionMode.single}
          items={this.state.timeSpents}
          setKey="tsId"
          columns={[
            {
              key: "hoursSpent", name: "hoursSpent", fieldName: "hoursSpent", minWidth: 100,
              onRender: (item?: any, index?: number, column?: IColumn) => <TextField
                value={item.hoursSpent}
              />
            }
          ]}
        />

```
It renders a single TextField for each row, When I enter info into the first texbox and then click the tab key, the focus goes to a control outside of the Details list. I would expect it to jump to the next TextBox in the Details list. I tried adding tabIndex={index} to the  TextFields , but that did not help. 

Looking at the page in chrome tools , I see that the tabindex of the TextBoxes are always set to -1.

Is there a way to have the tan key jump to the next input control on the Details List?

**Comment by betrue-final-final** [comment] 2017-05-31 18:31
It's a list, which uses arrows, and not a form. You never know how many items will be in a list, so using tabs is not scalable for them. Are you sure you need a list for this?

**Comment by dzearing** [comment] 2017-06-01 05:37
This is by design. As @betrue-final-final mentioned, the list is defined for rendering content. Yes, you can include text fields in the cells. If you arrow left/right, it will actually automatically jump between them. Which is very natural for buttons/links in the row, but not as much for textfields.

There is demand for a more data table component. We have this in our backlog, but no definitive date for when that drops.

**Closed by dzearing** 2017-06-01 05:37 UTC
