### ISSUE TITLE
PivotItem is not rendering

### ISSUE THREAD

**Issue by v-sosah** [OfficeDev/office-ui-fabric-react#6294] opened 2018-09-10 06:56 UTC
### Please provide a reproduction of the bug in a codepen:
 

In CodePen it is working fine ,but when we install package (office fabric) from npm and paste the sample code given on the office fabric site. it does not work.
### Bug Report 
 
 
- __Package version(s)__: (6.25.3) 
- __Typescript version:- Version 2.4.1
- __Webpack version:- 4.12.0

- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  High
 
Products/sites affected: (if applicable) Modern CMS
 
#### Describe the issue:
 

I am consuming office fabric in typescript based react application(Modern CMS). My installed “office-ui-fabric-react” version is 6.25.3. 
On my end the pivot is neither rendering nor throwing an error on browser console. However I pasted sample code given on the office fabric ui site. When I looked into the code then I found on the 
Pivot.base.js, method name “_getPivotLinks” , line no: 134  there is a type compare code check . so that was causing the problem . 
 
The code was child.type === PivotItemType
 
And I changed that to child.type.constructor === PivotItemType. Constructor then its started working. 

 
#### Actual behavior:
 It is not rendering the pivot items.

 
#### Expected behavior:
 it should render the pivot items

**Comment by micahgodbolt** [comment] 2018-09-10 14:17
Looks like swapping out PivotItemType with PivotItem does the trick. It's how we compare children in all other instances. Not sure why we drilled down into the Child's type in this case.

**Comment by KevinTCoughlin** [comment] 2018-09-11 00:53
Yea not sure.. seems to work for me with:

```diff
@@ -211,7 +203,7 @@ export class PivotBase extends BaseComponent<IPivotProps, IPivotState> {
     this._keyToTabIds = {};

     React.Children.map(props.children, (child: any, index: number) => {
-      if (typeof child === 'object' && child.type === PivotItemType) {
+      if (child && child.type === PivotItem) {
         const pivotItem = child as PivotItem;
```

But `master` also works unless I'm misunderstanding this thread. The only context I see re: that check is #4867.

**Comment by micahgodbolt** [comment] 2018-09-11 02:52
I was getting errors with that was in master and success with the testing of child.type === PivotItem.

**Comment by KevinTCoughlin** [comment] 2018-09-18 23:01
@v-sosah can you pull latest once it publishes with the linked change and see if it fixes your scenario?

**Comment by KevinTCoughlin** [comment] 2018-09-19 17:07
Spoke with @v-sosah off thread and this is still occurring. Will take another pass at it.

**Comment by v-sosah** [comment] 2018-09-28 05:40
Hello Office Fabric Team,

May we expect an ETA for this bug, as our product is about to go for public preview.

Thanks,

**Comment by Vitalius1** [comment] 2018-10-02 01:06
@v-sosah I was able to reproduce the issue in [HERE](https://github.com/OneCyrus/react-hot-loader-bugrepro), but the funny thing is that if I use a different component (ex: Dialog with DialogFooter) which uses the same type of comparison it's all working as expected.
@cliffkoh @kenotron any ideas? Why only Pivot is not playing well?

**Comment by KevinTCoughlin** [comment] 2018-10-04 07:08
Also stumped by this. Potentially related to https://github.com/gaearon/react-hot-loader/issues/304#issuecomment-223222772

**Comment by KevinTCoughlin** [comment] 2018-10-04 20:05
> 
> 
> @v-sosah I was able to reproduce the issue in [HERE](https://github.com/OneCyrus/react-hot-loader-bugrepro), but the funny thing is that if I use a different component (ex: Dialog with DialogFooter) which uses the same type of comparison it's all working as expected.
> @cliffkoh @kenotron any ideas? Why only Pivot is not playing well?

Here are the comparisons in the built scripts for additional context:

https://unpkg.com/office-ui-fabric-react@6.78.0/lib/components/Pivot/Pivot.base.js

```js
var PivotItemType = React.createElement(PivotItem, null).type;
...
if (typeof child === 'object' && child.type === PivotItemType) {
```

https://unpkg.com/office-ui-fabric-react@6.78.0/lib/components/Dialog/DialogContent.base.js

```js
var DialogFooterType = React.createElement(DialogFooter, null).type;
...
if (typeof child === 'object' && child !== null && child.type === DialogFooterType) {
```

https://unpkg.com/@uifabric/experiments@6.34.2/lib-commonjs/components/Stack/Stack.js

```js
var StackItemType = React.createElement(StackItem_1.default, null).type;
...
if (child.type === StackItemType) {
...

**Comment by khmakoto** [comment] 2018-10-29 23:30
@KevinTCoughlin tracking it down in the debugger, I see that `child.type` evaluates to a `PivotItem` function and PivotItemType does the same thing. Actually, adding `toString()` at the end of both fixes the rendering issue.

Judging from this, it appears they are referencing two different equivalent functions, which evaluates to false in JavaScript. Do you have any idea why this may be happening?

**Comment by khmakoto** [comment] 2018-10-30 17:54
@v-sosah Can you confirm if this is still happening? I cannot repro it anymore when using the latest office-ui-fabric-react version.

**Comment by khmakoto** [comment] 2018-10-30 21:43
@v-sosah can you try reproducing the bug using the latest version of Fabric? I was able to repro it at the beginning using the example @Vitalius1 kindly gave us. However, when using the latest version of Fabric I couldn't repro it anymore. For reference, [THIS](https://github.com/khmakoto/react-hot-loader-bugrepro) is the same example @Vitalius1 provided while using the latest version.

**Comment by khmakoto** [comment] 2018-11-02 16:33
Closing this as I cannot repro the bug and have received no answer from original poster regarding if they are still having the issue.

Please reopen if this surfaces again.

**Closed by khmakoto** 2018-11-02 16:33 UTC
Labels: Component: Pivot, Type: Bug :bug:
