### ISSUE TITLE
Slight outline around PeoplePicker image if Persona.initialsColor is also set

### ISSUE THREAD

**Issue by DianeD** [OfficeDev/office-ui-fabric-react#637] opened 2016-11-30 22:50 UTC
### Bug Report

- __Package version(s)__: 0.78.0

#### Describe the issue:

I'm making two calls to get people and pics for the PeoplePicker. 

1. The first call gets the user collection with users' metadata. Then I set Persona attributes, including Persona.imageInitials and Persona.initialsColor in case there's no profile pic or a problem retrieving it.
2. The second call gets each user's profile pic. If successful, I set Persona.imageUrl.

#### Actual behavior:

The profile pic in the picker image renders with ~1 pixel wide outline.

Easy workaround: Set initialsColor = null when I set the imageUrl, or set it if image retrieval fails.

#### Expected behavior:

No extra work to have a fallback visual display for the image.

**Comment by joschect** [comment] 2016-12-26 01:46
@DianeD Hi, I'll take a look at this.

**Comment by joschect** [comment] 2017-01-09 19:58
@DianeD It's interesting, the size of the image overlay, and background are the same, yet the background shows through. When I get some cycles I'll have to make the background imageInitials either conditional or have the color be not set when the image loads.

-Jon

**Comment by MLoughry** [comment] 2017-01-18 18:00
This is a dupe of #812, and was resolved by #816

**Closed by MLoughry** 2017-01-18 18:00 UTC
Labels: bug
