### ISSUE TITLE
Narrator treats table rows with "SelectionMode.none" as selectable

### ISSUE THREAD

**Issue by clmori** [OfficeDev/office-ui-fabric-react#11240] opened 2019-11-19 01:02 UTC
### Environment Information

- Package version(s): 7.60.1
- Browser and OS versions: Microsoft Edge 44.18362.449.0

### Describe the issue:

When the user tabs into the table row set as "SelectionMode.none" with narrator, it announces the row as "(Row item) Not Selected".  Since the row is not selectable, it should not say "Not selected".

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/Rafi_Mohammed/pen/zYYJLZW

#### Actual behavior:

In the codepen example above, narrator says: "Item 0, 0. Not selected."

#### Expected behavior:

In the codepen example above, narrator should say: "Item 0, 0."

**Comment by aneeshack4** [comment] 2019-11-20 00:02
@clmori I'm able to repro this but I think this is behaving as intended - it's simply reading out "Not selected" because that is the state of the element Narrator has focus on. I'm not aware of any way to get Narrator to say "Unselectable" or to override it's behavior and make it say "Not selected" when that is exactly what accurately describes the state of the element that currently has keyboard focus.

**Comment by clmori** [comment] 2019-11-20 00:42
@smhigley thoughts on the intended behavior?

**Comment by smhigley** [comment] 2019-11-20 20:53
I agree with @aneeshack4, I don't see anything in the markup that indicates selectability, so this seems like an issue on Edge or Narrator (or hold off at least until Edge officially releases on Chromium).

Mapping things like selection patterns and edit patterns on the grid role are still getting ironed out (NVDA thinks all grid cells are editable unless the grid is explicitly marked `readonly`, for example), so it doesn't entirely surprise me that Narrator/Edge would have a similar issue.

Thanks for looking into this!

**Comment by aneeshack4** [comment] 2019-11-20 21:24
Cool I'm going to close this issue then since it's external.

**Closed by aneeshack4** 2019-11-20 21:24 UTC
Labels: Area: Accessibility, Component: DetailsList, Needs: Attention :wave:, Priority 3: Fit and finish
