### ISSUE TITLE
'Esc' keyboard event propagation doesn't get prevented in combobox when using knockout

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#10738] opened 2019-10-08 13:18 UTC
### Environment Information

- **Package version(s)**: the latest verion of 6
- **Browser and OS versions**: Chrome, windows10

### Describe the issue:

Hi,

I had an issue that in a repro which using the knockout. We have an panel, inside it there is a combobox. When open panel -> navigate to combobox -> use keyboard to open the list -> press 'Esc" keyboard. Both the combobox and panel will get closed. I tried to repro it with the your pages [demo](https://codepen.io/keirayang/pen/vYYEbQB), but failed. I have no example here, but if you have any idea about why this happen and how to fix it. That's would be great! Thanks so much for the help!

#### Actual behavior:

Press 'Esc' to close combobox list will also close the panel which lay on.

#### Expected behavior:

Press 'Esc' should only close combobox, panel should keep open.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment] 2019-10-08 19:02
Without a repro, it's really not possible for me to help figure out what's going on. Just to confirm, is your actual code using the Fabric React Panel, or some other panel component? And if you're using the Fabric Panel, have you verified that you're passing in the same panel props in the codepen as you're using in your actual code?

If you're using the Fabric Panel, and the issue doesn't repro in the codepen when using the same panel props as your real code, it must be caused by some other keyboard event handling code on your page (which is out of scope of what we can help with).

**Comment by KeiraYang** [comment] 2019-10-10 12:11
Thanks @ecraig12345 for reply! Yes. It's not using Fabric panel, it's a div which role is "dialog". And this div is inside an iframe.

**Comment by ecraig12345** [comment] 2019-10-10 19:10
I *suspect* that the issue has to do with mixing React events and native DOM events. Knockout is probably using native event handlers, which (in most cases) are run *before* any React event handlers. As shown in [this codepen](https://codepen.io/ecraig12345/pen/RwwWLpY), although the ComboBox properly catches the React event for the escape key and stops its propagation, it's too late to stop the native event. [This article](https://fortes.com/2018/react-and-dom-events/) has more info about the issue.

Since the ComboBox is properly handling the React event, and interoperability with native events is outside the scope of what we support, I'm going to resolve this issue as external.

**Comment by KeiraYang** [comment] 2019-10-14 02:11
Thanks @ecraig12345. Our level is, We're using the Fabric panel as container, then the iframe as children. The combobox is inside iframe thus has the issue. But we also have Dropdown component which seems has similar event handler. But Dropdown works well, press 'Esc' won't close the panel. Any idea for why the different behavior for the Combobox and Dropdown? Thanks so much!

**Comment by KeiraYang** [comment] 2019-10-14 06:31
Hi @ecraig12345 I used your demo and replace the ComboBox component with Dropdown in [this codepen](https://codepen.io/keirayang/pen/YzzwoyR). Dropdown component stopped the native event propogation as in the example when press "Esc". Thus I think the ComboBox component should stop it as well just like Dropdown. Additional, I found the suggestion list width is different between ComboBox and Dropdown, is this by design? [Looks odd for me]

![image](https://user-images.githubusercontent.com/28148759/66732533-eff3a680-ee8e-11e9-9f03-1a5ae5a0f3ab.png)

![image](https://user-images.githubusercontent.com/28148759/66732522-e36f4e00-ee8e-11e9-8156-d7a37ffc0fb5.png)

**Comment by ecraig12345** [comment] 2019-10-15 00:06
Talked with @dzearing about this and he actually thinks it's odd that *any* of our components are interfering with native events. His recommendation is if you want native events caught, you should write a wrapper to handle that.

I also noticed that if I add an event listener to the body, Dropdown's key events *do* propagate to there (see [updated codepen](https://codepen.io/ecraig12345/pen/RwwWLpY)). So it's possible the reason the events didn't appear to propagate to the wrapper div is that the Dropdown's menu is not actually attached to that div.

**Comment by ecraig12345** [comment] 2019-10-15 00:09
For the ComboBox menu width, you can force it to match the field width by setting the `useComboBoxAsMenuWidth` prop to true. (I agree it's odd that's not the default, but it's not something we're going to change except as part of a full ComboBox rewrite.)

**Closed** 2019-10-22 02:00 UTC
Labels: Component: ComboBox, Needs: Author Feedback, Resolution: External, Status: No Recent Activity

**Comment by KeiraYang** [comment] 2019-10-31 12:46
@ecraig12345 Sorry I have to open the bug again. I've found the root cause why ComboBox cannot stop the 'esc' event propagation. I have no solution to fix it now which need your great help. The issue is, when the combobox menu is opened, the event target is not the callout but the input element. Thus the event will bubble to the parent -> ... -> body -> document. As there's event handler assocatied to the ancestor which catch the 'Esc' event and perform the panel close action. Thus panel got closed before ComboBox get the event as React event handler will always later than the native event. For the scenario, I want the div get the event later than the ComboBox get the event but seems I don't have place to do that. Any idea? [The codepen.](https://codepen.io/keirayang/pen/ZEEaKKd?editors=0010)
![image](https://user-images.githubusercontent.com/28148759/67947142-e8b5f200-fc1d-11e9-9d08-dde1ecf29f12.png)

For Dropdown component, it has no such issue because the current event target is not the input element, but the layer element which the event won't bubble to the element handle the panel close action.
![image](https://user-images.githubusercontent.com/28148759/67947634-05065e80-fc1f-11e9-9d10-49c0fdc457ac.png)

Thanks in advance!

**Comment by KeiraYang** [comment] 2019-10-31 12:49
@ecraig12345 Are the issue is auto-closed. I cannot re-open it. Could you help reopen it if you can? Thank you

**Comment by ecraig12345** [comment] 2019-10-31 23:14
Sorry but since mixing React and native events is not a scenario we really support, this is not something I can prioritize investigating or trying to fix. Though if you want to look at the ComboBox code yourself and submit a fix (without regressing the behavior in the primary scenario of React events only), you're welcome to do that.
