### ISSUE TITLE
"Infinite" loop in DocumentCardTitle

### ISSUE THREAD

**Issue by PerthCharern** [OfficeDev/office-ui-fabric-react#6241] opened 2018-09-05 19:45 UTC
### Please provide a reproduction of the bug in a codepen:
 
- Create a document card title (https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx) with shouldTruncate being `true`.

- Give the component a very long title

- Keep resizing the component. 

### Bug Report 
 
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

componentDidUpdate -> _shrinkTitle -> setState which then triggers render and componentDidUpdate again.

If this loop happens enough time before the title is truncated enough, React throws an error that maximum update depth exceeded.

- __Package version(s)__: 6.29.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? I'm unsure of the issue and fix at this point. If I'm confident enough at some point, yes.
 
Requested priority: Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

componentDidUpdate -> _shrinkTitle -> setState which then triggers render and componentDidUpdate again.

If this loop happens enough time before the title is truncated enough, React throws an error that maximum update depth exceeded.
 
#### Actual behavior:
 
Maximum update depth exceeded. 
 
#### Expected behavior:
 
No error.

**Comment by micahgodbolt** [comment] 2018-09-05 20:45
duplicate of #5308

**Closed** 2018-09-05 20:45 UTC
