### ISSUE TITLE
Accessibility: Tab keeps looping inside Lists

### ISSUE THREAD

**Issue by Khushveerkaur** [OfficeDev/office-ui-fabric-react#4024] opened 2018-02-20 07:51 UTC
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: NA

#### Describe the issue:
The bug was found during the accessibility testing for our page, where it was noticed that while keyboard navigation, on entering the ms-contextual list, the tab keeps looping inside the list rather than navigating to the next element.
![temp1519022910285](https://user-images.githubusercontent.com/36656468/36412474-7ca81530-1640-11e8-9e3c-ede1cf02bffc.png)
![temp1519023251701](https://user-images.githubusercontent.com/36656468/36412499-8daabdc4-1640-11e8-9f06-85d7b1a5353c.png)
![temp1519023167615](https://user-images.githubusercontent.com/36656468/36412500-8dd07ab4-1640-11e8-9415-a1029a63782c.png)

**Comment by michaelangotti** [comment] 2018-04-30 23:54
@Khushveerkaur Can you provide a repro and let us know which component you are referring to.

**Comment by michaelangotti** [comment] 2018-05-23 22:19
@Khushveerkaur Is this still an issue? If so, please provide a repro so we can investigate further. If not, we will close this in a few days since there hasn't been any response. Thanks!

**Comment by Khushveerkaur** [comment] 2018-05-24 08:44
@michaelangotti We are using the component: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx 
and on pressing tab inside the list, it never comes out, it keeps looping inside. 
If you see the attached image, you will see pressing tab takes you to the first item, then second, third and fourth. After fourth, if I press tab again, it should ideally take me out of the list, rather it navigates back to the first item in the list.

![image](https://user-images.githubusercontent.com/36656468/40474343-65a924c2-5f5c-11e8-8f73-cfd29e709a91.png)

**Comment by betrue-final-final** [comment] 2018-05-24 21:59
This is by design and expected behavior for menus since the dawn of Windows. Try it out!

**Closed by betrue-final-final** 2018-05-24 21:59 UTC
Labels: waiting-for-author
