### ISSUE TITLE
[Request] Add social icons

### ISSUE THREAD

**Issue by webdes03** [OfficeDev/office-ui-fabric-react#10634] opened 2019-09-26 16:17 UTC
#### Describe the feature that you would like added

Add social icons (Twitter, Facebook, Instagram, etc) to the Office UI Fabric Icons collection.

#### What component or utility would this be added to

Icons

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Today, it's impossible to build any social component using Office UI Fabric without including multiple font packages. This creates additional complexities as multiple packages are used and icons have to be pulled from different packages, as well as variation in the Office UI Fabric design language. Adding a collection of brand icons will reduce the number of dependencies in many solutions.

**Comment by joschect** [comment] 2019-09-27 23:45
@webdes03 Thanks for submitting this request. @Jahnp should be able to help out here.

**Comment by Jahnp** [comment] 2019-09-30 15:42
Hi @webdes03 , thanks for the feedback and request. I hear your pain and wish I had an easy solution today.

We actually _do_ have icons for several social media sites available on an internal version of the Fabric icons tool—which Microsoft apps can use—but unfortunately we don't have permission today to redistribute them, since the designs belong to their copyright owners.

That said, this is the message I was given several years ago, and I'm not sure if the guidance has changed. I can bring this up again.

Which social media sites would you be most interested in if it does work out?

**Comment by webdes03** [comment] 2019-09-30 17:48
Facebook, Twitter, YouTube, LinkedIn, and Instagram would be the big ones we use frequently. Today we're forced to include FontAwesome to gain access to those icons.

**Comment by xugao** [comment] 2020-02-06 02:03
tracking this request in #11886 together with other similar requests. closing this one as dup

**Closed by xugao** 2020-02-06 02:03 UTC
Labels: Area: Icons, Type: Feature

**Comment by ecraig12345** [comment] 2020-02-26 20:55
@Jahnp can confirm, but I don't think we're allowed to distribute icons of other companies' products for licensing/legal reasons.

**Comment by Jahnp** [comment] 2020-02-26 20:56
@ecraig12345 is correct. Apologies for the delay. I confirmed that we still have this constraint on us.
