### ISSUE TITLE
Ambient const enums are not allowed when the '--isolatedModules' flag is provided (Remove last const enum in IconNames.d.ts)

### ISSUE THREAD

**Issue by BTC-Bradley** [OfficeDev/office-ui-fabric-react#8003] opened 2019-02-14 21:11 UTC
Hi Microsoft UI Fabric team,

This is a follow up to #7110 where @micahgodbolt mentioned opening a new issue to track the last use of const enums which is causing this error.  The bug seems to have fallen through the cracks and I hope opening this new issue will help to resurface it and get it fixed.

Based on other discussions around this topic, I can see that @kenotron and others have spent a lot of time and effort in removing all the const enums from the library - this issue is to track removing the last remaining usage within `IconNames.d.ts`

Thanks,
Bradley

**Comment by JasonGore** [comment] 2019-02-14 21:31
We are considering `IconNames` to be deprecated with no easy path for resolving const enum usage and recommend using icon strings instead. I know #7110 hasn't had activity recently but this is technically a duplicate of that issue. I'll mark this one a duplicate, but in the meantime we're going to update #7110 to more clearly indicate overall const enum status. Thanks!

**Closed** 2019-02-15 20:14 UTC
Labels: Needs: Author Feedback, Resolution: Duplicate
