### ISSUE TITLE
Extra empty div class added (which leaves the list with more white space below the last row)

### ISSUE THREAD

**Issue by NivedhaChellam** [OfficeDev/office-ui-fabric-react#10968] opened 2019-10-25 03:42 UTC
### Environment Information

- **Package version(s)**: ("office-ui-fabric-react": "^5.43.1",)
- **Browser and OS versions**: (Edge 44.19002.1.0and Chrome 77)

#### Actual behavior:
Lots of white space before the button, which is happening due to the extra div
![image](https://user-images.githubusercontent.com/53238750/67541638-88173a00-f69e-11e9-8ae8-11de77019a79.png)

#### Expected behavior:

Extra div shouldn't be loading

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)
Additional validations tab in mseng account Pull Request

**Comment by kenotron** [comment] 2019-10-25 17:03
Can you please add a repro codepen here? The extra div is actually by design otherwise - to give scroll bar something to scroll to since this is a virtualizing list. If you do not need virtualization, simply render the items yourself without the List component.

**Comment by KevinTCoughlin** [comment] 2019-10-25 20:26
> The extra div is actually by design otherwise - to give scroll bar something to scroll to since this is a virtualizing list. If you do not need virtualization, simply render the items yourself without the List component.

Alternatively, the `onShouldVirtualize={() => false}` prop on `DetailsList` should disable virtualization and remove the need for that DIV. We cannot remove that DIV otherwise as it is there by design for scrollbar height.

**Comment by NivedhaChellam** [comment] 2019-10-25 21:19
Thanks Ken for the details. After Ken's explanation I ended doing the DOM  manipulation and it worked.

Thanks Kevin  `onShouldVirtualize={() => false}` worked well, no need to do the hack. 
 ```
public componentDidMount(){

        // Do a set timeout because React's componentDidMount method calls before components rendered.

        // Hack : To fix the Gap between the last validation and the queue button in Additional Validations extension => Set the height to 0px.

        setTimeout(() => {

            $("div.ms-List-page:not(:has(*))").css('height', '0px')}, 50);      

    }
```

**Comment by jdhuntington** [comment] 2019-10-28 21:49
Thanks for following up @NivedhaChellam - will close this issue; have a good one!

**Closed by jdhuntington** 2019-10-28 21:49 UTC
Labels: Component: List, Needs: Attention :wave:, Resolution: By Design
