### ISSUE TITLE
CommandBar items do not collapse when offset from left edge

### ISSUE THREAD

**Issue by danmarshall** [OfficeDev/office-ui-fabric-react#9296] opened 2019-05-31 03:35 UTC
In this example are 2 CommandBars, the top one is full width and collapses correctly.
The bottom one is offset from the left and incurs a horizontal scrollbar on the page.
![image](https://user-images.githubusercontent.com/11507384/58679663-5e3d2f80-8319-11e9-9f8f-ec3042849034.png)

Note: you may need to use the developer tools to set the page width to a very small size.

### Environment Information 
 
- __Package version(s)__: 6.187.1
- __Browser and OS versions__: Chrome/Windows 10

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/danmar/pen/gJQWJM
 
#### Actual behavior:
 
Items do not collapse in a CommandBar offset from the left.
 
#### Expected behavior:
 
Items collapse according to the space available, as the behavior works in a CommandBar which is the full width.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: https://microsoft.github.io/SandDance/app/

**Comment by leddie24** [comment] 2019-05-31 18:06
@danmarshall, thanks for submitting this issue. I can't seem to repro this on my browser (using Chrome, OSX)

![image](https://user-images.githubusercontent.com/1291968/58725458-098aca80-8394-11e9-802a-7c1e519818dd.png)

@micahgodbolt , is this reproable for you?

**Comment by danmarshall** [comment] 2019-05-31 18:56
@leddie24 Thanks for checking it. So, it does work correctly on a refresh, for a first time render. It does not work correctly on a resize. Also, I'm on Windows 10. BTW it behaves somewhat better in Firefox, but it's still not perfect.

**Comment by micahgodbolt** [comment] 2019-05-31 23:27
Ok, so the problem is that command bar measures to see if it fits in the available space, and if it does, it stops moving items into the overflow. Due to the "auto" nature of the grid element it is in, the command bar THINKS that it fits. It's a chicken or egg problem. Auto means "be as large as needed", and command bar says "only be as big as possible".  This problem happens with flexbox as well.

The key is to give the column some absolute value, even a percentage works:
```css 
grid-template-columns: 20% 80%;
```

The other option is to make whatever you need in "left" to be the 1st item in the command bar.

**Comment by micahgodbolt** [comment] 2019-05-31 23:29
@leddie24 could we add a "don't" on the flexbox page to say "don't use flexbox in an auto-sized container (like grid or flexbox) because the parent size needs to be a fixed width before command bar starts to resize ".

**Comment by danmarshall** [comment] 2019-05-31 23:50
@micahgodbolt I would like to have a custom first Item in the tool bar, but I couldn’t figure out how to do it.

**Comment by micahgodbolt** [comment] 2019-06-01 00:34
Each item can take an onRender prop. The width of this content will be used when considering if the command bar fits or not

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by danmarshall** [comment] 2019-06-04 00:12
I got it working by having this structure:
```html
<div style={{ position: 'relative', height: '32px' }}>
    <div style={{ position: 'absolute', left: 0, right: 0 }}>
        <CommandBar />
    </div>
</div>
```
I can close this if you'd like, given the workaround. Thanks for the help @micahgodbolt !

**Comment by micahgodbolt** [comment] 2019-06-04 03:47
Sounds good :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Closed** 2019-06-04 04:31 UTC
Labels: Component: CommandBar, Needs: Triage :mag:
