### ISSUE TITLE
Tooltip: Narrators unable to read the text inside the tooltip

### ISSUE THREAD

**Issue by akashperfect** [OfficeDev/office-ui-fabric-react#900] opened 2017-01-27 12:32 UTC
### Bug Report

- __Package version(s)__: (fabricreact website, latest version 1.3.3)
- __Browser and OS versions__: (Chrome, IE, Firefox, on Windows 10)

#### Describe the issue:

On hovering or tabbing over the element where tooltip is applied. The tooltip is getting displayed fine however, the narrator is not announcing the text being displayed on the tooltip

#### Actual behavior: 

Narrator is only saying the visible text on element and not the tooltip text

#### Expected behavior: 

Narrator should first say the text on element then announce the tooltip text. I tested this with I.E and windows narrator and Firefox with NVDA narrator on chrome doesn't work in general with narrator

**Comment by mdahamiwal** [comment] 2017-01-27 14:05
This was fixed by #695, can you verify with latest version ? Thanks

**Comment by dzearing** [comment] 2017-02-01 01:13
@akashperfect ping; can you verify? Want to make sure we can resolve this or close if it's fixed.

**Comment by dzearing** [comment] 2017-03-01 01:22
Closing.

**Comment by jeffersoneagley** [comment] 2019-01-31 21:22
This seems to not work still. The tooltiphost is not focusable unless there's something I missed.

**Comment by jeffersoneagley** [comment] 2019-01-31 22:13
I found some of the docs that use an html button around the children to make it selectable, then give that button an `aria-describedby`:
```
      <TooltipHost
        content={content}
      >
        <button
          aria-describedby={tooltipId}
          className='tooltip-class-to-hide-the-fact-that-this-is-an-html-button'
          aria-label={ariaLabel}
          role='tooltip'
        >
          <Icon
            iconName={iconName}
          />
        </button>
      </TooltipHost>
```

**Comment by micahgodbolt** [comment] 2019-02-01 17:59
Should narrator even be reading tooltips? Or should information in the tooltip be available via aria tags on the host element? Is a tooltip just a visual representation of the data already there? Tooltips are often used when text is truncated. Narrator would simply just read the text as it is in the DOM.

**Comment by jlukosky** [comment] 2019-10-11 16:29
It

> Should narrator even be reading tooltips? Or should information in the tooltip be available via aria tags on the host element? Is a tooltip just a visual representation of the data already there? Tooltips are often used when text is truncated. Narrator would simply just read the text as it is in the DOM.

It would be most appropriate to have the triggering element use aria-describedby to reference the tooltip. Tooltips should NOT be focusable.

**Comment by micahgodbolt** [comment] 2019-10-11 16:45
@jlukosky the problem is that we don't instantly render the tooltips on focus/hover. We delay rendering to reduce the perf hit. So the issue is that `aria-describedby` would be pointing at nothing.

**Comment by micahgodbolt** [comment] 2019-10-11 16:47
This is a duplicate of #10677.

**Closed** 2019-10-14 18:00 UTC
Labels: Resolution: Duplicate
