### ISSUE TITLE
Inconsistent Icon Naming

### ISSUE THREAD

**Issue by jcuenod** [OfficeDev/office-ui-fabric-react#2407] opened 2017-08-05 15:25 UTC
### Bug Report

- __Package version(s)__: 4.30.0
- __Browser and OS versions__: Chromium 59.0.3071.115

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? **No**

Requested priority: **Normal**

#### Describe the issue:

Some icons are not consistently named. For example, when examining `packages/office-ui-fabric-react/src/components/Icon/IconName.ts` or https://dev.office.com/fabric#/styles/icons we find icons named:

 - Delete
 - Switch

#### Actual behavior:

In `packages/styling/src/styles/IconCodes.ts` the icons are named (respectively):

 - Trash
 - Switcher

#### Expected behavior:

There should be consistency here (and probably some kind of test that ensures the name scheme matches).

I have only mentioned the issues that I have come across and I see that there is another issue open regarding the delete icon (#2205). Because I found another mismatched name and that issue hasn't received much attention, I though I would open a new issue.

**Comment by kristoferbrown** [comment] 2017-08-09 21:14
I'm closing this issue as a duplicate of #2205 and adding a mention of the Switch/Switcher mismatch to that issue so this can all be tracked in one place.

**Closed by kristoferbrown** 2017-08-09 21:14 UTC
Labels: bug
