### ISSUE TITLE
Panel dialog is not clearly visible in 400% zoom mode

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [OfficeDev/office-ui-fabric-react#11550] opened 2019-12-24 10:34 UTC
User Experience:
Users who rely on zooming features will be impacted as content is not clearly visible in 400% zoom mode.

Repro Steps:
Step 1: Browser settings - Zoom - 400%
Step 1: Open latest Fabric URL in Edge browser.
Step 2: Navigate to "Panel" and activate it
Step 3: Verify Panel dialog is clearly visible in 400% zoom mode

Actual:
Panel dialog is not clearly visible in 400% zoom mode

Expected:
Panel dialog should clearly visible in 400% zoom mode

![image](https://user-images.githubusercontent.com/53210862/71409304-1429eb80-2667-11ea-8dab-419cdf797c87.png)

**Comment by micahgodbolt** [comment] 2019-12-26 16:47
Duplicate of #10905

**Closed** 2019-12-29 18:00 UTC
Labels: Resolution: Duplicate
