### ISSUE TITLE
MarqueeSelection limit selection zone by id

### ISSUE THREAD

**Issue by Sodininkas** [OfficeDev/office-ui-fabric-react#5957] opened 2018-08-16 15:23 UTC
### Bug Report 
 
MarqueeSelection makes all page active for selection, hot to limit to MarqueeSelection div only 

 
#### Describe the issue:
 
![marqueeselection](https://user-images.githubusercontent.com/7899790/44218067-91934100-a181-11e8-9092-11ac4332354a.gif)

#### Actual behavior:
 
MarqueeSelection makes all page active for selection
 
#### Expected behavior:
 
Ability for MarqueeSelection limit selection zone, for example choose some id of the div

**Comment by JasonGore** [comment] 2018-08-16 21:55
I'm not sure if this is by design or a regression/bug. @dzearing @Markionium Do you have any input here? I'm not sure who else to ask regarding this input.

**Comment by JasonGore** [comment] 2018-08-16 22:31
Actually I've now discovered this can be constrained using the `isDraggingConstrainedToRoot` prop. [Here is a CodePen](https://codepen.io/jasongore/pen/RBzBvq) showing this prop in practice.

I will close this issue as resolved due to the availability of the `isDraggingConstrainedToRoot`. Please feel free to reopen if you are still having issues with the prop. Thanks!

**Closed by JasonGore** 2018-08-16 22:31 UTC
Labels: Component: MarqueeSelection, Needs: Triage🔍
