### ISSUE TITLE
Dropdown selection

### ISSUE THREAD

**Issue by javahemans** [OfficeDev/office-ui-fabric-react#6001] opened 2018-08-20 23:34 UTC
### Please provide a reproduction of the bug in a codepen:
I am not sure if it's a **bug** or it's a **feature** 

Why in the Fabric UI when user open the dropdown the first option will get selected without user intention. 

Below is the codepen link:
https://codepen.io/anon/pen/ZMErKa?editors=0010

 
#### Describe the issue:
 
Why when user click to open a dropdown it should choose an option without user intention??
 
#### Actual behavior:
 
Drop down functinoality choose the first item as a selected item when user want to visit drop down options
 
#### Expected behavior:
 
To be able to visit dropdown item and if you didn't want to choose anything it still ask you `choose an option` **NOT** choosing first option on your behalf

**Comment by KevinTCoughlin** [comment] 2018-08-20 23:46
Possibly related to #5473

**Comment by kkjeer** [comment] 2018-08-21 19:50
Duplicate of #5473

**Closed by kkjeer** 2018-08-21 19:50 UTC
