### ISSUE TITLE
[Dropdown] first option gets selected if defaultSelectedKey is unknown

### ISSUE THREAD

**Issue by neeraj-khanna** [OfficeDev/office-ui-fabric-react#9234] opened 2019-05-28 07:36 UTC
### Environment Information 
 
- __Package version(s)__: 6.186.1 
- __Browser and OS versions__: Chrome & Edge on Windows 10

### Please provide a reproduction of the bug in a codepen:
 
<https://codepen.io/v-harc/pen/xNJVoO>
 
#### Actual behavior:
 
We want no item to be selected initially, therefore setting the _defaultSelectedKey_ as an non-existent key. On clicking the dropdown to expand, _onChange()_ event is getting fired for first option in the dropdown.
 
#### Expected behavior:
 
_onChange()_ event should not be triggered when expanding the dropdown.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment] 2019-05-28 18:23
Duplicate of #5473

**Closed** 2019-05-28 18:23 UTC
Labels: Component: Dropdown, Resolution: Duplicate, Type: Bug :bug:
