### ISSUE TITLE
ComboBox: Mutates options directly in multiSelect mode

### ISSUE THREAD

**Issue by bt-88** [OfficeDev/office-ui-fabric-react#9162] opened 2019-05-21 15:01 UTC
### Environment Information 
 
- __Package version(s)__: 6.184

#### Actual behavior:
 

1. We have a ComboBox with `multiSelect` and `options={this.props.options}`.
2. We select the first option.
3. Now our options reference `this.props.options` is mutated. The first item will have an additional property `selected: true`.

#### Expected behavior:
 
The ComboBox should not mutate our options directly, but rather work with a copy.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal, since we can currently use the following work-around: `options={this.props.options.map(x => ({...x}))}`.
 
Products/sites affected: (if applicable)

**Comment by kenotron** [comment] 2019-05-21 16:51
I agree this is a bit odd to mutate objects inside a prop. However, I believe at this point enough code has been dependent of retrieving the selected state this way. To change this behavior at this point would be an API change. We would likely only be able to take this across some future major bump. I'm putting this on the backlog as a feature to be picked up by a future release.

I'm linking to #6030 to track this in an existing work item

**Comment by JFish63** [comment] 2019-05-22 06:56
If this is a 'feature' and not a bug then the documentation should be updated to mention this effect.

Perhaps I have time later on to create a PR, since my gut feeling tells me that there is a part of code that does `[...options]` instead of `options.map(x => ({...x}))`. This would a simple fix that does not require API change.

**Comment by cliffkoh** [comment] 2019-05-22 19:47
I think we definitely regard this as a bug rather than a feature. @joschect since you're in combobox code, could you take a look to see if this is something that can be fixed in the existing combobox without too much of a concern of breaking people who may depend on the current (buggy) behavior?

**Comment by joschect** [comment] 2019-05-22 19:52
@cliffkoh This is just a bug. I don't think it should be too much of a concern breaking people. Especially since it's not documented. No api change.

**Comment by cliffkoh** [comment] 2019-05-22 19:53
Cool, thanks for getting back on this :+1:

**Comment by Suresh-Lakum** [comment] 2019-08-19 21:22
Thanks @bt-88 it worked.

**Closed** 2019-09-11 17:00 UTC
Labels: Component: ComboBox, Status: In PR, Type: Bug :bug:
