### ISSUE TITLE
Label A11y Pass

### ISSUE THREAD

**Issue by TestAccessibilityGIT** [OfficeDev/office-ui-fabric-react#6962] opened 2018-11-02 23:41 UTC
Tracking all of the issues brought up with the 11/02 accessibility pass on label  control
Details on individual bugs can be found on [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7b8a57405f-1c87-4e2d-8c24-5f15d53276a8%7d&action=edit&activeCell='Bugs'!L3&wdInitialSession=e7ad14f3-cb60-478f-bca2-be595d14abee&wdRldC=1)

- [x] Bug 1: [Accessibility][Visual requirements]: Color contrast ratio of 'I'm a disabled Label' text is less than 4.5:1.
- [x] Bug 2: [Accessibility][Usable]: Provide one instance to show the usage of "for” attribute to associate the labels to the form controls.

Component: Label
@micahgodbolt

**Comment by kenotron** [comment] 2018-11-06 23:13
Got a confirmation that (1) above is by design.

(2) is addressed by the PR.

**Closed** 2018-11-07 17:59 UTC
Labels: Area: Accessibility, Component: Label
