### ISSUE TITLE
DocumentCard: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7108] opened 2018-11-14 22:05 UTC
Blocked - uses sass styles and needs mergeStyles conversion which is tracked in #5408

**Comment by mikewheaton** [comment] 2019-01-11 22:33
This is unblocked thanks to #7584

**Comment by mikewheaton** [comment] 2019-01-14 20:31
I've confirmed that the DocumentCard is now picking up the Fluent theme. Marking it as complete since there are no Fluent-specific designs for this component.

**Closed** 2019-01-19 03:56 UTC
Labels: Area: Fluent, Component: DocumentCard

**Comment by marygans** [comment] 2019-08-20 17:25
### Updates: 

**Title:**
Current: font-size: 18px; font weight: regular
Expected(based on toolkit): font-size: 16px ; font weight: semibold
Secondary title variant exists in code but not toolkit - Need new secondary font size value in code with this update.

**Card width:** 
Current: 320px
Expected(based on toolkit):254px 

box shadow:
Current: none
Expected(based on toolkit):4px elevation

OnHover:
Current: #c8c6c4 outline
Expected(based on toolkit):8px elevation
