### ISSUE TITLE
Link: ms-Link font-family should "inherit" rather than define any font details.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#506] opened 2016-11-07 23:08 UTC

**Comment by mikewheaton** [comment] 2016-11-07 23:13
Right now all of the components apply the `ms-baseFont()` mixin, defined [here in Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core/blob/21d51b669673631272dcd5eac56c242657edf350/src/sass/_Fabric.Typography.Mixins.scss). The problem is that these aren't localized, so changing an app's language will only affect classes like `ms-font-m` and not the components.

A solution is to only set the `font-family` on the root `ms-Fabric` wrapper class, and then inherit into all of the other type and component classes. This will provide a single selector we can override to adjust the font stack for localized content.

**Comment by dzearing** [comment] 2016-11-08 03:31
The `.ms-Fabric` class already does add the definition. DetailsList relies on this, for example, so if you don't wrap it in Fabric, then you get a Times New Roman styled list. But if you use a `Link` in a `DetailsList`, it will pick up the baseFont one. So ... if we just remove the Link's hardcoded font styling, it can behave consistently.

**Comment by mikewheaton** [comment] 2016-11-09 18:30
Nice, I didn't realize that was implemented in the base `ms-Fabric` component. 😄  So we should remove `baseFont()` from all of the components, right?

**Comment by micahgodbolt** [comment] 2017-03-20 21:18
@mikewheaton Is this still an issue? Or can I close this?

**Comment by mikewheaton** [comment] 2017-03-20 21:44
I'm removing the `baseFont()` mixin from all of the components as part of the update to Fabric Core 6.0. Here's the PR: #1290

**Comment by gitjain** [comment] 2017-03-21 18:56
Issue is closed. Updating the status.

**Closed by gitjain** 2017-03-21 18:56 UTC
Labels: bug
