### ISSUE TITLE
p Tag in Body of Teaching

### ISSUE THREAD

**Issue by maggiepint** [OfficeDev/office-ui-fabric-react#6189] opened 2018-08-31 19:13 UTC
### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment] 2018-08-31 20:41
duplicate of #6190

**Closed by micahgodbolt** 2018-08-31 20:41 UTC
