### ISSUE TITLE
Coachmark A11y Pass

### ISSUE THREAD

**Issue by awalia13** [OfficeDev/office-ui-fabric-react#8031] opened 2019-02-18 22:39 UTC
Tracking all of the issues brought up with the 2/18 accessibility pass on Coachmark control
Details on individual bugs can be found on [Sharepoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7Bec787de0-7a76-4b21-b593-fb839dfa9cd8%7D&action=default&uid=%7BEC787DE0-7A76-4B21-B593-FB839DFA9CD8%7D&ListItemId=1808&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble)

- [x] Bug1: [Accessibility][Programmatic access]: ARIA attributes must conform to valid values. 
- [x] Bug2: [Accessibility][Keyboard Navigation]: Focus indicator is not visible on the teaching bubble that appears on pressing enter on show coachmark button.
- [ ] Bug3: [Accessibility][Usable]: Coachmark bubble is not accessible by enter key in scan mode of narrator.
- [ ] Bug4: [Accessibility][Supporting the platform]: Coachmark bubble is not visible properly in High contrast mode black and white.
- [ ] Bug5: Accessibility][Usable]:Dialog which opens on pressing enter on coachmark bubble is getting hidden partially behind the side pane.
- [ ] Bug6: [Accessibility][Programmatic access] Inappropriate role defined for Coachmark Position ComboBox as Listbox.
- [ ] Bug7: [Functional]Not able the change the Coachmark Position from the available ComboBox.

**Comment by dzearing** [comment] 2019-09-16 06:22
@marygans can you work to close this out?

**Comment by dzearing** [comment] 2019-09-16 06:34
"Coachmark bubble is not visible properly in HC" is pretty serious.

**Comment by marygans** [comment] 2019-09-17 19:52
Yes I agree, and ok I am on it

**Comment by marygans** [comment] 2019-09-24 02:22
1: `aria-LabelledBy` and `aria-DescribedBy` for coachmark are mapping to the `aria-LabelledByText` and `aria-DescribedByText` props. `aria-LabelledBy` and `aria-DescribedBy` for teachingBubble maps to `example-Label` and `exampleDescription`. See example here
![example-coachmark](https://user-images.githubusercontent.com/38991459/65476258-2cefee80-de37-11e9-8357-a4993357a5c9.png)

**Comment by marygans** [comment] 2019-09-24 03:02
2: The focus indicator moves from the button to the Coachmark bubble after pressing Enter on "show coachmark" button: 
<img width="931" alt="coachmark-focus1" src="https://user-images.githubusercontent.com/38991459/65477998-edc49c00-de3c-11e9-9df3-f2b975cb6438.png">

which I believe is intended

**Comment by marygans** [comment] 2019-09-24 03:07
3: This seems to be an issue with just NVDA...will double check this

**Comment by marygans** [comment] 2019-09-24 06:35
5: seems to no longer be an issue
<img width="629" alt="Screen Shot 2019-09-23 at 11 34 31 PM" src="https://user-images.githubusercontent.com/38991459/65487000-c11f7d00-de5a-11e9-92d9-581af586d3d7.png">

**Comment by marygans** [comment] 2019-09-25 00:14
Bug 6 and 7 do no pertain to the `Coachmark` component  but rather the `Dropdown` component. 
So creating separate issues: 
- Bug 6: Doesn't seem to be an issue in `dropdown` based on the documentation for [listbox](https://www.w3.org/TR/wai-aria-practices/#Listbox)  and [combobox](https://www.w3.org/TR/wai-aria-practices/#combobox) - created new but closed issue [here](#10607) for tracking purposes under dropdown component.  
- Bug 7 - cannot repro but opened a separate issue #10608 for `dropdown` component tracking purposes.

**Comment by marygans** [comment] 2019-09-25 05:39
Hi @awalia13, the actionable bug has been addressed and merged.  I will soft close this issue and tag this issue with Needs: Author Feedback and let it resolve unless additional feedback is provided. Thanks for submitting!

**Comment by 999-Dev** [comment] 2019-09-25 11:10
Bug1: [Accessibility][Programmatic access]: ARIA attributes must conform to valid values.
Verify the bug of below Test Enviourment. Issue is not repro'ing, hence closing the bug.
Test Environment: 
OS: Version: RS5_Prerelease(1903 OS Build 18990.1) 
URL: https://github.com/OfficeDev/office-ui-fabric-react/issues/8031
Edge Browser Version: 
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

Bug5: [Accessibility][Usable]:Dialog which opens on pressing enter on coach mark bubble is getting hidden partially behind the side pane.
Verify the bug of below Test Enviourment. Issue is not repro'ing, hence closing the bug.
Test Environment: 
OS: Version: RS5_Prerelease(1903 OS Build 18990.1) 
URL: https://github.com/OfficeDev/office-ui-fabric-react/issues/8031
Edge Browser Version: 
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

Bug7: [Functional]Not able the change the Coachmark Position from the available ComboBox.
Verify the bug of below Test Enviourment. Issue is not repro'ing, hence closing the bug.
Test Environment: 
OS: Version: RS5_Prerelease(1903 OS Build 18990.1) 
URL: https://github.com/OfficeDev/office-ui-fabric-react/issues/8031
Edge Browser Version: 
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by 999-Dev** [comment] 2019-09-25 12:08
Bug6: Inappropriate role defined for Coachmark Position ComboBox as Listbox.
Verify the bug of below Test Enviourment. 
As per comment closing the bug.
Test Environment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: #8031
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by 999-Dev** [comment] 2019-09-25 12:27
> 2: The focus indicator moves from the button to the Coachmark bubble after pressing Enter on "show coachmark" button:
> 
> which I believe is intended

Verify the bug of below Test Enviourment.
"It should be accessible with keyboard as this is an interactive control and it should work with out screen reader as well for keyboard dependent users."
Test Environment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: #8031
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by 999-Dev** [comment] 2019-09-25 12:43
> 3: This seems to be an issue with just NVDA...will double check this

Verify the bug of below Test Enviourment.
"The bubble should be actionable by using Enter key in scan mode also. Issue is repro'ing with both screen readers.

Test Environment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: #8031
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by 999-Dev** [comment] 2019-09-25 13:37
New Bug Found :

Bug 8: Keyboard focus is not visible on "Try it" button while navigate using Tab key under 'Example Title' dialogue. 

Test Environment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: #8031
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by dzearing** [comment] 2019-09-25 14:14
@999-Dev im having a difficult time understanding the actions you expect here.

Can you clarify what you tried and what you expected? 

I believe in scan mode things become less interactive (onclicks stop working, reader takes over to allow the user to read content on the page.) is that not the case?

**Comment by 999-Dev** [comment] 2019-09-26 05:37
> 2: The focus indicator moves from the button to the Coachmark bubble after pressing Enter on "show coachmark" button:
> which I believe is intended
> 
> Verify the bug of below Test Enviourment.
> "It should be accessible with keyboard as this is an interactive control and it should work with out screen reader as well for keyboard dependent users."
> Test Environment:
> OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
> URL: #8031
> Edge Browser Version:
> Microsoft Edge: 44.18990.1.0
> Microsoft EdgeHTML: 18.18990
> Chrome Browser Version:
> Chrome Version: 76.0.3809.132

"If any user navigates with out screen reader and activate the 'Show coach mark' button, Coach mark bubble will be appeared but focus is not visible on it. So users  will not be able to know that focus is on 'Coach mark' bubble."

**Comment by 999-Dev** [comment] 2019-09-26 12:55
New Bug Found :

Bug 9: Color contrast ratio failed of Close button boundary under 'Example Title' pane.

Test Enviourment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1) 
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.39.0/#/examples/coachmark
Edge Browser Version: 
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132
Tool:
Color contrast analyzer

**Comment by 999-Dev** [comment] 2019-09-26 13:26
New Bug Found :

Bug 10: Screen reader conveying the incorrect information after activating the 'Show Coach Mark' button.
Test Enviourment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.39.0/#/examples/coachmark
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by 999-Dev** [comment] 2019-09-26 13:42
Bug 11: In scan mode while backward navigation Screen reader focus does not moves to the 'Close' button.
Test Enviourment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.39.0/#/examples/coachmark
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by dzearing** [comment] 2019-09-26 15:08
@999-Dev what does this issue imply? How do we reproduce this (what reader, how to enable the mode, what keypresses you made) and what is your expectation?

> Bug 11: In scan mode while backward navigation Screen reader focus does not moves to the 'Close' button.

**Comment by 999-Dev** [comment] 2019-09-27 04:59
> @999-Dev what does this issue imply? How do we reproduce this (what reader, how to enable the mode, what keypresses you made) and what is your expectation?
> 
> Bug 11: In scan mode while backward navigation Screen reader focus does not moves to the 'Close' button.

"In scan mode when we activating the 'Show Coach Mark' button, Coach mark bubble will be appeared, and after that press Alt+C , 'Example Title' dialog will be appeared. Now start to navigate 'Example Title' dialog by using up and down arrow keys and you will found that focus does not moves to 'Close' button, focus directly moves outside the dialog."
**Expected:** Screen reader focus should be land on 'Close' button and focus should not moves to outside the dialog.

**Comment by marygans** [comment] 2019-10-01 05:09
> > @999-Dev what does this issue imply? How do we reproduce this (what reader, how to enable the mode, what keypresses you made) and what is your expectation?
> > Bug 11: In scan mode while backward navigation Screen reader focus does not moves to the 'Close' button.
> 
> "In scan mode when we activating the 'Show Coach Mark' button, Coach mark bubble will be appeared, and after that press Alt+C , 'Example Title' dialog will be appeared. Now start to navigate 'Example Title' dialog by using up and down arrow keys and you will found that focus does not moves to 'Close' button, focus directly moves outside the dialog."
> **Expected:** Screen reader focus should be land on 'Close' button and focus should not moves to outside the dialog.

Hi @999-Dev I was unable to repro this issue using the up and down keys to get to the close button after the "Try it Again" button in scan mode. Can you provide a screen capture of this? I will provide a gif of what I see when I get my device with Edge back. 

Thanks!

**Comment by marygans** [comment] 2019-10-01 22:53
Hi @999-Dev, here is the screen recording repro attempt for Bug 11 in Edge: 

![testing6](https://user-images.githubusercontent.com/38991459/66006413-722da500-e463-11e9-8f1f-e3ab32b12cd9.gif)

**Comment by marygans** [comment] 2019-10-01 22:55
> New Bug Found :
> Bug 10: Screen reader conveying the incorrect information after activating the 'Show Coach Mark' button.
> Test Enviourment:
> OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
> URL: https://fabricweb.z5.web.core.windows.net/oufr/7.39.0/#/examples/coachmark
> Edge Browser Version:
> Microsoft Edge: 44.18990.1.0
> Microsoft EdgeHTML: 18.18990
> Chrome Browser Version:
> Chrome Version: 76.0.3809.132

Can you provide further information regarding this bug? E.g., actual vs expected with a possible screen recording of the issue? (Similar to the excel documentation provided previously)

thanks!

**Comment by 999-Dev** [comment] 2019-10-03 05:18
> New Bug Found :
> Bug 10: Screen reader conveying the incorrect information after activating the 'Show Coach Mark' button.
> Test Enviourment:
> OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
> URL: https://fabricweb.z5.web.core.windows.net/oufr/7.39.0/#/examples/coachmark
> Edge Browser Version:
> Microsoft Edge: 44.18990.1.0
> Microsoft EdgeHTML: 18.18990
> Chrome Browser Version:
> Chrome Version: 76.0.3809.132
> 
> Can you provide further information regarding this bug? E.g., actual vs expected with a possible screen recording of the issue? (Similar to the excel documentation provided previously)
> thanks!

@marygans 
**Actual:**
After activating the 'Show Coach Mark' button, Coach Mark bubble is appeared, but screen reader announce it "A Coach mark has appeared, Coach Mark notification **Dialog**' Coach mark notification press enter or Alt + C key to open". 
**Expected:**
Screen reader announce 'Coach Mark notification Dialog', but this is not a dialog, it is simple notification. Screen reader should not announce it  'Dialog'

**Comment by 999-Dev** [comment] 2019-10-03 05:42
> Hi @999-Dev, here is the screen recording repro attempt for Bug 11 in Edge:

@marygans 

**Actual:**
After activating the 'Show Coach Mark' bubble by using Alt+C, Narrator focus does not land on 'Try Again' button and also does not moves to Close button.

**Expected:**
After activating the bubble notification, screen reader should announce complete name of the control like 'Try It' button. After that navigate the 'Example title' by using up arrow keys and verify the issue weather focus moves to the Close button or not. 
**Already shared the video for the same in SharePoint. Refer the attachment.**

**Comment by dzearing** [comment] 2019-11-09 16:38
@marygans I don't believe this issue was completely resolved. Can you please split out individual bugs for anything that was remaining?

**Comment by dzearing** [comment] 2019-11-14 06:10
@marygans Regarding bug 2:

The focus indicator is not visible when tabbing to button, not running Narrator. (your screenshot is narrator's rectangle.)

You should see the focus on the button when you tab to it. Pressing enter opens the coachmark and moves focus. There is no visible rectangle.

I believe this is really won't fix here, because coachmark isn't really part of the normal tabbing order, similar to a tooltip.

And without using the keyboard tab or arrows, we by default do not display focus indicators by design, and tabbing or shift tabbing would likely focus something else, which would I think dismiss it.

Tracking as a p3 in https://github.com/OfficeDev/office-ui-fabric-react/issues/11183

**Comment by marygans** [comment] 2019-11-14 20:08
Hi @999-Dev! I am having some issues opening the .wmv files you specified in the Sharepoint site
![Screen Shot 2019-11-14 at 12 08 20 PM](https://user-images.githubusercontent.com/38991459/68892288-81954480-06d7-11ea-9923-240960736e35.png)

**Comment by dzearing** [comment] 2019-12-02 15:55
@marygans I think this bug is split out fully and tracked in indivudual issues. If so, can you close this?

**Comment by dzearing** [comment] 2019-12-07 12:47
Can we please get traction

**Comment by marygans** [comment] 2019-12-09 02:03
> @marygans I think this bug is split out fully and tracked in indivudual issues. If so, can you close this?
Yep! issues are being tracked/addressed so closing this

**Closed** 2019-12-09 02:03 UTC
Labels: Area: Accessibility, Component: Coachmark, Needs: Author Feedback, Priority 1: ASAP

**Comment by marygans** [comment] 2019-12-09 19:29
This issue was closed because the remaining issues mentioned in the comments are being tracked externally as individual issues.
