### ISSUE TITLE
Contextual menu does not dismiss on clicking in iframe

### ISSUE THREAD

**Issue by rohitrewa** [OfficeDev/office-ui-fabric-react#9718] opened 2019-07-05 18:43 UTC
### Environment Information 
 
- __Package version(s)__: 7.4.3
- __Browser and OS versions__: All

 

 
#### Actual behavior: 
Contextual meu remains open on clicking in an iframe
 

 
#### Expected behavior: 
Contextual menu should dismiss on clicking anywhere outside the contextual menu
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  Blocking 
 
Products/sites affected: (if applicable) Microsoft Visio Data Visualizer

### Important details:

We are trying to move to the latest fabric version but due to this issue, we are blocked. Contextual menu in version 5.76.0 dismisses on clicking on an iframe where as in the recent versions like 7.4.3 it does not.

Currently, we are on version 5.76.0 and want to move to latest to implement some important features. Which can only be implemented in latest fabric version. Please help asap. 

I tried to play a lot with contextual menu props and its focuszone props but nothing helped.

**Comment by khmakoto** [comment] 2019-07-05 21:28
Hi @rohitrewa, thanks for filing this issue!

I'll start investigating to find a fix as we want as many people as possible to move to Fabric 7. @joschect do you happen to have an idea right off the top of your mind as to what might have caused this regression?

**Comment by rohitrewa** [comment] 2019-07-09 12:12
@khmakoto For planning purpose, we would like to understand when can we see this fix in npm.

**Comment by khmakoto** [comment] 2019-07-10 21:05
@rohitrewa I hope to have a fix by the end of this week with the fix being on npm at the latest early next week.

**Comment by khmakoto** [comment] 2019-07-10 21:22
Hey @rohitrewa, I'm trying to repro the behavior where it used to dismiss on clicking on an iframe in 5.76.0 but I cannot seem to replicate it on a codepen. [Here ](https://codepen.io/khmakoto/pen/ydZxpJ?editors=1010) is what I've done. Could you fiddle with it to try to repro how it worked before? The version of Fabric used in the codepen is pinned to 5.76.0.

**Comment by khmakoto** [comment] 2019-07-11 21:58
Spoke with @rohitrewa offline. We'll try to get this behavior to repro together and then investigate on what change made this behavior disappear in later versions.

**Comment by khmakoto** [comment] 2019-07-16 18:55
@rohitrewa and I spoke offline, we were able to repro the issue in his environment but it seemed to be due to conditions unrelated to the fabric upgrade. I agreed to take a look into how we could get the behavior he wanted in current Fabric.

The main problem here is that it is impossible to get the mouse events that happen inside of an `iframe` propagated to the parent, given that an `iframe` essentially works as a different surface. I [mocked a workaround for this](https://codepen.io/khmakoto/pen/ydZxpJ?editors=0010) that emulates the wanted behavior by setting `pointerEvents` to `none` on the `iframe` when the `ContextualMenu` is open. With this, the page treats the `iframe` as a static element inside it and the `ContextualMenu` dismisses without a problem when the `iframe` is clicked. The only drawback with this approach is that the user cannot interact with elements inside of the `iframe` during that time, meaning that they need an extra click to close the `ContextualMenu` before, say, being able to click a `Button` inside of the `iframe`.

However, @rohitrewa confirmed that this is actually the behavior that's occurring right now, so this workaround is good enough for them and we agreed on closing the issue after I finished posting this update.

**Closed by khmakoto** 2019-07-16 18:55 UTC
Labels: Component: ContextualMenu, Type: Bug :bug:
