### ISSUE TITLE
DetailsList: DetailsRow isSelected styling not working

### ISSUE THREAD

**Issue by natalieethell** [OfficeDev/office-ui-fabric-react#10094] opened 2019-08-07 22:03 UTC
### Environment Information

- **Package version(s)**: office-ui-fabric-react v7.21.0
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/naethell/pen/WVzQwq

In the CodePen, I attempt to set the color of text in a details row to red when the row's `isSelected` style prop is true. That style is not applied on the row until a resize event or loss of focus.

#### Actual behavior:

The `isSelected` styling does not get applied on the row until a resize event or loss of focus. 

#### Expected behavior:

The `isSelected` styling should be applied when the row is selected.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by jdhuntington** [comment] 2019-08-16 18:45
Hi @natalieethell - It looks like the issue is occurring due to the specificity of the rules that govern the colors when the row is highlighted or selected. I was able to modify your codepen to make the colors change on selection without a redraw.

https://codepen.io/jdh-msft/pen/bGbeppe?editors=0010

Question: Does this work for you? Do you feel like the original code should work as-is without the changes in this codepen? Would like to figure out if this should be a bug that we try and change or something we just need to document better.

**Comment by KevinTCoughlin** [comment] 2019-08-16 19:49
> Question: Does this work for you? Do you feel like the original code should work as-is without the changes in this codepen?

Thanks for figuring out the root cause @jdhuntington.

Having to write the following code:

```ts
if (detailsRowStyleProps.isSelected) {
  style.root.color = "#FF0000";
  style.root.selectors[':hover'].selectors = overrideColorForSelectedRow;
  style.root.selectors[':focus'].selectors = overrideColorForSelectedRow;
  style.root.selectors[':focus:hover'].selectors = overrideColorForSelectedRow;
}  
```

Seems non-intuitive and not something that folks without intimate knowledge of the code would be able to supply. The specificity issue seems like something worth fixing if trivial.

cc: @natalieethell

**Comment by xugao** [comment] 2020-02-12 22:23
@Ianzhenw - to answer your typing question, you can have something like the following:
```
const stylesForRow: IStyleFunctionOrObject<IDetailsRowStyleProps, IDetailsRowStyles> = detailsRowStyleProps => {
  const rootStyle: IRawStyle = {
    color: detailsRowStyleProps.isSelected ? '#FF0000' : undefined,
    selectors: {
      ':hover': {
        background: '#3F3F40',
        color: '#FFFFFF',
        selectors: detailsRowStyleProps.isSelected ? overrideColorForSelectedRow : undefined
      },
      ':focus': {
        background: '#FFAACC',
        color: '#FFFFFF',
        selectors: detailsRowStyleProps.isSelected ? overrideColorForSelectedRow : undefined
      },
      ':focus:hover': {
        background: '#007ACC',
        color: '#FFFFFF',
        selectors: detailsRowStyleProps.isSelected ? overrideColorForSelectedRow : undefined
      }
    }
  };

  return { root: rootStyle };
};
```

**Comment by xugao** [comment] 2020-02-12 22:25
I understand the work around is ugly, but the proper fix is not something we can address in short term. marking this issue as won't fix

**Closed** 2020-02-16 01:00 UTC
Labels: Component: DetailsList, Status: Won't Fix, Type: Bug :bug:
