### ISSUE TITLE
Color & Themes area in website broken

### ISSUE THREAD

**Issue by jonathanhotono** [OfficeDev/office-ui-fabric-react#7972] opened 2019-02-13 00:54 UTC
I can't seem to access these pages anymore:
https://developer.microsoft.com/en-us/fabric#/customizations/themes
https://developer.microsoft.com/en-us/fabric#/customizations/colors

**Comment by JasonGore** [comment] 2019-02-13 02:11
@kenotron Do you think this could be a regression caused by #7894?

**Comment by Jahnp** [comment] 2019-02-13 08:09
It's definitely caused by that. The new links should be navigable from the left nav:
![image](https://user-images.githubusercontent.com/307118/52696260-6e283380-2f23-11e9-853b-7aa7b3447c09.png)

But the old links should continue to work for anyone who's bookmarked them. @kenotron is it possible to add back support for the old links? We can also work to update the UHF with the new links, but that may take a few days and won't fix the bookmark issue.

**Comment by kenotron** [comment] 2019-02-14 00:33
Sure, we could try to backport the bad links to the new one, I suppose. How many more days is this supposed to be?

**Comment by Jahnp** [comment] 2019-02-14 00:44
I'm working with the dev.microsoft.com infra team to get the links updated as we don't have perms to do it ourselves right now. It should be published within the next day or so. But that'll only fix the links on the UHF—if someone already had the original links bookmarked they'd break. I think @JasonGore did this with the old theme generator link.

**Comment by Jahnp** [comment] 2019-02-14 00:58
Correction—the UHF links should be live in the next hour or so.

**Comment by kenotron** [comment] 2019-02-14 01:06
So, do we still need to act on this?

**Comment by Jahnp** [comment] 2019-02-14 01:08
I think so, yes—not ideal, but, the old links will still break if someone has the old links.

**Comment by kenotron** [comment] 2019-02-14 04:11
Take a look at the PR for a quick fix for this.

**Comment by Jahnp** [comment] 2019-02-14 04:39
Awesome thank you! Will take a look shortly.

**Closed** 2019-02-14 12:11 UTC
Labels: Area: Documentation, Type: Bug :bug:, Type: Documentation
