### ISSUE TITLE
[Accessibility][Screen Readers-Calendar]: Information about the change of week is not narrated by screen reader whenever user press Enter on previous/next button

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9706] opened 2019-07-04 10:05 UTC
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EfQzz15i5S1MuFJ1F1X9xDgBaNTpsu3jvO_wgE-gVh-6Eg?e=gE9Ij5)

Component: Calendar

**Comment by khmakoto** [comment] 2019-07-05 20:21
Hi @dollykumari5, thanks for filing this issue! This seems to be a duplicate of Bug 5 in #8349, so I'll be closing this since the issue is already being tracked there. Thanks again!

**Closed by khmakoto** 2019-07-05 20:21 UTC
Labels: Area: Accessibility, Area: Narrator, Component: Calendar, Resolution: Duplicate, Type: Bug :bug:
