### ISSUE TITLE
Picker: Narrator not reading "noResultsFoundText" 

### ISSUE THREAD

**Issue by pandey11** [OfficeDev/office-ui-fabric-react#9393] opened 2019-06-10 16:11 UTC

**Comment by Rajeev-K** [comment] 2019-06-10 17:34
@pandey11 thank you for reporting the issue. In order to reproduce the problem could you provide a code sample on https://codepen.io/ ? Thank you!

**Comment by pandey11** [comment] 2019-06-10 19:02
try this
    const onFilterChanged =  (input?: string): ITag[] | [] => {
        return [];
    };                    
    <TagPicker
        onResolveSuggestions={onFilterChanged}
         pickerSuggestionsProps={{ noResultsFoundText: "noResultsFoundText}}
       />

**Comment by pandey11** [comment] 2019-06-10 20:42
[CodePenlink](https://codepen.io/anon/pen/QXWwbP)

**Comment by Rajeev-K** [comment] 2019-06-10 20:45
Thank you, @pandey11. We are investigating.

**Comment by Rajeev-K** [comment] 2019-06-13 20:35
@pandey11 after investigating this issue, it looks like the Picker is correctly implemented. Picker sets the role="alert" attribute on the popup which should result in Narrator reading the text. However it looks like there is currently an Edge bug that is causing the text to not be read aloud. See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/21900325/ When that bug is fixed this should work. Let us know if you need any additional information.

**Comment by pandey11** [comment] 2019-06-16 05:40
verified. I'm not able to repro only in chrome. Thanks

**Comment by Rajeev-K** [comment] 2019-06-17 17:17
Since we have verified that this is an Edge bug, we'll close this issue, but if you are experiencing any other problems, feel free to open another issue.

**Closed by Rajeev-K** 2019-06-17 17:17 UTC
Labels: Needs: Attention :wave:
