### ISSUE TITLE
selectionPreservedOnEmptyClick property not working in 7.6.0 on DetailsList

### ISSUE THREAD

**Issue by withgallantry** [OfficeDev/office-ui-fabric-react#9754] opened 2019-07-10 13:06 UTC
### Environment Information 
 
Package version: 7.6.0

### Please provide a reproduction of the bug in a codepen:
 
Between version 7.5.0 and 7.6.0 the selectionPreservedOnEmptyClick does not work correctly.
On 7.6.0 when clicking outside of the list, the selection is undone.

Occurs on version 7.6.0 on DetailsList with selectionPreservedOnEmptyClick property. In the example below if you enable modal selection via the toggle, select items, click into 'filter by name' input. Selection is reset.
https://codepen.io/anon/pen/EBrNeJ

Does not occur on version 7.5.0 with same settings on the DetailsList controllers:
https://codepen.io/anon/pen/mZvOjE

#### Actual behavior:
 
Clicking outside DetailsList area with selectionPreservedOnEmptyClick property set with items selected unselects all the selected items.
 
#### Expected behavior:
 
Clicking outside DetailsList area with selectionPreservedOnEmptyClick property set with items selected preserves the selected items.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal

**Comment by Vitalius1** [comment] 2019-07-11 00:20
Regression introduced in 7.5.2 by #9439

**Comment by Vitalius1** [comment] 2019-07-11 00:21
@wiolsen can you take a look please at what got regressed with your PR. Thanks!

**Comment by Vitalius1** [comment] 2019-07-11 00:22
cc: @KevinTCoughlin

**Comment by KevinTCoughlin** [comment] 2019-07-11 00:28
> @wiolsen can you take a look please at what got regressed with your PR. Thanks!

I believe @ThomasMichon just fixed this with #9762 & #9766. Both have been merged.

**Comment by Vitalius1** [comment] 2019-07-11 02:29
I verified on a local running instance with the current PR and indeed it has been fixed.
@withgallantry can you verify the fix on your end with tomorrow’s new release of OUFR and let us know if everything is OK. Thanks!

**Comment by withgallantry** [comment] 2019-07-11 10:41
Will do. Thanks for the speedy fix.

**Comment by withgallantry** [comment] 2019-07-11 17:03
Can confirmed that it's fixed @Vitalius1

**Comment by Vitalius1** [comment] 2019-07-11 21:22
Will close the issue manually since the author confirmed it’s fixed.

**Closed by Vitalius1** 2019-07-11 21:22 UTC
Labels: Component: DetailsList, Type: Bug :bug:, Type: Regression 🌩🌩
