### ISSUE TITLE
Arrow key makes focus move out of a blocking dialog

### ISSUE THREAD

**Issue by nkalpana** [OfficeDev/office-ui-fabric-react#11269] opened 2019-11-21 23:42 UTC
### Environment Information

- **Package version(s)**: 7.31.2
- **Browser and OS versions**: Edge + Narrator + OnScreen keyboard + Windows 10

### Describe the issue:
On a blocking dialog, use Right arrow key on Onscreen keyboard and notice the focus moves from content to dialog buttons. But it does not circle back into the dialog after focus is lost from last button of the dialog.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/nkalpana/pen/zYYXxNN

#### Actual behavior:

On a blocking dialog, use Right arrow key on Onscreen keyboard and notice the focus moves from content to dialog buttons. But it does not circle back into the dialog after focus is lost from last button of the dialog.

#### Expected behavior:
The focus should move back into the blocking dialog on arrow key navigation, until the user closes the dialog.

**Comment by nkalpana** [comment] 2019-11-22 00:31
This is the bug raised on our product: https://msdata.visualstudio.com/Vienna/_workitems/edit/522745
Please see the attached video on the bug for repro.

**Comment by aneeshack4** [comment] 2019-11-23 00:51
@nkalpana Thanks for reaching out to us. Please don't place internal ADO links here because this is public. Content in dialog is not focusable so not sure what you mean by "focus moves from content to dialog buttons" at least when Narrator is not in scan mode. I can see from the video that you're using scan mode - in that case, this is a dupe of #11241 and we're discussing the issue there - this is most likely an issue with Narrator. (please make sure to check for dupes before filing issue in our repo). I'm going to close this as it is a dupe and follow up on #11241

**Closed by aneeshack4** 2019-11-23 00:51 UTC
Labels: Needs: Triage :mag:
