### ISSUE TITLE
Panel Won't Close

### ISSUE THREAD

**Issue by LarsLiden** [OfficeDev/office-ui-fabric-react#3423] opened 2017-11-17 19:11 UTC
### Bug Report

- __Package version(s)__"office-ui-fabric-react": "^4.47.0",
- __Browser and OS versions__: Chrome

#### Describe the issue:

I'm seeing the same (or similar) issue to [Issue 930](https://github.com/OfficeDev/office-ui-fabric-react/issues/930)  

I have a help panel that is opened by clicking on an icon on a modal.  Usually it works just fine, but in certain situations, the panel will stop responding to clicks on the close icon or to a soft dismiss.  The panel is being opened in exactly the same way each time.  The only difference is that in the case where it doesn't work, there are two stacked models on the screen.

Specifically: 

1) Open ModalA + click on help icon on A -> Panel opens and closes fine
2) Open ModalB -> Open ModelA -> click on same help icon -> Panel opens but won't close

**Comment by LarsLiden** [comment] 2017-12-05 19:15
Any feedback / thoughts on this?

**Comment by mattmazzola** [comment] 2018-01-06 00:06
Forgot to add my info last time.  I tried debugging the click event and it seemed like some FocusTrapZone control was stealing the click event and redirecting onto the element with the trap zone such as a activating a ToolTip even when you are not over the tooltip.  This is why pressing `Escape` works to soft dismiss, but clicking on the `X` doesn't.

**Comment by dzearing** [comment] 2018-01-07 20:59
@dagoff @zoarif mentioning you if you have tips here.

**Comment by dzearing** [comment] 2018-01-07 21:06
I'm going to guess this; in scenario 2, focustrapzone in ModalA wants to pull focus back and fights the trap zone in the panel.

@dagoff on our team i believe also hit this and added support to layer trap zones, he may have ideas.

If you have a codepen to repro this, that would be helpful. I'll see if I can repro.

**Comment by dzearing** [comment] 2018-01-07 21:33
Ok think i got a repro.

https://codepen.io/dzearing/pen/Rxxber

If you press enter on the "open panel" command (with keyboard), then press enter on the close icon, panel closes as expected.

If you press enter on the "open dialog" and then in the dialog, press enter on the open panel button within it, THEN the panel close button stops working. You can press escape to close it but you can't click on the close button.

It's close to what you seem to be experiencing.

**Comment by LarsLiden** [comment] 2018-01-08 16:24
Much appreciated guys.  Let me know if there is anything else I can do to
be of assistance.

**Comment by mattmazzola** [comment] 2018-04-02 23:04
Is there any update here?
Does it need clearer reproduction in order for people to take action?
It seems the issue was confirmed in isolation based on the code pen, but I don't see any related PR's or labels/assignments for it to be addressed.

This is one of those issues that may seems lower priority because it's rare (requires multiple modals/panes/panels visible rendered at same time); however, the severity of the bug is high because it essentially leaves the user stuck and app unusable without hard refresh or maybe getting lucky and escape key works.

**Comment by oengusmacinog** [comment] 2018-04-16 23:55
@aditima Still present in Davids Codepen using 5.82.1, so no.

**Comment by oengusmacinog** [comment] 2018-04-20 21:05
Looks like the FocusTrapZone blocks clicks outside the Modal of the Dialog (unless you set a prop), then you click "open panel" and it opens but the FocusTrapZone of Dialog/Modal is still active, blocking the newly opened Panel's close button (not just on keyboard this breaks using mouse too).

Still working on a possible solution, I am open to ideas.

**Comment by dagoff** [comment] 2018-04-20 21:14
In

office-ui-fabric-react<https://github.com/OfficeDev/office-ui-fabric-react>/packages<https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages>/office-ui-fabric-react<https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react>/src<https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src>/components<https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components>/FocusTrapZone<https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components/FocusTrapZone>/FocusTrapZone.tsx

There are a pair of static stacks that keep track of which focustrapzone has priority. One of them is for click priority and the other is for focus priority. This is the bug. There should be only one stack and every new focustrapzone needs to be added to that stack, regardless of whether it asked to block clicks/focus or not.

Only the the focustrapzone on top of the stack should be allowed to trap focus or clicks. This shouldn’t be a large change.

**Comment by oengusmacinog** [comment] 2018-04-20 21:31
Ill also not Panel then Dialog stacks correctly, only in the order Dialog then Panel does it block.

**Comment by LarsLiden** [comment] 2018-06-11 19:44
Any progress on this one?  Still posing an issue for us.

**Comment by dzearing** [comment] 2018-06-19 16:52
@LarsLiden So sorry for the delay here. 

Hmm weird, so I did this in Panel:

```
        <Panel focusTrapZoneProps={{ }}
```

And now it works as expected... I haven't dug into why but I was playing with the code and hit this. Can you verify? I saved my example here:

https://codepen.io/dzearing/pen/Rxxber?editors=0010

@oengusmacinog fyi

**Comment by mattmazzola** [comment] 2018-06-19 18:21
> Can you verify?
I added this change to our app and it fixed a few of the cases I tested.  There are a few more cases that only reproduce under error conditions that I didn't test yet, but it's still good news! Thanks.

**Comment by dzearing** [comment] 2018-06-20 05:08
@dagoff or @oengusmacinog  Do you have any idea why passing in empty object for focusTrapZoneProps would change the behavior?

**Comment by oengusmacinog** [comment] 2018-06-20 23:31
I haven't been able to dig into the code yet but that seems in line with what we talked about above.  There's a FocusTrapZone stack and somehow the Panel wasn't getting stacked ontop of the Dialog when open, so the FocusTrapZone for Dialog was active behind the Panel.  I'm guessing by passing the empty props it is somehow saying "I'm here" and properly going on the stack.

**Comment by dzearing** [comment] 2018-06-26 18:54
Could we simply default the props to an empty object?

**Comment by dagoff** [comment] 2018-06-26 19:07
There are a pair of static stacks that keep track of which focustrapzone has priority. One of them is for click priority and the other is for focus priority. This is the bug. There should be only one stack and every new focustrapzone needs to be added to that stack, regardless of whether it asked to block clicks/focus or not. Only the the focustrapzone on top of the stack should be allowed to trap focus or clicks. This shouldn’t be a large change.

**Comment by dzearing** [comment] 2018-06-26 19:57
@dagoff possible for you to submit a quick fix?

**Comment by dagoff** [comment] 2018-06-26 20:43
Yes.

**Comment by dagoff** [comment] 2018-06-27 21:23
I’ve opened a pull request. Please review it.

https://github.com/OfficeDev/office-ui-fabric-react/pull/5351

**Comment by LarsLiden** [comment] 2018-07-12 15:40
Thanks @dagoff.  Any progress on getting the PR accepted?

**Comment by dzearing** [comment] 2018-07-31 22:59
@LarsLiden This will be merged today. It was an uphill battle here getting tests around this area and wanted to make sure we don't break this. @cliffkoh  is adding some cases right now and will get this merged today.

**Comment by LarsLiden** [comment] 2018-08-01 01:00
That's fantastic.  Thank you!

**Comment by cliffkoh** [comment] 2018-08-01 01:05
New unit tests and examples (thanks @natalieethell) have been added to @dagoff 's pull request in #5351.

**Closed** 2018-08-01 05:04 UTC
Labels: Priority 1: ASAP, Type: Bug :bug:
