### ISSUE TITLE
Commandbar elements within detailslist not accessible

### ISSUE THREAD

**Issue by bhuvan-iyer** [OfficeDev/office-ui-fabric-react#10119] opened 2019-08-11 13:42 UTC
### Environment Information

- **Package version(s)**: 7.20.1
- **Browser**: Chrome, Edge 
### Describe the issue:

Commandbar elements when within detailslist is not accessible using tab stops or arrow keys. But a button inside detailslist is accessible. 

#### Expected behavior:

Commandbar elements when within detailslist should be accessible using tab stops or arrow keys. 

### codepen repro:

https://codepen.io/kbh_Ms/pen/mNzxvO

### Priorities and help requested :

Requested priority: High

Products/sites affected: Internal Microsoft application

<img width="832" alt="accessibility_bug_office_fabric" src="https://user-images.githubusercontent.com/53990751/62834538-b1155a80-bc6b-11e9-805c-80f2f5af3d1e.PNG">

**Comment by JasonGore** [comment] 2019-08-12 15:14
I see the behavior described, thanks for the CodePen! Both `CommandBar` and `DetailsRow` contain a `FocusZone` which makes this a nested scenario. There could either be an issue with nested `FocusZones` or a configuration issue.

**Comment by bhuvan-iyer** [comment] 2019-10-30 10:29
Hi,

What is the status of this bug. Is it fixed ?

**Comment by joschect** [comment] 2019-11-06 18:29
@bhuvan-iyer I don't believe that this is a bug any more. The commandbar really isn't supposed to be used within a detailslist. Per our earlier conversation there is [this codesandbox](https://codesandbox.io/s/keen-water-gtymy) that gives you all the benefits of a commandbar by implementing a composed version. It's relatively small and is your best bet moving forward.

**Comment by bhuvan-iyer** [comment] 2019-11-11 03:59
ok.

**Comment by JasonGore** [comment] 2019-11-11 16:35
Please let us know if you have any other questions or comments. I will close this issue as "By Design". Thanks!

**Closed by JasonGore** 2019-11-11 16:35 UTC
Labels: Area: Accessibility, Component: CommandBar, Component: DetailsList, Component: FocusZone, Resolution: By Design
