### ISSUE TITLE
Panel: Footer bottom is cut on chrome browser in Android

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#6182] opened 2018-08-31 14:21 UTC
Requested priority: Low
Blocked: No

Similar to below issue for ios:
https://github.com/OfficeDev/office-ui-fabric-react/issues/5423

I also hit the same issue with ios and while debugging found the same issue exist for mobile users using chrome browser. Chrome is also following the same viewportHeight concept as Safari since 2016.

But in chrome browser in mobile, I am able to see the footer if I scroll panel up. Not blocked but I would not want a experience where my footer seems to be hidden when panel pops up.

![panel footer clipped](https://user-images.githubusercontent.com/19491487/44917574-5d5d7a00-ad56-11e8-97c1-8f4173df8e8d.jpg)

Possibly we need a check for chrome browser in mobile and set the height to window.innerHeight there also.

**Comment by Jahnp** [comment] 2019-03-25 22:28
@mdmdakbar Apologies for the delay, it seems this fell off the radar for a bit. Can you confirm if this still repros for you? I'm not able to repro on my iOS device at the moment, and won't be able to test on an Android until at least tomorrow.

cc @kkjeer who authored #5423 and may have thoughts here.

**Comment by schemburkar** [comment] 2019-03-30 18:33
Similar issue is occurring for me on Android for both Edge & Chrome. 
The footer does not show up at all and if footer is not specified the scrolling content gets clipped.

iOS Safari seems to work fine.

"office-ui-fabric-react": "^6.163.0",
"react": "^16.8.6",

**Comment by schemburkar** [comment] 2019-03-31 06:58
Hey @Jahnp , @kkjeer I have repo this issue using https://repl.it/repls/SkeletalSilverParser. The output is at https://skeletalsilverparser--five-nine.repl.co/

The footer is clipped on chrome and edge on android.


See below the renders on Android, iOS

Chrome_Android

<img src="https://user-images.githubusercontent.com/3159347/55285722-eac98100-53ae-11e9-8811-b97aafa0a011.png" width="250" />


Edge_Android

<img src="https://user-images.githubusercontent.com/3159347/55285724-eb621780-53ae-11e9-9cbc-3bae942cbe8a.png" width="250" />


Safari_iOS

<img src="https://user-images.githubusercontent.com/3159347/55285723-eb621780-53ae-11e9-90ce-ce2c60b80cad.png" width="250" />

Hope this helps. 

Thanks,
Shubhan

**Comment by kkjeer** [comment] 2019-04-01 19:31
Hi @schemburkar, I am also able to repro this on Android. I will continue investigating to find a fix.

**Comment by v-dhiraj** [comment] 2019-04-29 08:55
even I am facing the same issue on iPhones. When say I render the Done button within the Footer, it is not visible. It seems the browser/visible viewport is not being considered.

**Comment by kkjeer** [comment] 2019-04-29 17:31
@v-dhiraj which version of Fabric are you using? PR #6031 should have addressed the issue for iOS, which was released in Fabric [6.57.0](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v6.57.0).

**Comment by v-dhiraj** [comment] 2019-05-06 06:22
![IMG-7388](https://user-images.githubusercontent.com/50100379/57209184-10bcf380-6ff5-11e9-9f07-5d7ffae6842d.jpg)
![IMG-7380](https://user-images.githubusercontent.com/50100379/57209185-11558a00-6ff5-11e9-92ad-c7d9d1e45009.jpg)

Well, Yes that version did partially resolve the issue. Yet on mobile browsers specifically safari, the panel component is misbehaving.
1. The footer still gets blocked/not visible in safari, unless I manipulate the height of the component based on vh.
2. When I try to edit say any text field values inside the panel component the panel height reduces and presents an unexpected experience. Please refer to the picture attached. This does not happen on chrome browsers on iOS platforms.

**Comment by kkjeer** [comment] 2019-05-06 21:16
@v-dhiraj thank you for providing the images. I have a few questions to dig deeper into the issues you're observing:

> 1. The footer still gets blocked/not visible in safari, unless I manipulate the height of the component based on vh.

Which component are you manipulating the height of? Panel itself uses `maxHeight: window.innerHeight` on iOS Safari (see [Panel.styles.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Panel/Panel.styles.ts#L260)).

> 2. When I try to edit say any text field values inside the panel component the panel height reduces and presents an unexpected experience. Please refer to the picture attached. This does not happen on chrome browsers on iOS platforms.

Could you please provide a CodePen that reproduces this issue so that we can debug?

**Comment by v-dhiraj** [comment] 2019-05-07 10:44
@kkjeer Thanks for the quick reply, here are my following comments: 

> Which component are you manipulating the height of? Panel itself uses maxHeight: window.innerHeight on iOS Safari (see Panel.styles.ts).

we initially did not set any height to the panel component and worked with the maxHeight property only, but that did not help us. after further investigation, I found that there is a main property within IPanelStyles which is the main section of the panel that covers the header, content and footer of the panel. Upon making the height dynamic depending on the vh value of our viewport we were able to show the footer as well within the actual viewport(i.e, the space between the address bar and navigation bar of the safari/chrome browser on mobile phones)
 eg: 
export const DummyPanelstyle: IStyleFunctionOrObject<IPanelStyleProps, IPanelStyles> = {
  main: {
    height: 'calc(var(--vh, 1vh) * 100)'
  }
};
where, --vh is (window.innerHeight * 0.01)px. This --vh value is dynamic and changes on any kind of resize event of the window.

> Could you please provide a CodePen that reproduces this issue so that we can debug?

How much I wish I could you know reproduce this scenario in my local environment, but I have not been able to do so. It is only possible to reproduce it on an actual mobile phone. :/

**Comment by kkjeer** [comment] 2019-05-07 16:49
@v-dhiraj thanks for your reply; please see below.

This is what the Panel component looks like on our [website](https://developer.microsoft.com/en-us/fabric#/controls/web/panel) on Safari on my iPhone:

![panel-ios](https://user-images.githubusercontent.com/6687333/57317166-5d173a80-70ac-11e9-9ca4-8a73b2491e07.jpg)

This is without any custom styling applied to the Panel. Does the Panel work as expected for you without any custom styles applied?

> How much I wish I could you know reproduce this scenario in my local environment, but I have not been able to do so. It is only possible to reproduce it on an actual mobile phone. :/

We can use CodePens to debug on mobile phones. I have a [sample CodePen](https://codepen.io/kkjeer/pen/QRbqeP?editors=0010) with a Panel - could you please fork it and make any changes you need to show your scenario? Thanks!

**Comment by puco** [comment] 2019-05-09 12:17
I can see the issue also on your website. When I open the first Panel (https://developer.microsoft.com/en-us/fabric#/controls/web/panel, Panel - Small Panel, Anchored Right, Fixed Width). When I have the address bar displayed then the buttons are not visible. When the address bar is hidden, due to the fact that I scrolled down on the page the, then buttons are visible.

Why did you decide to use `{ position: fixed, top: 0, height: 100vh }` which exhibits this problem instead of `{ position: fixed, top: 0, bottom: 0 }`

**Comment by kkjeer** [comment] 2019-05-09 18:59
@puco unfortunately I am not able to repro the issue on our website. I see the following on an iPhone:

![ios-panel](https://user-images.githubusercontent.com/6687333/57478982-35150c00-7251-11e9-9162-b6bd9af5f524.jpg)

Could you share a screenshot of what you see on the website?

We do not use `{ position: fixed, top: 0, height: 100vh }` in the [Panel styles](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Panel/Panel.styles.ts). Are these referring to custom styles applied to a Panel?

**Comment by srvsoni** [comment] 2019-05-24 08:04
@kkjeer, this issue can repro on your website with Android mobile Chrome, when the address bar not hidden Panel bottom content cutting & even its not allow to be scroll the page.
![screenshot-1558684866179](https://user-images.githubusercontent.com/14307118/58312198-6b918000-7e28-11e9-8e70-dd9ffc44ed6e.jpg)

**Comment by schemburkar** [comment] 2019-05-24 08:31
@kkjeer Any updates? Did you get a chance to find a fix?

Get Outlook for Android<https://aka.ms/ghei36>

**Closed** 2019-06-06 18:33 UTC
Labels: Component: Panel, Platform: Chrome Android, Type: Bug :bug:
