### ISSUE TITLE
Combobox: onRenderOption gets called on every hover over combobox options

### ISSUE THREAD

**Issue by szmarci** [OfficeDev/office-ui-fabric-react#11237] opened 2019-11-18 14:12 UTC
### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/gifted-zhukovsky-ujh1b

#### Actual behavior:

When I open the Combobox and hover over the individual items, the onRenderOption function called every time. You can see it in the console

**Comment by aneeshack4** [comment] 2019-11-18 23:07
@szmarci Thank you for reporting this and providing the codepen! It does repro but I just spoke with the component owner and it turns out this is by design. It's explained [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx#L1307) in a comment of `_isOptionSelected`. This was done to mimic the behavior on native where if you hover over a dropdown menu and arrow through the options, then hover out and back in, it'll start from the menu item that has focus. If you'd like to request a change to this behavior as a feature request, that's totally fine, we can add it to our backlog for future consideration but for now, this is by design.

**Comment by szmarci** [comment] 2019-11-21 12:36
@aneeshack4 Thanks for the clarification. I'm okay with that, I just thought it was some sort of bug.

**Comment by aneeshack4** [comment] 2019-11-27 23:51
Spoke with the component owner & they agree this is working as intended & we're not going to consider it as a feature request. I'm going to go ahead and close this.

**Closed by aneeshack4** 2019-11-27 23:51 UTC
Labels: Component: ComboBox, Resolution: By Design, Type: Feature
