### ISSUE TITLE
On Focus Split button menu option Couldn't open. Not able to focus on Arrow of Split Button.

### ISSUE THREAD

**Issue by v-jashr** [OfficeDev/office-ui-fabric-react#12013] opened 2020-02-20 07:58 UTC
In Below official website of office fabric you can repro the issue. 

On focus could not able to open menu as we are not able to move focus on arrow in split button

Expected

On focus of split two different activity should happen

1. click event should work as it.
2. focus should come to down arrow and on click of down arrow menu should be open.

![image](https://user-images.githubusercontent.com/50479173/74912344-8bb89480-53e4-11ea-903b-10b13655a04f.png)

**Comment by aneeshack4** [comment] 2020-02-20 19:34
Hi @v-jashr, this is intentional - we designed it so that focus can be on the entire button - you have to do ALT + DOWN to open the dropdown menu. Going to close this as it's by design but please feel free to ping us again if you have anything further.

**Closed by aneeshack4** 2020-02-20 19:34 UTC
Labels: Needs: Triage :mag:
