### ISSUE TITLE
Modal resets focuses to first input/button in DOM causing scroll jumping

### ISSUE THREAD

**Issue by mattmazzola** [OfficeDev/office-ui-fabric-react#3804] opened 2018-01-25 18:06 UTC
### Bug Report

- __Package version(s)__: `"office-ui-fabric-react": "^5.38.0",`
- __Browser and OS versions__: 
Windows 10 (Version 10.0.16299 Build 16299)
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: High

Products/sites affected: (if applicable)

#### Describe the issue:

The Modal component seems to be using some FocusTrapZone and it is auto registering event handlers which will focus the top input.

#### Actual behavior:

User scrolls modal down to another input, enters text and clicks outside the input to unfocus it.
Then UI Fabric forces focus to the first control / input causing the modal to jump to the top causing confusion.

#### Expected behavior:

Modal should not implicitly have any scrolling behavior.

### If applicable, please provide a codepen repro:

I tried to ask how to reproduce this in code pen on the Teams group but no one seems to know how.
From my understanding the Modal component is not exposed through the top level, only the /lib/ package which means it cannot be access through the global / UMD module.

I reproduced in separate repo here:
https://github.com/mattmazzola/fabric-slate-test

I also have video of the issue here:
http://recordit.co/F3OxNnhyTq

Explanation: I open the modal and you notice the Close Button is immediately focused.  Then I show entering text on inputs that are down the page and move the scroll bar, notice as soon as I click outside the input the modal jumps back to the top.  I have to scroll back down again to continue and this jump and leave the user confused and ruins the linear form filling experience.

I could see how this default focus makes sense for Dialogs which ONLY have buttons such as Ok or Cancel, but for generic modals this is not acceptable and violates principle of least surprise. **Modals shouldn't be doing this extra behavior unless we ask for it. Stuff like this makes devs not trust the framework.**

**Comment by oengusmacinog** [comment] 2018-02-26 22:50
@mattmazzola have you seen this behavior occurring in any other instances specifically. I tried to recreate the situation in my own example and was unable to reproduce the result.  I did download your repo and I do see the behavior there. Any more insight you have about the cause in your app would be helpful so I can recreate it.

**Comment by mattmazzola** [comment] 2018-02-27 00:21
We were seeing this issue in app we're building which uses office-ui-fabric-react.  We have a modal that contains a scrollable pane which contains messages chronologically. The user is intended to look at the bottom of the chat messages since that is the latest and most relevant information. However, this bug causes the focus to be set to the the top item meaning the user has to scroll back down to the bottom to continue their work and makes for confusing experience.

I tried reducing it down to the most simple form with a Fabric.Modal that contains native button / inputs where as our app has a whole bunch of other controls and custom components that could be contributing to other problems.

**Comment by oengusmacinog** [comment] 2018-02-28 19:52
@mattmazzola I just retested your app [https://github.com/mattmazzola/fabric-slate-test](https://github.com/mattmazzola/fabric-slate-test) and ran `npm update office-ui-fabric-react` to update the package to v5.56.0 and the issue disappears, so it looks like another recent update must have fixed it.  Update to that version of Fabric React and you should be good to go.  I'm going to go ahead and close this issue, but feel free to reopen this issue or open an new issue if you continue having issues after the update.

**Closed by oengusmacinog** 2018-02-28 19:52 UTC
Labels: bug, focus-zone
