### ISSUE TITLE
Pivot component is not responsive on mobile view

### ISSUE THREAD

**Issue by SuganthanMathivanan** [OfficeDev/office-ui-fabric-react#9235] opened 2019-05-28 08:25 UTC

**Comment by SuganthanMathivanan** [comment] 2019-05-28 08:27
some buttons getting hide when you see in a mobile view. Need to use horizontal scrollbar.

**Comment by micahgodbolt** [comment] 2019-05-28 18:21
duplicate of #4066

**Comment by micahgodbolt** [comment] 2019-05-28 18:22
pivot wasn't created for this scenario. We have the feature in our backlog.

**Closed by micahgodbolt** 2019-05-28 18:22 UTC
Labels: Component: Pivot, Resolution: Duplicate
