### ISSUE TITLE
Clicking into Text Field while Menu is open makes keypresses not register

### ISSUE THREAD

**Issue by mattgriffin94** [OfficeDev/office-ui-fabric-react#9499] opened 2019-06-18 19:46 UTC
### Bug Report
- __Browser and OS versions__: IE/Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No
Requested priority: Normal

#### Describe the issue:

Internet Explorer / Edge bug only: Open up Menu and click into a TextField on IE and your keypresses get eaten.  For example, on https://developer.microsoft.com/en-us/fabric#/controls/web/textfield will repro if you select the theme tab to bring up the menu, click into a textfield when the menu is up, and start typing - your keypresses get eaten

#### Actual behavior:

Keypresses don't register

#### Expected behavior:

Typing works

**Comment by aftab-hassan** [comment] 2019-06-18 20:38
@mattgriffin94 Thanks for posting the issue.

I am able to reproduce the behavior you posted. However, I see the same on `Chrome` and `Firefox` as well. I shall reply back on the issue when I have a fix for this. Marking as `bug`

**Comment by aftab-hassan** [comment] 2019-06-19 02:39
@mattgriffin94, I'd like to clarify to be sure we are on the same page, especially since you mentioned, `Internet Explorer / Edge bug only`, whereas, I was able to reproduce, what I believe is the issue, on all supported browsers.

Is the issue that upon clicking the tab to bring up the menu, first keypress gets eaten, and you are having to keypress the `TextField` a second time, to place focus and be able to start typing? Please confirm.

Also, if this is indeed the issue, are you not able to see it on other browsers (`Chrome`/`Firefox`) as well ?

**Comment by aftab-hassan** [comment] 2019-06-20 19:55
The root cause for this issue is that the `TextField` does get focus, however, the `Dropdown` gets the focus back. This qualifies as a `Dropdown` focus issue. The same behavior can be seen on other controls also such as `ComboBox` and `SearchBox` when used with `Dropdown`

Spoke offline with @joschect. He is investigating this.

**Closed** 2019-06-29 21:00 UTC
Labels: Component: TextField, Needs: Author Feedback, Type: Bug :bug:, no-recent-activity
