### ISSUE TITLE
Dropdown className props only provides me styling access to the root element

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#1031] opened 2017-02-17 21:31 UTC
Is there anyway I can override "ms-Dropdown-title"- background-color, border etc. css properties using the className props which is set at the root element? 

I want to avoid office fabric css overriding and wish to do it via props for ms-Dropdown-title too.

- __Package version(s)__: 1.2.2

**Comment by battletoilet** [comment] 2017-02-23 22:26
We are currently discussing options for this issue.

**Comment by AkshanshSrivastava03** [comment] 2017-02-24 05:02
When can i expect this to release?

**Comment by mikewheaton** [comment] 2017-06-01 22:30
This looks to be a duplicate of #1548, which was fixed by #1756.

**Closed by mikewheaton** 2017-06-01 22:30 UTC
Labels: feature-request
